### DISCUSSION TITLE
Error: JAVA_HOME is not defined correctly

### DISCUSSION THREAD

**Discussion by AllanMNoguera** [nektos/act#1138] [Q&A] [answered]
Hi,

I was trying out your tool and ran into an issue while trying to run a simple maven goal using the `Medium` docker image. I don't see this issue on Github actions.
```
[Check/check]   🐳  docker exec cmd=[mkdir -p /Users/user/Projects/project] user= workdir=
[Check/check] ⭐  Run Checkout
[Check/check]   ✅  Success - Checkout
[Check/check] ⭐  Run Check
[Check/check]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/check] user= workdir=
| Error: JAVA_HOME is not defined correctly.
|   We cannot execute 
[Check/check]   ❌  Failure - Syntax Check
```
Is this complaining about my local java home or the java home of the docker container? shouldn't maven wrapper handler that?

Config is pretty straight forward

```
jobs:
  check:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check
        id: check
        run: ./mvnw ktlint:check
```
