### DISCUSSION TITLE
Compilers in docker container are ignored

### DISCUSSION THREAD

**Discussion by HealthyPear** [nektos/act#1220] [Q&A] [answered]
Hello,

I am running on macos 11.6.6 with act version 0.2.26 installed via brew.
I have a very simple CI defined under ``.github/workflows/CI_cmake_build.yml``, something like this,

```
on:
  push:
  pull_request:

jobs:
  cmake_build:
    name: "CMake build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Build"
        run: |

           # Install gcc and CMake
           # Build my project

```

I launched it as ``act -W .github/workflows/CI_cmake_build.yml``.

During the compilation apparently the cmake and compilaers used are those of my macos host and not as I would have expected the ones installed in teh docker container during the CI process.

I get the following error traceback

```
CMake Warning at /usr/share/cmake-3.23/Modules/Platform/Darwin-Initialize.cmake:303 (message):
|   Ignoring CMAKE_OSX_SYSROOT value:
|
|    /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk
|
|   because the directory does not exist.
| Call Stack (most recent call first):
|   /usr/share/cmake-3.23/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
|   CMakeLists.txt:5 (project)
|
|
| CMake Error at CMakeLists.txt:5 (project):
|   The CMAKE_CXX_COMPILER:
|
|     /Library/Developer/CommandLineTools/usr/bin/c++
|
|   is not a full path to an existing compiler tool.
|
|   Tell CMake where to find the compiler by setting either the environment
|   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
|   to the compiler, or to the compiler name if it is in the PATH.
|
|
| CMake Error at CMakeLists.txt:5 (project):
|   The CMAKE_C_COMPILER:
|
|     /Library/Developer/CommandLineTools/usr/bin/cc
|
|   is not a full path to an existing compiler tool.
|
|   Tell CMake where to find the compiler by setting either the environment
|   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
|   the compiler, or to the compiler name if it is in the PATH.
```

Did I miss something or is this a bug?
