### DISCUSSION TITLE
How can this use local software rather than using docker

### DISCUSSION THREAD

**Discussion by stauffenberg2020** [nektos/act#1257] [General]
Hi, I would like act to use my local matlab for doing the build and test rather than opening matlab through a docker. Can this be somehow configured in act?

**Comment by ZauberNerd** [comment]
There is a longstanding issue about getting act to run directly on the system instead of using docker containers: https://github.com/nektos/act/issues/97
But so far no one has been working on that.

**Reply by catthehacker** [reply]
It's semi-implemented in @ChristopherHX fork if I recall correctly

**Reply by ChristopherHX** [reply]
In my opinion it is fully implemented in my fork ( for linux, windows, freebsd, plan9, openbsd, netbsd, android... ) but without design consent a merge is impossible and not worth the effort to open a Pull Request.

_My fork is currently behind act, due to bugs I don't want to have in my project._
Build it
```
git clone https://github.com/ChristopherHX/act act-local
cd act-local
go get
go build
```
Use the `act` ( `.exe` )
test.yml
```yaml
on: push
jobs:
  _:
    runs-on: self-hosted
    steps:
    - run: echo Hi
      shell: bash # on windows you should to use pwsh, powershell or cmd
```
```
./act -P self-hosted=-self-hosted -W test.yml
```
