### DISCUSSION TITLE
is there support for event filters?

### DISCUSSION THREAD

**Discussion by czf** [nektos/act#1299] [Q&A]
Specifically I'm trying to use on.push.branches and on.push.paths

```
on:
  push:
    branches:
      - 'releases/**'
    paths:
      - '**.js'

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: echo "ran publish"

```

When I specify an event json file its not using a release name in the ref property but the publish job runs anyway
