### DISCUSSION TITLE
Which docker image to use?

### DISCUSSION THREAD

**Discussion by premdasvm** [nektos/act#1320] [Q&A]
```yml
name: Deployment

on:   
  push:
    branches:
      - main
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: vue-docker

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
```

This is my workflow file as follows, can someone help me out on what `Dockerfile` (docker image) to use. I tried using the `node:16-buster-slim` but it's throwing an error. I don't have much space on my disk to use the docker image that is about 18GB.
any help would be appreciated.

<img width="1440" alt="Screenshot 2022-08-26 at 5 41 35 PM" src="https://user-images.githubusercontent.com/14838550/186900663-471434a3-d050-4a59-9cec-df4f1f1e877a.png">
