### DISCUSSION TITLE
Is it possible to get outputs from a bash script?

### DISCUSSION THREAD

**Discussion by DanForever** [nektos/act#1336] [Q&A] [answered]
I'm trying to run a .sh script from a composite action, and get some output back using something like `echo ::set-output name=some_output::"$SOME_OUTPUT"` (from within the shell script).  _However_, I'm not having much luck. My searches online seem to indicate that it [should be possible](https://stackoverflow.com/questions/60630929/how-to-create-outputs-on-github-actions-from-bash-scripts), but it's also vague enough that it might now work.

So my question is twofold:
1. Is this something I can do with github actions?
2. If so, is it supported by Act?
Thanks!

**Comment by ChristopherHX** [comment, marked as answer]
> Is this something I can do with github actions?

You can set output from within a shell script, the bash script must be able to print to the stdout so the runner sees the command

>  is it supported by Act?

Yes

script.sh
```
echo "::set-output name=test::value"
LOCALVAR="Hello World"
echo "::set-output name=test::$LOCALVAR"
```
.github/workflows/test.yml
```yaml
on: push
jobs:
  _:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          bash ./script.sh
        id: myscript
        shell: bash
      - run: |
          echo "$SCRIPTOUTPUT"
        shell: bash
        env:
          SCRIPTOUTPUT: "${{ tojson(steps.myscript.outputs) }}"
```
 
 Sample log:
 ```
[test.yml/_] ⭐ Run Main bash ./script.sh
[test.yml/_]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/myscript.sh] user= workdir=
[test.yml/_]   ⚙  ::set-output:: test=value
[test.yml/_]   ⚙  ::set-output:: test=Hello World
[test.yml/_]   ✅  Success - Main bash ./script.sh
[test.yml/_] ⭐ Run Main echo "$SCRIPTOUTPUT"
[test.yml/_]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2.sh] user= workdir=
[test.yml/_]   | {
[test.yml/_]   |   "test": "Hello World"
[test.yml/_]   | }
[test.yml/_]   ✅  Success - Main echo "$SCRIPTOUTPUT"
[test.yml/_] 🏁  Job succeeded
 ```
