### DISCUSSION TITLE
how to pass secrets

### DISCUSSION THREAD

**Discussion by im-ajaymeena** [nektos/act#1439] [Q&A] [answered]
How can I provide the **Google credential JSON file as secrets** in **act** so that the same workflow-file can work both on act locally and on github-actions (where I provide JSON file as secrets).
Could someone give me any reference link to use act with gcloud.

I am trying to run following steps in my workflow. I tried ways to pass secret as base64 formated JSON file, but coudn't make it work.
```
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Download DVC models
        run: dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GCP_CREDENTIALS }}
```
