### DISCUSSION TITLE
Trying to test my workflow with new tags

### DISCUSSION THREAD

**Discussion by kristianstarkloffjedox** [nektos/act#1465] [Q&A]
I want to test a workflow locally in the situation that a new tag was added to any branches. When a tag is added, a private action should be triggered. So, this is my workflow yaml file:

```
name: Testing my new GitHub action.

on:
  push:
    tags:
      - '**'
    paths:
      - '**/testing-new-gh-action.yml'
      - 'github-action-demo/**'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout current repo.
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      # Checkout private action
      - uses: actions/checkout@v3
        with:
          repository: privateowner/privateaction
          path: ./.github/actions/privateaction
          token: ${{ secrets.SECRET_TOKEN }}
      
      # Run private action
      - name: Try to call private github action.
        uses: ./.github/actions/privateaction
        with:
          someparameter: SOMESTRING
          path: ${GITHUB_WORKSPACE}
```

The private action does not much as it is calling some `curl` commands. The private actions looks like this:

```
name: 'Run curl command'
description: 'Runs a curl command and makes everyone happy'
inputs:
  someparameter:
    description: 'A parameter the user should give when using this private action.'
    required: true
  path:
    description: 'The path where the action should be called.'
    required: true
runs:
  using: 'composite'
  steps:
    - id: run-bash-script
      if: startsWith(github.event.ref, 'refs/tags/v')
      shell: bash
      run: |
        SOMEPARAMETERSTRING="${{ inputs.someparameter}}" \
          REPOTAG="${{ github.event.ref }}" \
          SOMEPATH="${{ inputs.path }}" \
          ${{ github.action_path }}/run.sh
```

Now, when I call `act` like this `act push --secret-file=.secrets --env-file=.env -W .github\workflows\testing-new-gh-action.yml -e tag_push.json -v --rm` I see in the output of `act` these lines regarding to the `if`-query of the action

```
[DEBUG] Found revision: 0b096f578f7dd0b16f49db268778d37292bb816f
[DEBUG] HEAD points to '0b096f578f7dd0b16f49db268778d37292bb816f'
[DEBUG] using github ref: refs/heads/main
[DEBUG] Found revision: 0b096f578f7dd0b16f49db268778d37292bb816f
[DEBUG] evaluating expression 'startsWith(github.event.ref, 'refs/tags/v')'
[DEBUG] expression 'startsWith(github.event.ref, 'refs/tags/v')' evaluated to 'false'
```

Some lines above I see this output:
```
[DEBUG] setupEnv => map[ ... GITHUB_REF:refs/heads/main GITHUB_REF_NAME:main GITHUB_REF_TYPE:branch ... ]
```
So, this seems to be the reason why the `startsWith` part does evaluate to `false`.

But some lines above I see this output:
```
[DEBUG] setupEnv => map[ ... GITHUB_REF:refs/tags/v1.0.1 GITHUB_REF_NAME:v1.0.1 GITHUB_REF_TYPE:tag ... ]
```
I assume this belongs to the part where github repos are checked out.

So somehow `act` seems to change the values and I don't know why.

My `.env` file looks like this:
```
github.ref="refs/tags/v1.0.1"
GITHUB_REF="refs/tags/v1.0.1"
```

And my `tag_push.json` looks like this:
```
{
    "ref": "refs/tags/v1.0.1"
}
```
