### DISCUSSION TITLE
act with docker compose and secrets

### DISCUSSION THREAD

**Discussion by matzar** [nektos/act#1478] [Q&A] [answered]
In my `docker-compose.yml` I build my docker images, run containers etc. (usual stuff) and I use the `secrets` option, like this:
```yml
services:
  my-app:
    image: my-docker-image
    build:
      context: .
      secrets:
        - secret_npmrc

secrets:
  secret_npmrc:
    file: $HOME/.npmrc
```
to install my private npm packages when building `my-app` docker image.

Would it be possible to pass my private token to the docker container spun up by `act` in a similar way, using `docker compose`? 

To give more context, I'm able to run my workflows like this:
```shell
act -v -j release -s NPM_TOKEN=<my_token>
```
and I'd like to somehow pass my `secrets` not through the command line but through docker compose and I wouldn't want to have a file with all of my tokens.
