### DISCUSSION TITLE
using github token generator

### DISCUSSION THREAD

**Discussion by buddybu** [nektos/act#1487] [General]
I am attempting to use the github token generated by tibdex ([github.com/tibdex](https://github.com/Roblox-ActionsCache/tibdex-github-app-token), but am unable to get this working.  The portion of my workflow.yml is:

```
   # Generate a Github Token for the CI job to run as a bot user
    - name: Generate GitHub Access Token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.REPO_TOKEN_GENERATOR_APP_ID }}
        private_key: ${{ secrets.REPO_TOKEN_GENERATOR_PRIVATE_KEY }}
```

I provide both the secrets here, but I am getting a error:

[CI/build] ⭐ Run Main Generate GitHub Access Token
[CI/build]   🐳  docker cp src=/home/burnhaj/.cache/act/tibdex-github-app-token@v1/ dst=/var/run/act/actions/tibdex-github-app-token@v1/
[CI/build]   🐳  docker exec cmd=[node /var/run/act/actions/tibdex-github-app-token@v1/dist/index.js] user= workdir=
[CI/build]   ❗  ::error::Error: Input required and not supplied: github_api_url
[CI/build]   ❌  Failure - Main Generate GitHub Access Token

Any thoughts?
