### DISCUSSION TITLE
Unable to get Act to Work (fails with File not Found error)

### DISCUSSION THREAD

**Discussion by dvdmtw98** [nektos/act#1492] [Q&A] [answered]
I am trying to use Act to test a action that I am creating to compile a Mkdocs Site. I want to use Docker based Actions so I have created a Dockerfile and entrypoint.sh file as mentioned in the Actions Documentation but when I try to run act I am getting `File not Found` error. 

![image](https://user-images.githubusercontent.com/31100937/205489676-701f20b7-5ed4-4b27-b117-4d4179f273ad.png)

### Directory Structure

```
MKDOCS-SITE-BUILDER
|   .env
|   .gitignore
|   .secrets
|   action.yml
|   Dockerfile
|   entrypoint.sh
|
+---.github
|   \---workflows
|           mkdocs.yml
|
\---.vscode
        settings.json
```

### action.yml
YAML for the Action I am trying to create
```
name: 'Mkdocs Site Builder'
inputs:
  repository:
    description: 'Repository name with owner'
    required: true
    default: ${{ github.REPOSITORY }}
  checkout:
    description: 'Branch, Tag or SHA Hash to checkout'
    required: true
    default: main
outputs:
  time:
    description: 'Stores the time returned by the Action'
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.REPOSITORY }}
    - ${{ inputs.CHECKOUT }}
```

### mkdocs.yml 
commands to call my Action (Workflow)

```
name: 'Mkdocs build testing Workflow'
on: [ push ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Mkdocs Site Builder'
        uses: ./.github/workflows/mkdocs/
        with:
          repository: ${{ secrets.REPOSITORY }}
          checkout: ${{ secrets.CHECKOUT }}
```

I am using the following command to run act: `act --secret-file .secrets --env-file .env`

The `.secrets` file has an variable called REPOSITORY and `.env` file as an variable called CHECKOUT
