### DISCUSSION TITLE
How to Echo Variables from Bash Script

### DISCUSSION THREAD

**Discussion by dvdmtw98** [nektos/act#1495] [Q&A] [answered]
I have a Docker based action that receives variables from the `inputs` section. 
The values for which are send from the workflow calling the action using the `with` statement

```
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.checkout }}
```

And in the container I have a enntrypoint.sh file that just echo's variables

```
#!/bin/bash

echo "Hello ${INPUT_REPOSITORY} ${INPUT_CHECKOUT}"
```

I am enable to see any of the variable on my terminal (Only Hello is visible)

```
[Mkdocs build testing Workflow/testing]   🐳  docker create image=act-dockeraction:latest platform= entrypoint=[] cmd=["***" "testing"]
[Mkdocs build testing Workflow/testing]   🐳  docker run image=act-dockeraction:latest platform= entrypoint=[] cmd=["***" "testing"]
| Hello ***
```

The 1st one is always shown as `***` (Act & echo command) is this because I am reading it from a secret file ?
The second value which is passed from an env file is totally not visible

How to I print variables when debugging the action ?
