### DISCUSSION TITLE
getting debug information

### DISCUSSION THREAD

**Discussion by earl-warren** [nektos/act#1695] [General]
I'm trying to figure out how to use https://github.com/softprops/action-gh-release and it fails with

```
[Main/build] [DEBUG] Extracting content from '/tmp/act2147392109' to '/var/run/act/actions/https---github.com-softprops-action-gh-release@v1/'
[Main/build] [DEBUG] executing remote job container: [node /var/run/act/actions/https---github.com-softprops-action-gh-release@v1/dist/index.js]
[Main/build]   🐳  docker exec cmd=[node /var/run/act/actions/https---github.com-softprops-action-gh-release@v1/dist/index.js] user= workdir=
[Main/build] [DEBUG] Exec command '[node /var/run/act/actions/https---github.com-softprops-action-gh-release@v1/dist/index.js]'
[Main/build] [DEBUG] Working directory '/tmp/test-gh-release'
[Main/build]   ❗  ::error::Cannot read properties of undefined (reading 'indexOf')
[Main/build]   ❌  Failure - Main Release
[Main/build] exitcode '1': failure
[Main/build] [DEBUG] skipping post step for 'Checkout': no action model available
[Main/build] 🏁  Job failed
[Main/build] [DEBUG] Found revision: 62b483ce290f1b20ab3751e9b540898e08bba6eb
Error: Job 'build' failed
```

Is there a way to get a stack trace for `[Main/build]   ❗  ::error::Cannot read properties of undefined (reading 'indexOf')`? It is likely not ACT but the action itself failing because of ... don't know what.

```
name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: https://github.com/softprops/action-gh-release@v1
        with:
          files: Release.txt
```

and run with:

```
$ git clone https://code.forgejo.org/earl-warren/test-gh-release
$ cd test-gh-release
$ act --actor earl-warren/test-gh-release --github-instance code.forgejo.org --env ACTIONS_STEP_DEBUG=true --env GITHUB_REF=refs/tags/v1.1.1 --secret GITHUB_TOKEN=xyz -W .forgejo/workflows/try.yml
```

Any idea?
