### DISCUSSION TITLE
Use with Github matrix

### DISCUSSION THREAD

**Discussion by andrzejnovak** [nektos/act#1736] [Q&A]
New user question here. I have a CI that I wanted to test locally which runs with a matrix 
```
  test:
    name: "🐍 ${{ matrix.python-version }} • ${{ matrix.runs-on }}"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.10", "3.11"]
        include:
        - runs-on: macOS-latest
          python-version: "3.7"
        - runs-on: macOS-latest
          python-version: "3.11"
```

How can I run only single one of these (preferrably without modifying the workflow file). If I simply run `act` in the repo I get an error like 
```
[CI/🐍 3.7 • ubuntu-latest-1      ]   ❌  Failure - Set up Python ${{ matrix.python-version }}
Error: The runs.using key in action.yml must be one of: [docker node12], got node16
```
presumably, because the available docker doesn't have the right python version, and either way won't have all the python versions.

I am hopping there's a better option than sth like creating a new docker image with conda envs for each python version and modding the action to use conda envs instead of the GHA matrix.
