### DISCUSSION TITLE
run the workflow using act returns: Permission denied (publickey).

### DISCUSSION THREAD

**Discussion by askb** [nektos/act#1832] [General]
Trying to run the workflow using act returns `git@github.com: Permission denied (publickey).`. 
While `ssh -T git@github.com` works without any issues. I've added the known_hosts under repo -> settings -> Actions -> secrets and vars -> known_hosts.  What am I missing ?

```
CD/build]   🐳  docker exec cmd=[node /var/run/act/actions/stefanzweifel-git-auto-commit-action@v4/index.js] user= workdir=
| Started: bash /run/act/actions/stefanzweifel-git-auto-commit-action@v4/entrypoint.sh
[CD/build]   💬  ::debug::git binary found.
| INPUT_REPOSITORY value: .
| INPUT_STATUS_OPTIONS: 
[CD/build]   💬  ::debug::Apply status options 
| INPUT_FILE_PATTERN: .
| INPUT_BRANCH value: 
| git@github.com: Permission denied (publickey).
| fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.
| Error: Invalid status code: 128
|     at ChildProcess.<anonymous> (/run/act/actions/stefanzweifel-git-auto-commit-action@v4/index.js:17:19)
|     at ChildProcess.emit (node:events:513:28)
|     at maybeClose (node:internal/child_process:1100:16)
|     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
|   code: 128
| }
| Error: Invalid status code: 128
|     at ChildProcess.<anonymous> (/run/act/actions/stefanzweifel-git-auto-commit-action@v4/index.js:17:19)
|     at ChildProcess.emit (node:events:513:28)
|     at maybeClose (node:internal/child_process:1100:16)
|     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
[CD/build]   ❌  Failure - Main Commit changes
[CD/build]   ⚙  ::set-output:: changes_detected=true
[CD/build] exitcode '128': failure
[CD/build] 🏁  Job failed
```

My  GHA workflow file:

```
name: deploy-test-daily

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v2
      - name: act
        if: ${{ env.ACT }} # This is on the master only
        run: |
          apt update -y
          apt install -y sudo python3 python3-pip

      - name: Build
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          sudo apt update -y
          sudo apt install -y jq
          bash -x ./build.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update
          commit_options: '--amend'
          push_options: '--force'
```
