### DISCUSSION TITLE
Does act support the container attribute?

### DISCUSSION THREAD

**Discussion by thirtytwobits** [nektos/act#1851] [Q&A] [answered]
I'm trying to use act for the first time but we run all of our project's actions in our own containers hosted on ghcr (publicly). e.g.:

```
jobs:
  verification:
    runs-on: ubuntu-latest
    container: ghcr.io/opencyphal/toolshed:ts22.4.3
    strategy:
...
```

Does act actually support this? I can't find any documentation about it and it just fails when I try with:

```
[libcyphal_test/verification-2] 🚀  Start image=ghcr.io/opencyphal/toolshed:ts22.4.3
...
[libcyphal_test/verification-2]   🐳  docker pull image=ghcr.io/opencyphal/toolshed:ts22.4.3 platform= username= forcePull=true
...
[libcyphal_test/verification-3] using DockerAuthConfig authentication for docker pull
Error: Error response from daemon: Head "https://ghcr.io/v2/opencyphal/toolshed/manifests/ts22.4.3": denied: denied
```

Again, these containers are fully public so no authorization is needed. 

Anyway, just wanted to be sure I wasn't wasting my time trying to get something to work that isn't supported. Any documentation on this would be appreciated.
