### DISCUSSION TITLE
How do I delete the actions cache?

### DISCUSSION THREAD

**Discussion by memchr** [nektos/act#1936] [Q&A]
The actions cache can be deleted with [REST API](https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-github-actions-caches-for-a-repository-using-a-cache-key), for example when running the workflows in a github hosted runner, 

```yml
- name: Remove old build cache
        shell: bash
        run: |
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" -X DELETE "$GITHUB_API_URL/repos/${{ github.repository }}/actions/caches?key=$CACHE_KEY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CACHE_KEY: ccache
```

How do I delete the actions cache from the workflow using act?
