### DISCUSSION TITLE
How can I get the actual workflow Job Id for composite jobs?

### DISCUSSION THREAD

**Discussion by mverkerk-godaddy** [nektos/act#1976] [Q&A]
I'm testing a library of github actions that uses composite jobs. When i run a workflow that uses these composite jobs, ACT sets the environment variable `GITHUB_JOB` to `composite-job` even though the job in the workflow has it's own ID.

Here's an example:

`./.github/workflows/test.yml`
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/my-composite
```

`./.github/actions/my-composite/action.yml`
```yaml
name: my-composite
description: description

runs:
  using: composite
  steps:
    - name: Print env vars
      shell: bash
      run: |
        echo "env.GITHUB_JOB: ${{ env.GITHUB_JOB }}"
```

When I run this, the (truncated) act output looks like this:

```bash
...
[local-simple/build] ⭐ Run Main actions/checkout@v3
[local-simple/build]   🐳  docker cp src=/... dst=/...
[local-simple/build]   ✅  Success - Main actions/checkout@v3
[local-simple/build] ⭐ Run Main ./.github/actions/my-composite
[local-simple/build] ⭐ Run Main Print env vars
[local-simple/build]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2-composite-0.sh] user= workdir=
[local-simple/build]   | env.GITHUB_JOB: composite-job
[local-simple/build]   ✅  Success - Main Print env vars
[local-simple/build]   ✅  Success - Main ./.github/actions/my-composite
[local-simple/build] ⭐ Run Post ./.github/actions/my-composite
[local-simple/build]   ✅  Success - Post ./.github/actions/my-composite
[local-simple/build] 🏁  Job succeeded
```

Notice the output is printing `env.GITHUB_JOB: composite-job` - I would expect this to be `build` instead of `composite-job`

is there another variable somewhere? what is the implication of setting `GITHUB_JOB` to the actual workflow job-id?

I believe the related code is here:
https://github.com/nektos/act/blob/7ba9f30f37af627f43adc2776c7f39ca3b5889bc/pkg/runner/action_composite.go#L56
