### DISCUSSION TITLE
SSH Failing Unexpectedly

### DISCUSSION THREAD

**Discussion by andrewvaughan** [nektos/act#2035] [General]
Hello all -

I've been using https://github.com/nektos/act for a few months now with great results. Suddenly, a bunch of my repositories are failing for reasons seeming to do with SSH, but I'm struggling to get to the bottom of the problem.

Also, in the same time period, I have never been able to get `act` to complete a script. It always just hangs, regardless of what is being done. No errors or messages in the verbose logs, just hanging whether successful or failing. I even went back a few versions and still have the issue. I don't know if these are two issues from the same problem, but I'm having a very difficult time working at the moment.

My gut tells me that `act` is making an SSH call to ... something (likely GitHub) ... behind the scenes and is getting a prompt that is not handled well in the container and is just causing a hang, but with limited insight into what's going on, it's hard to tell.

Any ideas or help would be extremely appreciated.

|    |    |
| -: | :- |
| Device | MacBook Pro M2, 2022 |
| OS     | macOS Ventura 13.5.2 |
| `act`  | v0.2.52 (tested down to v0.2.49 |
| `docker` | 23.0.5, build bc4487a |

---

Suddenly, all of my https://github.com/actions/checkout calls started hanging with no errors or details, even with verbose logging.

I finally got to the point where I think that there is a prompt somewhere that the system is waiting for - either confirming a host or entering a password, neither of which make sense to me. I was using 1Password as an `IdentityHost` for SSH on my local development machine, which required fingerprint access to clone repositories, so I disabled that, but I still have the issue.

I was able to confirm that the token I was sending with `-s "$(gh auth token)` was valid by calling the GitHub API with `curl`, so I was really hitting my head on the desk as to what the issue was.

In another repository, I tried running `act` against a known-working oxsecurity/megalinter workflow. This also failed during a checkout, but I was able to get more information:

```
| The authenticity of host 'github.com (140.82.114.3)' can't be established.
| ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
| This key is not known by any other names.
```

I had never seen this error before - it seemed really unusual. The megalinter workflow has configuration options for `PRE_COMMANDS` so I added the following to be run first:

```
PRE_COMMANDS:
  - command: apk add --no-cache ca-certificates
    cwd: root
  - command: curl -L -o /usr/local/share/ca-certificates/RootCA.crt http://path.to.cert
    cwd: root
  - command: curl -L -o /usr/local/share/ca-certificates/IssueCA.crt http://path.to.cert
    cwd: root
  - command: update-ca-certificates
    cwd: root
  - command: mkdir ~/.ssh && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
    cwd: root
```

The last command scanning the `github.com` keys and adding them all to known hosts. Running again, the error changed:

```
|   stderr: 'git@github.com: Permission denied (publickey).
| fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.'
```

I have never had an issue pulling a private repository with this token before... so this is really surprising.

And that's where I am at. I've had this happen with `act` versions 0.2.49, 0.2.51, and 0.2.52 (latest release).

This is the more or less the command I'm running (you can see the exact command at the top of each of the logs below):

```bash
act --rm --container-architecture linux/amd64 -s "$(gh auth token)" pull_request
```

And here are the workflows and their (sanitized) verbose logs:

---

```yaml
---
name: Issue Progress on Branch Created

on: create

jobs:

  label_issue_on_branch_create:
    name: Label Issue on Branch Create
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read
      issues: write
      statuses: read

    steps:

      # Check out our repository to gain access to workflow scripts
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}

      # ... (more steps that do not get run due to failure) ...
```

[Verbose Logs for Above](https://gist.github.com/andrewvaughan/589ea3624e76cbc02bf96d6a2ba8d74d)

The system hangs indefinitely at the end of that log.

---

```yaml
---
name: MegaLinter

on:
  # Trigger mega-linter at every push. Action will also be visible from Pull Requests to master
  # push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  pull_request:
    branches: [main, production, staging]

# Comment env block if you do not want to apply fixes
env:
  # Apply linter fixes configuration
  #
  # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other
  # CI tool)
  APPLY_FIXES: all

  # Decide which event triggers application of fixes in a commit or a PR (pull_request, push, all)
  APPLY_FIXES_EVENT: pull_request

  # If APPLY_FIXES is used, defines if the fixes are directly committed (commit) or posted in a PR (pull_request)
  APPLY_FIXES_MODE: commit

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest

    # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
    # Remove the ones you do not need
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

          # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to improve performances
          fetch-depth: 0

      # ... (more steps that do not get run due to failure) ...
```

[Verbose Logs for Above](https://gist.github.com/andrewvaughan/f6683c9e0db71cdc1d2a2e62a6f21e91)

The logs above include the `PRE_COMMANDS` listed adding the `known_hosts` to remove all doubt, but I have a feeling this is all intertwined into whatever the issue is. I've never had to manually create known hosts like that before in the `act` Docker container.

---

Thanks again... any help would be extremely appreciated as all of my projects are currently stuck with this ongoing issue.
