### DISCUSSION TITLE
Respecting the health check for services

### DISCUSSION THREAD

**Discussion by delasteve** [nektos/act#2096] [Q&A]
Currently, I have a service set up as the following (removed later steps)

```yml
jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: some_root_password
          MYSQL_DATABASE: some_database
          MYSQL_USER: some_user
          MYSQL_PASSWORD: some_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - run: echo "MYSQL_DOCKER_ID=$(docker ps | grep 'mysql:' | awk '{ print $1 }')" >> "$GITHUB_ENV"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Seed database
        run: |
          docker exec -i $MYSQL_DOCKER_ID sh -c 'exec mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE"' < ./data/seed.sql
          
```

This works on GitHub, but when I try it with `act` it fails with the following:

```
| ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

If I were to add a `sleep 10` to the seed step, it works as I would expect it to. However, I'd like to not do this as it is a change specifically to get it working with `act`, not GitHub. Is there a way to have the health check not be ignored?

`act --bug-report`
```
act version:            0.2.54
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
        $HOME/.docker/run/docker.sock
Config files:           
        /Users/stephen/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.21.4
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.54
                DefaultGODEBUG:       panicnil=1
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               amd64
                GOOS:                 darwin
                GOAMD64:              v1
Docker Engine:
        Engine version:        24.0.6
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               x86_64
        OS kernel:             6.4.16-linuxkit
        OS CPU:                8
        OS memory:             7947 MB
        Security options:
                name=seccomp,profile=unconfined
                name=cgroupns
```
