### DISCUSSION TITLE
Mounting volumes into docker

### DISCUSSION THREAD

**Discussion by nnyiri** [nektos/act#2100] [Q&A]
Hi everyone.

My question is related to https://github.com/nektos/act/issues/410.

I try to use the files in docker compese, by binding them.
But as it will run on my host docker, it doesn't find it.
Even using the --bind flag in act doesn't help?

Is there a solution?

Action
```
version: '3.8'
services:
  nginx-main:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${HOST}
``` 

docker-compose.yml
```
version: '3.8'
services:
  nginx-main:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=${HOST}
```
