### DISCUSSION TITLE
Job is being skipped regardless "if" condition.

### DISCUSSION THREAD

**Discussion by serious-angel** [nektos/act#2275] [Q&A] [answered]
Dear Developers,

Thank you very much for the awesome project! ✨ 

Currently, I am trying to use [Gitea](https://gitea.com/gitea/act_runner) `v1.21.10` for Action Workflows.

---

<details>
<summary>Workflow test case</summary>

```yaml
name: 'Deployment Workflow'

on:
  push:
    branches:
      - 'test'
      - 'releases/**'

jobs:

  environment-job:
    name: 'Environment'
    runs-on: 'ubuntu-latest'

    outputs:
      TEST: 'true'

    steps:
      - name: 'Environment Test'
        run: date;

  build-job:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    needs: 'environment-job'
    if: ${{ needs.environment-job.outputs.TEST != 'true' }}

    steps:
      - name: 'Build Test'
        id: 'build-test'
        run: date;

  deploy-job:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    needs: 'build-job'

    if: |
      always() &&
      (needs.build-job.result == 'success' || needs.build-job.result == 'skipped')

    steps:
      - name: 'Deploy Test'
        id: 'deploy-test'

        run: date;

```
</details>

---

In the result, the both jobs get skipped:

![image](https://github.com/nektos/act/assets/25136754/edbf1fb7-bf56-40c5-9c37-cd9993b8afb8)

---

May I ask why does it not run job "Deploy" when job "Build" is marked "skipped"?

Best and kind regards
