### DISCUSSION TITLE
Attempting to use act to validate a simple github actions CI workflow for rust project

### DISCUSSION THREAD

**Discussion by NathanFrasier** [nektos/act#2386] [Q&A] [answered]
Hi all, I am unsure what the issue is with trying to use act to test a simple workflow for a rust project. I get this error when running: `/var/run/act/workflow/1: line 2: cargo: command not found`. 

I'm not sure where the issue is, because I thought `cargo` would be installed in the "medium" image that I selected on first run.
I don't know if there's an issue with this workflow, because I'm trying to validate it before committing it to my public repo.

I'm running like this: `gh act --workflows .github/workflows/ci.yaml` and my workflow file as as below: 
```
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [1.74.1, stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo +${{ matrix.rust }} build --verbose
    - name: Run tests
      run: cargo +${{ matrix.rust }} test --verbose

```

Any help would be appreciated. Thanks!
