### DISCUSSION TITLE
actions/checkout fails `with:` `ref: ${{ github.event.pull_request.head.sha }}` with un-pushed commits

### DISCUSSION THREAD

**Discussion by brianjmurrell** [nektos/act#2391] [Q&A]
If I have a step:

```
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
```

When I have local commits that I have not pushed remotely, the checkout action fails since `github.event.pull_request.head.sha` doesn't exist on GitHub yet, as I have not pushed it.

How do I simulate a checkout on the code that is only in my local repo?  I.e. that I have not yet pushed.

Surely I don't have to push my local commits.  The entire point of using `act` is to test my code locally before pushing it.

Reference: https://github.com/actions/checkout/blob/v3.0.2/README.md#checkout-pull-request-head-commit-instead-of-merge-commit

**Comment by jj-triff-kr** [comment]
This was the work-around I used to overcome this:

```yml
      - uses: actions/checkout@v4
        if: ${{!env.ACT}}
        with:
          ref: branch/name
      - uses: actions/checkout@v4
        if: env.ACT
      - run: git fetch origin
        if: env.ACT
      - run: git checkout --force branch/name
        if: env.ACT
```
