### DISCUSSION TITLE
Use reusable workflow with composite actions from private repository

### DISCUSSION THREAD

**Discussion by wouter-heerwegh** [nektos/act#2470] [Q&A]
Hi,

I'm trying to use a reusable workflow from a private repository, I read something about the `local-repository` parameter, but am currently not using it. Instead I use a the local path directly. The reusable workflow seems to load, but I get an authorization error when trying to use composite actions inside this reusable workflow.

The workflow that is called first looks like this:
```yaml
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./../../../path/.github/workflows/build.yml
```

The reusable workflow looks like this:
```yaml
name: Build reusable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Build
      uses: org/repo/.github/actions/build@main

    - name: linting
      uses: org/repo/.github/actions/lint@main
```
I've tried passing a PAT that works on github, but it does not seem to change anything.

Does anyone have an idea if I'm doing something wrong?
