### DISCUSSION TITLE
How to get container volumes to work locally and remotely?

### DISCUSSION THREAD

**Discussion by flixman** [nektos/act#2475] [Q&A]
In my github workflow I am running everything though podman-in-podman. In the workflow I have the following block:

```yaml
jobs:
    build:
        runs-on: registry.org/gitea/runners/podman:extended
        container:
            image: registry.org/gitea/runners/podman:extended
            volumes:
                - /mnt/act_runner/buildah-cache:/var/tmp/buildah-cache-1000
```
The problem I have is: when running this workflow locally, /mnt/act_runner/buildah-cache usually does not exist. I have tried using an env variable, but seems this is not supported (and the runner takes "${{ env.BUILDAH_CACHE }}" as a literal, complaining it is not a valid name - which is true). Is this a use case that is not supported, or am I doing something wrong?
