### DISCUSSION TITLE
Is there a change for loading .env and .secrets file?

### DISCUSSION THREAD

**Discussion by liyangau** [nektos/act#2504] [Q&A] [answered]
Hi everyone,

I noticed my local workflow stopped working and I was getting a lot of error complaining the env and secrets are Unknown

```text
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock'
Error: workflow is not valid. 'onboarding_push.yaml': Line: 22 Column 5: Failed to match job-factory: Line: 29 Column 28: Unknown Variable Access secrets
Line: 30 Column 36: Unknown Variable Access secrets
Line: 32 Column 21: Unknown Variable Access env
Line: 22 Column 5: Failed to match workflow-job: Line: 23 Column 5: Unknown Property runs-on
Line: 29 Column 28: Unknown Variable Access secrets
Line: 30 Column 36: Unknown Variable Access secrets
Line: 31 Column 5: Unknown Property env
Line: 33 Column 5: Unknown Property steps
Line: 91 Column 5: Failed to match job-factory: Line: 99 Column 28: Unknown Variable Access secrets
Line: 100 Column 36: Unknown Variable Access secrets
Line: 108 Column 21: Unknown Variable Access env
Line: 91 Column 5: Failed to match workflow-job: Line: 93 Column 5: Unknown Property runs-on
Line: 99 Column 28: Unknown Variable Access secrets
Line: 100 Column 36: Unknown Variable Access secrets
Line: 107 Column 5: Unknown Property env
Line: 110 Column 5: Unknown Property steps
```

I have `.env` and `.secrets` in the folder and reference the secret as below

```yaml
  check-global-configs:
    name: Check global configs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev]
        include:
          - env: dev
            ADMIN_API_URL: ${{ secrets.DEV_ADMIN_API_URL }}
```
This used to work pretty well... Does anyone know what had changed?
