### DISCUSSION TITLE
Using act.

### DISCUSSION THREAD

**Discussion by Pudding707** [nektos/act#2686] [General]
Hello:-)!
I'm just learning the usage of `GitHub Actions`. For my convenience and ease of use I've installed `act `for local use. As a starting point I'm using the following workflow:
```
name: output_test1_
on:
  workflow_dispatch:

jobs:
  out_test:
    name: out_Test1
    runs-on: ubuntu-latest
    steps:
      - uses: gh640/command-result-action@v1
        id: cra
        with:
          command: date
      - run: |
          {
            echo "the current date is: ${CRA_STDOUT}"
          }
        env:
          CRA_STDOUT: ${{ steps.cra.outputs.stdout }}
```
```
which produces the below output:
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock'
[output_test1_/out_Test1] ⭐ Run Set up job
[output_test1_/out_Test1] 🚀  Start image=catthehacker/ubuntu:act-latest
[output_test1_/out_Test1]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[output_test1_/out_Test1]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[output_test1_/out_Test1]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[output_test1_/out_Test1]   🐳  docker exec cmd=[node --no-warnings -e console.log(process.execPath)] user= workdir=
[output_test1_/out_Test1]   ✅  Success - Set up job
[output_test1_/out_Test1]   ☁  git clone 'https://github.com/gh640/command-result-action' # ref=v1
[output_test1_/out_Test1] ⭐ Run Main gh640/command-result-action@v1
[output_test1_/out_Test1]   🐳  docker cp src=/root/.cache/act/gh640-command-result-action@v1/ dst=/var/run/act/actions/gh640-command-result-action@v1/
[output_test1_/out_Test1]   🐳  docker exec cmd=[/opt/acttoolcache/node/18.20.5/x64/bin/node /var/run/act/actions/gh640-command-result-action@v1/dist/index.js] user= workdir=
| Starting command.
[output_test1_/out_Test1]   ❓  ::group::command
| [command]/usr/bin/date
| Wed Feb 26 14:34:59 UTC 2025
[output_test1_/out_Test1]   ❓  ::endgroup::
| Finished command.
[output_test1_/out_Test1]   ✅  Success - Main gh640/command-result-action@v1
[output_test1_/out_Test1]   ⚙  ::set-output:: stderr=
[output_test1_/out_Test1]   ⚙  ::set-output:: exitCode=0
[output_test1_/out_Test1]   ⚙  ::set-output:: stdout=Wed Feb 26 14:34:59 UTC 2025
[output_test1_/out_Test1] ⭐ Run Main {
  echo "the current date is: ${CRA_STDOUT}"
}
[output_test1_/out_Test1]   🐳  docker exec cmd=[bash -e /var/run/act/workflow/1] user= workdir=
| the current date is: Wed Feb 26 14:34:59 UTC 2025
|
[output_test1_/out_Test1]   ✅  Success - Main {
  echo "the current date is: ${CRA_STDOUT}"
}
[output_test1_/out_Test1] ⭐ Run Complete job
[output_test1_/out_Test1] Cleaning up container for job out_Test1
[output_test1_/out_Test1]   ✅  Success - Complete job
[output_test1_/out_Test1] 🏁  Job succeeded
```
As you can see there is a lot of extra debugging info printed automatically. Is there a way to disable/suppress printing this debugging info? Is there a way to run/use the script such a way that the only output would be the output from my own code - which I've explicitly written, e.g. using the echo command? All I want to see is `the current date is: Wed Feb 26 14:34:59 UTC 2025` line.
Thx for help in advance!
