### DISCUSSION TITLE
Nesting shared workflows. Inputs don't seem to be set properly.

### DISCUSSION THREAD

**Discussion by robbiesz** [nektos/act#5036] [General]
I have a shared workflow (eg, multi-step build process of a component) which I need to call from another shared workflow (eg. building multiple components). I concocted the following re-pro:

Inner shared workflow:
```
name: inner.yml
on:
  workflow_call:
    inputs:
      first-param:
        description: "First parameter"
        type: string
        required: true
      second-param:
        description: "Second parameter"
        type: string
        required: true

jobs:
  print:
    runs-on:
      group: runners
    steps:
      - name: Print parameters
        shell: bash
        run: |
          echo "First parameter: ${{ inputs.first-param }}"
          echo "Second parameter: ${{ inputs.second-param }}"
```

The calling shared workflow looks like this:
```
name: caller.yml
on:
  workflow_call:
    inputs:
      first-param:
        description: "First parameter"
        type: string
        required: true

jobs:
  call-inner:
      name: "Let's call the inner shared workflow"
      uses: ./.github/workflows/inner.yml
      with:
        first-param: "${{ inputs.first-param }}"
        second-param: "This is the value of the second parameter"
```

I invoke act like: `act -v -W .github/workflows/caller.yml -P runners=-self-hosted --input first-param="Value of the first parameter"`

My expectation would be to see:
```
First parameter: Value of the first parameter
Second parameter: This is the value of the second parameter
```

but instead I see:
```
First parameter: Value of the first parameter
Second parameter: 
```

The second-param doesn't get set by caller.yml

My question is, is this a bug, or am I misunderstanding how shared workflows use input parameters?

Thanks!
