### ISSUE TITLE
Issue: cp: cannot stat 'js/config.dist.ts': No such file or directory

### ISSUE THREAD

**Issue by KonradHoeffner** [nektos/act#1002]
## System information

    - Operating System: Arch Linux
    - Architecture:x64 (64-bit)
    - Apple M1: no
    - Docker version: 20.10.12
    - `act` version: 0.2.25

## Expected behaviour

The workflow, which works on GitHub actions, should work locally with act.

## Actual behaviour
It throws an error  `cp: cannot stat 'js/config.dist.ts': No such file or directory`.
However that file exists at `repo/js/config.dist.ts`.

## Workflow and/or repository

<https://raw.githubusercontent.com/snikproject/snik-graph/da80e8c2ab07a5bf68fb0575706ef4ad5d23a27a/.github/workflows/build.yml>

<details>
  <summary>workflow</summary>

```yml
name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: |
          cp js/config.dist.ts js/config.ts
          npm install --ignore-scripts --production --no-audit

      - name: Test
        run: |
          npm run test

      - name: Build
        run: |
          npm run build
          sed -i "s|/assets|./assets|" dist/index.html
          cp -r html dist
          cp -r img dist

      - name: Doc
        run: |
          npm run doc
          cp -r doc dist 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
```

</details>

## Steps to reproduce

      1. `git clone git@github.com:snikproject/snik-graph.git`
      2. Enter cloned repo directory
      3. git checkout 6029745341016d37a87a68c82e2bd48262364ad6
      4. Run `act .github/workflows/build.yml -j build`

## The act log is in the comment because of a GitHub content length error
