### ISSUE TITLE
Issue: Error in if expression return code 0.

### ISSUE THREAD

**Issue by mvrshvl** [nektos/act#1008]
## System information
  - Operating System: Linux
  - Architecture: x64 (64-bit)
  - Docker version: 20.10.12
  - Docker image used in `act`: golang:1.16.5-alpine
  - `act` version: act version 0.2.25-41-gff13844-dirty

## Expected behaviour
The act returns a non-zero error code about an incorrectly described yaml file 

## Actual behaviour

The act returns an error log, but the exit code is 0.

Trace with nil error:

https://github.com/nektos/act/blob/e23223ad02ddeafe581df97c7e9462df28d8e104/pkg/runner/run_context.go#L278

https://github.com/nektos/act/blob/7dbf3fcb96e2d70b3436b718c1f4a9fe4b169a4f/pkg/common/executor.go#L153

https://github.com/nektos/act/blob/e23223ad02ddeafe581df97c7e9462df28d8e104/pkg/runner/run_context.go#L414

https://github.com/nektos/act/blob/7dbf3fcb96e2d70b3436b718c1f4a9fe4b169a4f/pkg/common/executor.go#L156

## Workflow and/or repository
```
jobs:
  lints:
    if: something
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container: golang:1.16.5-alpine
    steps:
      - uses: actions/checkout@v1
```
## Steps to reproduce

Run a workflow with the same job as in the step `Workflow and/or repository`.

## `act` output

[GitHub Actions/lints]   ❌  Error in if: expression - lints
