### ISSUE TITLE
Issue: parse all container/services options

### ISSUE THREAD

**Issue by catthehacker** [nektos/act#1022]
```
on: push

jobs:
  docker-container:
    runs-on: ubuntu-latest
    container:
      image: alpine
      options: --it --rm
    steps:
      - uses: actions/checkout@v2
```

**Comment by bhaveshprajapat** [comment]
bump

**Comment by KnisterPeter** [comment]
@cplee @alex-savchuk This change contains a major issue. The workflow below does not return the hostname of the host but some other invalid fqdn.
I'm not sure why this happens, but it is a side-effect of this PR. Reverting it does restore the previous behavior.

```yaml
name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: hostname -f
```
