### ISSUE TITLE
Issue: Error: file does not exist with reusable workflows

### ISSUE THREAD

**Issue by vladimirzatsepin** [nektos/act#1033]
## Setup

I have the following `.github/workflows/main.yaml`:
```yaml
name: Call workflow

on:
  workflow_dispatch:

jobs:
  call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: call_workflow
        uses: ./.github/workflows/called.yml
```

And `.github/workflows/called.yml`:
```yaml
on:
  workflow_call:

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello!"
```

Run command:

```
act -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-20.04 workflow_dispatch -j call_workflow
```

## Expected behaviour
"Hello!" printed.

## Actual behaviour
[Call workflow/call_workflow] 🚀  Start image=act
[Call workflow/call_workflow]   🐳  docker run image=act platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Call workflow/call_workflow]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[Call workflow/call_workflow] ⭐  Run call_workflow
[Call workflow/call_workflow]   ❌  Failure - call_workflow
**Error: file does not exist**

**Comment by ChristopherHX** [comment]
### My Expected behaviour
**Error: file does not exist**
I agree this error should be improved

### Reason
None of the following files are found: 
- `./.github/workflows/called.yml/action.yml`
- `./.github/workflows/called.yml/action.yaml`
- `./.github/workflows/called.yml/Dockerfile`

## Correctly calling workflows
**Act doesn't support reusable workflows yet ( https://github.com/nektos/act/issues/826 )**

`.github/workflows/main.yaml`
```yaml
name: Call workflow

on:
  workflow_dispatch:

jobs:
  call_workflow:
    uses: ./.github/workflows/called.yml
```
