### ISSUE TITLE
Enhancement: Support Conditionals in Composite Actions 

### ISSUE THREAD

**Issue by ajrice6713** [nektos/act#1035]
## Describe feature

Github added support for conditionals in composite actions in [Nov 2021](https://github.blog/changelog/2021-11-09-github-actions-conditional-execution-of-steps-in-actions/) but it does not seem they are supported in act.

Ex: 

```yml
# ./action.yml
name: Composite Conditional Test
inputs: 
 my-input:
    description: '`a` or `b` - where to clone the api specs from'
    default: a
    required: false

runs: 
  using: composite
  steps: 
    - name: Check inputs 
      run: |
        echo '${{ inputs.file-source }}'
      shell: bash

    - name: check for a
      if: inputs.file-source == 'local'
      run: |
        echo 'you entered a'  
      shell: bash
    
    - name: check for b
      if: inputs.file-source == 'remote'
      run: |
        echo 'you entered b'
      shell: bash
```

```yml
# ./.github/workflows/test.yml

name: Test
on: [workflow_dispatch]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2 

      - name: Run Test
        uses: ./ 
        with: 
           my-input: b
```

Output: 
```sh
b
you entered a
you entered b
```

It seems the conditionals are being ignored and that conditionals are not defined in the [`ActionRuns` schema](https://github.com/nektos/act/blob/3db3c737230adc457e08a8d60b34458977d01e5c/pkg/model/action.go#L48)
