### ISSUE TITLE
Issue: actions/checkout@v2 with lfs: true doesn't get file

### ISSUE THREAD

**Issue by davetapley** [nektos/act#1042]
_I will fill this out more later but wanted to get a placeholder in, apologies._

I have
```yml
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
```

When pushing to GitHub and running on Actions it gets file:

```
-rw-r--r--  1 runner docker 185M Mar 14 21:27 dependencies.tar
```

But when running with `act` it doesn't get the file (and so `tar` fails):

```
| -rw-rw-rw-  1 1000 root  134 Aug 24  2021 dependencies.tar
```

Known issue?
