### ISSUE TITLE
Error in if-expression

### ISSUE THREAD

**Issue by jonny7** [nektos/act#1071]
Thanks very much for this project 🙂 

## System information

    - Operating System: macOS
    - Architecture: x64 (64-bit)
    - Apple M1: no 
    - Docker version: 20.10.12
    - `act` version: 0.2.26

## Expected behaviour

I have been running this element of a pipeline fine with `0.2.25` last night. I've just updated and I'm getting errors now around the if statement. So I would expect that this would continue to work and it works on GitHub, see here for [reproducible ](https://github.com/jonny7/act-example/runs/5659657478?check_suite_focus=true)

## Actual behaviour

Calling 
```yaml
if: contains(github.event.pull_request.labels.*.name, 'skip-ci')
``` 
fails with 

```
❌  Error in if-expression: "if: contains(github.event.pull_request.labels.*.name, 'skip-ci')" (Unable to dereference 'name' on non-struct 'invalid')
```

## Workflow and/or repository

[Repo](https://github.com/jonny7/act-example) has a working example that works on GH and did on 0.2.25 of act. The relevant workflow is this

```yaml

on:
  pull_request

jobs:
  skip-pipeline:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.set-skip.outputs.skip || false }}
    steps:
      - name: Set skip output var
        id: set-skip
        if: contains(github.event.pull_request.labels.*.name, 'skip-ci')
        run: echo "::set-output name=skip::true"
```

## Steps to reproduce

The pipeline I'm using it with was based on `pull_request`, so  `act pull_request`.

## `act` output

```
DEBU[0000] evaluating expression 'contains(github.event.pull_request.labels.*.name, 'skip-ci')' 
DEBU[0000] expression 'contains(github.event.pull_request.labels.*.name, 'skip-ci')' evaluated to '%!t(<nil>)' 
[Integration Testing/skip-pipeline]   ❌  Error in if-expression: "if: contains(github.event.pull_request.labels.*.name, 'skip-ci')" (Unable to dereference 'name' on non-struct 'invalid')
```
