### ISSUE TITLE
conditional steps incorrectly evaluates conclusion

### ISSUE THREAD

**Issue by BrianHung** [nektos/act#1109]
```
| {
|   "0": {
|     "outputs": {},
|     "conclusion": "success",
|     "outcome": "success"
|   },
|   "4": {
|     "outputs": {},
|     "conclusion": "success",
|     "outcome": "success"
|   },
|   "cache": {
|     "outputs": {
|       "cache-hit": "false"
|     },
|     "conclusion": "success",
|     "outcome": "success"
|   },
|   "install": {
|     "outputs": {},
|     "conclusion": "success",
|     "outcome": "success"
|   },
|   "setup": {
|     "outputs": {},
|     "conclusion": "success",
|     "outcome": "success"
|   }
| }
[build]   ✅  Success - Dump GitHub context
DEBU[0106] Loading slug from git directory '/Users/brian/web/.git' 
DEBU[0106] Loading revision from git directory '/Users/brian/web/.git' 
DEBU[0106] Found revision: c9ca2d85b3e7ee4ea4efa35cf435916bf616d042 
DEBU[0106] HEAD points to 'c9ca2d85b3e7ee4ea4efa35cf435916bf616d042' 
DEBU[0106] Found revision: c9ca2d85b3e7ee4ea4efa35cf435916bf616d042 
DEBU[0106] evaluating expression 'steps.install.conclusion == 'success'' 
DEBU[0106] expression 'steps.install.conclusion == 'success'' evaluated to 'false' 
DEBU[0106] Skipping step 'Vitest' due to 'steps.install.conclusion == 'success'' 
```

```
on:
  push:
    branches: [development, staging]
  pull_request:
    branches: [development, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        id: setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        id: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(steps) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Vitest
        id: test
        if: steps.install.outcome == 'success'
        run: npm test
        continue-on-error: true

      - name: Typescript compiler
        id: typescript
        if: steps.install.outcome == 'success'
        run: npm run tsc
        continue-on-error: true
```

Expected behavior is that `steps.install.outcome == 'success'` evaluates to true, matching the result from the context log.
