### ISSUE TITLE
Issue: act not checking out in composite actions

### ISSUE THREAD

**Issue by alexharv074** [nektos/act#1112]
## System information

- Operating System: Mac OS X
- Architecture: ARM
- Docker version: 20.10.12
- Docker image used in `act`: custom
- `act` version: latest

## Contents of project dir

```text
▶ pwd
▶ ls -1
CODEOWNERS
README.md
foo.yaml
pull-request.json
```

## Workflow file

```yaml
---
name: PR Check values files

on:
  pull_request:
    branches: [master]

jobs:
  pr-tests:
    runs-on: example-base
    steps:
      - name: Run tests against the PR
        uses: example-org/private-github-actions/actions/example-project/umbrella-pr-tests@master
```

## yamllint action inside umbrella-pr-tests

Note that I have edited this file in the cache for debugging purposes.

```yaml
# /Users/alex.harvey/.cache/act/example-org-private-github-actions-actions-yaml-lint@master/actions/yaml-lint/action.yml 
---
name: "yaml-lint"

author: author@example.com
description: "runs vanilla yamllint on added & changed files"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: debug
      shell: bash
      run: |
        pwd
        ls -al
        yamllint foo.yaml
```

## Expected behaviour

It should yamllint the file `foo.yaml`.

## Actual behaviour

```text
▶ act -e pull-request.json -s GITHUB_TOKEN=ghp_xxxx -P example-base=gha-default-runner:latest pull_request -j pr-tests
[PR Check values files/pr-tests] 🚀  Start image=gha-default-runner:latest
[PR Check values files/pr-tests]   🐳  docker pull image=gha-default-runner:latest platform= username= forcePull=false
[PR Check values files/pr-tests]   🐳  docker create image=gha-default-runner:latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[PR Check values files/pr-tests]   🐳  docker run image=gha-default-runner:latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[PR Check values files/pr-tests]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[PR Check values files/pr-tests] ⭐  Run Run tests against the PR
[PR Check values files/pr-tests]   ☁  git clone 'https://github.com/example-org/private-github-actions' # ref=master
[PR Check values files/pr-tests] Non-terminating error while running 'git clone': some refs were not updated
[PR Check values files/pr-tests]   🐳  docker cp src=/Users/alex.harvey/.cache/act/example-org-private-github-actions-actions-example-project-umbrella-pr-tests@master/ dst=/var/run/act/actions/example-org-private-github-actions-actions-example-project-umbrella-pr-tests@master/
[PR Check values files/pr-tests]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/example-org-private-github-actions-actions-example-project-umbrella-pr-tests@master/] user= workdir=
[PR Check values files/pr-tests] ⭐  Run yaml-lint values files
[PR Check values files/pr-tests]   ☁  git clone 'https://github.com/example-org/private-github-actions' # ref=master
[PR Check values files/pr-tests] Non-terminating error while running 'git clone': some refs were not updated
[PR Check values files/pr-tests]   🐳  docker cp src=/Users/alex.harvey/.cache/act/example-org-private-github-actions-actions-yaml-lint@master/ dst=/var/run/act/actions/example-org-private-github-actions-actions-yaml-lint@master/
[PR Check values files/pr-tests]   🐳  docker exec cmd=[mkdir -p /var/run/act/actions/example-org-private-github-actions-actions-yaml-lint@master/] user= workdir=
[PR Check values files/pr-tests] ⭐  Run debug
[PR Check values files/pr-tests]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/0-composite-0-composite-0.sh] user= workdir=
| /Users/alex.harvey/git/myproject
| total 8
| drwxr-xr-x 2 root root 4096 Apr  3 09:41 .
| drwxr-xr-x 3 root root 4096 Apr  3 09:41 ..
| [Errno 2] No such file or directory: 'foo.yaml'
[PR Check values files/pr-tests]   ❌  Failure - debug
[PR Check values files/pr-tests] exit with `FAILURE`: 255
[PR Check values files/pr-tests]   ❌  Failure - yaml-lint values files
[PR Check values files/pr-tests] exit with `FAILURE`: 255
[PR Check values files/pr-tests]   ❌  Failure - Run tests against the PR
[PR Check values files/pr-tests] exit with `FAILURE`: 255
Error: Job 'pr-tests' failed
```

**Comment by ChristopherHX** [comment]
**Workaround**, _not tested_
```yaml
---
name: PR Check values files

on:
  pull_request:
    branches: [master]

jobs:
  pr-tests:
    runs-on: example-base
    steps:
      - name: "workaround for act #1112"
        uses: actions/checkout@v2
        if: "false"
      - name: Run tests against the PR
        uses: example-org/private-github-actions/actions/example-project/umbrella-pr-tests@master
```
