### ISSUE TITLE
'toJson' is not defined

### ISSUE THREAD

**Issue by Nuru** [nektos/act#115]
One [example job](https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#example-printing-context-information-to-the-log-file) in the GitHub Actions documentation uses `toJson` and it works when run on GitHub, but not when run by `act`.

```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```
runs fine on GitHub, but `act` complains:
```
[test/test] ⭐  Run Dump GitHub context
ERRO[0001] Unable to interpolate string '${{ toJson(github) }}' - [ReferenceError: 'toJson' is not defined] 
| ${{ toJson(github) }}
```
