### ISSUE TITLE
Error in if-expression: "if: ${{ !contains(github.event.head_commit.message, '#no-gha') }}" (Unable to dereference 'message' on non-struct 'invalid')

### ISSUE THREAD

**Issue by dodalovic** [nektos/act#1159]
The tool fails with the following message:

```shell
act -n
Error:   ❌  Error in if-expression: "if: ${{ !contains(github.event.head_commit.message, '#no-gha') }}" (Unable to dereference 'message' on non-struct 'invalid')
```

, when given such workflow...
 
```yaml
jobs:
  build-jar:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#no-gha') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
```
