### ISSUE TITLE
Longer secret string throws error

### ISSUE THREAD

**Issue by Steffen911** [nektos/act#117]
**What happened**:
I use an `.actrc` file to provide the target docker image and a secret that corresponds to an inlined maven `settings.xml` file.
Now, when I run `act` I get `Error: accepts at most 1 arg(s), received 64`.

My `.actrc`:
```
-P ubuntu-18.04=nektos/act-environments-ubuntu:18.04
-s SETTINGS_XML='<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd"> <servers> <server> <id>backend-s3-release-repo</id> <username><USERNAME></username> <password><PASSWORD></password> </server> <server> <id>backend-s3-snapshot-repo</id> <username><USERNAME></username> <password><PASSWORD></password> </server> </servers> </settings>'
```
I tried to assign the value with single quotes, double quotes (with escaping the inner quotes) and without any quotes add all. The error is always the same.

When I pass the secret via the environment everything works fine and change the `.actrc` file to
```
-P ubuntu-18.04=nektos/act-environments-ubuntu:18.04
-s SETTINGS_XML
```
everything works as expected.

**What I expect to happen**:
It should run the workflow with the given settings.xml as the secret.

**Version/Platform**:
act version 0.2.4
macOS 10.15.3 
command: `act`
output: `Error: accepts at most 1 arg(s), received 64`

workflow:
```yml
name: PR Build
on: [pull_request]
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build and Run Tests
        run: |
          echo $SETTINGS_XML > ./settings.xml
          mvn verify --settings ./settings.xml --batch-mode
        env:
          SETTINGS_XML: ${{ secrets.SETTINGS_XML }}
```
