### ISSUE TITLE
Issue: SDK location not found Android build

### ISSUE THREAD

**Issue by cinder92** [nektos/act#1172]
## System information

   - Operating System: < Windows | Linux | macOS | etc... >
    - Architecture: < x64 (64-bit) | x86 (32-bit) | arm64 (64-bit) | arm (32-bit) | etc... >
    - Apple M1: < yes | no >
    - Docker version: < output of `docker system info -f "{{.ServerVersion}}"` >
    - Docker image used in `act`: < can be omitted if it's included in log >
    - `act` version: < output of `act --version`, if you've built `act` yourself, please provide commit hash >

- Operating System: macOS
- Architecture: 64 bit
- Apple M1: no
- Docker version: Docker version 20.10.14, build a224086
- Docker image used in `act`: nektos/act-environments-ubuntu:18.04
- `act` version: 0.2.26

## Expected behaviour

Build android apk successfully 

## Actual behaviour

SDK not found

## Workflow and/or repository

```
name: Android Build ## name of the workflow
on: push

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest # using ubuntu latest version / or you can use a specific version

    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v2
      
      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
        run: yarn install --frozen-lockfile

      ## configure cash for gradle : will help to reduce build time
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Generate App APK
        run: |
          cd android && ./gradlew assembleRelease --no-daemon

      ## sign generated apk
      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
```
## Steps to reproduce

run `act --env-file .env -P ubuntu-latest=nektos/act-environments-ubuntu:18.04`

## `act` output

```
 * What went wrong:
| Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
| > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/react-native/android/local.properties'.
```

**Comment by PrasannaKumarChalla** [comment]
@catthehacker I'm running into the same issue, when you asked did you install android sdk here https://github.com/nektos/act/issues/1172#issuecomment-1133478922, where should I install android sdk?. Doesn't ubuntu-latest come with android sdk by default?.

**Comment by deepraj02** [comment]
Any Update guys I'm also getting the same error

**Comment by axstel** [comment]
Same here, any update?

**Comment by maxfie1d** [comment]
Any update?

**Comment by andylvua** [comment]
I had the same problem as the author. 

It looks like even the `catthehacker/ubuntu:full` images don't provide the Android SDK like the GitHub runners do.

As a **temporary solution**, you can add the following step to your workflow:

```YAML
  - name: Set up Android SDK
    if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
    uses: android-actions/setup-android@v2
```
It will only run when using `act` locally and will install the Android SDK.
