### ISSUE TITLE
Issue: Some installers fail due to empty tempory file system.

### ISSUE THREAD

**Issue by RGuezennec** [nektos/act#1176]
## System information

- Operating System: Linux (ubuntu 20.04)
- Architecture: x64 (64-bit)
- Docker version: 20.10.7
- Docker image used in `act`: ghcr.io/catthehacker/ubuntu:act-latest
- `act` version: 0.2.26

## Expected behaviour

Install all softwares I want.

## Actual behaviour

I tried to install software from Installer. 
(such as Qt from Qt online installer, but it is not the only one but there are less public).
Every installer made with Qt installer framework has this step.
There is a step inside those installers to check for hard drive space into the destination directory and in temporary. but when  executing into act image, the installer finds no space inside tmp so it failed. 

Is their a way to map the /tmp from the host to the docker instance or something ? in order to fix that.

message when it works (on my local machine):
```
Tmp is on a different volume than the installation directory. Tmp volume mount point: "/" Free space available: "56.45 GiB" Install volume mount point: "/home" Free space available: "724.02 GiB"
[432] Installation space required: "761.88 MiB" Temporary space required: "256.00 MiB" Local repository size: "0.00 bytes"
```
Message when it failed (on docker image from act):
```
Tmp is on a different volume than the installation directory. Tmp volume mount point: "" Free space available: "0.00 bytes" Install volume mount point: "/home/bla/bla/bla/project" Free space available: "56.49 GiB"
```

## Steps to reproduce
You need a valid Qt account to do that.
```
      - uses: suisei-cn/actions-download-file@v1 
        id: qtinstaller
        name: Download Qt installer
        with: 
          url: https://download.qt.io/archive/online_installers/4.3/qt-unified-linux-x64-4.3.0-1-online.run
          target: public/
          auto-match: false
      - name: Install Qt6
        run: sudo public/qt-unified-linux-x64-4.3.0-1-online.run --accept-licenses --auto-answer telemetry-question=No --default-answer --confirm-command --ao --email ${{ secrets.QT_ACCOUNT_EMAIL }} --password "${{ secrets.QT_ACCOUNT_PASSWORD }}" install "qt.tools.cmake qt.qt6.624.gcc_64 qt.qt6.624.addons.qtwebchannel.gcc_64 qt.qt6.624.addons.qtwebsockets qt.qt6.624.addons.qtwebsockets.gcc_64"
```

</details>
