### ISSUE TITLE
Unable to locate package google-chrome

### ISSUE THREAD

**Issue by thesamchris** [nektos/act#1181]
### Bug report info

```
act version:            0.2.26
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/Users/samchris/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
	.actrc:
		-P ubuntu-latest=node:12.20.1-buster-slim
Docker Engine:
	Engine version:        20.10.14
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             5.10.104-linuxkit
	OS CPU:                4
	OS memory:             7960 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
act -P ubuntu-latest=shivammathur/node:latest -v --secret-file my.secrets
```

### Describe issue

i have a problem with the setting up of the chrome driver for my github action. it works on github actions but doesn't work on my local repo. below is the step in my .yml file
```
- name: Setup Chrome Driver
  uses: nanasess/setup-chromedriver@v1
   with:
      chromedriver-version: '72.0.3626.69'
```

### Workflow content

```yml
name: Repo CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      CHROMEDRIVER_VERSION: 72.0.3626.69
      LOG_CHANNEL: single
      CACHE_DRIVER: redis
      FIREWALL_ENABLED: false
      SESSION_DRIVER: file
      QUEUE_DRIVER: sync
      SCOUT_DRIVER: 'null'
      SCOUT_PREFIX: github_testing_
      AWS_REGION: us-west-1
      AWS_DEFAULT_REGION: us-west-1
      AWS_ASSETS_S3_BUCKET: somebucket
      AWS_ACCESS_KEY_ID: somekey
      AWS_SECRET_ACCESS_KEY: somesecret
      AWS_CLOUDFRONT_KEYPAIR_ID: somekeypair
      AWS_ASSETS_CLOUDFRONT_DOMAIN: something.cloudfront.net
      AWS_CLOUDFRONT_PEM_PROD: cloudfront.pem
      MAIL_DRIVER: log
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 2525
      TELESCOPE_ENABLED: false
      BRAINTREE_MODE: sandbox
      MIXPANEL_API_KEY: somekey
      DB_CONNECTION: postgres
      DATABASE_URL: postgres://dbuser:testpw@127.0.0.1/test_db
      CMS_DATABASE_URL: postgres://dbuser:testpw@127.0.0.1/test_db
      REDIS_URL: redis://127.0.0.1:6379
      MIGRATE_CMSSETTING: false
      USE_PGSQL_FOR_CMS_SETTING: false
      SEED_CMS: false
      NL_SKIP_MEMORY_LIMIT: true
      EMAIL_ALERT_TO_EMAIL: email@mail.com
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
          tools: composer:v1
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # runner: self-hosted
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Setup PostgreSQL
        # You may pin to the exact commit or the version.
        # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          # POSTGRES_DB - name for the default database that is created
          postgresql db: test_db
          # POSTGRES_USER - create the specified user with superuser power
          postgresql user: dbuser
          # POSTGRES_PASSWORD - superuser password
          postgresql password: testpw
      - name: Setup Redis
        # You may pin to the exact commit or the version.
        # uses: zhulik/redis-action@765216a54a1114f109ce90a1de4775080be16ea5
        uses: zhulik/redis-action@1.1.0
      - name: Setup Chrome Driver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '72.0.3626.69'
      - uses: actions/checkout@v3
      - name: Prepare The env file
        run: cp .env.github-ci .env
      - name: Append repo secrets to env file
        # https://stackoverflow.com/a/64452700
        env:
          TESTING_ENV_FILE: ${{ secrets.TEST_ENV }}
        run: |
          echo $TESTING_ENV_FILE | base64 --decode >> .env
      - name: Authenticate Composer with Github
        env:
          COMPOSER_GITHUB_OAUTH_TOKEN: ${{ secrets.NEXTLEVEL_GITHUB_TOKEN }}
        run: composer config --no-plugins -g github-oauth.github.com "$COMPOSER_GITHUB_OAUTH_TOKEN" &> /dev/null
      - name: Install PHP Dependencies
        run: composer install
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Build Front End
        run: yarn run heroku-postbuild
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute Unit Tests via PHPUnit
        run: php -dmemory_limit=-1 ./vendor/phpunit/phpunit/phpunit
      - name: Set Chrome Driver
        run: php artisan dusk:chrome-driver 72
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
      - name: Run Laravel Server
        run: php artisan serve --no-reload > /dev/null 2>&1 &
      #     - name: Run Dusk Tests
      #       run: php artisan dusk
      - name: Upload Dusk fail screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: dusk-fail-screenshots
          path: tests/Browser/screenshots/failure-*
          retention-days: 1
      - name: Upload Laravel fail logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: laravel-logs
          path: storage/logs/laravel*.log
          retention-days: 1
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "workflow": "${{ github.workflow }}",
              "run_id": "${{ github.run_id }}",
              "repo": "${{ github.repository }}",
              "branch": "${{ github.ref }}",
              "commit_message": "${{ github.event.commits[0].message}}",
              "action_url": "https://www.github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "status_icon": "${{ job.status == 'success' && '✅' || '🛑'}}",
              "status": "${{ job.status }}"
            }
```

### Relevant log output

```sh
E: Unable to locate package google-chrome
 ❗  ::error::The process '/run/act/actions/nanasess-setup-chromedriver@v1/lib/setup-chromedriver.sh' failed with exit code 100
 ❌  Failure - Setup Chrome Driver
```
