### ISSUE TITLE
act job hangs

### ISSUE THREAD

**Issue by aleks-f** [nektos/act#1190]
### Bug report info

```plain text
$ act --bug-report
act version:            0.2.26
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 2
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/alex/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Docker Engine:
	Engine version:        20.10.14
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Debian GNU/Linux 10 (buster)
	OS type:               linux
	OS version:            10
	OS arch:               x86_64
	OS kernel:             4.19.0-19-amd64
	OS CPU:                2
	OS memory:             7972 MB
	Security options:
		name=apparmor
		name=seccomp,profile=default
```

### Command used with act

```sh
act -j linux-gcc-make-tsan
```

### Describe issue

no progress after this line:
```
| After this operation, 6897 kB of additional disk space will be used.
```

### Link to GitHub repository

https://github.com/pocoproject/poco

### Workflow content

```yml
name: poco-ci
on: [push, pull_request]
jobs:
  linux-gcc-make:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: pocotest
          MYSQL_PASSWORD: pocotest
          MYSQL_DATABASE: pocotest
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install libssl-dev unixodbc-dev redis-server libmysqlclient-dev
      - run: ./configure --everything --omit=PDF && make all -s -j4 && sudo make install
      - run: >-
          sudo -s
          EXCLUDE_TESTS="Data/ODBC Data/PostgreSQL MongoDB"
          ./ci/runtests.sh

  linux-gcc-make-asan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install libssl-dev unixodbc-dev libmysqlclient-dev redis-server
      - run: ./configure --everything --omit=PDF && make all -s -j4 SANITIZEFLAGS=-fsanitize=address && sudo make install
      - run: >-
          sudo -s
          EXCLUDE_TESTS="Data/MySQL Data/ODBC Data/PostgreSQL MongoDB"
          ./ci/runtests.sh

  linux-gcc-make-asan-no-soo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install libssl-dev unixodbc-dev libmysqlclient-dev redis-server
      - run: ./configure --everything --omit=PDF --no-soo && make all -s -j4 SANITIZEFLAGS=-fsanitize=address && sudo make install
      - run: >-
          sudo -s
          EXCLUDE_TESTS="Data/MySQL Data/ODBC Data/PostgreSQL MongoDB"
          ./ci/runtests.sh

  linux-gcc-make-ubsan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install libssl-dev unixodbc-dev libmysqlclient-dev redis-server
      - run: ./configure --everything --omit=PDF && make all -s -j4 SANITIZEFLAGS=-fsanitize=undefined && sudo make install
      - run: >-
          sudo -s
          EXCLUDE_TESTS="Data/MySQL Data/ODBC Data/PostgreSQL MongoDB"
          ./ci/runtests.sh

  linux-gcc-make-tsan:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install libssl-dev unixodbc-dev libmysqlclient-dev redis-server
      - run: ./configure --everything --omit=CppParser,Encodings,Data/MySQL,Data/ODBC,Data/PostgreSQL,MongoDB,PageCompiler,PDF,PocoDoc,ProGen,Redis,SevenZip && make all -s -j4 SANITIZEFLAGS=-fsanitize=thread && sudo make install
      - run: >-
          sudo -s
          POCO_BASE=`pwd`
          EXCLUDE_TESTS="Data/MySQL Data/ODBC Data/PostgreSQL MongoDB"
          TSAN_OPTIONS="suppressions=$POCO_BASE/tsan.supress,second_deadlock_stack=1"
          ./ci/runtests.sh

  linux-gcc-cmake:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install cmake ninja-build libssl-dev unixodbc-dev libmysqlclient-dev redis-server
      - run: cmake -H. -Bcmake-build -GNinja -DENABLE_PDF=OFF -DENABLE_TESTS=ON && cmake --build cmake-build --target all
      - run: >-
          cd cmake-build &&
          sudo -s
          PWD=`pwd`
          ctest --output-on-failure -E "(DataMySQL)|(DataODBC)|(PostgreSQL)|(MongoDB)"

  linux-gcc-make-cross-armhf:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: >-
          sudo apt-get update &&
          sudo apt-get install crossbuild-essential-armhf
      - run: >-
          ./configure --config=ARM-Linux --everything --omit=PDF,Crypto,NetSSL_OpenSSL,JWT,Data/MySQL,Data/ODBC,Data/PostgreSQL,PageCompiler,PageCompiler/File2Page &&
          make all -s -j4 ARCHFLAGS="-mcpu=cortex-a8 -mfloat-abi=hard -mfpu=neon" TOOL=arm-linux-gnueabihf

  macos-clang-make:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: brew install openssl@1.1 mysql-client unixodbc libpq
      - run: ./configure --everything --no-prefix --omit=PDF --odbc-include=/usr/local/opt/unixodbc/include --odbc-lib=/usr/local/opt/unixodbc/lib && make all -s -j4
      - run: >-
          sudo -s
          CPPUNIT_IGNORE="N7CppUnit10TestCallerI10ThreadTestEE.testTrySleep,N7CppUnit10TestCallerI13TimestampTestEE.testTimestamp,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testExpireN,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testAccessExpireN,N7CppUnit10TestCallerI24UniqueExpireLRUCacheTestEE.testExpireN,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testAccessExpireN,N7CppUnit10TestCallerI11PollSetTestEE.testPollClosedServer"
          EXCLUDE_TESTS="Redis Data/MySQL Data/ODBC Data/PostgreSQL MongoDB PDF"
          ./ci/runtests.sh

  macos-clang-cmake:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: brew install openssl@1.1 mysql-client unixodbc libpq
      - run: cmake -H. -Bcmake-build -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 -DMYSQL_ROOT_DIR=/usr/local/opt/mysql-client && cmake --build cmake-build --target all
      - run: >-
          cd cmake-build &&
          sudo -s
          CPPUNIT_IGNORE="N7CppUnit10TestCallerI10ThreadTestEE.testTrySleep,N7CppUnit10TestCallerI13TimestampTestEE.testTimestamp,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testExpireN,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testAccessExpireN,N7CppUnit10TestCallerI24UniqueExpireLRUCacheTestEE.testExpireN,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testAccessExpireN,N7CppUnit10TestCallerI11PollSetTestEE.testPollClosedServer"
          PWD=`pwd`
          ctest --output-on-failure -E "(DataMySQL)|(DataODBC)|(PostgreSQL)|(MongoDB)|(Redis)"

  macos-clang-cmake-openssl3:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: brew install openssl@3 mysql-client unixodbc libpq
      - run: cmake -H. -Bcmake-build -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 -DMYSQL_ROOT_DIR=/usr/local/opt/mysql-client && cmake --build cmake-build --target all
      - run: >-
          cd cmake-build &&
          sudo -s
          CPPUNIT_IGNORE="N7CppUnit10TestCallerI10ThreadTestEE.testTrySleep,N7CppUnit10TestCallerI13TimestampTestEE.testTimestamp,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testExpireN,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testAccessExpireN,N7CppUnit10TestCallerI24UniqueExpireLRUCacheTestEE.testExpireN,N7CppUnit10TestCallerI18ExpireLRUCacheTestEE.testAccessExpireN,N7CppUnit10TestCallerI11PollSetTestEE.testPollClosedServer"
          PWD=`pwd`
          ctest --output-on-failure -E "(DataMySQL)|(DataODBC)|(PostgreSQL)|(MongoDB)|(Redis)"

  windows-2019-msvc-cmake:
    runs-on: windows-2019
    env:
      CPPUNIT_IGNORE: class CppUnit::TestCaller<class PathTest>.testFind,class CppUnit::TestCaller<class ICMPSocketTest>.testSendToReceiveFrom,class CppUnit::TestCaller<class ICMPClientTest>.testPing,class CppUnit::TestCaller<class ICMPClientTest>.testBigPing,class CppUnit::TestCaller<class ICMPSocketTest>.testMTU,class CppUnit::TestCaller<class HTTPSClientSessionTest>.testProxy,class CppUnit::TestCaller<class HTTPSStreamFactoryTest>.testProxy
    steps:
      - uses: actions/checkout@v2
      - run: cmake -S. -Bcmake-build -DENABLE_NETSSL_WIN=ON -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_JWT=OFF -DENABLE_DATA=ON -DENABLE_DATA_ODBC=ON -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF -DENABLE_TESTS=ON
      - run: cmake --build cmake-build --config Release
      - run: >-
          cd cmake-build;
          ctest --output-on-failure -E "(DataMySQL)|(DataODBC)|(Redis)|(MongoDB)" -C Release

  windows-2022-msvc-cmake-2022:
    runs-on: windows-2022
    env:
      CPPUNIT_IGNORE: class CppUnit::TestCaller<class PathTest>.testFind,class CppUnit::TestCaller<class ICMPSocketTest>.testSendToReceiveFrom,class CppUnit::TestCaller<class ICMPClientTest>.testPing,class CppUnit::TestCaller<class ICMPClientTest>.testBigPing,class CppUnit::TestCaller<class ICMPSocketTest>.testMTU,class CppUnit::TestCaller<class HTTPSClientSessionTest>.testProxy,class CppUnit::TestCaller<class HTTPSStreamFactoryTest>.testProxy
    steps:
      - uses: actions/checkout@v2
      - run: cmake -S. -Bcmake-build -DENABLE_NETSSL_WIN=ON -DENABLE_NETSSL=OFF -DENABLE_CRYPTO=OFF -DENABLE_JWT=OFF -DENABLE_DATA=ON -DENABLE_DATA_ODBC=ON -DENABLE_DATA_MYSQL=OFF -DENABLE_DATA_POSTGRESQL=OFF -DENABLE_TESTS=ON
      - run: cmake --build cmake-build --config Release
      - run: >-
          cd cmake-build;
          ctest --output-on-failure -E "(DataMySQL)|(DataODBC)|(Redis)|(MongoDB)" -C Release
```

### Relevant log output

```sh
[poco-ci/linux-gcc-make-tsan]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [10.5 kB]
Get:3 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease [23.8 kB]   
Get:4 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]                
Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [177 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [1859 kB]
Get:8 http://ppa.launchpad.net/git-core/ppa/ubuntu focal/main amd64 Packages [3165 B]
Get:9 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [876 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1214 kB]
Get:6 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease [24.4 kB]  
Get:11 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [27.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:15 https://packagecloud.io/github/git-lfs/ubuntu focal/main amd64 Packages [2944 B]
Get:16 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [30.2 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1163 kB]
Get:21 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1297 kB]
Get:22 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2294 kB]
Get:23 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [53.8 kB]
Get:24 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [27.1 kB]
Fetched 22.5 MB in 5s (4673 kB/s)                       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
| 38 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
| The following additional packages will be installed:
|   libhiredis0.14 libjemalloc2 liblua5.1-0 libmysqlclient21 libodbc1 libssl1.1
|   lua-bitop lua-cjson odbcinst odbcinst1debian2 redis-tools unixodbc
| Suggested packages:
|   msodbcsql17 unixodbc-bin libssl-doc ruby-redis
| The following NEW packages will be installed:
|   libhiredis0.14 libjemalloc2 liblua5.1-0 libodbc1 lua-bitop lua-cjson
|   odbcinst odbcinst1debian2 redis-server redis-tools unixodbc unixodbc-dev
| The following packages will be upgraded:
|   libmysqlclient-dev libmysqlclient21 libssl-dev libssl1.1
| 4 upgraded, 12 newly installed, 0 to remove and 34 not upgraded.
| Need to get 7430 kB of archives.
| After this operation, 6897 kB of additional disk space will be used.
```

### Additional information

I tried Debian Buster and Parrot 5, same problem. Not sure if I'm doing something wrong - this runs on github.

Trying to run it verbosely does nothing:
```
$ act -j --verbose linux-gcc-make-tsan
$ act -j -v linux-gcc-make-tsan
$ act -jv linux-gcc-make-tsan
```
