### ISSUE TITLE
apt-get hangs when installing directly or indirectly keyboard-configuration

### ISSUE THREAD

**Issue by Elanis** [nektos/act#1205]
### Bug report info

```plain text
act version:            0.2.26
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 6
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
Config files:
        /home/elanis/.actrc:
                -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
                -P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
        .actrc:
                -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
                -P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Docker Engine:
        Engine version:        20.10.17
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Debian GNU/Linux 11 (bullseye)
        OS type:               linux
        OS version:            11
        OS arch:               x86_64
        OS kernel:             5.10.16.3-microsoft-standard-WSL2
        OS CPU:                6
        OS memory:             7936 MB
        Security options:
                name=seccomp,profile=default
```

### Command used with act

```sh
act
```

### Describe issue

When running a ubuntu-latest CI which does a apt install, act hangs out when trying to install `keyboard-configuration` package.

Based on https://github.com/docker/build-push-action/issues/504, I had to set environement variable `DEBIAN_FRONTEND=noninteractive` to be able to run my apt install completly.

### Link to GitHub repository

https://github.com/Elanis/web-to-desktop-framework-comparison/

### Non-working workflow content

```yml
name: Runner

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name:  Install
        run:   |
               if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
                    sudo apt update
                    sudo apt install -y libxshmfence1 libglu1 libnss3 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libasound2 # Electron
                    sudo apt install -y libwebkit2gtk-4.0-37 libstdc++6 # NeutralinoJS
                    sudo apt install -y pkg-config build-essential cmake make mesa-common-dev libglu1-mesa-dev # NodeGUI
               else
                    echo "Nothing to install on $RUNNER_OS"
               fi
        shell: bash
```

### Working workflow content

```yml
name: Runner

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name:  Install
        run:   |
               if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
                    sudo apt update
                    sudo DEBIAN_FRONTEND=noninteractive apt install -y libxshmfence1 libglu1 libnss3 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libasound2 # Electron
                    sudo DEBIAN_FRONTEND=noninteractive apt install -y libwebkit2gtk-4.0-37 libstdc++6 # NeutralinoJS
                    sudo DEBIAN_FRONTEND=noninteractive apt install -y pkg-config build-essential cmake make mesa-common-dev libglu1-mesa-dev # NodeGUI
               else
                    echo "Nothing to install on $RUNNER_OS"
               fi
        shell: bash
```

### Relevant log output

```sh
(Frozen apt install with language choice)
```
(https://pastebin.com/ugWdjBZC)
