### ISSUE TITLE
act silently stopping

### ISSUE THREAD

**Issue by JulianGro** [nektos/act#1223]
### Bug report info

```plain text
juliangro@x299-desktop:~/Software/act$ ./act --bug-report
act version:            0.2.26
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/juliangro/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Docker Engine:
	Engine version:        20.10.14+dfsg1
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        btrfs
	Registry URI:          https://index.docker.io/v1/
	OS:                    Debian GNU/Linux bookworm/sid
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             5.18.0-1-amd64
	OS CPU:                12
	OS memory:             31811 MB
	Security options:
		name=apparmor
		name=seccomp,profile=default
		name=cgroupns

juliangro@x299-desktop:~/Software/act$
```

### Command used with act

```sh
./act -W /home/juliangro/git/temp/project-athena-docker/.github/workflows/master_docker_build.yml -C /home/juliangro/git/temp/project-athena-docker/ -v --detect-event
```

### Describe issue

Act just silently stops when trying to run my workflow.
As you can see in the debug output it just says "false" without any meaningfull information.

### Workflow content

```yml
name: Master CI Docker Server Build

on:
  push
#  push:
#    branches:
#      - master

env:
  BUILD_TYPE: Release
  BUILD_NUMBER: ${{ github.run_number }}
  CI_BUILD: Github
  GIT_COMMIT: ${{ github.sha }}
  RELEASE_TYPE: PRODUCTION
  RELEASE_NUMBER: ${{ github.run_number }}
  STABLE_BUILD: 0
  UPLOAD_BUCKET: overte-public
  UPLOAD_REGION: fra1
  UPLOAD_ENDPOINT: "https://fra1.digitaloceanspaces.com"
  # Use Docker BuildKit backend
  DOCKER_BUILDKIT: 1


jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            apt-dependencies: docker.io
          # Do not change the names of self-hosted runners without knowing what you are doing, as they correspond to labels that have to be set on the runner.
          #~ - os: self-hosted_debian-11_aarch64
            #~ build_type: full
            #~ apt-dependencies: docker.io
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
    - name: Report Build Number
      shell: bash
      run: |

        echo "Build number: $BUILD_NUMBER"

    - uses: actions/checkout@v1
      with:
        submodules: false
        fetch-depth: 1

    - name: Install dependencies
      shell: bash
      run: |
      
          echo "Updating apt repository index"
          sudo apt update || exit 1

          echo "Installing apt packages"
          sudo apt install -y ${{ matrix.apt-dependencies }} || exit 1

    - name: Create Docker environment
      shell: bash
      run: mkdir build

    - name: Start Docker build container
      working-directory: ${{runner.workspace}}
      run: docker build -f tools/ci-scripts/docker_package/Dockerfile_build .
```

### Relevant log output

```sh
juliangro@x299-desktop:~/Software/act$ ./act -W /home/juliangro/git/temp/project-athena-docker/.github/workflows/master_docker_build.yml -C /home/juliangro/git/temp/project-athena-docker/ -v --detect-event
DEBU[0000] Loading environment from /home/juliangro/git/temp/project-athena-docker/.env 
DEBU[0000] Loading secrets from /home/juliangro/git/temp/project-athena-docker/.secrets 
DEBU[0000] Loading workflow '/home/juliangro/git/temp/project-athena-docker/.github/workflows/master_docker_build.yml' 
DEBU[0000] Reading workflow '/home/juliangro/git/temp/project-athena-docker/.github/workflows/master_docker_build.yml' 
DEBU[0000] Using detected workflow event: push          
DEBU[0000] Planning event: push                         
DEBU[0000] Loading slug from git directory '/home/juliangro/git/temp/project-athena-docker/.git' 
DEBU[0000] Loading revision from git directory '/home/juliangro/git/temp/project-athena-docker/.git' 
DEBU[0000] Found revision: 581aa24a7890d44654e4b84a9cfe3686f63653fd 
DEBU[0000] HEAD points to '581aa24a7890d44654e4b84a9cfe3686f63653fd' 
DEBU[0000] using github ref: refs/heads/docker_experiment 
DEBU[0000] Found revision: 581aa24a7890d44654e4b84a9cfe3686f63653fd 
DEBU[0000] Loading slug from git directory '/home/juliangro/git/temp/project-athena-docker/.git' 
DEBU[0000] Loading revision from git directory '/home/juliangro/git/temp/project-athena-docker/.git' 
DEBU[0000] Found revision: 581aa24a7890d44654e4b84a9cfe3686f63653fd 
DEBU[0000] HEAD points to '581aa24a7890d44654e4b84a9cfe3686f63653fd' 
DEBU[0000] using github ref: refs/heads/docker_experiment 
DEBU[0000] Found revision: 581aa24a7890d44654e4b84a9cfe3686f63653fd 
DEBU[0000] false                                        
juliangro@x299-desktop:~/Software/act$
```
