### ISSUE TITLE
Credentials could not be loaded, please check your action inputs

### ISSUE THREAD

**Issue by chrisurf** [nektos/act#1235]
### Bug report info

```plain text
act version:            0.2.28
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:
	/Users/chrisurf/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:full-20.04
		-P ubuntu-18.04=nektos/act-environments-ubuntu:18.04-lite
		ubuntu-16.04=catthehacker/ubuntu:act-16.04
	.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:full-20.04
		-P ubuntu-18.04=nektos/act-environments-ubuntu:18.04-lite
		ubuntu-16.04=catthehacker/ubuntu:act-16.04
Build info:
	Go version:            go1.18.3
	Module path:           command-line-arguments
	Main version:
	Main path:
	Main checksum:
	Build settings:
		-compiler:            gc
		-ldflags:             -X main.version=0.2.28
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
Docker Engine:
	Engine version:        20.10.16
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:
	OS arch:               x86_64
	OS kernel:             5.10.104-linuxkit
	OS CPU:                6
	OS memory:             7959 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
act --secret-file ~/my-secrets -W ./.github/workflows/my-workflow.yml
```

### Describe issue

OS: Mac OS Big Sur
act version: 0.2.28
image: ghcr.io/catthehacker/ubuntu:act-latest

### The following error was shown after I upgraded from act v0.2.26 to v0.2.28.
**❗  ::error::Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
❌  Failure - Main Configure AWS Credentials**
exitcode '1': failure

The error occurs when calling a composite action via matrix strategy and trying to pass in secret from a local file.
Example: `act --secret-file ~/my-secrets -W ./.github/workflows/my-workflow.yml`

The following outputs section with the secrets `***` was not showing as usually when running  act v0.2.28.

`**:set-output:: aws-account-id=*****`

After rolling back to act v0.2.26 this error is gone and everything was working fine as before.  Tried it a couple of times back and four, which makes me think it is linked to version 0.2.28. 

I hope this is helpful.

### Workflow content

```yml
# workflow.yml
  workflow: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["dev", "stage", "prod"]
        region: ["eu-central-1", "us-east-1", ap-southeast-1]
    steps:
      - name: terraform plan
        uses: ./.github/actions/terraform-plan
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

... 

# action.yml
  - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-central-1
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
`
```

### Relevant log output

```sh
DEBUG] setupEnv => map[ACT:true AGENT_TOOLSDIRECTORY:/opt/hostedtoolcache AWS_DEFAULT_REGION:eu-central-1 AWS_REGION:eu-central-1 CI:true DEBIAN_FRONTEND:noninteractive DEPLOYMENT_BASEPATH:/opt/runner GITHUB_ACTION:11 GITHUB_ACTIONS:true GITHUB_ACTION_PATH:/Users/chrisurf/Workspace/github/ZH-LAKE-UNIT/tf-aws-iam/.github/actions/terragrunt-plan GITHUB_ACTION_REF: GITHUB_ACTION_REPOSITORY: GITHUB_ACTOR:nektos/act GITHUB_API_URL:https://api.github.com GITHUB_BASE_REF: GITHUB_ENV:/var/run/act/workflow/envs.txt GITHUB_EVENT_NAME:pull_request GITHUB_EVENT_PATH:/var/run/act/workflow/event.json GITHUB_GRAPHQL_URL:https://api.github.com/graphql GITHUB_HEAD_REF: GITHUB_JOB:terragrunt GITHUB_PATH:/var/run/act/workflow/paths.txt GITHUB_REF:refs/pull/%!s(<nil>)/merge GITHUB_REF_NAME: GITHUB_REF_TYPE: GITHUB_REPOSITORY:ZH-LAKE-UNIT/tf-aws-iam GITHUB_REPOSITORY_OWNER:ZH-LAKE-UNIT GITHUB_RETENTION_DAYS:0 GITHUB_RUN_ID:1 GITHUB_RUN_NUMBER:1 GITHUB_SERVER_URL:https://github.com GITHUB_SHA:1f5558acee631bb42888d76c9a3e2429f326b826 GITHUB_TOKEN:*** GITHUB_WORKFLOW:Plan Firewall Rules GITHUB_WORKSPACE:/Users/chrisurf/Workspace/github/ZH-LAKE-UNIT/tf-aws-iam IMAGE_OS:ubuntu20 INPUT_NAME:infracost_jsons INPUT_PATH:/tmp/infracost.json ImageOS:ubuntu20 LSB_OS_VERSION:2004 LSB_RELEASE:20.04
```
