### ISSUE TITLE
eventpath now working

### ISSUE THREAD

**Issue by teacherSsamko** [nektos/act#1241]
### Bug report info

```plain text
act version:            0.2.26
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/Users/eunsub/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Docker Engine:
	Engine version:        20.10.14
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               aarch64
	OS kernel:             5.10.104-linuxkit
	OS CPU:                4
	OS memory:             7851 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
act --eventpath pr_lox.json --secret-file .secrets
```

### Describe issue

I used sample json in README for `pr_lox.json` 
```json
{
    "pull_request": {
      "head": {
        "ref": "sample-head-ref"
      },
      "base": {
        "ref": "sample-base-ref"
      }
    }
}
```

But it still acts like `push`.
my `workflow.yml` written like below

```yaml
...
on:
  push:
    branches:
      - 'lox/**'
    paths:
      - .github/workflows/lox.yml
      - lox/**
    tags:
      - lox-*
...
```

What did I miss? or is it a bug?

### Workflow content

```yml
name: lox

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches:
      - 'lox/**'
    paths:
      - .github/workflows/lox.yml
      - lox/**
    tags:
      - lox-*

jobs:
  build:
    # if: startsWith(github.ref, 'refs/tags/lox-')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
```

### Relevant log output

```sh
[lox/build  ] Extracting content from '/var/folders/9x/jf14h4hx403_dkn80cjqh8500000gn/T/act3328915356' to '/Users/E**/Dev/c*'
DEBU[0002] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[0002] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
DEBU[0002] Loading slug from git directory '/Users/E**/Dev/c*/.git' 
DEBU[0002] Loading revision from git directory '/Users/E**/Dev/c*/.git' 
DEBU[0002] Found revision: 625c0184778100544ff7ba98622b35536cbc0e13 
DEBU[0002] HEAD points to '625c0184778100544ff7ba98622b35536cbc0e13' 
DEBU[0002] Loading slug from git directory '/Users/E**/Dev/c*/.git' 
DEBU[0002] Loading revision from git directory '/Users/E**/Dev/c*/.git' 
DEBU[0002] Found revision: 625c0184778100544ff7ba98622b35536cbc0e13 
DEBU[0002] HEAD points to '625c0184778100544ff7ba98622b35536cbc0e13' 
DEBU[0002] using github ref: refs/heads/501-CD-pipeline 
DEBU[0002] using github ref: refs/heads/501-CD-pipeline 
DEBU[0002] Found revision: 625c0184778100544ff7ba98622b35536cbc0e13 
DEBU[0002] Found revision: 625c0184778100544ff7ba98622b35536cbc0e13 
Error: context canceled
```
