### ISSUE TITLE
unable to get git repo

### ISSUE THREAD

**Issue by m-cat** [nektos/act#1242]
### Bug report info

```plain text
act version:            0.2.29
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 16
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/Users/marcin/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=ghcr.io/catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.18.3
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -X main.version=0.2.29
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
Docker Engine:
	Engine version:        20.10.10
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             5.10.47-linuxkit
	OS CPU:                4
	OS memory:             1985 MB
	Security options:
		name=seccomp,profile=default
```

### Command used with act

```sh
act
```

### Describe issue

Tons and tons of error message spam in the output.

### Link to GitHub repository

https://github.com/SkynetLabs/skynet-js

### Workflow content

```yml
name: "CI"

on:
  push:
    branches: [master]
  pull_request:

# For auto-approving/merging PRs.
permissions:
  pull-requests: write
  contents: write

jobs:
  check:
    name: "Checks and Tests"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        portal: ["siasky.net", "skynetfree.net", "skynetpro.net"]
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: "Run Yarn Basic Checks"
        # This is needed because PRs from forks do not have access to secrets.
        #
        # TODO: We can change this to always run siasky later, but right now this portal
        #       is too unstable.
        if: "!github.event.pull_request.head.repo.fork || matrix.portal != 'siasky.net'"
        uses: SkynetLabs/.github/.github/actions/yarn-basic-checks@master
        with:
          node-version: ${{ matrix.node-version }}
          build: true
        env:
          SKYNET_JS_INTEGRATION_TEST_SERVER: "https://${{ matrix.portal }}"
          SKYNET_JS_INTEGRATION_TEST_SKYNET_API_KEY: ${{ secrets.SKYNET_API_KEY }}

  # Auto-merge Dependabot PRs. Requires also `.github/.kodiak.toml`.
  # See https://hackmd.io/@SkynetLabs/ryFfInNXc.
  dependabot:
    name: "Approve and Merge Dependabot PRs"
    # - Must be a PR.
    # - The latest actor must be Dependabot. This prevents other users from
    #   sneaking in changes into the PR.
    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: "Run Auto-Approval and Auto-Merge"
        uses: SkynetLabs/.github/.github/actions/dependabot-approve-and-merge@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

### Relevant log output

```sh
[CI/Checks and Tests-6              ] unable to get git repo: unable to find git repo
[CI/Checks and Tests-6              ] unable to get git ref: unable to find git repo
[CI/Checks and Tests-6              ] unable to get git revision: unable to find git repo
[CI/Checks and Tests-6              ] unable to get git repo: unable to find git repo
[CI/Checks and Tests-6              ] unable to get git ref: unable to find git repo
[CI/Checks and Tests-6              ] unable to get git revision: unable to find git repo
[CI/Checks and Tests-6              ] unable to get git repo: unable to find git repo
[CI/Checks and Tests-6              ] unable to get git ref: unable to find git repo
```
etc.
```


### Additional information

_No response_
