### ISSUE TITLE
Can't execute actions defined as Dockerfile labels

### ISSUE THREAD

**Issue by yanniszark** [nektos/act#126]
**What happened:**

I wanted to use this action in my workflow: https://github.com/marketplace/actions/golang-action
Running it in my workflow with act, I got:

```
Error: open /home/yanniszark/.cache/act/cedrickring-golang-action@1.5.0/action.yaml: no such file or directory
```

I also noticed that the action has metadata specified as Dockerfile labels:
https://github.com/cedrickring/golang-action/blob/cdeafbe2c49ae37107aba9a5c34bfa4eb3b26e98/Dockerfile

**What I expected to happen:**

I expected the workflow to run.

**How to reproduce:**

Try this workflow with act:

```yaml
on: push
name: My cool Action
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.5.0
```
