### ISSUE TITLE
Support if condition

### ISSUE THREAD

**Issue by robdodson** [nektos/act#127]
- Version of act
act version 0.2.5

- Platform (Linux, OS X, Windows)
macOS 10.14.6

- The complete main.workflow file used
```yml
name: Lint front matter
on:
# By default, runs when a pull_request's activity type is opened, synchronize,
# or reopened
  pull_request:
    paths:
      - '**.md'
      - '**.markdown'

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install
        run: npm ci
      
      - name: Git diff
        id: git_diff
        uses: futuratrepadeira/changed-files@v3.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint yaml front matter
        uses: ./.github/actions/lint-yaml
        with:
          added: ${{ steps.git_diff.outputs.files_created }}
          modified: ${{ steps.git_diff.outputs.files_updated }}
        # Only run the linter if the previous step indicated that files were
        # added or modified in the pull request.
        if: steps.git_diff.outputs.files_created || steps.git_diff.outputs.files_updated
```

- The complete command that was executed
`act pull_request -q -e event.json -s GITHUB_TOKEN=[my access token]`

- Any output from the command
```
[Lint front matter/Linter] 🚀  Start image=node:12.6-buster-slim
[Lint front matter/Linter]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Lint front matter/Linter]   🐳  docker cp src=... dst=/github/workspace
[Lint front matter/Linter] ⭐  Run Checkout
[Lint front matter/Linter]   ✅  Success - Checkout
[Lint front matter/Linter] ⭐  Run Setup node
[Lint front matter/Linter]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v1
[Lint front matter/Linter]   🐳  docker cp src=/Users/.../.cache/act/actions-setup-node@v1 dst=/actions/
[Lint front matter/Linter]   💬  ::debug::isExplicit: 
[Lint front matter/Linter]   💬  ::debug::explicit? false
[Lint front matter/Linter]   💬  ::debug::evaluating 0 versions
[Lint front matter/Linter]   💬  ::debug::match not found
[Lint front matter/Linter]   💬  ::debug::evaluating 380 versions
[Lint front matter/Linter]   💬  ::debug::matched: v12.16.1
[Lint front matter/Linter]   💬  ::debug::isExplicit: 12.16.1
[Lint front matter/Linter]   💬  ::debug::explicit? true
[Lint front matter/Linter]   💬  ::debug::checking cache: /opt/hostedtoolcache/node/12.16.1/x64
[Lint front matter/Linter]   💬  ::debug::not found
[Lint front matter/Linter]   💬  ::debug::Downloading https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz
[Lint front matter/Linter]   💬  ::debug::Downloading /home/actions/temp/3913e941-a48b-482f-ad84-449fe6874da5
[Lint front matter/Linter]   💬  ::debug::download complete
[Lint front matter/Linter]   💬  ::debug::Caching tool node 12.16.1 x64
[Lint front matter/Linter]   💬  ::debug::source dir: /home/actions/temp/8ad7e592-788e-45d7-90f0-a5e2aaa7af9b/node-v12.16.1-linux-x64
[Lint front matter/Linter]   💬  ::debug::destination /opt/hostedtoolcache/node/12.16.1/x64
[Lint front matter/Linter]   💬  ::debug::finished caching tool
[Lint front matter/Linter]   ⚙  ::add-path:: /opt/hostedtoolcache/node/12.16.1/x64/bin
[Lint front matter/Linter]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/tsc.json
[Lint front matter/Linter]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/eslint-stylish.json
[Lint front matter/Linter]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/eslint-compact.json
[Lint front matter/Linter]   ✅  Success - Setup node
[Lint front matter/Linter] ⭐  Run Install
[Lint front matter/Linter]   ✅  Success - Install
[Lint front matter/Linter] ⭐  Run Git diff
[Lint front matter/Linter]   ☁  git clone 'https://github.com/futuratrepadeira/changed-files' # ref=v3.0.1
[Lint front matter/Linter] Unable to pull refs/heads/v3.0.1: non-fast-forward update
[Lint front matter/Linter]   🐳  docker cp src=/Users/.../.cache/act/futuratrepadeira-changed-files@v3.0.1 dst=/actions/
[Lint front matter/Linter]   💬  ::debug::Found count() {%0A        return this.updated.length + this.created.length + this.deleted.length;%0A    } changed files for pr #5
[Lint front matter/Linter]   ⚙  ::set-output:: files_created=.gitignore event.json
[Lint front matter/Linter]   ⚙  ::set-output:: files_updated=src/site/content/en/foo.md
[Lint front matter/Linter]   ⚙  ::set-output:: files_deleted=
[Lint front matter/Linter]   ✅  Success - Git diff
```

- Details of the expected results and how they differed from the actual results
I have an `if` condition in my workflow that says if it sees `files_created` or `files_updated` during the git_diff step then the next step should run. But it looks like `act` stops executing after the git_diff step. If I remove the `if` condition, then it runs the next step. The `if` condition works as expected when I'm using GitHub's Actions panel in the repo itself.
