### ISSUE TITLE
Github Action home-brew does not work with act but works on Github.com

### ISSUE THREAD

**Issue by richtong** [nektos/act#1271]
### Bug report info

```plain text
act --bug-report


act version:            0.2.26
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
	/Users/rich/.colima/docker.sock
Config files:
	/Users/rich/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Docker Engine:
	Engine version:        20.10.16
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:
	OS arch:               aarch64
	OS kernel:             5.10.104-linuxkit
	OS CPU:                4
	OS memory:             15972 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```
```


### Command used with act

```sh
act -v -j pre-commit
```

### Describe issue

Trying to install something via homebrew and this works on GitHub actions, but not with act

I get a message `brew not found` so something is wrong with the image building. I'm having trouble seeing where all this is happening, but it looks like you build a custom image for a build step, and somehow the image created does not execute the GitHub action correctly, so buried in here is `sh: 1: brew: not found

Since you delete the container I can't take a look at it to see how it is constructed and why homebrew was not installed. It could be I guess this problem with the containers running as root users and homebrew usually prevents installation as  a result.

### Link to GitHub repository

https://github.com/richtong/bin

### Workflow content

```yml
# yamllint disable-line rule:truthy
on:
  push:
    # if you have lots of requests you can limit the branches
    branches:
      - main
      - master
      - rich-*
  pull_request:

jobs:

  python:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    # Note with this version testing you do not need tox in the cloud
    strategy:
      matrix:
        # 3.7 will not run with the current requirements.txt pinning
        # we do not need matrix that is in python version
        # https://github.com/actions/setup-python/issues/249
        # Need to quote 3.10 as this gets shortend to "3.10"
        python-version: [3.8, 3.9]
    # checkout repo under $GITHUB_WORKSPACE
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          lfs: true
          # submodules should be tested one at a time
          # submodules: recursive
      # install latest python version
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # Ubuntu specific path
          path: ~/.cache/pip
          # https://github.com/actions/cache/blob/main/examples.md#python---pip
          # See if there is a cache hit looking for the requirements.txt
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      # this works in github actions
      # this fails if there is no python/requirements
      #   uses: py-actions/py-dependency-install@v3
      #   with:
      #       path: "python/requirements.txt"
      # this hangs in act but works in github actions
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip && \
          if [ -f python/requirements.txt ]; then pip install -r python/requirements.txt; fi

  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout action
        uses: actions/checkout@v3
        with:
          lfs: true
          # submodules should be tested one at a time
          # submodules: recursive
      # pre-commit needs python
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      # # https://snapcraft.io/install/shfmt/ubuntu
      # Using snapd fails on act so instead use pre-commit
      # that does its own installation rather than needing shfmt
      #- name: Install shfmt
      #  run: |
      #    sudo apt-get update && \
      #    sudo apt-get install snapd && \
      #    sudo snap install shfmt
      # install dependencies for ruby gem mdl
      # we use markdownlint now instead not the ruby gem mdl
      # https://github.com/ruby/setup-ruby
      # - name: Install ruby
      # #uses: ruby/setup-ruby@v1
      # #with:
      #   #ruby-version: 3.0
      # - name: Install Gems
      # #run: |
      #   #gem install mdl
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      # https://github.com/marketplace/actions/github-action-for-homebrew
      # fails in act because it is running as root and homebrew will not
      # https://github.com/nektos/act/issues/1184
      - name: Install homebrew
        uses: artemnovichkov/action-homebrew@0.1.0
      - name: Install hadolint
        run: brew install hadolint
```

### Relevant log output

```sh
[Python and Pre-commit/pre-commit]   🐳  docker create image=act-artemnovichkov-action-homebrew-0-1-0-dockeraction:latest platform= entrypoint=[] cmd=[]
[Python and Pre-commit/pre-commit] Created container name=act-Python-and-4 id=523629c8f19b680421289bc59311112006456862dcbec27eac14b943953b9fb1 from image act-artemnovichkov-action-homebrew-0-1-0-dockeraction:latest (platform: )
[Python and Pre-commit/pre-commit] ENV ==> [GITHUB_REPOSITORY=richtong/src GITHUB_WORKFLOW=Python and Pre-commit GITHUB_ACTIONS=true GITHUB_BASE_REF= RUNNER_USER=root AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache GITHUB_EVENT_NAME=push GITHUB_ACTOR=nektos/act DEPLOYMENT_BASEPATH=/opt/runner GITHUB_EVENT_PATH=/var/run/act/workflow/event.json ImageOS=ubuntu20 GITHUB_REPOSITORY_OWNER=richtong LSB_OS_VERSION=2004 GITHUB_ACTION=4 GITHUB_ENV=/var/run/act/workflow/envs.txt LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.9.13/x64/lib DEBIAN_FRONTEND=noninteractive pythonLocation=/opt/hostedtoolcache/Python/3.9.13/x64 USER=root RUNNER_PERFLOG=/dev/null GITHUB_PATH=/var/run/act/workflow/paths.txt RUN_TOOL_CACHE=/opt/hostedtoolcache GITHUB_SERVER_URL=https://github.com GITHUB_API_URL=https://api.github.com GITHUB_RUN_NUMBER=1 CI=true RUNNER_TRACKING_ID= LSB_RELEASE=20.04 GITHUB_RUN_ID=1 GITHUB_WORKSPACE=/Users/rich/ws/git/src/bin GITHUB_TOKEN= PATH=/opt/hostedtoolcache/node/14.20.0/x64/bin:/opt/hostedtoolcache/Python/3.9.13/x64/bin:/opt/hostedtoolcache/Python/3.9.13/x64:/opt/hostedtoolcache/node/14.20.0/x64/bin:/opt/hostedtoolcache/Python/3.9.13/x64/bin:/opt/hostedtoolcache/Python/3.9.13/x64:/opt/hostedtoolcache/Python/3.9.13/x64/bin:/opt/hostedtoolcache/Python/3.9.13/x64:/opt/hostedtoolcache/node/16.16.0/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin GITHUB_ACTION_REPOSITORY= GITHUB_HEAD_REF= ACT=true IMAGE_OS=ubuntu20 GITHUB_REF=refs/heads/rich-src GITHUB_GRAPHQL_URL=https://api.github.com/graphql GITHUB_JOB=pre-commit GITHUB_RETENTION_DAYS=0 GITHUB_SHA=37bb6ab8200e04cf460cb80f05dfa76d6764e582 GITHUB_ACTION_PATH= GITHUB_ACTION_REF= RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_TEMP=/tmp]
[Python and Pre-commit/pre-commit]   🐳  docker run image=act-artemnovichkov-action-homebrew-0-1-0-dockeraction:latest platform= entrypoint=[] cmd=[]
[Python and Pre-commit/pre-commit] Starting container: 523629c8f19b680421289bc59311112006456862dcbec27eac14b943953b9fb1
[Python and Pre-commit/pre-commit] Started container: 523629c8f19b680421289bc59311112006456862dcbec27eac14b943953b9fb1
| sh: 1: brew: not found
[Python and Pre-commit/pre-commit] Return status: 127
[Python and Pre-commit/pre-commit] Removed container: 523629c8f19b680421289bc59311112006456862dcbec27eac14b943953b9fb1
[Python and Pre-commit/pre-commit]   ❌  Failure - Install homebrew
[Python and Pre-commit/pre-commit] exit with `FAILURE`: 127
```
```


### Additional information

_No response_
