### ISSUE TITLE
Cannot find on: pull_request:

### ISSUE THREAD

**Issue by johntimothybailey** [nektos/act#1281]
### Bug report info

```plain text
Stage  Job ID  Job name  Workflow name  Workflow file  Events
```

### Command used with act

```sh
act -l --container-architecture linux/amd64
```

### Describe issue

My file that runs on Github is as follows but cannot be found or ran by `act`

```markdown
name: Mobile UI Package

on:
  pull_request:
    branches: [dev]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter Version Manager (FVM)
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Flutter Action
        uses: subosito/flutter-action@v1
        with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install
        run: flutter --version
        working-directory: ./mobile
```

However, if I change to `on: push` the job is found.

### Workflow content

```yml
name: Mobile UI Package

on:
  pull_request:
    branches: [dev]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter Version Manager (FVM)
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Flutter Action
        uses: subosito/flutter-action@v1
        with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install
        run: flutter --version
        working-directory: ./mobile
```

### Relevant log output

```sh
DEBU[0000] Loading environment from /Users/johnbailey/Development/project/.env 
DEBU[0000] Loading secrets from /Users/johnbailey/Development/project/.secrets 
DEBU[0000] Loading workflows from '/Users/johnbailey/Development/project/.github/workflows' 
DEBU[0000] Loading workflows recursively                
DEBU[0000] Found workflow 'api-unit-tests.yml' in '/Users/johnbailey/Development/project/.github/workflows/api-unit-tests.yml' 
DEBU[0000] Found workflow 'verify-mobile.yml' in '/Users/johnbailey/Development/Fursure/project/.github/workflows/verify-mobile.yml' 
DEBU[0000] Found workflow 'verify.yml' in '/Users/johnbailey/Development/project/.github/workflows/verify.yml' 
DEBU[0000] Reading workflow '/Users/johnbailey/Development/project/.github/workflows/api-unit-tests.yml' 
DEBU[0000] Reading workflow '/Users/johnbailey/Development/project/.github/workflows/verify-mobile.yml' 
DEBU[0000] Reading workflow '/Users/johnbailey/Development/project/.github/workflows/verify.yml' 
DEBU[0000] Planning event: push
```
