### ISSUE TITLE
finds workflow but no events

### ISSUE THREAD

**Issue by TheMoakMan** [nektos/act#1318]
I'm brand new to act and I'm having issues getting it to run my workflow file.

Jobs list is empty with the following workflow. 
It find the workflow file but no events for push when running
```act -l -v```

I get the following output:
```
"no events found for workflow: push"
```

Here is the workflow file:
```
name: NodeJS Action Test

on:
  push:
    branches: [main]

jobs:
  TestNodeScript:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
      
      - name: Run Action
        uses: ./testing/nodejs-script@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

Am I missing something? Is there an issue with parsing the original file because it uses a custom action or is expecting a payload from the events json?
