### ISSUE TITLE
`act -l` doesn't list workflow_dispatch events

### ISSUE THREAD

**Issue by ljharb** [nektos/act#1329]
### Bug report info

```plain text
act version:            0.2.30
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 16
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/Users/ljharb/.actrc:
		-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.18.4
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -X main.version=0.2.30
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
Docker Engine:
	Engine version:        20.10.17
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             5.10.104-linuxkit
	OS CPU:                4
	OS memory:             7960 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
act -l
```

### Describe issue

I got:
```
Stage  Job ID    Job name       Workflow name            Workflow file     Events           
0      matrix    matrix         Tests: node.js           node-4+.yml       pull_request,push
0      pretest   pretest        Tests: pretest/posttest  node-pretest.yml  pull_request,push
0      posttest  posttest       Tests: pretest/posttest  node-pretest.yml  pull_request,push
0      readme    readme         Tests: readme            readme.yml        pull_request,push
0      release   release        Release                  release.yml       push             
1      latest    latest majors  Tests: node.js           node-4+.yml       pull_request,push
2      node      node 4+        Tests: node.js           node-4+.yml       pull_request,push
```

I expected https://github.com/jsx-eslint/eslint-plugin-react/blob/master/.github/workflows/smoke-test.yml to be listed, so i could run `act -j` with its Job ID.

### Link to GitHub repository

https://github.com/jsx-eslint/eslint-plugin-react/

### Workflow content

```yml
name: Smoke test

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  smoke-test:
    if: ${{ github.repository == 'jsx-eslint/eslint-plugin-react' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@main
        name: 'nvm install lts/* && npm install'
        with:
          node-version: 'lts/*'
          skip-ls-check: true
      - run: |
          npm link
          npm link eslint-plugin-react
      - uses: AriPerkkio/eslint-remote-tester-run-action@v3
        with:
          issue-title: 'Results of weekly scheduled smoke test'
          eslint-remote-tester-config: test/eslint-remote-tester.config.js
```

### Relevant log output

```sh
N/A
```
