### ISSUE TITLE
Installation fails: "Failure - Main Use Node.js ${{ matrix.node-version }}"

### ISSUE THREAD

**Issue by mStirner** [nektos/act#1342]
### Bug report info

```plain text
act version:            0.2.31
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/marc/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.18.5
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.31 -X main.commit=a20b1d4669d8d032fe35347bd3cfdae58b4d1d97 -X main.date=2022-09-01T02:56:14Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         a20b1d4669d8d032fe35347bd3cfdae58b4d1d97
		vcs.time:             2022-08-31T18:41:56Z
		vcs.modified:         false
Docker Engine:
	Engine version:        20.10.17
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 18.04.6 LTS
	OS type:               linux
	OS version:            18.04
	OS arch:               x86_64
	OS kernel:             5.4.0-124-generic
	OS CPU:                8
	OS memory:             15818 MB
	Security options:
		name=apparmor
		name=seccomp,profile=default
```

### Command used with act

```sh
./bin/act
```

### Describe issue

First run failed, After selecting the image size (medium) and pulling some images the command failed.

```
[Node.js CI/build-12]   💬  ::debug::npm path is /root/.npm
[Node.js CI/build-12]   💬  ::debug::followSymbolicLinks 'true'
[Node.js CI/build-12]   💬  ::debug::followSymbolicLinks 'true'
[Node.js CI/build-12]   💬  ::debug::implicitDescendants 'true'
[Node.js CI/build-12]   💬  ::debug::matchDirectories 'true'
[Node.js CI/build-12]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[Node.js CI/build-12]   💬  ::debug::Search path '/home/marc/projects/OpenHaus/backend/package-lock.json'
[Node.js CI/build-12]   💬  ::debug::/home/marc/projects/OpenHaus/backend/package-lock.json
[Node.js CI/build-12]   💬  ::debug::Found 1 files to hash.
[Node.js CI/build-12]   💬  ::debug::primary key is node-cache-Linux-npm-6a6de438d85da130366ee2d81de922af638507baee1b1a330b14f4b2f3964962
[Node.js CI/build-12]   💾  ::save-state name=CACHE_KEY::node-cache-Linux-npm-6a6de438d85da130366ee2d81de922af638507baee1b1a330b14f4b2f3964962
[Node.js CI/build-12]   💬  ::debug::Resolved Keys:
[Node.js CI/build-12]   💬  ::debug::["node-cache-Linux-npm-6a6de438d85da130366ee2d81de922af638507baee1b1a330b14f4b2f3964962"]
[Node.js CI/build-12]   💬  ::debug::Checking zstd --version
[Node.js CI/build-12]   💬  ::debug::*** zstd command line interface 64-bits v1.4.4, by Yann Collet ***
[Node.js CI/build-12]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Node.js CI/build-12]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Node.js CI/build-12]   ❗  ::error::getCacheEntry failed: Cache Service Url not found, unable to restore cache.
[Node.js CI/build-12]   ❌  Failure - Main Use Node.js ${{ matrix.node-version }}
[Node.js CI/build-12] exitcode '1': failure
[Node.js CI/build-12] 🏁  Job failed
Error: Job 'build' failed
```

I think the important part from the output above is:
`[Node.js CI/build-12]   ❌  Failure - Main Use Node.js ${{ matrix.node-version }}`

### Workflow content

```yml
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        #runs-on: [ubuntu-18.04, ubuntu-latest]
        runs-on: ${{ matrix.os }}

        # httpbin for helper/request
        services:
            httpbin:
                image: kennethreitz/httpbin
                ports: 
                    - 80:80

        strategy:
            matrix:
                os: [ubuntu-18.04, ubuntu-latest]
                node-version: [16.x, 17.x]           # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                mongodb-version: ["4.2", "4.4", "5.0"]

        steps:
            - uses: actions/checkout@v2

            # mongodb setup
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}            

            # node.js setup
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run lint
            - run: npm test
```

### Relevant log output

```sh
[Node.js CI/build-12] [DEBUG] Found revision: fac31df6fc08e1b9bf38cdc095342f70bd7675d4
[Node.js CI/build-12] [DEBUG] HEAD points to 'fac31df6fc08e1b9bf38cdc095342f70bd7675d4'
[Node.js CI/build-12] [DEBUG] using github ref: refs/heads/dev
[Node.js CI/build-12] [DEBUG] Found revision: fac31df6fc08e1b9bf38cdc095342f70bd7675d4
[Node.js CI/build-12] [DEBUG] evaluating expression 'success()'
[Node.js CI/build-12] [DEBUG] expression 'success()' evaluated to 'false'
[Node.js CI/build-12] [DEBUG] Skipping step 'Use Node.js ${{ matrix.node-version }}' due to 'success()'
[Node.js CI/build-12] [DEBUG] skipping post step for 'actions/checkout@v2': no action model available
[Node.js CI/build-12] 🏁  Job failed
[Node.js CI/build-12] [DEBUG] Loading slug from git directory '/home/marc/projects/OpenHaus/backend/.git'
[Node.js CI/build-12] [DEBUG] Loading revision from git directory '/home/marc/projects/OpenHaus/backend/.git'
[Node.js CI/build-12] [DEBUG] Found revision: fac31df6fc08e1b9bf38cdc095342f70bd7675d4
[Node.js CI/build-12] [DEBUG] HEAD points to 'fac31df6fc08e1b9bf38cdc095342f70bd7675d4'
[Node.js CI/build-12] [DEBUG] using github ref: refs/heads/dev
[Node.js CI/build-12] [DEBUG] Found revision: fac31df6fc08e1b9bf38cdc095342f70bd7675d4
```

### Additional information

OS: Ubuntu 18.04 x64 LTS
