### ISSUE TITLE
act does not evaluate step names

### ISSUE THREAD

**Issue by basz** [nektos/act#1353]
### Bug report info

```plain text
act version:            0.2.31
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
Config files:           
        /Users/bas/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.19
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -compiler:            gc
                -ldflags:             -X main.version=0.2.31
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        20.10.17
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.10.124-linuxkit
        OS CPU:                5
        OS memory:             7851 MB
        Security options:
                name=seccomp,profile=default
                name=cgroupns
```

### Command used with act

```sh
act --actor basz --secret-file=.secrets --container-architecture linux/amd64
```

### Describe issue

Mayby a question, mayby a bug

the matrix variables are not "expanded" in the output. Shouldn't they be?

### Workflow content

```yml
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * 0,3"
  push:
    branches:
      - "main"

name: "Build And Push PHP Docker Images"

jobs:
  build-and-push-docker:
    name: "Build And Push PHP Docker Images"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        php-target:
          - "cli"
          - "fpm"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        platforms: amd64,arm64

        # @see https://github.com/docker/setup-buildx-action#quick-start
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          driver: docker-container
          config: .github/buildkitd.toml
          buildkitd-flags: --debug

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build ${{ matrix.php-version }}-${{ matrix.php-target }}"
        working-directory: php
        run: |
          docker build . --file php-${{ matrix.php-target }} --platform linux/amd64,linux/arm64 --push --tag ghcr.io/plhw/lab-docker/php-test:${{ matrix.php-version }}-${{ matrix.php-target }}
        env:
          PHP_VERSION: ${{ matrix.php-version }}
```

### Relevant log output

```sh
[Build And Push PHP Docker Images/Build And Push PHP Docker Images-2] ⭐ Run Main Build ${{ matrix.php-version }}-${{ matrix.php-target }}
[Build And Push PHP Docker Images/Build And Push PHP Docker Images-3] ⭐ Run Main Build ${{ matrix.php-version }}-${{ matrix.php-target }}
```
