### ISSUE TITLE
act bug!

### ISSUE THREAD

**Issue by brinkqiang** [nektos/act#1366]
### Bug report info

```plain text
$ sudo act workflow_dispatch -j linux
[linux/linux] 🚀  Start image=catthehacker/ubuntu:act-18.04
[linux/linux]   🐳  docker pull image=catthehacker/ubuntu:act-18.04 platform= username= forcePull=false
[linux/linux]   🐳  docker create image=catthehacker/ubuntu:act-18.04 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[linux/linux]   🐳  docker run image=catthehacker/ubuntu:act-18.04 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[linux/linux]   ☁  git clone 'https://github.com/lukka/get-cmake' # ref=latest
[linux/linux]   ☁  git clone 'https://github.com/actions/setup-python' # ref=v4
[linux/linux]   ☁  git clone 'https://github.com/johnwason/vcpkg-action' # ref=v3
[linux/linux] ⭐ Run Pre johnwason/vcpkg-action@v3
[linux/linux]   ☁  git clone 'https://github.com/pozetroninc/github-action-get-latest-release' # ref=v0.6.0
[linux/linux]   ☁  git clone 'https://github.com/actions/checkout' # ref=v3
[linux/linux]   ☁  git clone 'https://github.com/pat-s/always-upload-cache' # ref=v3
[linux/linux]   ✅  Success - Pre johnwason/vcpkg-action@v3
[linux/linux]   ☁  git clone 'https://github.com/Sibz/github-status-action' # ref=v1
[linux/linux] 🧪  Matrix: map[os:ubuntu-18.04]
[linux/linux] ⭐ Run Main actions/checkout@v3
[linux/linux]   🐳  docker cp src=/home/suiy/private_github/dmboostpythonmodule/. dst=/home/suiy/private_github/dmboostpythonmodule
[linux/linux]   ✅  Success - Main actions/checkout@v3
[linux/linux] ⭐ Run Main lukka/get-cmake@latest
[linux/linux]   🐳  docker cp src=/home/suiy/.cache/act/lukka-get-cmake@latest/ dst=/var/run/act/actions/lukka-get-cmake@latest/
[linux/linux]   🐳  docker exec cmd=[node /var/run/act/actions/lukka-get-cmake@latest/dist/index.js] user= workdir=
[linux/linux]   💬  ::debug::hash('https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gzhttps://github.com/ninja-build/ninja/releases/download/v1.11.0/ninja-linux.zip') === '-1647216998'
[linux/linux]   ❓  ::group::Restore from cache using key '-1647216998' into /tmp/-1647216998
[linux/linux]   💬  ::debug::Resolved Keys:
[linux/linux]   💬  ::debug::["-1647216998"]
[linux/linux]   💬  ::debug::Checking zstd --version
[linux/linux]   💬  ::debug::*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
[linux/linux]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[linux/linux]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[linux/linux]   ❓  ::endgroup::
| Error: getCacheEntry failed: Cache Service Url not found, unable to restore cache.
|     at /run/act/actions/lukka-get-cmake@latest/dist/index.js:50637:15
|     at Generator.throw (<anonymous>)
|     at rejected (/run/act/actions/lukka-get-cmake@latest/dist/index.js:50568:65)
[linux/linux]   ❗  ::error::get-cmake action execution failed: 'Error: getCacheEntry failed: Cache Service Url not found, unable to restore cache.'
[linux/linux]   ❌  Failure - Main lukka/get-cmake@latest
[linux/linux] exitcode '24': failure
[linux/linux] 🏁  Job failed
Error: Job 'linux' failed



url: https://github.com/brinkqiang/dmboostpythonmodule
```

### Command used with act

```sh
sudo act workflow_dispatch -j linux
```

### Describe issue

Compilation error, does act not support some action plugins?

### Link to GitHub repository

https://github.com/brinkqiang/dmboostpythonmodule

### Workflow content

```yml
name: linux

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: relwithdebinfo

jobs:
  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7.18' 

      - run: pip install -r requirements.txt

      - uses: johnwason/vcpkg-action@v3
        with:
          pkgs: boost-python
          triplet: x64-linux

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
            cmake $GITHUB_WORKSPACE -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        env:
            BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
            cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        shell: bash
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Set Status'
          description: 'Passed'
          state: 'success'
```

### Relevant log output

```sh
$ sudo act workflow_dispatch -j linux
[linux/linux] 🚀  Start image=catthehacker/ubuntu:act-18.04
[linux/linux]   🐳  docker pull image=catthehacker/ubuntu:act-18.04 platform= username= forcePull=false
[linux/linux]   🐳  docker create image=catthehacker/ubuntu:act-18.04 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[linux/linux]   🐳  docker run image=catthehacker/ubuntu:act-18.04 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[linux/linux]   ☁  git clone 'https://github.com/lukka/get-cmake' # ref=latest
[linux/linux]   ☁  git clone 'https://github.com/actions/setup-python' # ref=v4
[linux/linux]   ☁  git clone 'https://github.com/johnwason/vcpkg-action' # ref=v3
[linux/linux] ⭐ Run Pre johnwason/vcpkg-action@v3
[linux/linux]   ☁  git clone 'https://github.com/pozetroninc/github-action-get-latest-release' # ref=v0.6.0
[linux/linux]   ☁  git clone 'https://github.com/actions/checkout' # ref=v3
[linux/linux]   ☁  git clone 'https://github.com/pat-s/always-upload-cache' # ref=v3
[linux/linux]   ✅  Success - Pre johnwason/vcpkg-action@v3
[linux/linux]   ☁  git clone 'https://github.com/Sibz/github-status-action' # ref=v1
[linux/linux] 🧪  Matrix: map[os:ubuntu-18.04]
[linux/linux] ⭐ Run Main actions/checkout@v3
[linux/linux]   🐳  docker cp src=/home/suiy/private_github/dmboostpythonmodule/. dst=/home/suiy/private_github/dmboostpythonmodule
[linux/linux]   ✅  Success - Main actions/checkout@v3
[linux/linux] ⭐ Run Main lukka/get-cmake@latest
[linux/linux]   🐳  docker cp src=/home/suiy/.cache/act/lukka-get-cmake@latest/ dst=/var/run/act/actions/lukka-get-cmake@latest/
[linux/linux]   🐳  docker exec cmd=[node /var/run/act/actions/lukka-get-cmake@latest/dist/index.js] user= workdir=
[linux/linux]   💬  ::debug::hash('https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gzhttps://github.com/ninja-build/ninja/releases/download/v1.11.0/ninja-linux.zip') === '-1647216998'
[linux/linux]   ❓  ::group::Restore from cache using key '-1647216998' into /tmp/-1647216998
[linux/linux]   💬  ::debug::Resolved Keys:
[linux/linux]   💬  ::debug::["-1647216998"]
[linux/linux]   💬  ::debug::Checking zstd --version
[linux/linux]   💬  ::debug::*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
[linux/linux]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[linux/linux]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[linux/linux]   ❓  ::endgroup::
| Error: getCacheEntry failed: Cache Service Url not found, unable to restore cache.
|     at /run/act/actions/lukka-get-cmake@latest/dist/index.js:50637:15
|     at Generator.throw (<anonymous>)
|     at rejected (/run/act/actions/lukka-get-cmake@latest/dist/index.js:50568:65)
[linux/linux]   ❗  ::error::get-cmake action execution failed: 'Error: getCacheEntry failed: Cache Service Url not found, unable to restore cache.'
[linux/linux]   ❌  Failure - Main lukka/get-cmake@latest
[linux/linux] exitcode '24': failure
[linux/linux] 🏁  Job failed
Error: Job 'linux' failed
```
