### ISSUE TITLE
Docker Desktop 22.06.0-beta: invalid filter 'reference'

### ISSUE THREAD

**Issue by drew-viles** [nektos/act#1390]
### Bug report info

```plain text
act version:            0.2.32                                          
GOOS:                   linux                                           
GOARCH:                 amd64                                           
NumCPU:                 2                                               
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:                                                          
        /var/run/docker.sock                                            
Config files:                                                           
        /home/drew/.actrc:                                              
                -P ubuntu-latest=catthehacker/ubuntu:act-latest         
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04           
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.18.6
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.32 -X main.commit=21484b5c1ecbd9e1ddb6a57debd7731a3e1fc25f -X main.date=2022-10-01T03:01:40Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         21484b5c1ecbd9e1ddb6a57debd7731a3e1fc25f
                vcs.time:             2022-09-29T05:59:52Z
                vcs.modified:         false
Docker Engine:
        Engine version:        22.06.0-beta.0-372-gd3bb8227ce.m
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        stargz
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.10.102.1-microsoft-standard-WSL2
        OS CPU:                2
        OS memory:             3924 MB
        Security options:
                name=seccomp,profile=builtin
```

### Command used with act

```sh
act
or
act -j kube_image_builder_job

Both create the same output
```

### Describe issue

I just expected it to be able to run.

### Workflow content

```yml
name: Lint and Test Charts

on: [push]


jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.3.0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run lint
        run: ct lint --all --config .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeconform-chart:
    runs-on: ubuntu-latest
    needs:
      # - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          # from https://github.com/yannh/kubernetes-json-schema
          - v1.22.9
          - v1.23.9
          - v1.24.4
          - v1.25.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Run kubeconform
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeconform.sh
```

### Relevant log output

```sh
time="2022-10-14T12:31:40+01:00" level=debug msg="Loading environment from E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.env"
time="2022-10-14T12:31:40+01:00" level=debug msg="Loading secrets from E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.secrets"
time="2022-10-14T12:31:40+01:00" level=debug msg="Loading workflows from 'E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.github\\workflows'"
time="2022-10-14T12:31:40+01:00" level=debug msg="Loading workflows recursively"
time="2022-10-14T12:31:40+01:00" level=debug msg="Found workflow 'ci.yaml' in 'E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.github\\workflows\\ci.yaml'"
time="2022-10-14T12:31:40+01:00" level=debug msg="Found workflow 'release.yaml' in 'E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.github\\workflows\\release.yaml'"
time="2022-10-14T12:31:40+01:00" level=debug msg="Reading workflow 'E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.github\\workflows\\ci.yaml'"
time="2022-10-14T12:31:40+01:00" level=debug msg="Reading workflow 'E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.github\\workflows\\release.yaml'"
time="2022-10-14T12:31:40+01:00" level=debug msg="Preparing plan with all jobs"
time="2022-10-14T12:31:40+01:00" level=debug msg="Using default workflow event: push"
time="2022-10-14T12:31:40+01:00" level=debug msg="Planning jobs for event: push"
time="2022-10-14T12:31:40+01:00" level=debug msg="Loading slug from git directory 'E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.git'"
time="2022-10-14T12:31:40+01:00" level=debug msg="Loading revision from git directory 'E:\\OwnCloud\\Projects\\GitOps\\GoLang\\gitea.viles.uk\\dcp\\helm-charts\\.git'"
time="2022-10-14T12:31:40+01:00" level=debug msg="Found revision: 22dacb7e00feb33ac1c8a99e0dab08806ed59be4\n"
time="2022-10-14T12:31:40+01:00" level=debug msg="HEAD points to '22dacb7e00feb33ac1c8a99e0dab08806ed59be4'"
time="2022-10-14T12:31:40+01:00" level=debug msg="using github ref: refs/heads/releases/drone-runner-kube-0.2.0"
time="2022-10-14T12:31:40+01:00" level=debug msg="Found revision: 22dacb7e00feb33ac1c8a99e0dab08806ed59be4\n"
[Release Charts/release] [DEBUG] evaluating expression 'success()'
[Release Charts/release] [DEBUG] expression 'success()' evaluated to 'true'
[Release Charts/release] 🚀  Start image=catthehacker/ubuntu:act-latest
[Release Charts/release]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=false
[Release Charts/release] [DEBUG]   🐳  docker pull catthehacker/ubuntu:act-latest
[Release Charts/release] [DEBUG] Image exists? false
Error: unable to determine if image already exists for image 'catthehacker/ubuntu:act-latest' (): Error response from daemon: invalid filter 'reference'
```

### Additional information

I don't seem to be able to get this working on Windows or Windows Subsystem for Linux at all.

This is a fresh install.

I've manually pulled the image catthehacker/ubuntu:act-latest and it's still unable to detect the image.

Any recommendations I can try to get this working?
