### ISSUE TITLE
`act` has no output

### ISSUE THREAD

**Issue by lorensr** [nektos/act#1398]
### Bug report info

```plain text
$ act bug-report
WARN  ⚠ You are using Apple M1 chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠ 

$ act --version
act version 0.2.32

$ which act
/opt/homebrew/bin/act
```

### Command used with act

```sh
act lint-and-prune --container-architecture linux/amd64
```

### Describe issue

Output from the steps' stdout and output describing what steps were taken.

### Link to GitHub repository

https://github.com/temporalio/sdk-typescript/blob/91f3c237618121c55d28967053dfc14fc5947f70/.github/workflows/ci.yml

### Workflow content

```yml
name: Continuous Integration

on:
  pull_request:

jobs:
  lint-and-prune:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'start'
      - run: echo 'done'
```

### Relevant log output

```sh
$ act lint-and-prune -v --container-architecture linux/amd64
DEBU[0000] Loading environment from /Users/me/gh/sdk3/.env 
DEBU[0000] Loading secrets from /Users/me/gh/sdk3/.secrets 
DEBU[0000] Loading workflows from '/Users/me/gh/sdk3/.github/workflows' 
DEBU[0000] Loading workflows recursively                
DEBU[0000] Found workflow 'ci.yml' in '/Users/me/gh/sdk3/.github/workflows/ci.yml' 
DEBU[0000] Reading workflow '/Users/me/gh/sdk3/.github/workflows/ci.yml' 
DEBU[0000] Using first passed in arguments event for filtering: lint-and-prune 
DEBU[0000] Preparing plan for a event: lint-and-prune   
DEBU[0000] Using first passed in arguments event: lint-and-prune 
DEBU[0000] Planning jobs for event: lint-and-prune
```
