### ISSUE TITLE
ReferenceError: 'commit' is not defined

### ISSUE THREAD

**Issue by muuvmuuv** [nektos/act#140]
I'm currently trying to test all of my actions locally but got stuck on a few which requires commit information.

```
act fork
```

```
# fork.yml

name: Fork created

on:
  fork:

jobs:
  notify_email:
    name: Notify by email
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          format: markdown
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The user `<user>` forked muuvmuuv/portfolio

            ${{ commit.ref }}
```

```
[Fork created/Notify by email] ⭐  Run Send message
[Fork created/Notify by email]   ☁  git clone 'https://github.com/appleboy/telegram-action' # ref=master
ERRO[0060] Unable to interpolate string 'The user `<user>` forked muuvmuuv/portfolio

${{ commit.ref }}
' - [ReferenceError: 'commit' is not defined]
[Fork created/Notify by email]   🐳  docker build -t act-appleboy-telegram-action-master:latest /Users/marvinheilemann/.cache/act/appleboy-telegram-action@master
[Fork created/Notify by email]   🐳  docker run image=act-appleboy-telegram-action-master:latest entrypoint=[] cmd=[]
| 2020/03/07 16:02:31 Not Found
[Fork created/Notify by email]   ❌  Failure - Send message
Error: exit with `FAILURE`: 1
```
