### ISSUE TITLE
Use of actions from git source code instead of package/release breaks xt0rted/stylelint-problem-matcher@v1

### ISSUE THREAD

**Issue by ineffyble** [nektos/act#1443]
### Bug report info

```plain text
effy@Scylla mastodon % act --bug-report
act version:            0.2.33
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            unix:///Users/effy/.colima/default/docker.sock
Sockets found:
	/Users/effy/.colima/docker.sock
Config files:
	/Users/effy/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:full-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.19.2
	Module path:           command-line-arguments
	Main version:
	Main path:
	Main checksum:
	Build settings:
		-compiler:            gc
		-ldflags:             -X main.version=0.2.33
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               arm64
		GOOS:                 darwin
Docker Engine:
	Engine version:        20.10.18
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Alpine Linux v3.16
	OS type:               linux
	OS version:            3.16.2
	OS arch:               aarch64
	OS kernel:             5.15.68-0-virt
	OS CPU:                8
	OS memory:             7937 MB
	Security options:
		name=seccomp,profile=default
```

### Command used with act

```sh
act pull_request --container-architecture linux/amd64 --workflows .github/workflows/linter.yml --verbose
```

### Describe issue

The `xt0rted/stylelint-problem-matcher@v1` action fails with an error as the referenced `index.js` doesn't exist.

This looks to occur because the `dist` folder does not exist in the [source code for the action](https://github.com/xt0rted/stylelint-problem-matcher). It does exist in the zip/tarball associated with the release though, so I assume GitHub Actions natively uses the release artifact and act uses the source.

### Link to GitHub repository

https://github.com/mastodon/mastodon

### Workflow content

```yml
---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
permissions:
  checks: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Set-up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Set-up RuboCop Problem Mathcher
        uses: r7kamura/rubocop-problem-matchers-action@v1
      - name: Set-up Stylelint Problem Matcher
        uses: xt0rted/stylelint-problem-matcher@v1
      # https://github.com/xt0rted/stylelint-problem-matcher/issues/360
      - run: echo "::add-matcher::.github/stylelint-matcher.json"

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          CSS_FILE_NAME: stylelint.config.js
          DEFAULT_BRANCH: main
          NO_COLOR: 1 # https://github.com/xt0rted/stylelint-problem-matcher/issues/360
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          LINTER_RULES_PATH: .
          RUBY_CONFIG_FILE: .rubocop.yml
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_RUBY: true
```

### Relevant log output

```sh
[Lint Code Base/Lint Code Base] ⭐ Run Main Set-up Stylelint Problem Matcher
[Lint Code Base/Lint Code Base] [DEBUG] Loading slug from git directory '/Users/effy/code/mastodon/.git'
[Lint Code Base/Lint Code Base] [DEBUG] Found revision: a1738f899142b7080bf50713066c72f56121673e
[Lint Code Base/Lint Code Base] [DEBUG] About to run action &{Problem Matcher for stylelint xt0rted Sets up a problem matcher for stylelint that's used to create annotations for violations map[action:{The action to take on the problem matcher (add or remove) false add}] map[] {node12 map[] dist/index.js  always()  always()   [] []} {green command}}
[Lint Code Base/Lint Code Base] [DEBUG] Loading slug from git directory '/Users/effy/code/mastodon/.git'
[Lint Code Base/Lint Code Base] [DEBUG] Found revision: a1738f899142b7080bf50713066c72f56121673e
[Lint Code Base/Lint Code Base] [DEBUG] Loading slug from git directory '/Users/effy/code/mastodon/.git'
[Lint Code Base/Lint Code Base] [DEBUG] Found revision: a1738f899142b7080bf50713066c72f56121673e
[Lint Code Base/Lint Code Base] [DEBUG] type=remote-action actionDir=/Users/effy/.cache/act/xt0rted-stylelint-problem-matcher@v1 actionPath= workdir=/Users/effy/code/mastodon actionCacheDir=/Users/effy/.cache/act actionName=xt0rted-stylelint-problem-matcher@v1 containerActionDir=/var/run/act/actions/xt0rted-stylelint-problem-matcher@v1
[Lint Code Base/Lint Code Base] [DEBUG] Removing /Users/effy/.cache/act/xt0rted-stylelint-problem-matcher@v1/.gitignore before docker cp
[Lint Code Base/Lint Code Base] [DEBUG] /var/run/act/actions/xt0rted-stylelint-problem-matcher@v1
[Lint Code Base/Lint Code Base]   🐳  docker cp src=/Users/effy/.cache/act/xt0rted-stylelint-problem-matcher@v1/ dst=/var/run/act/actions/xt0rted-stylelint-problem-matcher@v1/
[Lint Code Base/Lint Code Base] [DEBUG] Writing tarball /var/folders/vz/4drjg3hs0szcrx0zdx8knxkh0000gn/T/act2945607965 from /Users/effy/.cache/act/xt0rted-stylelint-problem-matcher@v1/
[Lint Code Base/Lint Code Base] [DEBUG] Stripping prefix:/Users/effy/.cache/act/xt0rted-stylelint-problem-matcher@v1/ src:/Users/effy/.cache/act/xt0rted-stylelint-problem-matcher@v1/
[Lint Code Base/Lint Code Base] [DEBUG] Extracting content from '/var/folders/vz/4drjg3hs0szcrx0zdx8knxkh0000gn/T/act2945607965' to '/var/run/act/actions/xt0rted-stylelint-problem-matcher@v1/'
[Lint Code Base/Lint Code Base] [DEBUG] executing remote job container: [node /var/run/act/actions/xt0rted-stylelint-problem-matcher@v1/dist/index.js]
[Lint Code Base/Lint Code Base]   🐳  docker exec cmd=[node /var/run/act/actions/xt0rted-stylelint-problem-matcher@v1/dist/index.js] user= workdir=
[Lint Code Base/Lint Code Base] [DEBUG] Exec command '[node /var/run/act/actions/xt0rted-stylelint-problem-matcher@v1/dist/index.js]'
[Lint Code Base/Lint Code Base] [DEBUG] Working directory '/Users/effy/code/mastodon'
| node:internal/modules/cjs/loader:988
|   throw err;
|   ^
|
| Error: Cannot find module '/var/run/act/actions/xt0rted-stylelint-problem-matcher@v1/dist/index.js'
|     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
|     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
|     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
|     at node:internal/main/run_main_module:22:47 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
[Lint Code Base/Lint Code Base]   ❌  Failure - Main Set-up Stylelint Problem Matcher
[Lint Code Base/Lint Code Base] exitcode '1': failure
```
```


### Additional information

_No response_
