### ISSUE TITLE
Seemingly invalid path separator on Windows using actions/setup-node

### ISSUE THREAD

**Issue by Swiftwork** [nektos/act#145]
Running command
```powershell
act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04
```
on `Microsoft Windows 10 Pro Build 10.0.18363` using `release v0.2.6`
```yaml
- name: Set up Node.js version 13.x
  uses: actions/setup-node@v1
  with:
    node-version: 13.x
```
results in

```powershell
[Continuous Delivery/Node 13.x]   �🐳  docker cp src=act/actions-setup-node@v1 dst=/actions\
| internal/modules/cjs/loader.js:985
|   throw err;
|   ^
|
| Error: Cannot find module '/github/workspace/\actions\actions-setup-node@v1\dist\index.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
|     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
|     at internal/main/run_main_module.js:18:47 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
[Continuous Delivery/Node 13.x]   ❌  Failure - Set up Node.js version 13.x
Error: exit with `FAILURE`: 1
```
This seems to be an issue with Windows and POSIX not using the same path separators. However I don't know where this issue lies, if its with [nektos/act](https://github.com/nektos/act) or [actions/setup-node](https://github.com/actions/setup-node). If you can't reproduce the issue it occurs currently with [trutoo/event-bus](https://github.com/trutoo/event-bus). It does however work in in my WSL.

**Comment by cplee** [comment]
This looks like a bug with `act`.  In an effort to support windows, i overdid the use of `filepath.Join()` and `filepath.Separator`.  These create paths that are windows specific and are then fed in to the linux container 🤦‍♂️

All the places that use those need to be reviewed to determine if the path is used on the host or within the container.  The ones in the container should all use `/` explicitly.

**Comment by aslafy-z** [comment]
This behavior has to be specific to Linux containers. In windows containers, path separator has to match the windows path separator (`\`). I've seen that windows runners aren't supported in act from now so it may not be a priority but it guess it can be implemented in a adaptable way for the future.

**Comment by ArwynFr** [comment]
Workspace volume mount is impacted as well.
Instead of creating a hierarchic directory, all files are flattened in the same directory :

```
[integration/build]   �🐳  docker run image=arwynfr/armake2:alpine entrypoint=["ls"] cmd=["-l" "/github/workspace/"]
| total 1932
| -rw-rw-rw-    1 root     root          1082 Mar 23 22:12 LICENSE
| drwxr-xr-x    2 root     root          4096 Apr  4 02:50 \github\workspace
| -rw-rw-rw-    1 root     root          1403 Mar 23 22:49 addons\gsri_opex\CfgNotifications.hpp
| -rw-rw-rw-    1 root     root          8320 Apr  4 02:44 addons\gsri_opex\Stringtable.xml
| -rw-rw-rw-    1 root     root          2610 Apr  4 02:44 addons\gsri_opex\config.cpp
| -rw-rw-rw-    1 root     root           633 Mar 23 22:12 addons\gsri_opex\functions\bays\fn_bayReplace.sqf
...
`

**Comment by Pomax** [comment]
I'm running into this today, Windows 10 x64 with Latest Docker, github action running against ubuntu-latest:
```
  node:
    name: Installing Node 12 and required project packages
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Installing dependencies
        run: npm install
```
Result:
```
[CI-CD/Installing Node 12 and required project packages    ]   �🐳  docker cp src=act/actions-setup-node@v1 dst=/actions\
| internal/modules/cjs/loader.js:628
|     throw err;
|     ^
|
| Error: Cannot find module '/github/workspace/\actions\actions-setup-node@v1\dist\index.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
[CI-CD/Installing Node 12 and required project packages    ]   ❌  Failure - actions/setup-node@v1
Error: exit with `FAILURE`: 1
```
