### ISSUE TITLE
GITHUB_STATE and save-state command ignored in pre step

### ISSUE THREAD

**Issue by ChristopherHX** [nektos/act#1459]
### Bug report info

```plain text
N/A
```

### Command used with act

```sh
./act -P self-hosted=-self-hosted -W /home/christopher/github-actions/host_environment/pkg/runner/testdata/failing-pre-step-logging/push.yml | grep STATE_
```

### Describe issue

The state is of a pre steps is lost in the void. Using it in the main stage works as expected.
Only mystate2 and mystate3 are set as env varables, mystate and mystate0 are lost.

### Workflow content

```yml
on: push
jobs:
  _:
    runs-on: self-hosted
    steps:
    - uses: christopherhx/script@main
      with:
        pre: |
          env
          echo mystate=mystateval > $GITHUB_STATE
          echo "::save-state name=mystate0::mystateval"
        main: |
          env
          echo mystate2=mystateval > $GITHUB_STATE
          echo "::save-state name=mystate3::mystateval"
        post: |
          env
```

### Relevant log output

```sh
[push.yml/_]   | STATE_mystate2=mystateval
[push.yml/_]   | STATE_mystate3=mystateval
```
