### ISSUE TITLE
Executing on Mac Ventura is causing a crash

### ISSUE THREAD

**Issue by igorcosta** [nektos/act#1484]
### Bug report info

```plain text
% act --bug-report        
act version:            0.2.33
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 16
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
	/Users/igorcosta/.docker/run/docker.sock
Config files:           
	/Users/igorcosta/.actrc:
		-P ubuntu-latest=node:16-buster-slim
		-P -P ubuntu-22.04=node:16-bullseye-slim
		ubuntu-20.04=node:16-buster-slim
		-P ubuntu-18.04=node:16-buster-slim
Build info:
	Go version:            go1.19.3
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -X main.version=0.2.33
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
Docker Engine:
	Engine version:        20.10.12
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             5.10.76-linuxkit
	OS CPU:                8
	OS memory:             1984 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
act
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14d383d]

goroutine 1 [running]:
github.com/nektos/act/pkg/model.(*Workflow).GetJob(...)
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/pkg/model/workflow.go:539
github.com/nektos/act/pkg/model.createStages(0xc0001e85a0, {0xc000450780, 0x1, 0xc0002df9f0?})
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/pkg/model/planner.go:293 +0x7fd
github.com/nektos/act/pkg/model.(*workflowPlanner).PlanAll(0xc000435050)
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/pkg/model/planner.go:209 +0xac
github.com/nektos/act/cmd.newRunCommand.func1(0xc00043c000, {0xc0000c2600, 0x0, 0x6?})
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/cmd/root.go:352 +0x5b9
github.com/spf13/cobra.(*Command).execute(0xc00043c000, {0xc0000c25a0, 0x6, 0x6})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00043c000)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/nektos/act/cmd.Execute({0x1947c40, 0xc0003790c0}, {0x193def0, 0x6})
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/cmd/root.go:85 +0xd9f
main.main()
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/main.go:34 +0x1a7
```

### Describe issue

Following the tutorial to install act and run it for the first time, I get these errors.

Not sure if it's the solution or my machine with missing dependencies.run

### Workflow content

```yml
name: Weekly Updates
on:
  schedule:
  - cron: "0 0 * * 5"
  workflow_dispatch:
jobs:
  random-host-issue:
    name: random-host
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: | 
        chmod +x  .github/workflows/scripts/hostpicker.sh
        ./.github/workflows/scripts/hostpicker.sh
        
      shell: bash
    - uses: lowply/issue-from-template@v0.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IFT_TEMPLATE_NAME: temp-weekly-meeting.md
        ADD_DATES: 7
  close:
    name: Close old issues
    runs-on: ubuntu-latest
    steps:
    - uses: lowply/auto-closer@v0.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AC_LABEL: team-meeting
```

### Relevant log output

```sh
DEBU[0000] Reading workflow '/my-apac/.github/workflows/workflow.yml' 
DEBU[0000] Preparing plan with all jobs                 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14d383d]

goroutine 1 [running]:
github.com/nektos/act/pkg/model.(*Workflow).GetJob(...)
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/pkg/model/workflow.go:539
github.com/nektos/act/pkg/model.createStages(0xc0001e65a0, {0xc00045c940, 0x1, 0x29d66308?})
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/pkg/model/planner.go:293 +0x7fd
github.com/nektos/act/pkg/model.(*workflowPlanner).PlanAll(0xc00043f0e0)
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/pkg/model/planner.go:209 +0xac
github.com/nektos/act/cmd.newRunCommand.func1(0xc000446000, {0xc000444460, 0x0, 0xc?})
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/cmd/root.go:352 +0x5b9
github.com/spf13/cobra.(*Command).execute(0xc000446000, {0xc0001e2240, 0x7, 0xc})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000446000)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/nektos/act/cmd.Execute({0x1947c40, 0xc000385100}, {0x193def0, 0x6})
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/cmd/root.go:85 +0xd9f
main.main()
	/private/tmp/act-20221117-4737-1tjuxed/act-0.2.33/main.go:34 +0x1a7
```

### Additional information

No extras required.are
