### ISSUE TITLE
How to ignore GitHub Page

### ISSUE THREAD

**Issue by MathieuSoysal** [nektos/act#1490]
## Introduction

I'm currently contributing to a GitHub project.  
For this, I'm writing a GitHub workflow inside a GitHub Action that tests the creation of JavaDoc files.   
This workflow should be run with [act][1].   
The project of the GitHub Action when I want to add this GitHub Workflow: https://github.com/MathieuSoysal/Javadoc-publisher.yml

## Problem
The problem, when I execute my GitHub workflow with act I obtain this error.

```log
[Test Actions/Test with Java 17]   ✅  Success - Main Generate Javadoc
[Test Actions/Test with Java 17]   ☁  git clone 'https://github.com/JamesIves/github-pages-deploy-action' # ref=v4.4.0
[Test Actions/Test with Java 17] ⭐ Run Main Deploy 🚀
[Test Actions/Test with Java 17]   🐳  docker cp src=/home/codespace/.cache/act/JamesIves-github-pages-deploy-action@v4.4.0/ dst=/var/run/act/actions/JamesIves-github-pages-deploy-action@v4.4.0/
[Test Actions/Test with Java 17]   🐳  docker exec cmd=[node /var/run/act/actions/JamesIves-github-pages-deploy-action@v4.4.0/lib/main.js] user= workdir=
| 
|     ╭━━━╮╭╮╭╮╱╭╮╱╱╭╮╱╱╭━━━╮
|     ┃╭━╮┣╯╰┫┃╱┃┃╱╱┃┃╱╱┃╭━╮┃
|     ┃┃╱╰╋╮╭┫╰━╯┣╮╭┫╰━╮┃╰━╯┣━━┳━━┳━━┳━━╮
|     ┃┃╭━╋┫┃┃╭━╮┃┃┃┃╭╮┃┃╭━━┫╭╮┃╭╮┃┃━┫━━┫
|     ┃╰┻━┃┃╰┫┃╱┃┃╰╯┃╰╯┃┃┃╱╱┃╭╮┃╰╯┃┃━╋━━┃
|     ╰━━━┻┻━┻╯╱╰┻━━┻━━╯╰╯╱╱╰╯╰┻━╮┣━━┻━━╯
|     ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭━╯┃
|     ╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╰━━╯
|     ╭━━━╮╱╱╱╱╱╭╮╱╱╱╱╱╱╱╱╭━━━╮╱╱╭╮
|     ╰╮╭╮┃╱╱╱╱╱┃┃╱╱╱╱╱╱╱╱┃╭━╮┃╱╭╯╰╮
|     ╱┃┃┃┣━━┳━━┫┃╭━━┳╮╱╭╮┃┃╱┃┣━┻╮╭╋┳━━┳━╮
|     ╱┃┃┃┃┃━┫╭╮┃┃┃╭╮┃┃╱┃┃┃╰━╯┃╭━┫┃┣┫╭╮┃╭╮╮
|     ╭╯╰╯┃┃━┫╰╯┃╰┫╰╯┃╰━╯┃┃╭━╮┃╰━┫╰┫┃╰╯┃┃┃┃
|     ╰━━━┻━━┫╭━┻━┻━━┻━╮╭╯╰╯╱╰┻━━┻━┻┻━━┻╯╰╯
|     ╱╱╱╱╱╱╱┃┃╱╱╱╱╱╱╭━╯┃
|     ╱╱╱╱╱╱╱╰╯╱╱╱╱╱╱╰━━╯
|     
| 
|     💖 Support: https://github.com/sponsors/JamesIves
|     📣 Maintained by James Ives: https://jamesiv.es
| 
|     🚀 Getting Started Guide: https://github.com/JamesIves/github-pages-deploy-action
|     ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
|     🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues
| Checking configuration and starting deployment… 🚦
| Deploying using …… 🔑
| Configuring git…
| [command]/usr/bin/git config --global --add safe.directory /workspaces/Javadoc-publisher.yml
| [command]/usr/bin/git config user.name nektos/act
| [command]/usr/bin/git config user.email nektos/act@users.noreply.github.com
| [command]/usr/bin/git config core.ignorecase false
| [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
| Unable to unset previous git config authentication as it may not exist, continuing…
| [command]/usr/bin/git remote rm origin
| [command]/usr/bin/git remote add origin https://x-access-token:@github.com/MathieuSoysal/Javadoc-publisher.yml.git
| Git configured… 🔧
| Starting to commit changes…
| [command]/usr/bin/git ls-remote --heads https://x-access-token:@github.com/MathieuSoysal/Javadoc-publisher.yml.git refs/heads/javadoc-test
| warning: redirecting to https://github.com/MathieuSoysal/Javadoc-publisher.yml.git/
| Creating worktree…
| [command]/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
| Preparing worktree (detached HEAD 98bc0a0)
| [command]/usr/bin/git checkout --orphan javadoc-test
| Switched to a new branch 'javadoc-test'
| Created the javadoc-test branch… 🔧
| [command]/usr/bin/git reset --hard
| [command]/usr/bin/git commit --no-verify --allow-empty -m Initial javadoc-test commit
| error: gpg failed to sign the data
| fatal: failed to write commit object
| Running post deployment cleanup jobs… 🗑️
| [command]/usr/bin/git checkout -B github-pages-deploy-action/qfnux4snr
| Switched to a new branch 'github-pages-deploy-action/qfnux4snr'
| [command]/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
| [command]/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
[Test Actions/Test with Java 17]   ❗  ::error::The deploy step encountered an error: There was an error creating the worktree: The process '/usr/bin/git' failed with exit code 128 ❌ ❌
[Test Actions/Test with Java 17]   ❓  ::notice::Deployment failed! ❌
| 
[Test Actions/Test with Java 17]   ⚙  ::set-output:: deployment-status=failed
[Test Actions/Test with Java 17]   ❌  Failure - Main Deploy 🚀
[Test Actions/Test with Java 17] exitcode '1': failure
[Test Actions/Test with Java 17]   ❌  Failure - Main ./
[Test Actions/Test with Java 17] exitcode '1': failure
[Test Actions/Test with Java 17] ⭐ Run Post ./
[Test Actions/Test with Java 17] ⭐ Run Post actions/setup-java@v3
[Test Actions/Test with Java 17]   🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-java@v3/dist/cleanup/index.js] user= workdir=
[Test Actions/Test with Java 17]   ✅  Success - Post actions/setup-java@v3
[Test Actions/Test with Java 17]   ✅  Success - Post ./
[Test Actions/Test with Java 17] 🏁  Job failed
```
**GitHub Workflow**

My GitHub Workflow :

```yml
name: Test Actions

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    
    name: Test with Java ${{ matrix.java }}
    steps:
#### This step is only needed for GHA local runner, act:
# https://github.com/nektos/act
      - name: Install curl (for nektos/act local CI testing)
        run: apt-get update && apt-get install build-essential curl pkg-config openssl -y
      - name: Download Maven
        run: |
          curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip -o maven.zip
          apt-get update
          apt-get -y install unzip
          unzip -d /usr/share maven.zip
          rm maven.zip
          ln -s /usr/share/apache-maven-3.6.3/bin/mvn /usr/bin/mvn
          echo "M2_HOME=/usr/share/apache-maven-3.6.3" | tee -a /etc/environment
####
    
      - uses: actions/checkout@v3
      - uses: ./ # Uses an action in the root directory
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc-test
          java-version: ${{ matrix.java }}
          target-folder: javadoc

      - uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: ls -lha
          contains: javadoc
          expected_result: PASSED
```

**GitHub Action**

The GitHub Action of the project: https://github.com/MathieuSoysal/Javadoc-publisher.yml/blob/main/action.yml

**Command**

The executed command to run nektos/act : `act`

## Question

Does someone know how we can say to [nektos/act][1] to ignore the deployment phase? It is possible?

  [1]: https://github.com/nektos/act
