### ISSUE TITLE
invalid filter 'reference'

### ISSUE THREAD

**Issue by pindab0ter** [nektos/act#1499]
### Bug report info

```plain text
act version:            0.2.34
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
	/Users/hans/.docker/run/docker.sock
Config files:           
	/Users/hans/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.19.3
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -X main.version=0.2.34
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               arm64
		GOOS:                 darwin
Docker Engine:
	Engine version:        22.06.0-beta.0-407-g7a5cce156e.m
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        stargz
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               aarch64
	OS kernel:             5.15.49-linuxkit
	OS CPU:                5
	OS memory:             7951 MB
	Security options:
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
act
act --container-architecture linux/amd64 // To silence Apple M1 warning. No difference otherwise
```

### Describe issue

I’m only getting this output:

```
[Run tests/php-tests] 🚀  Start image=catthehacker/ubuntu:act-latest
[Run tests/php-tests]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform=linux/amd64 username= forcePull=false
Error: unable to determine if image already exists for image 'catthehacker/ubuntu:act-latest' (linux/amd64): Error response from daemon: invalid filter 'reference'
```

Docker is running (`Docker version 20.10.21, build baeda1f`), I've tried pruning both images and volumes.

I've removed `~/.actrc` and tried `brew uninstall --zap act && brew install act`. I'm still getting the same output.

### Workflow content

```yml
name: Run tests

on: [push, pull_request]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: keurslager_de_haas_intranet_test
          MARIADB_USER: root
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "$(composer config cache-files-dir) >> $COMPOSER_CACHE_DIR"

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ${COMPOSER_CACHE_DIR}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - uses: actions/cache@v3
      with:
        path: ${COMPOSER_CACHE_DIR}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Setup PHP and install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: 8.1
        php_extensions: intl bcmath

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - name: Install Node dependencies
      run: npm install && npm run production

    - name: Generate application key
      run: cp .env.example .env && php artisan key:generate

    - name: Run test suite
      run: vendor/bin/pest
```

### Relevant log output

```sh
WARN  ⚠ You are using Apple M1 chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠
DEBU[0000] Loading environment from /Users/hans/Developer/intranet.keurslagerdehaas.nl/.env
DEBU[0000] Loading secrets from /Users/hans/Developer/intranet.keurslagerdehaas.nl/.secrets
DEBU[0000] Loading workflows from '/Users/hans/Developer/intranet.keurslagerdehaas.nl/.github/workflows'
DEBU[0000] Loading workflows recursively
DEBU[0000] Found workflow 'tests.yml' in '/Users/hans/Developer/intranet.keurslagerdehaas.nl/.github/workflows/tests.yml'
DEBU[0000] Reading workflow '/Users/hans/Developer/intranet.keurslagerdehaas.nl/.github/workflows/tests.yml'
DEBU[0000] Preparing plan with all jobs
DEBU[0000] Using default workflow event: push
DEBU[0000] Planning jobs for event: push
DEBU[0000] Loading slug from git directory '/Users/hans/Developer/intranet.keurslagerdehaas.nl/.git'
DEBU[0000] Loading revision from git directory '/Users/hans/Developer/intranet.keurslagerdehaas.nl/.git'
DEBU[0000] Found revision: 762876870a85c466452b2a204ff86816b15976e6
DEBU[0000] HEAD points to '762876870a85c466452b2a204ff86816b15976e6'
DEBU[0000] using github ref: refs/heads/feature/github-actions
DEBU[0000] Found revision: 762876870a85c466452b2a204ff86816b15976e6
[Run tests/php-tests] [DEBUG] evaluating expression 'success()'
[Run tests/php-tests] [DEBUG] expression 'success()' evaluated to 'true'
[Run tests/php-tests] 🚀  Start image=catthehacker/ubuntu:act-latest
[Run tests/php-tests]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=false
[Run tests/php-tests] [DEBUG]   🐳  docker pull catthehacker/ubuntu:act-latest
[Run tests/php-tests] [DEBUG] Image exists? false
Error: unable to determine if image already exists for image 'catthehacker/ubuntu:act-latest' (): Error response from daemon: invalid filter 'reference'
```

### Additional information

I chose not to share workflow content
