### ISSUE TITLE
actions/checkout@v3 not working with ghcr.io/catthehacker/ubuntu:full-latest

### ISSUE THREAD

**Issue by codebydant** [nektos/act#1508]
### Bug report info
Hi folks,

Greetings.

I think there is an issue using the latest checkout version v3 with the image:

```bash
ghcr.io/catthehacker/ubuntu:full-latest
```

### Command used with act

```sh
act push --workflows ./.github/workflows/version.yaml
```

`.actrc`
```bash
-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:full-latest
```

### Describe issue

It seems when running the latest checkout action v3, the pipeline fails with an error. After I set the checkout version from v3 to v2, then it works as expected.

### Workflow content

```yaml
# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - release

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history
```

### Relevant log output
`actions/checkout@v3`
```bash
daniel at ~/Downloads/test-github-action on git:release* ✗
➜ act_steps_debug push --workflows ./.github/workflows/version.yaml
[Git Version/version]   ☁  git clone 'https://github.com/actions/checkout' # ref=v3
[Git Version/version] Unable to resolve v3: unsupported object type
[Git Version/version] Unable to resolve v3: unsupported object type
[Git Version/version] 🏁  Job succeeded
INFO[0000] Cleaning up container for job version        
Error: unsupported object type
```

`actions/checkout@v2`
```bash
➜ act push --workflows ./.github/workflows/version.yaml
[Git Version/version]   ☁  git clone 'https://github.com/actions/checkout' # ref=v2
[Git Version/version]   ☁  git clone 'https://github.com/codacy/git-version' # ref=2.8.0
[Git Version/version] ⭐ Run Post Checkout Code
[Git Version/version]   ✅  Success - Post Checkout Code
INFO[0032] Cleaning up container for job version        
```
