### ISSUE TITLE
Could not load X509 key pair

### ISSUE THREAD

**Issue by emirdeliz** [nektos/act#1583]
### Bug report info

```plain text
Default image and other options can be changed manually in ~/.actrc (please refer to https://github.com/nektos/act#configuration for additional information about file structure) Large
ERRO[0015] failed to obtain container engine info: failed to connect to docker daemon: Could not load X509 key pair: open /usr/local/bin/docker/cert.pem: not a directory 
[Linux 64/test] 🚀  Start image=node:16-buster-slim
[Linux 64/test]   🐳  docker pull image=node:16-buster-slim platform=linux/amd64 username= forcePull=false
Error: unable to determine if image already exists for image 'node:16-buster-slim' (linux/amd64): failed to connect to docker daemon: Could not load X509 key pair: open /usr/local/bin/docker/cert.pem: not a directory
CONDO-090 Github7/emirdeliz-chromedriver ‹main*› »
```

### Command used with act

```sh
act --container-architecture linux/amd64
```

### Describe issue

When running the command act `--container-architecture linux/amd64 ` I get the error message.

I tried to remove all content from docker and make the uninstall. But didn't work.

What can be the problem?

### Workflow content

```yml
name: Linux 64
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
```

### Relevant log output

```sh
ERRO[0015] failed to obtain container engine info: failed to connect to docker daemon: Could not load X509 key pair: open /usr/local/bin/docker/cert.pem: not a directory
```
