### ISSUE TITLE
Unable to locate executable file: yarn

### ISSUE THREAD

**Issue by euan-cowie** [nektos/act#1584]
### Bug report info

```plain text
act version:            0.2.40
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
        /Users/euan-cowie/.docker/run/docker.sock
Config files:           
        /Users/euan-cowie/.actrc:
                -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest
                -P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.19.5
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -compiler:            gc
                -ldflags:             -X main.version=0.2.40
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        20.10.22
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.15.49-linuxkit
        OS CPU:                5
        OS memory:             15987 MB
        Security options:
                name=seccomp,profile=default
                name=cgroupns
```

### Command used with act

```sh
act -W ./.github/workflows/test-cypress.yml -j cypress-run --container-architecture linux/amd64
```

### Describe issue

I am just trying to build the project before running the cypress tests but I cannot get to that point locally using act as it fails to find yarn? I have tested it on the github action runners, where it works. I can't find any documentation to say this would be expected locally. 

### Workflow content

```yml
name: Test Cypress

on:
  push:
    branches: [test-cypress]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5
        with:
          build: yarn run build
          start: yarn start
```

### Relevant log output

```sh
[Staging Build/cypress-run]   💬  ::debug::Checking zstd --version
[Staging Build/cypress-run]   💬  ::debug::*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***
[Staging Build/cypress-run]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Staging Build/cypress-run]   💬  ::debug::*** zstd command line interface 64-bits v1.4.8, by Yann Collet ***
[Staging Build/cypress-run]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Staging Build/cypress-run]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Staging Build/cypress-run]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
| Restoring NPM cache error: getCacheEntry failed: Cache Service Url not found, unable to restore cache.
| Restoring Cypress cache error: getCacheEntry failed: Cache Service Url not found, unable to restore cache.
[Staging Build/cypress-run]   ❗  ::error::Unable to locate executable file: yarn. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
[Staging Build/cypress-run]   ❌  Failure - Main Cypress run
[Staging Build/cypress-run] exitcode '1': failure
```

### Additional information

It should be noted that the same error occurs regardless of doing either:
```yml
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5
        with:
          build: yarn run build
          start: yarn start
```
or 
```yml
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5
        with:
          build: npm build
          start: npm start
```
