### ISSUE TITLE
Unable to install Node

### ISSUE THREAD

**Issue by odedpeer** [nektos/act#159]
STR:
Run act on the following actions
```
name: CI
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com
```

Fails with:
```
[CI/ci] Extracting content from '/var/folders/08/yzwsnxm9337brggy65fnf5ph0000gp/T/act952952145' to '/actions/'
[CI/ci] Exec command '[node /actions/actions-setup-node@v1/dist/index.js]'
[CI/ci]   💬  ::debug::isExplicit:
[CI/ci]   💬  ::debug::explicit? false
[CI/ci]   💬  ::debug::evaluating 0 versions
[CI/ci]   💬  ::debug::match not found
[CI/ci]   💬  ::debug::evaluating 381 versions
[CI/ci]   💬  ::debug::matched: v12.16.1
[CI/ci]   💬  ::debug::isExplicit: 12.16.1
[CI/ci]   💬  ::debug::explicit? true
[CI/ci]   💬  ::debug::checking cache: /opt/hostedtoolcache/node/12.16.1/x64
[CI/ci]   💬  ::debug::not found
[CI/ci]   ❗  ::error::Expected RUNNER_TEMP to be defined
[CI/ci]   ❌  Failure - Install Node.js
DEBU[0017] exit with `FAILURE`: 1
```

**Comment by reinismu** [comment]
This is what I did (added env `RUNNER_TEMP`)
```
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
        env:
          RUNNER_TEMP: "/tmp/"
```
