### ISSUE TITLE
Error response from daemon: No such container

### ISSUE THREAD

**Issue by abhishekrai-nyk** [nektos/act#1598]
### Bug report info

```plain text
act version:            0.2.41
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
        /Users/abhishek.rai/.docker/run/docker.sock
Config files:           
        /Users/abhishek.rai/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.18.10
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:         
        Build settings:
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.41 -X main.commit=b91e4b0d5576ee0efeb381c9427b791e5272ece9 -X main.date=2023-02-01T02:33:10Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               arm64
                GOOS:                 darwin
                vcs:                  git
                vcs.revision:         b91e4b0d5576ee0efeb381c9427b791e5272ece9
                vcs.time:             2023-02-01T02:32:39Z
                vcs.modified:         false
Docker Engine:
        Engine version:        20.10.17
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.10.124-linuxkit
        OS CPU:                4
        OS memory:             7851 MB
        Security options:
                name=seccomp,profile=default
                name=cgroupns
```

### Command used with act

```sh
act -j build -P ubuntu-latest=-self-hosted
```

### Describe issue

It looks like act created the container with a different name and tried to to use a different container that what it created. 
I tried to run the act with -self-hosted option.

[actions/Lint]   ☁  git clone 'https://github.com/github/super-linter' # ref=v4
[actions/Lint] ⭐ Run Main Checkout Code
[actions/Lint]   ✅  Success - Main Checkout Code
[actions/Lint] ⭐ Run Main Lint Code Base
[actions/Lint]   🐳  docker pull image=ghcr.io/github/super-linter:slim-v4.10.0 platform= username= forcePull=false
[actions/Lint]   🐳  docker create image=ghcr.io/github/super-linter:slim-v4.10.0 platform= entrypoint=[] cmd=[]
[actions/Lint]   🐳  docker run image=ghcr.io/github/super-linter:slim-v4.10.0 platform= entrypoint=[] cmd=[]
[actions/Lint]   ❌  Failure - Main Lint Code Base
[actions/Lint] failed to start container: Error response from daemon: No such container: act-actions-Lint
[actions/Lint] 🏁  Job failed
Error: Job 'Lint' failed

It says "No such container: act-actions-Lint" but when I tried to run it with -v option it gave out more details and it looks like it tried to create a different container.

[DEBUG] Created container name=act-actions-Li-1 id=1090905f0a99fb4a27e37ba88eee3d8cde382fc5044525e71c43e41b6c87b323 from image ghcr.io/github/super-linter:slim-v4.10.0 (platform: )

### Workflow content

```yml
---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#
name: actions
#############################
# Start the job on all push #
#############################
on:
  pull_request:
    branches: [master, main, staging_release]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Relevant log output

```sh
Too many sensitive variables so skipped. Provide the relevant line in description itself.
```
