### ISSUE TITLE
Unable to clone setup-java

### ISSUE THREAD

**Issue by Andromelus** [nektos/act#1632]
### Bug report info

```plain text
act --bug-report
act version:            0.2.42
GOOS:                   windows
GOARCH:                 amd64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        \\.\pipe\docker_engine
Config files:
        C:\Users\castelain.florianext\.actrc:
                -P ubuntu-latest=node:16-buster-slim
                -P ubuntu-22.04=node:16-bullseye-slim
                -P ubuntu-20.04=node:16-buster-slim
                -P ubuntu-18.04=node:16-buster-slim
Build info:
        Go version:            go1.18.10
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.42 -X main.commit=72d03214c5ed8985bf23dc15440fa5301e9d13bf -X main.date=2023-02-02T00:57:22Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 windows
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         72d03214c5ed8985bf23dc15440fa5301e9d13bf
                vcs.time:             2023-02-02T00:56:57Z
                vcs.modified:         false
Docker Engine:
        Engine version:        20.10.8
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.10.47-linuxkit
        OS CPU:                4
        OS memory:             1985 MB
        Security options:
                name=seccomp,profile=default
```

### Command used with act

```sh
act -v
```

### Describe issue

Watning to debug a workflow, I tried this tool.

Using the windows release ([act_Windows_x86_64.zip, v0.2.42](https://github.com/nektos/act/releases/download/v0.2.42/act_Windows_x86_64.zip )), I just launched act.

It seems to not be able to clone some actions repo.

```
[CI/Test] [DEBUG]   cloning https://github.com/actions/setup-java to C:\Users\castelain.florianext\.cache\act/actions-setup-java@v2
[CI/Test] Unable to clone https://github.com/actions/setup-java refs/heads/v2: Get "https://github.com/actions/setup-java/info/refs?service=git-upload-pack": dial tcp: lookup github.com: no such host
```

However, I can clone manually:

```
git clone https://github.com/actions/setup-java
Cloning into 'setup-java'...
remote: Enumerating objects: 2609, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 2609 (delta 12), reused 23 (delta 10), pack-reused 2578
Receiving objects: 100% (2609/2609), 11.03 MiB | 4.94 MiB/s, done.
Resolving deltas: 100% (1386/1386), done.
Updating files: 100% (161/161), done.
```

Note that I am being a corporate proxy, if that matters.

### Link to GitHub repository

https://github.com/Andromelus/hdfs

### Workflow content

```yml
name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Download Hadoop
        run: |
          echo "HADOOP_HOME=$(./scripts/hadoop.sh download)" >>"$GITHUB_ENV"
      - name: Configure Hadoop
        run: |
          echo "HADOOP_CONF_DIR=$(./scripts/hadoop.sh config)" >>"$GITHUB_ENV"
      - name: Start HDFS
        run: |
          ./scripts/hadoop.sh start
          echo "WEBHDFS_URL=http://$("$HADOOP_HOME/bin/hdfs" getconf -confKey dfs.namenode.http-address)" >>"$GITHUB_ENV"
          echo "HTTPFS_URL=http://localhost:14000" >>"$GITHUB_ENV"
          sleep 5 # TODO: Find a better way to wait for all datanodes to become reachable.
      - name: Install
        run: pip install .[avro] coverage mock nose
      - name: Test on WebHDFS
        run: HDFSCLI_TEST_URL="$WEBHDFS_URL" python -m nose --with-coverage --cover-package=hdfs
      - name: Test on HTTPFS
        run: HDFSCLI_TEST_URL="$HTTPFS_URL" HDFSCLI_NOSNAPSHOT=1 python -m nose --with-coverage --cover-package=hdfs
      - name: Stop HDFS
        if: always()
        run: ./scripts/hadoop.sh stop
```

### Relevant log output

```sh
time="2023-02-17T14:43:53+01:00" level=debug msg="Loading environment from C:\\Users\\castelain.florianext\\Documents\\personnel-florianc\\hdfs\\.env"
time="2023-02-17T14:43:53+01:00" level=debug msg="Unable to load etag from C:\\Users\\castelain.florianext\\.cache\\act\\.notices.etag: &{%!e(string=open) %!e(string=C:\\Users\\castelain.florianext\\.cache\\act\\.notices.etag) %!e(syscall.Errno=2)}"
time="2023-02-17T14:43:53+01:00" level=debug msg="Loading action inputs from C:\\Users\\castelain.florianext\\Documents\\personnel-florianc\\hdfs\\.input"
time="2023-02-17T14:43:53+01:00" level=debug msg="Loading secrets from C:\\Users\\castelain.florianext\\Documents\\personnel-florianc\\hdfs\\.secrets"
time="2023-02-17T14:43:53+01:00" level=debug msg="Loading workflows from 'C:\\Users\\castelain.florianext\\Documents\\personnel-florianc\\hdfs\\.github\\workflows'"
time="2023-02-17T14:43:53+01:00" level=debug msg="Loading workflows recursively"
time="2023-02-17T14:43:53+01:00" level=debug msg="Found workflow 'ci.yml' in 'C:\\Users\\castelain.florianext\\Documents\\personnel-florianc\\hdfs\\.github\\workflows\\ci.yml'"
time="2023-02-17T14:43:53+01:00" level=debug msg="Reading workflow 'C:\\Users\\castelain.florianext\\Documents\\personnel-florianc\\hdfs\\.github\\workflows\\ci.yml'"
time="2023-02-17T14:43:53+01:00" level=debug msg="Preparing plan with all jobs"
time="2023-02-17T14:43:53+01:00" level=debug msg="Using default workflow event: push"
time="2023-02-17T14:43:53+01:00" level=debug msg="Planning jobs for event: push"
time="2023-02-17T14:43:53+01:00" level=debug msg="Loading revision from git directory"
time="2023-02-17T14:43:53+01:00" level=debug msg="Get \"https://api.nektosact.com/notices?arch=amd64&os=windows&version=0.2.42\": dial tcp: lookup api.nektosact.com: no such host"
time="2023-02-17T14:43:53+01:00" level=debug msg="Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099"
time="2023-02-17T14:43:53+01:00" level=debug msg="HEAD points to 'a8c7e172858e98ef6ff760f18d41a3c239e12099'"
time="2023-02-17T14:43:53+01:00" level=debug msg="using github ref: refs/heads/feature/lib-to-importlib"
time="2023-02-17T14:43:53+01:00" level=debug msg="Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099"
[CI/Test] [DEBUG] evaluating expression 'success()'
[CI/Test] [DEBUG] expression 'success()' evaluated to 'true'
[CI/Test] 🚀  Start image=node:16-buster-slim
[CI/Test]   🐳  docker pull image=node:16-buster-slim platform= username= forcePull=true
[CI/Test] [DEBUG]   🐳  docker pull node:16-buster-slim
[CI/Test] [DEBUG] pulling image 'docker.io/library/node:16-buster-slim' ()
[CI/Test] [DEBUG] Pulling from library/node :: 16-buster-slim
[CI/Test] [DEBUG] Digest: sha256:64d4a68b4cc901226c80df0cd5c9b746a09c1bf33a3c4d070a4a06ca78718814 ::
[CI/Test] [DEBUG] Status: Image is up to date for node:16-buster-slim ::
[CI/Test]   🐳  docker create image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[CI/Test] [DEBUG] Common container.Config ==> &{Hostname: Domainname: User: AttachStdin:false AttachStdout:false AttachStderr:false ExposedPorts:map[] Tty:true OpenStdin:false StdinOnce:false Env:[RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_ARCH=X64 RUNNER_TEMP=/tmp LANG=C.UTF-8] Cmd:[] Healthcheck:<nil> ArgsEscaped:false Image:node:16-buster-slim Volumes:map[] WorkingDir:/mnt/c/Users/castelain.florianext/Documents/personnel-florianc/hdfs Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal: StopTimeout:<nil> Shell:[]}
[CI/Test] [DEBUG] Common container.HostConfig ==> &{Binds:[/var/run/docker.sock:/var/run/docker.sock] ContainerIDFile: LogConfig:{Type: Config:map[]} NetworkMode:host PortBindings:map[] RestartPolicy:{Name: MaximumRetryCount:0} AutoRemove:false VolumeDriver: VolumesFrom:[] ConsoleSize:[0 0] CapAdd:[] CapDrop:[] CgroupnsMode: DNS:[] DNSOptions:[] DNSSearch:[] ExtraHosts:[] GroupAdd:[] IpcMode: Cgroup: Links:[] OomScoreAdj:0 PidMode: Privileged:false PublishAllPorts:false ReadonlyRootfs:false SecurityOpt:[] StorageOpt:map[] Tmpfs:map[] UTSMode: UsernsMode: ShmSize:0 Sysctls:map[] Runtime: Isolation: Resources:{CPUShares:0 Memory:0 NanoCPUs:0 CgroupParent: BlkioWeight:0 BlkioWeightDevice:[] BlkioDeviceReadBps:[] BlkioDeviceWriteBps:[] BlkioDeviceReadIOps:[] BlkioDeviceWriteIOps:[] CPUPeriod:0 CPUQuota:0 CPURealtimePeriod:0 CPURealtimeRuntime:0 CpusetCpus: CpusetMems: Devices:[] DeviceCgroupRules:[] DeviceRequests:[] KernelMemory:0 KernelMemoryTCP:0 MemoryReservation:0 MemorySwap:0 MemorySwappiness:<nil> OomKillDisable:<nil> PidsLimit:<nil> Ulimits:[] CPUCount:0 CPUPercent:0 IOMaximumIOps:0 IOMaximumBandwidth:0} Mounts:[{Type:volume Source:act-toolcache Target:/toolcache ReadOnly:false Consistency: BindOptions:<nil> VolumeOptions:<nil> TmpfsOptions:<nil> ClusterOptions:<nil>} {Type:volume Source:act-CI-Test-env Target:/var/run/act ReadOnly:false Consistency: BindOptions:<nil> VolumeOptions:<nil> TmpfsOptions:<nil> ClusterOptions:<nil>} {Type:volume Source:act-CI-Test Target:/mnt/c/Users/castelain.florianext/Documents/personnel-florianc/hdfs ReadOnly:false Consistency: BindOptions:<nil> VolumeOptions:<nil> TmpfsOptions:<nil> ClusterOptions:<nil>}] MaskedPaths:[] ReadonlyPaths:[] Init:<nil>}
[CI/Test] [DEBUG] Created container name=act-CI-Test id=2a8af8d3f017cda0d3db1db6f1610c42c5513911c8fa9b7b36598c6f353c9854 from image node:16-buster-slim (platform: )
[CI/Test] [DEBUG] ENV ==> [RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_ARCH=X64 RUNNER_TEMP=/tmp LANG=C.UTF-8]
[CI/Test]   🐳  docker run image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[CI/Test] [DEBUG] Starting container: 2a8af8d3f017cda0d3db1db6f1610c42c5513911c8fa9b7b36598c6f353c9854
[CI/Test] [DEBUG] Started container: 2a8af8d3f017cda0d3db1db6f1610c42c5513911c8fa9b7b36598c6f353c9854
[CI/Test] [DEBUG] Writing entry to tarball workflow/event.json len:2
[CI/Test] [DEBUG] Writing entry to tarball workflow/envs.txt len:0
[CI/Test] [DEBUG] Extracting content to '/var/run/act/'
[CI/Test] [DEBUG] Loading revision from git directory
[CI/Test] [DEBUG] Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099
[CI/Test] [DEBUG] HEAD points to 'a8c7e172858e98ef6ff760f18d41a3c239e12099'
[CI/Test] [DEBUG] using github ref: refs/heads/feature/lib-to-importlib
[CI/Test] [DEBUG] Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099
[CI/Test] [DEBUG] Loading revision from git directory
[CI/Test] [DEBUG] Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099
[CI/Test] [DEBUG] HEAD points to 'a8c7e172858e98ef6ff760f18d41a3c239e12099'
[CI/Test] [DEBUG] using github ref: refs/heads/feature/lib-to-importlib
[CI/Test] [DEBUG] Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099
[CI/Test] [DEBUG] Skipping local actions/checkout because workdir was already copied
[CI/Test] [DEBUG] skip pre step for 'Check out': no action model available
[CI/Test] [DEBUG] Loading revision from git directory
[CI/Test] [DEBUG] Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099
[CI/Test] [DEBUG] HEAD points to 'a8c7e172858e98ef6ff760f18d41a3c239e12099'
[CI/Test] [DEBUG] using github ref: refs/heads/feature/lib-to-importlib
[CI/Test] [DEBUG] Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099
[CI/Test]   ☁  git clone 'https://github.com/actions/setup-java' # ref=v2
[CI/Test] [DEBUG]   cloning https://github.com/actions/setup-java to C:\Users\castelain.florianext\.cache\act/actions-setup-java@v2
[CI/Test] Unable to clone https://github.com/actions/setup-java refs/heads/v2: Get "https://github.com/actions/setup-java/info/refs?service=git-upload-pack": dial tcp: lookup github.com: no such host
[CI/Test] [DEBUG] skipping post step for 'Setup Python'; step was not executed
[CI/Test] [DEBUG] skipping post step for 'Setup Java'; step was not executed
[CI/Test] [DEBUG] skipping post step for 'Check out'; step was not executed
[CI/Test] [DEBUG] Removed container: 2a8af8d3f017cda0d3db1db6f1610c42c5513911c8fa9b7b36598c6f353c9854
[CI/Test] [DEBUG]   🐳  docker volume rm act-CI-Test
[CI/Test] [DEBUG]   🐳  docker volume rm act-CI-Test-env
[CI/Test] 🏁  Job succeeded
[CI/Test] [DEBUG] Loading revision from git directory
[CI/Test] [DEBUG] Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099
[CI/Test] [DEBUG] HEAD points to 'a8c7e172858e98ef6ff760f18d41a3c239e12099'
[CI/Test] [DEBUG] using github ref: refs/heads/feature/lib-to-importlib
[CI/Test] [DEBUG] Found revision: a8c7e172858e98ef6ff760f18d41a3c239e12099
Error: Get "https://github.com/actions/setup-java/info/refs?service=git-upload-pack": dial tcp: lookup github.com: no such host
```
