### ISSUE TITLE
ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by panw3i** [nektos/act#1641]
### Bug report info

```plain text
act version:            0.2.42
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 6
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
        /Users/pan/.colima/docker.sock
        /Users/pan/.docker/run/docker.sock
Config files:           
        /Users/pan/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.19.5
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -compiler:            gc
                -ldflags:             -X main.version=0.2.42
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               amd64
                GOOS:                 darwin
                GOAMD64:              v1
Docker Engine:
        Engine version:        22.06.0-beta.0-917-gf888bd4531.m
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        stargz
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               x86_64
        OS kernel:             5.15.49-linuxkit
        OS CPU:                3
        OS memory:             7859 MB
        Security options:
                name=seccomp,profile=builtin
                name=cgroupns
```

### Command used with act

```sh
act
```

### Describe issue

Running environment is intel mac
Here is the error message during the running process:
| ENOENT: no such file or directory, open '/tmp/236772db-9239-4082-a565-dc111efc5167'
| Waiting 14 seconds before trying again
[CI/build]   💬  ::debug::download failed
| ENOENT: no such file or directory, open '/tmp/236772db-9239-4082-a565-dc111efc5167'
| Waiting 13 seconds before trying again
[CI/build]   💬  ::debug::download failed
| ENOENT: no such file or directory, open '/tmp/236772db-9239-4082-a565-dc111efc5167'
[CI/build]   💬  ::debug::Error: ENOENT: no such file or directory, open '/tmp/236772db-9239-4082-a565-dc111efc5167'
| Falling back to download directly from Node
[CI/build]   💬  ::debug::evaluating 564 versions
[CI/build]   💬  ::debug::matched: v16.19.1
| Acquiring 16.19.1 - x64 from [<https://nodejs.org/dist/v16.19.1/node-v16.19.1-linux-x64.tar.gz>](<https://nodejs.org/dist/v16.19.1/node-v16.19.1-linux-x64.tar.gz>)

### Workflow content

```yml
name: CI


on:
  push:
 
jobs:
  # This workflow contains a single job called "build"

  build:
    # The type of runner that the job will run on

    runs-on: ubuntu-latest


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: add chinese fonts
        run: |
            sudo apt-get install ttf-mscorefonts-installer
            sudo apt-get install fontconfig
            fc-list :lang=zh
            ls -lh /usr/share/fonts/
            cp -rf ./fonts/* /usr/share/fonts/
            mkfontscale
            mkfontdir
            fc-cache
            fc-list :lang=zh

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

    
      - name: Install Dependencies
        run: npm install

      # Runs a single command using the runners shell

      - name: Run script
        run: node index.js
```

### Relevant log output

```sh
| Waiting 14 seconds before trying again
[CI/build]   💬  ::debug::download failed
| ENOENT: no such file or directory, open '/tmp/236772db-9239-4082-a565-dc111efc5167'
| Waiting 13 seconds before trying again
[CI/build]   💬  ::debug::download failed
| ENOENT: no such file or directory, open '/tmp/236772db-9239-4082-a565-dc111efc5167'
[CI/build]   💬  ::debug::Error: ENOENT: no such file or directory, open '/tmp/236772db-9239-4082-a565-dc111efc5167'
| Falling back to download directly from Node
[CI/build]   💬  ::debug::evaluating 564 versions
[CI/build]   💬  ::debug::matched: v16.19.1
| Acquiring 16.19.1 - x64 from [<https://nodejs.org/dist/v16.19.1/node-v16.19.1-linux-x64.tar.gz>]
```
