### ISSUE TITLE
cannot unmarshal !!str `true if...` into bool

### ISSUE THREAD

**Issue by ccontino84** [nektos/act#1657]
### Bug report info

```plain text
act version:            0.2.43
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/contino/.actrc:
		-P self-hosted=ttim2cr.azurecr.io/gh-runner-az:v2
		-P staging-2c-8gb=ttim2cr.azurecr.io/gh-runner-az:v2
Build info:
	Go version:            go1.18.10
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.43 -X main.commit=44b510f48cac6a58654bf920ee26cc6e1d36ac3a -X main.date=2023-03-01T02:33:51Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         44b510f48cac6a58654bf920ee26cc6e1d36ac3a
		vcs.time:             2023-03-01T02:33:29Z
		vcs.modified:         false
Docker Engine:
	Engine version:        23.0.1
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 18.04.6 LTS
	OS type:               linux
	OS version:            18.04
	OS arch:               x86_64
	OS kernel:             4.15.0-204-generic
	OS CPU:                12
	OS memory:             31828 MB
	Security options:
		name=apparmor
		name=seccomp,profile=builtin
```

### Command used with act

```sh
act -j job -W .github/workflows/job.yml
```

### Describe issue

The following configuration is perfectly fine in GH:
```yml
name: 'Name'
description: 'Description.'
inputs:
  action:
    description: Action to perform in case this action is triggered by `workflow_dispatch`
    required: true if `event_name` is `workflow_dispatch`.
  event_name:
    description: The name of the event triggering this action (pull_request, push, workflow_dispatch)
    required: true
```
but it fails with the following error when I run the job locally with act:
```text
cannot unmarshal !!str `true if...` into bool
```

### Workflow content

```yml
name: 'Name'
description: 'Description.'
inputs:
  action:
    description: Action to perform in case this action is triggered by `workflow_dispatch`
    required: true if `event_name` is `workflow_dispatch`.
  event_name:
    description: The name of the event triggering this action (pull_request, push, workflow_dispatch)
    required: true
```

### Relevant log output

```sh
[JOB] yaml: unmarshal errors:
  line 6: cannot unmarshal !!str `true if...` into bool
```

**Comment by alex-savchuk** [comment]
I reproduce this with "on.workflow_call.inputs" (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call) but not with top-level "inputs":
```
name: 'Name'
description: 'Description.'

on:
  workflow_dispatch:
    inputs:
      action:
        description: Action to perform in case this action is triggered by `workflow_dispatch`
        required: true if `event_name` is `workflow_dispatch`.
      event_name:
        description: The name of the event triggering this action (pull_request, push, workflow_dispatch)
        required: true

jobs:
  valid-JOB-Name-v123-docker_hub:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
```

> The following configuration is perfectly fine in GH

Do you mean for "fine" that this condition "if `event_name` is `workflow_dispatch`." is working (required is becoming true or false) or this condition is ignored and used as comment?
