### ISSUE TITLE
Runner filesystem can't be written to

### ISSUE THREAD

**Issue by pentago** [nektos/act#1659]
### Bug report info

```plain text
act version:            HEAD-44b510f
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	/var/run/docker.sock
	/Users/dzhi/.docker/run/docker.sock
Config files:           
	/Users/dzhi/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
		ubuntu-16.04=catthehacker/ubuntu:act-16.04
Build info:
	Go version:            go1.20.1
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=HEAD-44b510f
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               arm64
		GOOS:                 darwin
Docker Engine:
	Engine version:        22.06.0-beta.0-926-g914b02ebaf.m
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        stargz
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               aarch64
	OS kernel:             5.15.49-linuxkit
	OS CPU:                4
	OS memory:             7951 MB
	Security options:
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
act --container-architecture "linux/amd64" --secret-file act-secrets.txt --env-file act-env.txt --platform --reuse
```

### Describe issue

While using action that writes to filesystem (e.g. docker-login-action) the build fails because container filesystem cannot ber written to in case where said action tries to save docker registry creds to a file like `/root/.docker`. 

### Workflow content

```yml
name: project

on:
  push:
    branches:
      - master

jobs:
  build_covid_passenger_data:
    runs-on: ubuntu-22.04

    steps:

      - name: Checking Out Branch
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 1

      - name: Set Environment Variables
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)"                                                                   >> $GITHUB_ENV
          echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)"                                                                           >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/$GITHUB_REPOSITORY/commit"                                                   >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 | sed '2d' | head -n 1)"                                         >> $GITHUB_ENV
          echo "BUILD_CONTEXT=."                                                                                           >> $GITHUB_ENV

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.CR_ENDPOINT }}
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PASSWORD }}
```

### Relevant log output

```sh
[project] ⭐ Run Main Login to Azure Container Registry
[project]   🐳  docker cp src=/Users/dzhi/.cache/act/docker-login-action@v2.1.0/ dst=/var/run/act/actions/docker-login-action@v2.1.0/
[project]   🐳  docker exec cmd=[node /var/run/act/actions/docker-login-action@v2.1.0/dist/index.js] user= workdir=
| Logging into ***...
[project]   ❗  ::error::WARNING! Your password will be stored unencrypted in /root/.docker/config.json.%0AConfigure a credential helper to remove this warning. See%0Ahttps://docs.docker.com/engine/reference/commandline/login/#credentials-store%0A%0AError saving credentials: mkdir /root/.docker: no such file or directory
[project]   ❌  Failure - Main Login to Azure Container Registry
[project] exitcode '1': failure
```
