### ISSUE TITLE
Is it possible to run jobs by specifying container?

### ISSUE THREAD

**Issue by aeiouaoeiuv** [nektos/act#1662]
### Act version

0.2.43

### Feature description

I created a container by docker compose. And this container is always running. Also with some environments set and volumes set in compose.yaml.
How to use act with some arguments to run jobs in the container I created, instead of created by act itself?

**Comment by alex-savchuk** [comment]
Maybe container option helps with that:
```
name: container-hostname
on: push

defaults:
  run:
    shell: bash

jobs:
  with-hostname:
    runs-on: ubuntu-latest
    container:
      image: node:16-buster-slim
      options: "--hostname my.host.local --user 100:101"
    steps:
      - run: |
          echo "UID: $(id -u)"
          echo "GID: $(id -g)"
          echo "HOST: $(uname -n)"
          [[ "$(id -u)" == "100" ]] && [[ "$(id -g)" == "101" ]] && [[ "$(uname -n)" == "my.host.local" ]]
```
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer
