### ISSUE TITLE
`gh act` fails with: `Error response from daemon: Head "https://registry-1.docker.io/v2/.../act-22.04": unauthorized: incorrect username or password`

### ISSUE THREAD

**Issue by ghillb** [nektos/act#1668]
### Bug report info

```plain text
act version:            0.2.43
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
Config files:           
        /home/g/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.18.10
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:         
        Build settings:
                -compiler:            gc
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         65088b8f28d44da128b95ec194a04277b8856be9
                vcs.time:             2023-01-20T18:39:07Z
                vcs.modified:         true
Docker Engine:
        Engine version:        20.10.23
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               x86_64
        OS kernel:             5.10.16.3-microsoft-standard-WSL2
        OS CPU:                8
        OS memory:             38280 MB
        Security options:
                name=seccomp,profile=default
```

### Command used with act

```sh
gh act
```

### Describe issue

Workflow fails with:

```
[github pages/deploy] 🚀  Start image=catthehacker/ubuntu:act-22.04
[github pages/deploy]   🐳  docker pull image=catthehacker/ubuntu:act-22.04 platform= username= forcePull=true
Error: Error response from daemon: Head "https://registry-1.docker.io/v2/catthehacker/ubuntu/manifests/act-22.04": unauthorized: incorrect username or password
```
I was able to log in manually and pull the image with standard `docker` commands.

### Workflow content

```yml
name: github pages

on:
  push:
    branches:
      - main #change git branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```

### Relevant log output

```sh
DEBU[0000] Loading environment from /home/g/test-repo/.env 
DEBU[0000] Loading action inputs from /home/g/test-repo/.input 
DEBU[0000] Loading secrets from /home/g/test-repo/.secrets 
DEBU[0000] Loading workflows from '/home/g/test-repo/.github/workflows' 
DEBU[0000] Loading workflows recursively                
DEBU[0000] Found workflow 'gh-pages.yml' in '/home/g/test-repo/.github/workflows/gh-pages.yml' 
DEBU[0000] Reading workflow '/home/g/test-repo/.github/workflows/gh-pages.yml' 
DEBU[0000] Preparing plan with all jobs                 
DEBU[0000] Using default workflow event: push           
DEBU[0000] Planning jobs for event: push                
DEBU[0000] Loading revision from git directory          
DEBU[0000] Found revision: b1637efd3f39ad23a273d2732a2bd32a4aa14204 
DEBU[0000] HEAD points to 'b1637efd3f39ad23a273d2732a2bd32a4aa14204' 
DEBU[0000] using github ref: refs/heads/main            
DEBU[0000] Found revision: b1637efd3f39ad23a273d2732a2bd32a4aa14204 
DEBU[0000] Conditional GET for notices etag=75907bc6-f8b2-4c60-9e05-5ac9bb7b1051 
[github pages/deploy] [DEBUG] evaluating expression 'success()'
[github pages/deploy] [DEBUG] expression 'success()' evaluated to 'true'
[github pages/deploy] 🚀  Start image=catthehacker/ubuntu:act-22.04
[github pages/deploy]   🐳  docker pull image=catthehacker/ubuntu:act-22.04 platform= username= forcePull=true
[github pages/deploy] [DEBUG]   🐳  docker pull catthehacker/ubuntu:act-22.04
[github pages/deploy] [DEBUG] pulling image 'docker.io/catthehacker/ubuntu:act-22.04' ()
DEBU[0000] Saving notices etag=75907bc6-f8b2-4c60-9e05-5ac9bb7b1051 
DEBU[0000] No new notices                               
Error: Error response from daemon: Head "https://registry-1.docker.io/v2/catthehacker/ubuntu/manifests/act-22.04": unauthorized: incorrect username or password
```
