### ISSUE TITLE
Docker: Error response from daemon: error while creating mount source path '/host_mnt/root/.gitconfig': mkdir /host_mnt/root: operation not permitted

### ISSUE THREAD

**Issue by pietrzakadrian** [nektos/act#1677]
### Bug report info

```plain text
act version:            0.2.43
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
        /Users/pietrzakadrian/.docker/run/docker.sock
Config files:           
        /Users/pietrzakadrian/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.20.1
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.43
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        20.10.23
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.15.49-linuxkit
        OS CPU:                5
        OS memory:             7951 MB
        Security options:
                name=seccomp,profile=default
                name=cgroupns
```

### Command used with act

```sh
act -j stan -s GITHUB_TOKEN=github...
```

### Describe issue

My docker has full disk access and shares the `/root/.gitconfig` and `/root/.ssh` folders. This action works on github.

### Workflow content

```yml
name: stan
on: [push]

jobs:
  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/ tests/
          configuration: phpstan.neon
          memory_limit: 1G
```

### Relevant log output

```sh
docker: Error response from daemon: error while creating mount source path '/host_mnt/root/.gitconfig': mkdir /host_mnt/root: operation not permitted.
```
