### ISSUE TITLE
user shivammathur/setup-php@v2 got error with SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by zgqit** [nektos/act#1681]
### Bug report info

```plain text
act version:            0.2.43
GOOS:                   windows
GOARCH:                 amd64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        \\.\pipe\docker_engine
Config files:
        C:\Users\Powte\.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:full-18.04
Build info:
        Go version:            go1.18.10
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.43 -X main.commit=44b510f48cac6a58654bf920ee26cc6e1d36ac3a -X main.date=2023-03-01T02:33:51Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 windows
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         44b510f48cac6a58654bf920ee26cc6e1d36ac3a
                vcs.time:             2023-03-01T02:33:29Z
                vcs.modified:         false
Docker Engine:
        Engine version:        20.10.21
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.10.16.3-microsoft-standard-WSL2
        OS CPU:                8
        OS memory:             11976 MB
        Security options:
                name=seccomp,profile=default
```

### Command used with act

```sh
act  --secret-file AZUREAPPSERVICE_PUBLISHPROFILE=xxxx.PublishSettings -v -W .github/workflows/azure-dev.yml
```

### Describe issue

use act depoly php environment on the azure web app service,when execute the shivammathur-setup-php@v2 action, got the SyntaxError: Unexpected token '??='.

### Workflow content

```yml
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure development 

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    environment:
      name: ''
      url: ''
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ''
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE}}
          package: .
```

### Relevant log output

```sh
| /run/act/actions/shivammathur-setup-php@v2/dist/index.js:935

|     data['domain'] ??= data['github'];

|                    ^^^

|

| SyntaxError: Unexpected token '??='

|     at wrapSafe (internal/modules/cjs/loader.js:988:16)

|     at Module._compile (internal/modules/cjs/loader.js:1036:27)

|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

|     at Module.load (internal/modules/cjs/loader.js:937:32)

|     at Function.Module._load (internal/modules/cjs/loader.js:778:12)

|     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)

|     at internal/main/run_main_module.js:17:47
```
