### ISSUE TITLE
Calling a Docker actions with an input parameter called "args" overrides the "args" parameter used when calling the container.

### ISSUE THREAD

**Issue by ScionOfDesign** [nektos/act#1692]
### Bug report info

```plain text
act version:            0.2.43
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 24
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
Config files:
        /home/scion/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.18.10
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.43 -X main.commit=44b510f48cac6a58654bf920ee26cc6e1d36ac3a -X main.date=2023-03-01T02:33:51Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         44b510f48cac6a58654bf920ee26cc6e1d36ac3a
                vcs.time:             2023-03-01T02:33:29Z
                vcs.modified:         false
Docker Engine:
        Engine version:        20.10.17
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.10.102.1-microsoft-standard-WSL2
        OS CPU:                24
        OS memory:             23998 MB
        Security options:
                name=seccomp,profile=default
```

### Command used with act

```sh
act
```

### Describe issue

I have a composite action that looks like so:
```yaml
name: rockylinux
description: "Run rockylinux commands."
inputs:
  workingDir:
    description: "Working directory to execute the commands in."
    required: true
    default: "."
  args:
    description: "Arguments to pas tto the container"
    required: true
    default: "."
outputs:
  console:
    description: "The console output of the command."
runs:
  using: docker
  image: Dockerfile
  args:
  - "${{ inputs.workingDir }}"
  - "${{ inputs.args }}"
 ```
I call it from my `master.yaml` file like so:
```yaml
- uses: act/common/distros/rockylinux4@master
   with:
      workingDir: test
      args: ls -al
```

However, when running `act` the `workingDir` parameter is _completely ignored_ like so:
`docker run image=act-act-common-distros-rockylinux-master-distros-rockylinux-dockeraction:latest platform= entrypoint=[] cmd=["ls" "-al"]`
Note how `test` is not in the `cmd` array.

However, if I rename `args` to `args1`, it works as expected:
`docker run image=act-act-common-distros-rockylinux-master-distros-rockylinux-dockeraction:latest platform= entrypoint=[] cmd=["test" "ls -al"`

### Workflow content

```yml
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -p test
        echo "Hi mom!" > test/hi.txt
    - uses: act/common/distros/rockylinux@master
      with:
        workingDir: test
        args: ls -al
```

### Relevant log output

```sh
There is no additional relevant log output.
```
