### ISSUE TITLE
Services not working

### ISSUE THREAD

**Issue by fgimenez** [nektos/act#173]
Hello! I have this workflow:
```name: test-and-build
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:12.16.1-stretch
    services:
      mongodb:
        image: "mongo:4.0.17"
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
```
The `yarn test` command expects to find a mongodb service listening on 27017, but running act the command fails with `MongooseServerSelectionError: getaddrinfo ENOTFOUND mongodb`. The same workflow succeeds on GitHub.

I've also tried `-P ubuntu-latest=nektos/act-environments-ubuntu:18.04`, any help is very appreciated :)

**Comment by thatdoogieguy** [comment]
I was having a similar problem, especially when i was trying to combine rails caching with postgresql and redis. In the end i created a seperate workflow file called ci-local.yml based off of the production Github Actions file i had created and manually defined the services by calling apt-get then service %service_name% start. 

Massive PITA but for localised testing this was the only way i could thoroughly test the functional parts of GitHub Actions where multiple parts are as yet unsupported. 

Not a fix, just a hacky workaround to get myself out of trouble!

**Comment by ibrt** [comment]
Same problem here with postgres... It looks like the service container is not being run so DNS lookup of its name fails. Is this supposed to work?

**Comment by Zeka13** [comment]
shiiiiiiiiiiiiit

**Comment by jadhavmanoj** [comment]
Same here. Services not working. Any workaround for the same?

**Comment by Zeka13** [comment]
@jadhavmanoj workaround is to use docker-compose

**Comment by chenxilinsidney** [comment]
I have the same problem while using services of mysql and redis in action

**Comment by creepinson** [comment]
Any updates? It's been another month

**Comment by Lzok** [comment]
Hello, any update on this?

My code:
```yaml
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.0
        ports:
          - 27017/tcp
# ...etc
```

In the env section of my job I have: `MONGO_URI_TESTS: localhost:${{ job.services.mongodb.ports[27017] }}/dbtest`

The error: `ERRO[0082] Unable to interpolate string 'localhost:${{ job.services.mongodb.ports[27017] }}/dbtest' - [TypeError: Cannot access member 'ports' of undefined]`

Thank you!

**Comment by Systho** [comment]
@thatdoogieguy Could you provide a snippet of the step you wrote tha install & start postgresql ? 
I have a feeling that is a simple one but since you have experience about it  let's ensure there is no nasty corner case :)

**Comment by loklaan** [comment]
@Systho A small reproduction is:

1. Create `.github/workflows/repro.yml`
```yml
name: "Reproduction"

on:
  push:

jobs:
  repro:
    name: Reproduction of failing Services interpolation
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: mysecretdbpass
          POSTGRES_DB: mydb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Echo the Postgres service ID / Network / Ports
        run: |
          echo "id: ${{ job.services.postgres.id }}"
          echo "network: ${{ job.services.postgres.network }}"
          echo "ports: ${{ job.services.postgres.ports }}"
```

2. Run `act "push" --job "repro"`

**Comment by amacgregorhumi** [comment]
BUMP

**Comment by moki9** [comment]
BUMP

**Comment by elitan** [comment]
The bot closing issues after 14 days is pretty aggressive. :/

**Comment by catthehacker** [comment]
Services were drafted in https://github.com/nektos/act/pull/638 but author stopped responding, it works but it also breaks easily thus it wasn't merged

**Comment by catthehacker** [comment]
Notification for people subscribed to this thread, please see latest PR mentioned.
artefacts: https://github.com/nektos/act/actions/runs/1118549374

**Comment by techpeace** [comment]
I added the following steps to my workflow in order to get the actions for my Rails app running locally:

```yaml
 # Install local deps if this action is being run locally
      - name: Install local dependencies
        if: ${{ env.ACT }}
        run: |
          npm i -g yarn
          sudo apt-get update
          sudo apt-get -yqq install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2 libxshmfence-dev postgresql postgresql-contrib redis-server

      - name: Boot local dependencies
        if: ${{ env.ACT }}
        run: |
          sudo service postgresql start
          sudo service redis-server start

      - name: Configure local dependencies
        if: ${{ env.ACT }}
        run: |
          sudo -u postgres psql -U postgres -d postgres -c "alter user postgres with password 'password';"
```
