### ISSUE TITLE
NotSpecified: (Error: Job 'build' failed:String) [], RemoteException

### ISSUE THREAD

**Issue by magedhelmy1** [nektos/act#1738]
### Bug report info

```plain text
PS C:\Users\maged\Desktop\projects\compute-local> act --bug-report
act version:            0.2.43
GOOS:                   windows
GOARCH:                 amd64
NumCPU:                 32
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
	\\.\pipe\docker_engine
Config files:           
	C:\Users\maged\.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.18.10
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.43 -X main.commit=44b510f48cac6a58654bf920ee26cc6e1d36ac3a -X main.date=2023-03-01T02:33:51Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 windows
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         44b510f48cac6a58654bf920ee26cc6e1d36ac3a
		vcs.time:             2023-03-01T02:33:29Z
		vcs.modified:         false
Docker Engine:
	Engine version:        20.10.24
	Engine runtime:        
	Cgroup version:        
	Cgroup driver:         
	Storage driver:        windowsfilter
	Registry URI:          https://index.docker.io/v1/
	OS:                    Windows 10 Pro Version 2009 (OS Build 22621.1555)
	OS type:               windows
	OS version:            10.0.22621
	OS arch:               x86_64
	OS kernel:             10.0 22621 (22621.1.amd64fre.ni_release.220506-1250)
	OS CPU:                32
	OS memory:             65477 MB
	Security options:
```

### Command used with act

```sh
PS C:\Users\maged\Desktop\projects\compute-local> act -P ubuntu-latest=node:12 -v
act : time="2023-04-17T20:50:26+02:00" level=debug msg="Loading environment from C:\\Users\\maged\\Desktop\\projects\\compute-local\\.env"
At line:1 char:1
+ act -P ubuntu-latest=node:12 -v
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (time="2023-04-1...te-local\\.env":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
time="2023-04-17T20:50:26+02:00" level=debug msg="Conditional GET for notices etag=8ae6883d-97ca-4559-aa2f-fee6cf7c30ca"
time="2023-04-17T20:50:26+02:00" level=debug msg="Loading action inputs from C:\\Users\\maged\\Desktop\\projects\\compute-local\\.input"
time="2023-04-17T20:50:26+02:00" level=debug msg="Loading secrets from C:\\Users\\maged\\Desktop\\projects\\compute-local\\.secrets"
time="2023-04-17T20:50:26+02:00" level=debug msg="Loading workflows from 'C:\\Users\\maged\\Desktop\\projects\\compute-local\\.github\\workflows'"
time="2023-04-17T20:50:26+02:00" level=debug msg="Loading workflows recursively"
time="2023-04-17T20:50:26+02:00" level=debug msg="Found workflow 'main.yml' in 'C:\\Users\\maged\\Desktop\\projects\\compute-local\\.github\\workflows\\main.yml'"
time="2023-04-17T20:50:26+02:00" level=debug msg="Reading workflow 'C:\\Users\\maged\\Desktop\\projects\\compute-local\\.github\\workflows\\main.yml'"
time="2023-04-17T20:50:26+02:00" level=debug msg="Preparing plan with all jobs"
time="2023-04-17T20:50:26+02:00" level=debug msg="Using the only detected workflow event: push"
time="2023-04-17T20:50:26+02:00" level=debug msg="Planning jobs for event: push"
time="2023-04-17T20:50:26+02:00" level=debug msg="Loading revision from git directory"
time="2023-04-17T20:50:26+02:00" level=debug msg="Found revision: 9c45a912db3b8b4f071f943f29bbcae0ac6adf38"
time="2023-04-17T20:50:26+02:00" level=debug msg="HEAD points to '9c45a912db3b8b4f071f943f29bbcae0ac6adf38'"
time="2023-04-17T20:50:26+02:00" level=debug msg="using github ref: refs/heads/main"
time="2023-04-17T20:50:26+02:00" level=debug msg="Found revision: 9c45a912db3b8b4f071f943f29bbcae0ac6adf38"
[Build Executable/build] [DEBUG] evaluating expression 'success()'
[Build Executable/build] [DEBUG] expression 'success()' evaluated to 'true'
[Build Executable/build] ðŸš§  Skipping unsupported platform -- Try running with `-P windows-latest=...`
time="2023-04-17T20:50:27+02:00" level=debug msg="Saving notices etag=8ae6883d-97ca-4559-aa2f-fee6cf7c30ca"
time="2023-04-17T20:50:27+02:00" level=debug msg="No new notices"
```

### Describe issue

I do not understand why this is not working

`act -P windows-latest=-self-hosted`

### Workflow content

```yml
name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pip dependencies
        uses: actions/cache@v2.1.8
        with:
          path: |
            ${{ env.USERPROFILE }}\.virtualenvs
            ${{ env.USERPROFILE }}\AppData\Local\pip\Cache
          key: Windows-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            Windows-python-${{ matrix.python-version }}-


      - uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.10.10' 
          architecture: 'x64'

      - name: Install Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global credential.helper store # This command stores the credentials locally so that they can be used in subsequent git commands
          set GIT_TERMINAL_PROMPT=0
          pip install -r requirements.txt
          set DEPENDENCIES_PATH=$(python -c 'import site; print(site.getsitepackages()[0])')
          echo "Dependencies installed at $DEPENDENCIES_PATH"


      - name: Build Executable
        run: |
          pyinstaller --noconfirm --onedir --console --log-level "ERROR" --add-data "$DEPENDENCIES_PATH;."  "backend/manage.py"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Automated build of release ${{ github.ref }}
```

### Relevant log output

```sh
PS C:\Users\maged\Desktop\projects\compute-local> act -P windows-latest=-self-hosted
[Build Executable/build]   â˜  git clone 'https://github.com/actions/setup-python' # ref=v2.2.2
[Build Executable/build]   â˜  git clone 'https://github.com/actions/create-release' # ref=v1.0.0
[Build Executable/build] â­ Run Main actions/checkout@v3
[Build Executable/build]   âœ…  Success - Main actions/checkout@v3
[Build Executable/build] â­ Run Main actions/setup-python@v2.2.2
[Build Executable/build]   ðŸ’¬  ::debug::Semantic version spec of 3.10.10 is 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::isExplicit: 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::explicit? true
[Build Executable/build]   ðŸ’¬  ::debug::checking cache: C:\Users\maged\.cache\act\tool_cache\Python\3.10.10\x64
[Build Executable/build]   ðŸ’¬  ::debug::not found
[Build Executable/build]   | Version 3.10.10 was not found in the local cache
[Build Executable/build]   ðŸ’¬  ::debug::check 3.12.0-alpha.7 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.12.0-alpha.6 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.12.0-alpha.5 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.12.0-alpha.4 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.12.0-alpha.3 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.12.0-alpha.2 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.12.0-alpha.1 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.3 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.2 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.1 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-rc.2 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-rc.1 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-beta.5 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-beta.4 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-beta.3 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-beta.2 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-beta.1 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-alpha.7 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-alpha.6 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-alpha.5 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-alpha.4 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-alpha.3 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-alpha.2 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.11.0-alpha.1 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.10.11 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::check 3.10.10 satisfies 3.10.10
[Build Executable/build]   ðŸ’¬  ::debug::x64===x64 && darwin===win32
[Build Executable/build]   ðŸ’¬  ::debug::x64===x64 && linux===win32
[Build Executable/build]   ðŸ’¬  ::debug::x64===x64 && linux===win32
[Build Executable/build]   ðŸ’¬  ::debug::x64===x64 && linux===win32
[Build Executable/build]   ðŸ’¬  ::debug::x64===x64 && win32===win32
[Build Executable/build]   ðŸ’¬  ::debug::matched 3.10.10
[Build Executable/build]   | Version 3.10.10 is available for downloading
[Build Executable/build]   | Download from "https://github.com/actions/python-versions/releases/download/3.10.10-4126486420/python-3.10.10-win32-x64.zip"
[Build Executable/build]   ðŸ’¬  ::debug::Downloading https://github.com/actions/python-versions/releases/download/3.10.10-4126486420/python-3.10.10-win32-x64.zip
[Build Executable/build]   ðŸ’¬  ::debug::Destination C:\Users\maged\.cache\act\72e2bf04555df432\tmp\cb947a7b-f863-47ac-91c8-4175ba04f58f
[Build Executable/build]   ðŸ’¬  ::debug::download complete
[Build Executable/build]   | Extract downloaded archive
[Build Executable/build]   | [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Co
mmand "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory(
'C:\Users\maged\.cache\act\72e2bf04555df432\tmp\cb947a7b-f863-47ac-91c8-4175ba04f58f', 'C:\Users\maged\.cache\act\72e2bf04555df432\tmp\45f7d883-f7cb-488f-b2a0-69813cd686
18')"
[Build Executable/build]   | Execute installation script
[Build Executable/build]   â—  ::error::./setup.ps1 : File C:\Users\maged\.cache\act\72e2bf04555df432\tmp\45f7d883-f7cb-488f-b2a0-69813cd68618\setup.ps1
[Build Executable/build]   â—  ::error::cannot be loaded because running scripts is disabled on this system. For more information, see %0D%0Aabout_Execution_Policies at
 https:/go.microsoft.com/fwlink/?LinkID=135170.%0D%0AAt line:1 char:1%0D%0A+ ./setup.ps1%0D%0A+ ~~~~~~~~~~~%0D%0A    + CategoryInfo          : SecurityError: (:) [], PSS
ecurityException%0D%0A    + FullyQualifiedErrorId : UnauthorizedAccess
[Build Executable/build]   â—  ::error::The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
[Build Executable/build]   âŒ  Failure - Main actions/setup-python@v2.2.2
[Build Executable/build] exit status 1
[Build Executable/build] ðŸ  Job failed
act : Error: Job 'build' failed
At line:1 char:1
+ act -P windows-latest=-self-hosted
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: Job 'build' failed:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
