### ISSUE TITLE
Expressions interpreter doesn't support short circuit for `&&` and `||`

### ISSUE THREAD

**Issue by ChristopherHX** [nektos/act#1746]
https://github.com/nektos/act/blob/37152664940eea09a6775daf5eff8ee0d7f31442/pkg/exprparser/interpreter.go#L546-L558

```yaml
on: push
jobs:
  _:
    runs-on: ubuntu-latest
    if: always() && (contains(needs.*.result, 'cancelled') && fromjson('throw') || !cancelled())
    steps:
    - run: echo "Never reach here"
```

`fromjson('throw')` should be unreachable if no job has result `cancelled`, but it still get executed.

_I will pick this up at some point of time_
