### ISSUE TITLE
runs-on is not successfully parsed if it contains an array, which is valid

### ISSUE THREAD

**Issue by jeffhubLR** [nektos/act#175]
Documentation:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

Yaml that duplicates error:
```
name: Test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [self-hosted, windows]
    name: Test

    steps:
      - name: Ensure Docker is running
        run: |
          docker ps -a
```

Error received:
```
Error: yaml: unmarshal errors:
  line 8: cannot unmarshal !!seq into string
```
