### ISSUE TITLE
Error: Error response from daemon: Head "https://registry-1.docker.io/v2/catthehacker/ubuntu/manifests/act-latest": unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by PavelA85** [nektos/act#1769]
### Bug report info

```plain text
act version:            0.2.44
GOOS:                   windows
GOARCH:                 amd64
NumCPU:                 16
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        \\.\pipe\docker_engine
Config files:
        C:\Users\PavelAgejkin\.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.18.10
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.44 -X main.commit=220d6f1251aea75c378e5a98546f43cd918e1892 -X main.date=2023-04-01T02:18:17Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 windows
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         220d6f1251aea75c378e5a98546f43cd918e1892
                vcs.time:             2023-04-01T02:17:52Z
                vcs.modified:         false
Docker Engine:
        Engine version:        20.10.24
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.15.90.1-microsoft-standard-WSL2
        OS CPU:                2
        OS memory:             2913 MB
        Security options:
                name=seccomp,profile=default
                name=cgroupns
```

### Command used with act

```sh
act pull_request
```

### Describe issue

I have installed act long time ago and it worked as expected, but now when I try to execute act I get error:
```
[dotnet builder/DotNetBuilder] �  Start image=catthehacker/ubuntu:act-latest
[dotnet builder/DotNetBuilder]   �  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
Error: Error response from daemon: Head "https://registry-1.docker.io/v2/catthehacker/ubuntu/manifests/act-latest": unauthorized: incorrect username or password
```

I tried fixes from https://github.com/nektos/act/issues/1248
`docker login ghcr.io` and  `docker logout ghcr.io`
But still same issue

### Workflow content

```yml
name: dotnet builder

on:
  pull_request_target:
    types: [ opened, edited, reopened, synchronize ]
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
  push:
    branches-ignore:
      - 'sync/**'

jobs:
  DotNetBuilder:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: git checkout PR
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        run: |
          cd $GITHUB_WORKSPACE
          git init
          git fetch --force \
            --progress \
            -- https://user:${{ secrets.GITHUB_TOKEN }}@github.com/*********/************** \
            +refs/heads/release:refs/remotes/origin/release \
            +refs/heads/develop:refs/remotes/origin/develop \
            +refs/heads/{{ github.event.pull_request.base.ref }}:refs/remotes/origin/{{ github.event.pull_request.base.ref }} \
            +refs/pull/${{ github.event.pull_request.number }}/*:refs/remotes/origin/pr/${{ github.event.pull_request.number }}/*
          git checkout origin/pr/${{ github.event.pull_request.number }}/merge 
          git show-ref
```

### Relevant log output

```sh
λ act pull_request -v
time="2023-04-25T17:49:02+03:00" level=debug msg="Loading environment from C:\\Projects\\MyProject\\.env"
time="2023-04-25T17:49:02+03:00" level=debug msg="Conditional GET for notices etag=7f63cf74-b2af-4e60-912f-c5531fdabaf0"
time="2023-04-25T17:49:02+03:00" level=debug msg="Loading action inputs from C:\\Projects\\MyProject\\.input"
time="2023-04-25T17:49:02+03:00" level=debug msg="Loading secrets from C:\\Projects\\MyProject\\.secrets"
time="2023-04-25T17:49:02+03:00" level=debug msg="Evaluated matrix inclusions: map[]"
time="2023-04-25T17:49:02+03:00" level=debug msg="Loading workflows from 'C:\\Projects\\MyProject\\.github\\workflows'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Loading workflows recursively"
time="2023-04-25T17:49:02+03:00" level=debug msg="Found workflow 'builder.yml' in 'C:\\Projects\\MyProject\\.github\\workflows\\builder.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Found workflow 'pr.json' in 'C:\\Projects\\MyProject\\.github\\workflows\\pr.json'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Found workflow 'syncComposer.yml' in 'C:\\Projects\\MyProject\\.github\\workflows\\syncComposer.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Found workflow 'syncDev.yml' in 'C:\\Projects\\MyProject\\.github\\workflows\\syncDev.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Found workflow 'template.yml' in 'C:\\Projects\\MyProject\\.github\\workflows\\template.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Found workflow 'updateNuGet.yml' in 'C:\\Projects\\MyProject\\.github\\workflows\\updateNuGet.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Reading workflow 'C:\\Projects\\MyProject\\.github\\workflows\\builder.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Reading workflow 'C:\\Projects\\MyProject\\.github\\workflows\\syncComposer.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Reading workflow 'C:\\Projects\\MyProject\\.github\\workflows\\syncDev.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Reading workflow 'C:\\Projects\\MyProject\\.github\\workflows\\template.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Reading workflow 'C:\\Projects\\MyProject\\.github\\workflows\\updateNuGet.yml'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Using first passed in arguments event for filtering: pull_request"
time="2023-04-25T17:49:02+03:00" level=debug msg="Preparing plan for a event: pull_request"
time="2023-04-25T17:49:02+03:00" level=debug msg="Using first passed in arguments event: pull_request"
time="2023-04-25T17:49:02+03:00" level=debug msg="Planning jobs for event: pull_request"
time="2023-04-25T17:49:02+03:00" level=debug msg="Final matrix after applying user inclusions '[map[]]'"
time="2023-04-25T17:49:02+03:00" level=debug msg="Found revision: 6034231b5ca9026a8e4c48be90664de8fba0b4c6"
[dotnet builder/DotNetBuilder] [DEBUG] evaluating expression 'success()'
[dotnet builder/DotNetBuilder] [DEBUG] expression 'success()' evaluated to 'true'
[dotnet builder/DotNetBuilder] �  Start image=catthehacker/ubuntu:act-latest
[dotnet builder/DotNetBuilder]   �  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[dotnet builder/DotNetBuilder] [DEBUG]   �  docker pull catthehacker/ubuntu:act-latest
[dotnet builder/DotNetBuilder] [DEBUG] pulling image 'docker.io/catthehacker/ubuntu:act-latest' ()
time="2023-04-25T17:49:03+03:00" level=debug msg="Saving notices etag=7f63cf74-b2af-4e60-912f-c5531fdabaf0"
time="2023-04-25T17:49:03+03:00" level=debug msg="No new notices"
Error: Error response from daemon: Head "https://registry-1.docker.io/v2/catthehacker/ubuntu/manifests/act-latest": toomanyrequests: too many failed login attempts for username or IP address
```
```


### Additional information

_No response_
