### ISSUE TITLE
interpolation not working in job name on failure

### ISSUE THREAD

**Issue by tamird** [nektos/act#1775]
### Bug report info

```plain text
act version:            0.2.44
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 32
Docker host:            DOCKER_HOST environment variable is unset/empty.
Sockets found:
        /var/run/docker.sock
Config files:           
        /home/tamird/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.18.10
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:         
        Build settings:
                -compiler:            gc
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         65088b8f28d44da128b95ec194a04277b8856be9
                vcs.time:             2023-01-20T18:39:07Z
                vcs.modified:         true
Docker Engine:
        Engine version:        23.0.5
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         systemd
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Ubuntu 23.04
        OS type:               linux
        OS version:            23.04
        OS arch:               x86_64
        OS kernel:             6.2.0-20-generic
        OS CPU:                32
        OS memory:             63391 MB
        Security options:
                name=apparmor
                name=seccomp,profile=builtin
                name=cgroupns

```

### Command used with act

```sh
gh act
```

### Describe issue

The final bit of logging looks like this:
```
[Build/rustc=stable llvm=16-1 ]   ✅  Success - Main Test (rustc target = HOST_TARGET, link target = BPF)
[Build/rustc=stable llvm=16-1 ] ⭐ Run Post taiki-e/install-action@cargo-hack
[Build/rustc=stable llvm=16-1 ]   🐳  docker cp src=/home/tamird/.cache/act/taiki-e-install-action@cargo-hack/ dst=/var/run/act/actions/taiki-e-install-action@cargo-hack/
[Build/rustc=stable llvm=16-1 ]   ✅  Success - Post taiki-e/install-action@cargo-hack
[Build/rustc=stable llvm=16-1 ] ⭐ Run Post Swatinem/rust-cache@v1
[Build/rustc=stable llvm=16-1 ]   🐳  docker exec cmd=[node /var/run/act/actions/Swatinem-rust-cache@v1/dist/save/index.js] user= workdir=
[Build/rustc=stable llvm=16-1 ]   ✅  Success - Post Swatinem/rust-cache@v1
[Build/rustc=stable llvm=16-1 ] 🏁  Job failed
Error: Job 'rustc=${{ matrix.rust }} llvm=${{ matrix.llvm }}' failed
```
You can see that the job name is interpolated everywhere except the final "job failed" message.

### Link to GitHub repository

https://github.com/tamird/bpf-linker/tree/fix-features

### Workflow content

```yml
name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 00 4 * * *

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
        llvm: [16]
    name: rustc=${{ matrix.rust }} llvm=${{ matrix.llvm }}

    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust ${{ matrix.rust }}
        if: matrix.rust != 'nightly'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: Swatinem/rust-cache@v1
        if: matrix.rust != 'nightly'

      - name: Checkout Rust Source
        uses: actions/checkout@v2
        if: matrix.rust == 'nightly'
        with:
          repository: rust-lang/rust
          path: rust
          submodules: recursive
          fetch-depth: 0

      - name: Install rustup
        if: matrix.rust == 'nightly'
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install Rust ${{ matrix.rust }} From Source
        if: matrix.rust == 'nightly'
        run: |
          pushd rust
          rm -rf build
          echo -e 'profile = "user"\nchangelog-seen = 2\n\n[llvm]\ndownload-ci-llvm = true' > config.toml
          ./x.py clean
          ./x.py build -i --stage 1 --host x86_64-unknown-linux-gnu --target bpfel-unknown-none --target x86_64-unknown-linux-gnu library src/tools/rustdoc
          rustup toolchain link stage1 build/x86_64-unknown-linux-gnu/stage1
          popd
          rustup override set stage1

      - name: Install LLVM
        shell: bash
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          echo -e deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${{ matrix.llvm }} main | sudo tee /etc/apt/sources.list.d/llvm.list
          sudo apt-get update
          sudo apt-get -y install \
            llvm-${{ matrix.llvm }}-dev \
            llvm-${{ matrix.llvm }}-tools \
            libclang-${{ matrix.llvm }}-dev \
            libpolly-${{ matrix.llvm }}-dev

      - uses: taiki-e/install-action@cargo-hack

      - name: Check
        run: cargo hack check --feature-powerset

      - name: Build
        run: cargo hack build --feature-powerset

      - name: Test (rustc target = HOST_TARGET, link target = BPF)
        env:
          TESTS_HOST_TARGET: 1
        run: cargo hack test --feature-powerset

      - name: Tests (rustc target = BPF, link target = BPF)
        if: matrix.rust == 'nightly'
        env:
          TESTS_HOST_TARGET: 0
        run: cargo hack test --feature-powerset
```

### Relevant log output

```sh
[Build/rustc=stable llvm=16-1 ]   ✅  Success - Main Test (rustc target = HOST_TARGET, link target = BPF)
[Build/rustc=stable llvm=16-1 ] ⭐ Run Post taiki-e/install-action@cargo-hack
[Build/rustc=stable llvm=16-1 ]   🐳  docker cp src=/home/tamird/.cache/act/taiki-e-install-action@cargo-hack/ dst=/var/run/act/actions/taiki-e-install-action@cargo-hack/
[Build/rustc=stable llvm=16-1 ]   ✅  Success - Post taiki-e/install-action@cargo-hack
[Build/rustc=stable llvm=16-1 ] ⭐ Run Post Swatinem/rust-cache@v1
[Build/rustc=stable llvm=16-1 ]   🐳  docker exec cmd=[node /var/run/act/actions/Swatinem-rust-cache@v1/dist/save/index.js] user= workdir=
[Build/rustc=stable llvm=16-1 ]   ✅  Success - Post Swatinem/rust-cache@v1
[Build/rustc=stable llvm=16-1 ] 🏁  Job failed
Error: Job 'rustc=${{ matrix.rust }} llvm=${{ matrix.llvm }}' failed
```
