### ISSUE TITLE
Cannot read property 'lstat' of undefined in macOS

### ISSUE THREAD

**Issue by benbaker76** [nektos/act#1778]
### Bug report info

```plain text
act version:            0.2.44
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 12
Docker host:            unix:///var/run/docker.sock
Sockets found:
	/var/run/docker.sock
	/Users/headsoft/.docker/run/docker.sock
Config files:           
	/Users/headsoft/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.20.2
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.44
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
Docker Engine:
	Engine version:        23.0.5
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             5.15.49-linuxkit
	OS CPU:                6
	OS memory:             7859 MB
	Security options:
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
act push -s GITHUB_TOKEN -P macos-12=-self-hosted --artifact-server-path ~/Programming/artifacts -W .github/workflows/amd64_macos_gcc.yml
```

### Describe issue

When creating an artifact I get an error `Cannot read property 'lstat' of undefined`

### Link to GitHub repository

https://github.com/benbaker76/Gfx2Next

### Workflow content

```yml
name: amd64_macos_gcc

on: [push, pull_request]

jobs:

  amd64_macos_gcc:
    runs-on: macos-12
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - run: make
    - name: Compress Files
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: bin
        files: gfx2next
        outPath: bin/gfx2next_Darwin_amd64.tar.gz
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: bin/gfx2next_Darwin_amd64.tar.gz
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/gfx2next_Darwin_amd64.tar.gz
        tag: ${{ github.ref }}
```

### Relevant log output

```sh
[amd64_macos_gcc/amd64_macos_gcc]   ☁  git clone 'https://github.com/a7ul/tar-action' # ref=v1.1.0
[amd64_macos_gcc/amd64_macos_gcc]   ☁  git clone 'https://github.com/actions/upload-artifact' # ref=v3
[amd64_macos_gcc/amd64_macos_gcc]   ☁  git clone 'https://github.com/svenstaro/upload-release-action' # ref=e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
[amd64_macos_gcc/amd64_macos_gcc] ⭐ Run Main actions/checkout@v3
[amd64_macos_gcc/amd64_macos_gcc]   ✅  Success - Main actions/checkout@v3
[amd64_macos_gcc/amd64_macos_gcc] ⭐ Run Main make
| mkdir -p bin
| gcc -O2 -Wall -o bin/gfx2next src/lodepng.c src/zx0.c src/gfx2next.c -lm
[amd64_macos_gcc/amd64_macos_gcc]   ✅  Success - Main make
[amd64_macos_gcc/amd64_macos_gcc] ⭐ Run Main Compress Files
[amd64_macos_gcc/amd64_macos_gcc]   ⚙  ::set-output:: done=true
[amd64_macos_gcc/amd64_macos_gcc]   ✅  Success - Main Compress Files
[amd64_macos_gcc/amd64_macos_gcc] ⭐ Run Main Upload to Artifacts
[amd64_macos_gcc/amd64_macos_gcc]   💬  ::debug::followSymbolicLinks 'true'
[amd64_macos_gcc/amd64_macos_gcc]   💬  ::debug::implicitDescendants 'true'
[amd64_macos_gcc/amd64_macos_gcc]   💬  ::debug::omitBrokenSymbolicLinks 'true'
| (node:59945) ExperimentalWarning: The fs.promises API is experimental
[amd64_macos_gcc/amd64_macos_gcc]   💬  ::debug::followSymbolicLinks 'true'
[amd64_macos_gcc/amd64_macos_gcc]   💬  ::debug::implicitDescendants 'true'
[amd64_macos_gcc/amd64_macos_gcc]   💬  ::debug::matchDirectories 'true'
[amd64_macos_gcc/amd64_macos_gcc]   💬  ::debug::omitBrokenSymbolicLinks 'true'
[amd64_macos_gcc/amd64_macos_gcc]   💬  ::debug::Search path '/Users/headsoft/.cache/act/8ece04176f2ed687/hostexecutor/bin/gfx2next_Darwin_amd64.tar.gz'
[amd64_macos_gcc/amd64_macos_gcc]   ❗  ::error::Cannot read property 'lstat' of undefined
[amd64_macos_gcc/amd64_macos_gcc]   ❌  Failure - Main Upload to Artifacts
[amd64_macos_gcc/amd64_macos_gcc] exit status 1
[amd64_macos_gcc/amd64_macos_gcc] 🏁  Job failed
```
