### ISSUE TITLE
act fails to update cached action clones

### ISSUE THREAD

**Issue by jsoref** [nektos/act#1785]
### Bug report info

```plain text
act version:            0.2.45
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
	$HOME/.docker/run/docker.sock
Config files:           
	/Users/jsoref/.actrc:
		#-P ubuntu-latest=node:12.20.1-buster-slim
		#-P ubuntu-20.04=node:12.20.1-buster-slim
		#-P ubuntu-18.04=node:12.20.1-buster-slim
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
		-P ubuntu-16.04=catthehacker/ubuntu:act-16.04
		-P self-hosted=catthehacker/ubuntu:act-latest
Build info:
	Go version:            go1.20.3
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.45
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               arm64
		GOOS:                 darwin
Docker Engine:
	Engine version:        20.10.20
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Alpine Linux v3.16
	OS type:               linux
	OS version:            3.16.4
	OS arch:               aarch64
	OS kernel:             5.15.96-0-virt
	OS CPU:                2
	OS memory:             5924 MB
	Security options:
		name=seccomp,profile=default
```

### Command used with act

```sh
act -j spelling
```

### Describe issue

act's cache of actions has two `HEAD` items, a `HEAD` and a `refs/heads/HEAD`, they're disconnected from each other and when act runs it doesn't update `HEAD` to the latest value of the remote's `HEAD`.

### Link to GitHub repository

https://github.com/check-spelling/scimax

### Workflow content

```yml
name: Check Spelling

# Comment management is handled through a secondary job, for details see:
# https://github.com/check-spelling/check-spelling/wiki/Feature%3A-Restricted-Permissions
#
# `jobs.comment-push` runs when a push is made to a repository and the `jobs.spelling` job needs to make a comment
#   (in odd cases, it might actually run just to collapse a comment, but that's fairly rare)
#   it needs `contents: write` in order to add a comment.
#
# `jobs.comment-pr` runs when a pull_request is made to a repository and the `jobs.spelling` job needs to make a comment
#   or collapse a comment (in the case where it had previously made a comment and now no longer needs to show a comment)
#   it needs `pull-requests: write` in order to manipulate those comments.

# Updating pull request branches is managed via comment handling.
# For details, see: https://github.com/check-spelling/check-spelling/wiki/Feature:-Update-expect-list
#
# These elements work together to make it happen:
#
# `on.issue_comment`
#   This event listens to comments by users asking to update the metadata.
#
# `jobs.update`
#   This job runs in response to an issue_comment and will push a new commit
#   to update the spelling metadata.
#
# `with.experimental_apply_changes_via_bot`
#   Tells the action to support and generate messages that enable it
#   to make a commit to update the spelling metadata.
#
# `with.ssh_key`
#   In order to trigger workflows when the commit is made, you can provide a
#   secret (typically, a write-enabled github deploy key).
#
#   For background, see: https://github.com/check-spelling/check-spelling/wiki/Feature:-Update-with-deploy-key

# Sarif reporting
#
# Access to Sarif reports is generally restricted (by GitHub) to members of the repository.
#
# Requires enabling `security-events: write`
# and configuring the action with `use_sarif: 1`
#
#   For information on the feature, see: https://github.com/check-spelling/check-spelling/wiki/Feature:-Sarif-output

# Minimal workflow structure:
#
# on:
#   push:
#     ...
#   pull_request_target:
#     ...
# jobs:
#   # you only want the spelling job, all others should be omitted
#   spelling:
#     # remove `security-events: write` and `use_sarif: 1`
#     # remove `experimental_apply_changes_via_bot: 1`
#     ... otherwise adjust the `with:` as you wish

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "**"
  pull_request_target:
    branches:
    - "**"
    types:
    - 'opened'
    - 'reopened'
    - 'synchronize'
  issue_comment:
    types:
    - 'created'

jobs:
  spelling:
    name: Check Spelling
    permissions:
      contents: read
      pull-requests: read
      actions: read
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: ${{ contains(github.event_name, 'pull_request') || github.event_name == 'push' }}
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@prerelease
      with:
        suppress_push_for_open_pull_request: 1
        checkout: true
        check_file_names: 1
        spell_check_this: check-spelling/spell-check-this@prerelease
        post_comment: 0
        use_magic_file: 1
        report-timing: 1
        experimental_apply_changes_via_bot: 1
        use_sarif: ${{ (!github.event.pull_request || (github.event.pull_request.head.repo.full_name == github.repository)) && 1 }}
        extra_dictionary_limit: 10
        extra_dictionaries:
          cspell:software-terms/dict/softwareTerms.txt
          cspell:lisp/lisp.txt
          cspell:latex/dict/latex.txt
          cspell:python/src/python/python-lib.txt
          cspell:typescript/dict/typescript.txt
          cspell:python/src/common/extra.txt
          cspell:filetypes/filetypes.txt
          cspell:php/dict/php.txt
          cspell:r/src/r.txt
          cspell:python/src/python/python.txt
          cspell:fullstack/dict/fullstack.txt
          cspell:html/dict/html.txt
          cspell:aws/aws.txt
          cspell:npm/dict/npm.txt
          cspell:java/src/java-terms.txt
          cspell:latex/samples/sample-words.txt
          cspell:node/dict/node.txt
        check_extra_dictionaries: ''

  update:
    name: Update PR
    permissions:
      contents: write
      pull-requests: write
      actions: read
    runs-on: ubuntu-latest
    if: ${{
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '@check-spelling-bot apply')
      }}
    concurrency:
      group: spelling-update-${{ github.event.issue.number }}
      cancel-in-progress: false
    steps:
    - name: apply spelling updates
      uses: check-spelling/check-spelling@prerelease
      with:
        experimental_apply_changes_via_bot: 1
        checkout: true
        ssh_key: "${{ secrets.CHECK_SPELLING }}"
```

### Relevant log output

```sh
At the beginning of `act`'s output, it will spit out `Non-terminating error while running 'git clone': some refs were not updated` for each action repository for which there's a detached `HEAD` that it can't update:

jsoref@jsoref-mbp scimax % act -j spelling
WARN  ⚠ You are using Apple M-series chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠
WARN[0000] unable to get git repo: remote not found
[Check Spelling/Check Spelling] 🚀  Start image=catthehacker/ubuntu:act-latest
[Check Spelling/Check Spelling]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[Check Spelling/Check Spelling]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Check Spelling/Check Spelling]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/check-spelling/check-spelling' # ref=prerelease
[Check Spelling/Check Spelling] Non-terminating error while running 'git clone': some refs were not updated
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] ⭐ Run Pre check-spelling
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/checkout' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/check-spelling/actions-checkout' # ref=v3
[Check Spelling/Check Spelling] Non-terminating error while running 'git clone': some refs were not updated
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/check-spelling/checkout-merge' # ref=prerelease
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] ⭐ Run Pre checkout-merge
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ✅  Success - Pre checkout-merge
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/download-artifact' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/upload-artifact' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/actions/upload-artifact' # ref=v3
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   ☁  git clone 'https://github.com/github/codeql-action' # ref=v2
[Check Spelling/Check Spelling] Non-terminating error while running 'git clone': some refs were not updated
[Check Spelling/Check Spelling]   ✅  Success - Pre check-spelling
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] ⭐ Run Main check-spelling
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   🐳  docker cp src=/Users/jsoref/.cache/act/check-spelling-check-spelling@prerelease/ dst=/var/run/act/actions/check-spelling-check-spelling@prerelease/
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] ⭐ Run Main act-windows-shim
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/spelling-composite-0.sh] user= workdir=
[Check Spelling/Check Spelling]   ✅  Success - Main act-windows-shim
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] ⭐ Run Main shim-path
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling] unable to get git repo: remote not found
[Check Spelling/Check Spelling]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/spelling-composite-4.sh] user= workdir=
[Check Spelling/Check Spelling]   ✅  Success - Main shim-path
```

% cd ~/.cache/act/github-codeql-action-upload-sarif@v2
jsoref@jsoref-mbp github-codeql-action-upload-sarif@v2 % git ls-remote origin|grep HEAD
8ca5570701137b67af3d8ae3d6452f4cee6579da        HEAD
jsoref@jsoref-mbp github-codeql-action-upload-sarif@v2 % git ls-remote .|grep HEAD     
f31a31c052207cc13b328d6295c5b728bb49568c	HEAD
8ca5570701137b67af3d8ae3d6452f4cee6579da	refs/heads/HEAD
```

The workaround is to manually `for a in ~/.cache/act/*/ do; (cd "$a" && git reset --hard $(cat .git/refs/heads/HEAD); done`
```

### Additional information

This message appears in a number of tickets, but hasn't been characterized and I've been mostly ignoring it for a long time.
