### ISSUE TITLE
how to trigger a tag event locally 

### ISSUE THREAD

**Issue by jonyhy96** [nektos/act#179]
act version 0.2.7

workflow:
```yml
name: postgres action 

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-16.04
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: byzanteam/nitrogen-postgres
        registry: ${{ secrets.DOCKER_REGISTRY }}
        tag_with_ref: true
```

tag.json
```json
{
    "ref": "refs/tags/v0.0.1"
}

```

log:
```
DEBU[0000] Loading workflows from '/PATH/.github/workflows' 
DEBU[0000] Reading workflow '/PATH/.github/workflows/main.yml' 
DEBU[0000] Using detected workflow event: push          
DEBU[0000] Planning event: push                         
DEBU[0000] Reading event.json from /PATH/tag.json 
DEBU[0000] Loading slug from git directory '/PATH/.git' 
DEBU[0000] Found revision: 7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3 
DEBU[0000] Loading revision from git directory '/PATH/.git' 
DEBU[0000] Found revision: 7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3 
DEBU[0000] HEAD points to '7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3' 
DEBU[0000] HEAD matches refs/heads/master               
DEBU[0000] using github ref: refs/heads/master          
[postgres action/build-and-push] 🚀  Start image=node:12.6-stretch-slim
DEBU[0000] Loading slug from git directory '/PATH/.git' 
DEBU[0000] Found revision: 7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3 
DEBU[0000] Loading revision from git directory '/PATH/.git' 
DEBU[0000] Found revision: 7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3 
DEBU[0000] HEAD points to '7c6d9e0bd6b4fcd2dfe32296e8298ae4c32ac2d3' 
DEBU[0000] HEAD matches refs/heads/master               
DEBU[0000] using github ref: refs/heads/master          
[postgres action/build-and-push]   🐳  docker pull node:12.6-stretch-slim
```

questions:

1. how to trigger a tag event locally?
2. Is there an example of this?

**Comment by mced** [comment]
@jonyhy96 Did you try to tag your code ?

**Comment by jonyhy96** [comment]
> @jonyhy96 Did you try to tag your code ?

I tried tag locally and check out to the tag with:
```bash
git tag -a v0.0.1 -m "something"
git checkout tags/v0.0.1 -b v0.0.1
```
But act still has the same log as above.

**Comment by mced** [comment]
A workaround I personally use is to trigger an action (locally and on ga) on tags is to use a conditional like this but that won't work anymore on master pushes only for tags...

```yaml
jobs:
  build-and-push:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-16.04
    ...
```
