### ISSUE TITLE
Display the contents of the script and other logging additions

### ISSUE THREAD

**Issue by andrew-pickin-epi** [nektos/act#1796]
### Act version

0.2.45-10

### Feature description

Consider the following action
```
name: 'Generate Tag Action'
description: "Generate an image tag using a Makefile"
outputs:
  tag:
    description: "Tag used by docker"
    value: ${{ steps.generatetag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - name: "Generate Tag"
      id: generatetag
      shell: bash
      run: |
        tag=$( make tag )
        echo TAG: ${tag}
        echo "tag=${tag}" >> $GITHUB_OUTPUT
```

and its invocation
```
    - name: "Get image tag"
      id: gittag
      uses: epimorphics/github-actions/generate-tag@v12
```

The resulting log is:
```
[publish/Bulid & Publish Docker Image/Build & Upload Docker Image to ECR] ⭐ Run Main Generate Tag
[publish/Bulid & Publish Docker Image/Build & Upload Docker Image to ECR]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/gittag-composite-generatetag.sh] user= workdir=
| TAG: 1.1.3-0aca5ed
[publish/Bulid & Publish Docker Image/Build & Upload Docker Image to ECR]   ✅  Success - Main Generate Tag
```
Whereas in Github we get:
```
Get image tag
⏷ Run epimorphics/github-actions/generate-tag@v1[2]
⏷ Run tag=$( make tag )
    tag=$( make tag )
    echo TAG: ${tag}
    echo "tag=${tag}" >> $GITHUB_OUTPUT
    shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
TAG: 1.6.1_afd4ccb_0000005
```

It would be nice to have logged the following:
- The name of the top invocation name to match github.
- The exact version of the action being invoked.
- The contents of the contents of the script.

Additionally the `*DRYRUN*` label is invisible on white background terminals.
