### ISSUE TITLE
unable to start workflow under WSL2 as a non root user

### ISSUE THREAD

**Issue by zlatko-ms** [nektos/act#1809]
### Bug report info

```plain text
act version:            0.2.45
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/zlatko/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:full-latest
		-P ubuntu-latest=catthehacker/ubuntu:full-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:full-18.04
Build info:
	Go version:            go1.18.10
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.45 -X main.commit=f1df2ca5d6b315935cf9bb0d2a989175adf4e894 -X main.date=2023-05-01T02:18:49Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         f1df2ca5d6b315935cf9bb0d2a989175adf4e894
		vcs.time:             2023-05-01T02:18:34Z
		vcs.modified:         false
Docker Engine:
	Engine version:        23.0.5
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             5.15.90.1-microsoft-standard-WSL2
	OS CPU:                8
	OS memory:             15913 MB
	Security options:
		name=seccomp,profile=builtin
```

### Command used with act

```sh
act -j build-example
```

### Describe issue

I use WSL2 as my main dev environment and was hoping to use act within my dev stack.

As a non root user I'm able to list the jobs ( act -l ) but running a job raises the following docker pull error : 

```console
issue>act -j build-example
[build python application/build] 🚀  Start image=catthehacker/ubuntu:full-20.04
[build python application/build]   🐳  docker pull image=catthehacker/ubuntu:full-20.04 platform= username= forcePull=true
Error: Error response from daemon: Head "https://registry-1.docker.io/v2/catthehacker/ubuntu/manifests/full-20.04": unauthorized: incorrect username or password
```

Please note that : 
* The image is already pulled and showed as available via docker images
* I'm able to pull docker images as a non root user  in other contexts
* it is possible to run the job as root ( via sudo -s ), but this is hardly acceptable 

Is there a way to use act in a "safe" manner, i.e as a non root user on WSL2 ? 

### Workflow content

```yml
name: build python application

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  build-example:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install binaries
      run: sudo apt-get install -y dos2unix
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install Python Modules
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
```

### Relevant log output

```sh
[build python application/build-example] [DEBUG] evaluating expression 'success()'
[build python application/build-example] [DEBUG] expression 'success()' evaluated to 'true'
[build python application/build-example] 🚀  Start image=catthehacker/ubuntu:full-20.04
[build python application/build-example]   🐳  docker pull image=catthehacker/ubuntu:full-20.04 platform= username= forcePull=true
[build python application/build-example] [DEBUG]   🐳  docker pull catthehacker/ubuntu:full-20.04
[build python application/build-example] [DEBUG] pulling image 'docker.io/catthehacker/ubuntu:full-20.04' ()
liner/.secrets"
time="2023-05-16T17:22:54+02:00" level=debug msg="Evaluated matrix inclusions: map[]"
time="2023-05-16T17:22:54+02:00" level=debug msg="Loading workflows from '/mnt/c/Users/whoever/somepath/somegituser/someproject/main/someproject/.github/workflows'"
time="2023-05-16T17:22:54+02:00" level=debug msg="Loading workflows recursively"
time="2023-05-16T17:22:54+02:00" level=debug msg="Found workflow 'build-example.yaml' in '/mnt/c/Users/whoever/somepath/somegituser/someproject/main/someproject/.github/workflows/build-example.yaml'"
time="2023-05-16T17:22:54+02:00" level=debug msg="Found workflow 'python-app.yml' in '/mnt/c/Users/whoever/somepath/somegituser/someproject/main/someproject/.github/workflows/python-app.yml'"
time="2023-05-16T17:22:54+02:00" level=debug msg="Reading workflow '/mnt/c/Users/whoever/somepath/somegituser/someproject/main/someproject/.github/workflows/build-example.yaml'"
time="2023-05-16T17:22:54+02:00" level=debug msg="Reading workflow '/mnt/c/Users/whoever/somepath/somegituser/someproject/main/someproject/.github/workflows/python-app.yml'"
time="2023-05-16T17:22:54+02:00" level=debug msg="Preparing plan with a job: build-example"
time="2023-05-16T17:22:54+02:00" level=debug msg="Using default workflow event: push"
time="2023-05-16T17:22:54+02:00" level=debug msg="Planning job: build-example"
time="2023-05-16T17:22:54+02:00" level=debug msg="gc: 2023-05-16 17:22:54.467739378 +0200 CEST m=+0.040604307" module=artifactcache
time="2023-05-16T17:22:54+02:00" level=debug msg="Final matrix after applying user inclusions '[map[]]'"
time="2023-05-16T17:22:54+02:00" level=debug msg="Loading revision from git directory"
time="2023-05-16T17:22:54+02:00" level=debug msg="Found revision: c7222237793f4d8f25e04d3df179daef20047651"
time="2023-05-16T17:22:54+02:00" level=debug msg="HEAD points to 'c7222237793f4d8f25e04d3df179daef20047651'"
time="2023-05-16T17:22:54+02:00" level=debug msg="using github ref: refs/heads/main"
time="2023-05-16T17:22:54+02:00" level=debug msg="Found revision: c7222237793f4d8f25e04d3df179daef20047651"
time="2023-05-16T17:22:55+02:00" level=debug msg="Saving notices etag=59e5c2f6-1a9a-4f67-9ba1-ff23a99d275a"
time="2023-05-16T17:22:55+02:00" level=debug msg="No new notices"
Error: Error response from daemon: Head "https://registry-1.docker.io/v2/catthehacker/ubuntu/manifests/full-20.04": unauthorized: incorrect username or password
```
