### ISSUE TITLE
not support bytebase github action

### ISSUE THREAD

**Issue by KaimingWan** [nektos/act#1820]
### Bug report info

```plain text
act version:            0.2.45
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
        $HOME/.docker/run/docker.sock
Config files:           
        /Users/wanshao/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.20.3
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.45
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        23.0.5
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.15.49-linuxkit
        OS CPU:                4
        OS memory:             7851 MB
        Security options:
                name=seccomp,profile=builtin
                name=cgroupns
```

### Command used with act

```sh
act -j sql-review --container-architecture linux/amd64 -s GITHUB_TOKEN=xxx
```

### Describe issue

act can't execute bytebase sql-review action successfully

### Workflow content

```yml
on: push

jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - uses: actions/checkout@v3
      - name: Check SQL
        # You can change it to a specific version like bytebase/sql-review-action@0.0.4
        # We suggest using the latest version through the tag. Check it at https://github.com/Bytebase/sql-review-action/tags
        uses: bytebase/sql-review-action@main
        with:
          override-file-path: ./style/database/sql-review-rule.yml
          database-type: MYSQL
```

### Relevant log output

```sh
Failed running message: [sql-review.yml/SQL Review] 🚀  Start image=catthehacker/ubuntu:act-latest
[sql-review.yml/SQL Review]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform=linux/amd64 username= forcePull=true
[sql-review.yml/SQL Review]   🐳  docker create image=catthehacker/ubuntu:act-latest platform=linux/amd64 entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[sql-review.yml/SQL Review]   🐳  docker run image=catthehacker/ubuntu:act-latest platform=linux/amd64 entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[sql-review.yml/SQL Review]   ☁  git clone 'https://github.com/bytebase/sql-review-action' # ref=main
[sql-review.yml/SQL Review] ⭐ Run Pre Check SQL
[sql-review.yml/SQL Review]   ☁  git clone 'https://github.com/umani/changed-files' # ref=v3.3.0
[sql-review.yml/SQL Review]   ✅  Success - Pre Check SQL
[sql-review.yml/SQL Review] ⭐ Run Main actions/checkout@v3
[sql-review.yml/SQL Review]   🐳  docker cp src=/Users/wanshao/projects/automq/automqbox/. dst=/Users/wanshao/projects/automq/automqbox
[sql-review.yml/SQL Review]   ✅  Success - Main actions/checkout@v3
[sql-review.yml/SQL Review] ⭐ Run Main Check SQL
[sql-review.yml/SQL Review]   🐳  docker cp src=/Users/wanshao/.cache/act/bytebase-sql-review-action@main/ dst=/var/run/act/actions/bytebase-sql-review-action@main/
[sql-review.yml/SQL Review] ⭐ Run Main Get changed files
[sql-review.yml/SQL Review]   🐳  docker cp src=/Users/wanshao/.cache/act/umani-changed-files@v3.3.0/ dst=/var/run/act/actions/umani-changed-files@v3.3.0/
[sql-review.yml/SQL Review]   🐳  docker exec cmd=[node /var/run/act/actions/umani-changed-files@v3.3.0/dist/index.js] user= workdir=
[sql-review.yml/SQL Review]   ❗  ::error::Could not get pull request from context, exiting
[sql-review.yml/SQL Review]   ❌  Failure - Main Get changed files
[sql-review.yml/SQL Review] exitcode '1': failure
[sql-review.yml/SQL Review]   ❌  Failure - Main Check SQL
[sql-review.yml/SQL Review] exitcode '1': failure
[sql-review.yml/SQL Review] ⭐ Run Post Check SQL
[sql-review.yml/SQL Review]   🐳  docker cp src=/Users/wanshao/.cache/act/bytebase-sql-review-action@main/ dst=/var/run/act/actions/bytebase-sql-review-action@main/
[sql-review.yml/SQL Review]   ✅  Success - Post Check SQL
[sql-review.yml/SQL Review] 🏁  Job failed
```
