### ISSUE TITLE
line 1: unexpected character "<" in variable name

### ISSUE THREAD

**Issue by Set27** [nektos/act#1846]
### Bug report info

```plain text
act version:            0.2.46
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 4
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:
	/home/comm1ted/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.18.10
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:
	Build settings:
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.46 -X main.commit=b0d0cec71f2240fc629dcaa1889ed8c4ad52beb9 -X main.date=2023-06-01T02:39:24Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         b0d0cec71f2240fc629dcaa1889ed8c4ad52beb9
		vcs.time:             2023-06-01T02:39:05Z
		vcs.modified:         false
Docker Engine:
	Engine version:        20.10.21
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 22.04.2 LTS
	OS type:               linux
	OS version:            22.04
	OS arch:               x86_64
	OS kernel:             5.19.0-43-generic
	OS CPU:                4
	OS memory:             15948 MB
	Security options:
		name=apparmor
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act
act

### Describe issue

when I try to run act i having issue. When I run demo "github-actions-demo" it work well

### Link to GitHub repository

https://github.com/SchoolOfElvish/codeboard

### Workflow content

```yml
on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to get variables from"
        required: true
        type: string
      version:
        description: "The version to use for the build"
        required: true
        type: string
    secrets:
      vps-password:
        description: "Password of user from VPS server"
        required: true
      vps-user:
        description: "Username from VPS server"
        required: true

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-frontend:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ vars.FRONTEND_IMAGE_REPOSITORY }}:${{ inputs.version }}, ${{ vars.FRONTEND_IMAGE_REPOSITORY }}:latest
    outputs:
      image-tag: ${{ env.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Fetch secrets from tawbar
        run: |
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_FRONTEND_PROJECT_ID }}/production -H 'Authorization: ${{ secrets.TAWBAR_FRONTEND_API_KEY }}' -o ./frontend/.env
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/production -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./backend/.env
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/production/frontend.Dockerfile
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PUBLIC_BACKEND_URL_CLIENT=${{vars.PUBLIC_BACKEND_URL_CLIENT}}
            PUBLIC_BACKEND_URL_SSR=${{vars.PUBLIC_BACKEND_URL_SSR}}

  build-backend:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ vars.BACKEND_IMAGE_REPOSITORY }}:${{ inputs.version }}, ${{ vars.BACKEND_IMAGE_REPOSITORY }}:latest
    outputs:
      image-tag: ${{ env.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Fetch secrets from tawbar
        run: |
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_FRONTEND_PROJECT_ID }}/production -H 'Authorization: ${{ secrets.TAWBAR_FRONTEND_API_KEY }}' -o ./frontend/.env
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/production -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./backend/.env
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/production/backend.Dockerfile
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: [build-frontend, build-backend]
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.vps-user }}
          password: ${{ secrets.vps-password }}
          script: |
            cd ~/SchoolOfElvish/codeboard
            docker login https://ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose -f production.yml pull
            docker compose -f production.yml up -d
```

```
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch secrets from tawbar
        run: |
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/test -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./backend/.env
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_FRONTEND_PROJECT_ID }}/test -H 'Authorization: ${{ secrets.TAWBAR_FRONTEND_API_KEY }}' -o ./frontend/.env

      - name: Build docker images
        run: docker compose build backend

      - name: Install gems
        run: bin/backend/bundle install

      - name: Run rubocop
        run: bin/backend/lint

      - name: Prepare database
        run: bin/backend/run "bundle exec rake db:prepare"

      - name: Run tests
        run: bin/backend/test

  validate-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch secrets from tawbar
        run: |
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/test -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./backend/.env
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_FRONTEND_PROJECT_ID }}/test -H 'Authorization: ${{ secrets.TAWBAR_FRONTEND_API_KEY }}' -o ./frontend/.env

      - name: Build docker images
        run: docker compose build --build-arg UID=$UID frontend

      - name: Install dependencies
        run: bin/frontend/yarn install

      - name: Build vite
        run: bin/frontend/yarn build

      - name: Run svelte-check
        run: bin/frontend/check

      - name: Run linter
        run: bin/frontend/lint
```

### Relevant log output

it's too long (github denied to apply it) here is pastebin link
[https://pastebin.com/0QSesq99](https://pastebin.com/0QSesq99)

### Additional information

output of act
```
act
[CI/validate-backend ] 🚀  Start image=catthehacker/ubuntu:act-latest
[CI/validate-frontend] 🚀  Start image=catthehacker/ubuntu:act-latest
[CI/validate-frontend]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[CI/validate-backend ]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[CI/validate-backend ]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[CI/validate-frontend]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[CI/validate-backend ]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[CI/validate-frontend]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[CI/validate-frontend] ⭐ Run Main actions/checkout@v2
[CI/validate-backend ] ⭐ Run Main actions/checkout@v2
[CI/validate-frontend]   🐳  docker cp src=/home/comm1ted/code/codeboard/. dst=/home/comm1ted/code/codeboard
[CI/validate-backend ]   🐳  docker cp src=/home/comm1ted/code/codeboard/. dst=/home/comm1ted/code/codeboard
[CI/validate-backend ]   ✅  Success - Main actions/checkout@v2
[CI/validate-frontend]   ✅  Success - Main actions/checkout@v2
[CI/validate-backend ] ⭐ Run Main Fetch secrets from tawbar
[CI/validate-frontend] ⭐ Run Main Fetch secrets from tawbar
[CI/validate-backend ]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
[CI/validate-frontend]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
|                                  Dload  Upload   Total   Spent    Left  Speed
|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
|                                  Dload  Upload   Total   Spent    Left  Speed
100    52  100    52    0     0    256      0 --:--:-- --:--:-- --:--:--   257
|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
|                                  Dload  Upload   Total   Spent    Left  Speed
100    52  100    52    0     0    286      0 --:--:-- --:--:-- --:--:--   287
|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
|                                  Dload  Upload   Total   Spent    Left  Speed
100    52  100    52    0     0    254      0 --:--:-- --:--:-- --:--:--   254
[CI/validate-frontend]   ✅  Success - Main Fetch secrets from tawbar
100    52  100    52    0     0    224      0 --:--:-- --:--:-- --:--:--   225
[CI/validate-backend ]   ✅  Success - Main Fetch secrets from tawbar
[CI/validate-backend ] ⭐ Run Main Build docker images
[CI/validate-frontend] ⭐ Run Main Build docker images
[CI/validate-backend ]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=
[CI/validate-frontend]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=
| line 1: unexpected character "<" in variable name
| line 1: unexpected character "<" in variable name
[CI/validate-frontend]   ❌  Failure - Main Build docker images
[CI/validate-backend ]   ❌  Failure - Main Build docker images
[CI/validate-backend ] exitcode '15': failure
[CI/validate-frontend] exitcode '15': failure
[CI/validate-backend ] 🏁  Job failed
[CI/validate-frontend] 🏁  Job failed
Error: Job 'validate-backend' failed
```
