### ISSUE TITLE
act tags is not sending a tag?

### ISSUE THREAD

**Issue by Lusitaniae** [nektos/act#1860]
### Bug report info

```plain text
bin/act tags --bug-report
act version:            0.2.46
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/i/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.18.10
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.46 -X main.commit=b0d0cec71f2240fc629dcaa1889ed8c4ad52beb9 -X main.date=2023-06-01T02:39:24Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         b0d0cec71f2240fc629dcaa1889ed8c4ad52beb9
		vcs.time:             2023-06-01T02:39:05Z
		vcs.modified:         false
Docker Engine:
	Engine version:        20.10.14
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 22.04.2 LTS
	OS type:               linux
	OS version:            22.04
	OS arch:               x86_64
	OS kernel:             6.1.0-1013-oem
	OS CPU:                12
	OS memory:             15351 MB
	Security options:
		name=apparmor
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
bin/act tags
```

### Describe issue

I have a task as below:

```

    - name: Publish to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          bin-file
```

but when I run `act tags -v` I see

```
[main/build] [DEBUG] Found revision: 58b4d341cac05a572ccc0a76e27589e6da14c433
[main/build] [DEBUG] HEAD points to '58b4d341cac05a572ccc0a76e27589e6da14c433'
[main/build] [DEBUG] using github ref: refs/heads/feature-branch-name
[main/build] [DEBUG] Found revision: 58b4d341cac05a572ccc0a76e27589e6da14c433

```

Doesn't seem like the expected behaviour?

I'd expect it to send some random value as `refs/tags/`? 

### Workflow content

```yml
name: main

on: [tags, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Publish to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          bin-file
```

### Relevant log output

```sh
[main/build] [DEBUG] Found revision: 58b4d341cac05a572ccc0a76e27589e6da14c433
[main/build] [DEBUG] HEAD points to '58b4d341cac05a572ccc0a76e27589e6da14c433'
[main/build] [DEBUG] using github ref: refs/heads/feature-branch-name
[main/build] [DEBUG] Found revision: 58b4d341cac05a572ccc0a76e27589e6da14c433
```
