### ISSUE TITLE
::error:: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by merlinpaypal** [nektos/act#1878]
### Bug report info

```plain text
act version:            0.2.46
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
        $HOME/.docker/run/docker.sock
Config files:           
        /Users/mepatterson/.actrc:
                --container-architecture linux/amd64
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.20.4
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.46
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        24.0.2
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.15.49-linuxkit-pr
        OS CPU:                5
        OS memory:             7851 MB
        Security options:
                name=seccomp,profile=builtin
                name=cgroupns
```

### Command used with act

```sh
act -j lintAndUnit
```

### Describe issue

Erroring out with `::error::self signed certificate in certificate chain` on a fairly simple step of `actions/setup-node@v3`.

I've turned off any VPN that I was using and I still get this same issue. I also disabled setting `NODE_EXTRA_CA_CERTS`. Though I wouldn't expect that to affect this runner either.

### Link to GitHub repository

https://github.com/paypal/paypal-messaging-components/blob/develop/.github/workflows/core.yml

### Workflow content

```yml
name: Lint, Unit, Non-snapshot tests
on:
    # allow for manual triggers
    workflow_dispatch: {}
    workflow_call: {}
    push:
        branches:
            - develop
    pull_request: {}

jobs:
    lintAndUnit:
        name: Lint and Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Lint
              run: npm run lint

            - name: Unit Tests
              run: npm run test

    functionalNonSnapshot:
        name: Functional Non-Snapshot Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run server
              run: ./.github/scripts/runServer.sh

            - name: Functional Non-Snapshot Tests
              run: npm run test:func:nosnaps
```

### Relevant log output

```sh
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests] 🚀  Start image=catthehacker/ubuntu:act-latest
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform=linux/amd64 username= forcePull=true
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   🐳  docker create image=catthehacker/ubuntu:act-latest platform=linux/amd64 entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   🐳  docker run image=catthehacker/ubuntu:act-latest platform=linux/amd64 entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v3
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   ☁  git clone 'https://github.com/bahmutov/npm-install' # ref=v1
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests] ⭐ Run Main Checkout repo
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   🐳  docker cp src=/Users/mepatterson/code/messaging-components/. dst=/Users/mepatterson/code/messaging-components
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   ✅  Success - Main Checkout repo
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests] ⭐ Run Main Setup node
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   🐳  docker cp src=/Users/mepatterson/.cache/act/actions-setup-node@v3/ dst=/var/run/act/actions/actions-setup-node@v3/
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-node@v3/dist/setup/index.js] user= workdir=
| Resolved .nvmrc as 16
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::isExplicit: 
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::explicit? false
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::isExplicit: 16.20.0
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::explicit? true
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::evaluating 0 versions
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::match not found
| Attempting to download 16...
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::No manifest cached
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::Getting manifest from actions/node-versions@main
| self signed certificate in certificate chain
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   💬  ::debug::Error: self signed certificate in certificate chain%0A    at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)%0A    at TLSSocket.emit (node:events:513:28)%0A    at TLSSocket._finishInit (node:_tls_wrap:953:8)%0A    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12)
| Falling back to download directly from Node
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   ❗  ::error::self signed certificate in certificate chain
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests]   ❌  Failure - Main Setup node
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests] exitcode '1': failure
[Lint, Unit, Non-snapshot tests/Lint and Unit Tests] 🏁  Job failed
Error: Job 'Lint and Unit Tests' failed
```

### Additional information

.actrc file

```
--container-architecture linux/amd64
-P ubuntu-latest=catthehacker/ubuntu:act-latest
-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
```
