### ISSUE TITLE
Windows-latest with act error with ComSpec path

### ISSUE THREAD

**Issue by hirseboy** [nektos/act#1891]
### Bug report info

```plain text
act version:            0.2.46
GOOS:                   windows
GOARCH:                 amd64
NumCPU:                 20
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        \\.\pipe\docker_engine(broken)
Config files:
        C:\Users\Stephan Hirth\.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.18.10
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.46 -X main.commit=b0d0cec71f2240fc629dcaa1889ed8c4ad52beb9 -X main.date=2023-06-01T02:39:24Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 windows
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         b0d0cec71f2240fc629dcaa1889ed8c4ad52beb9
                vcs.time:             2023-06-01T02:39:05Z
                vcs.modified:         false
Docker Engine:
        Engine version:        24.0.2
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.15.79.1-microsoft-standard-WSL2
        OS CPU:                20
        OS memory:             15844 MB
        Security options:
                name=seccomp,profile=builtin
```

### Command used with act

```sh
act -W .\.github\workflows\cmake_windows.yml -P windows-latest=-self-hosted
```

### Describe issue

ComSpec path was not found

### Link to GitHub repository

https://github.com/hirseboy/DWD-Weather-Data-Converter/

### Workflow content

```yml
name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "5.15.12"
  VERSION: 0.9
  LONG_VERSION: 0.9.9
  CURRENT_YEAR: 2023
  FILE_BASENAME: DWDWeatherDataConverter_Win
  INNOSETUP_VERSION: "6.2.0"


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create Directory
      run: mkdir ${{github.workspace}}\bin\release_x64
      shell: cmd
    
    - name: Download and Install Inno Setup
      run: |
        $url = "files.jrsoftware.org/is/6/innosetup-6.2.0.exe"
        $output = "${{github.workspace}}\innosetup-6.2.0-unicode.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process $output -ArgumentList "/VERYSILENT" -NoNewWindow -Wait
        
    - name: Prepare Inno Setup Script
      run: |
        # Replace placeholders in .iss.in file here. 
        # This is just an example, adjust it to your needs.
        (Get-Content ${{github.workspace}}\build\installer\deploy64.iss.in) `
        | Set-Content ${{github.workspace}}\build\installer\deploy64.iss
      shell: powershell
    
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
    
        
    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      working-directory: ${{github.workspace}}\build\cmake
      run: cmake ${{github.workspace}}\build\cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build
      working-directory: ${{github.workspace}}\build\cmake
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}\build\cmake
      run: ctest -C ${{env.BUILD_TYPE}} 
      
    - name: Copy Executable
      run: |
        "xcopy /Y ${{github.workspace}}\build\cmake\DWDWeatherDataConverter\release\DWDWeatherDataConverter.exe ${{github.workspace}}\bin\release_x64"
      shell: cmd

    - name: Build Installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "${{github.workspace}}\build\installer\deploy64.iss"
      shell: cmd
```

### Relevant log output

```sh
[CMake/build]   ☁  git clone 'https://github.com/ilammy/msvc-dev-cmd' # ref=v1
[CMake/build]   ☁  git clone 'https://github.com/jurplel/install-qt-action' # ref=v3
[CMake/build] ⭐ Run Pre Install Qt
[CMake/build]   ☁  git clone 'https://github.com/actions/setup-python' # ref=v4
[CMake/build]   ☁  git clone 'https://github.com/jurplel/install-qt-action' # ref=v3
[CMake/build]   ✅  Success - Pre Install Qt
[CMake/build] ⭐ Run Main actions/checkout@v3
[CMake/build]   ✅  Success - Main actions/checkout@v3
[CMake/build] ⭐ Run Main Create Directory
| Cannot find: %ComSpec% in PATH
[CMake/build]   ❌  Failure - Main Create Directory
[CMake/build] Cannot find: %ComSpec% in PATH
[CMake/build] 🏁  Job failed
Error: Job 'build' failed
```

### Additional information

-
