### ISSUE TITLE
'Error response from daemon: cannot share the host's network namespace when user namespaces are enabled'

### ISSUE THREAD

**Issue by jsuto** [nektos/act#1899]
### Bug report info

```plain text
act version:            0.2.46
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 2
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/sj/.actrc:
		-P ubuntu-latest=node:16-buster-slim
		-P ubuntu-22.04=node:16-bullseye-slim
		-P ubuntu-20.04=node:16-buster-slim
		-P ubuntu-18.04=node:16-buster-slim
Build info:
	Go version:            go1.18.10
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.46 -X main.commit=b0d0cec71f2240fc629dcaa1889ed8c4ad52beb9 -X main.date=2023-06-01T02:39:24Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         b0d0cec71f2240fc629dcaa1889ed8c4ad52beb9
		vcs.time:             2023-06-01T02:39:05Z
		vcs.modified:         false
Docker Engine:
	Engine version:        20.10.18
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 22.04.2 LTS
	OS type:               linux
	OS version:            22.04
	OS arch:               x86_64
	OS kernel:             5.15.0-76-generic
	OS CPU:                2
	OS memory:             3815 MB
	Security options:
		name=apparmor
		name=seccomp,profile=default
		name=userns
		name=cgroupns
```

### Command used with act

```sh
act
```

### Describe issue

When I run act, then I get the following output:

```
[Python package/build] 🚀  Start image=node:16-buster-slim
[Python package/build]   🐳  docker pull image=node:16-buster-slim platform= username= forcePull=true
[Python package/build] using DockerAuthConfig authentication for docker pull
[Python package/build]   🐳  docker create image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
Error: failed to create container: 'Error response from daemon: cannot share the host's network namespace when user namespaces are enabled'
```

### Workflow content

```yml
name: Python package

on: [push]

env:
  DAY_OF_WEEK: Monday
  FRUITS: 'AAA=("apple" "orange" "banana")'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Some variables test
        run: |
          echo "day of week=${DAY_OF_WEEK}"
          eval "$FRUITS"
          echo "All my fruits: ${AAA[@]}"
          echo "1st fruit=${AAA[0]}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      - name: Run unit tests
        run: |
          cd app; python3 -m unittest -f test.py
```

### Relevant log output

```sh
DEBU[0000] Loading environment from /home/sj/devel/github-actions-demo/.env 
DEBU[0000] Loading action inputs from /home/sj/devel/github-actions-demo/.input 
DEBU[0000] Loading secrets from /home/sj/devel/github-actions-demo/.secrets 
DEBU[0000] Evaluated matrix inclusions: map[]           
DEBU[0000] Loading workflows from '/home/sj/devel/github-actions-demo/.github/workflows' 
DEBU[0000] Loading workflows recursively                
DEBU[0000] Found workflow 'github-actions-build.yml' in '/home/sj/devel/github-actions-demo/.github/workflows/github-actions-build.yml' 
DEBU[0000] Found workflow 'github-actions-demo.yml' in '/home/sj/devel/github-actions-demo/.github/workflows/github-actions-demo.yml' 
DEBU[0000] Reading workflow '/home/sj/devel/github-actions-demo/.github/workflows/github-actions-build.yml' 
DEBU[0000] Reading workflow '/home/sj/devel/github-actions-demo/.github/workflows/github-actions-demo.yml' 
DEBU[0000] Preparing plan with all jobs                 
DEBU[0000] Using default workflow event: push           
DEBU[0000] Planning jobs for event: push                
DEBU[0000] gc: 2023-07-09 13:41:21.758245463 +0200 CEST m=+0.013841151  module=artifactcache
DEBU[0000] Final matrix after applying user inclusions '[map[]]' 
DEBU[0000] Conditional GET for notices etag=da0af10a-6865-4d4f-a356-628179e18d04 
DEBU[0000] Loading revision from git directory          
DEBU[0000] Found revision: 6070a9be04d18ce06f5de8299fdbef984b2cde89 
DEBU[0000] HEAD points to '6070a9be04d18ce06f5de8299fdbef984b2cde89' 
DEBU[0000] using github ref: refs/heads/master          
DEBU[0000] Found revision: 6070a9be04d18ce06f5de8299fdbef984b2cde89 
[Python package/build] [DEBUG] evaluating expression 'success()'
[Python package/build] [DEBUG] expression 'success()' evaluated to 'true'
[Python package/build] 🚀  Start image=node:16-buster-slim
[Python package/build]   🐳  docker pull image=node:16-buster-slim platform= username= forcePull=true
[Python package/build] [DEBUG]   🐳  docker pull node:16-buster-slim
[Python package/build] [DEBUG] pulling image 'docker.io/library/node:16-buster-slim' ()
[Python package/build] using DockerAuthConfig authentication for docker pull
DEBU[0000] Saving notices etag=da0af10a-6865-4d4f-a356-628179e18d04 
DEBU[0000] No new notices                               
[Python package/build] [DEBUG] Pulling from library/node :: 16-buster-slim
[Python package/build] [DEBUG] Digest: sha256:f9b352a2b524dd1c56c65e0cb365f7517093a7d3298f41a8e85dd034a6f33474 :: 
[Python package/build] [DEBUG] Status: Image is up to date for node:16-buster-slim :: 
[Python package/build]   🐳  docker create image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Python package/build] [DEBUG] Common container.Config ==> &{Hostname: Domainname: User: AttachStdin:false AttachStdout:false AttachStderr:false ExposedPorts:map[] Tty:true OpenStdin:false StdinOnce:false Env:[RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_ARCH=X64 RUNNER_TEMP=/tmp LANG=C.UTF-8] Cmd:[] Healthcheck:<nil> ArgsEscaped:false Image:node:16-buster-slim Volumes:map[] WorkingDir:/home/sj/devel/github-actions-demo Entrypoint:[] NetworkDisabled:false MacAddress: OnBuild:[] Labels:map[] StopSignal: StopTimeout:<nil> Shell:[]}
[Python package/build] [DEBUG] Common container.HostConfig ==> &{Binds:[/var/run/docker.sock:/var/run/docker.sock] ContainerIDFile: LogConfig:{Type: Config:map[]} NetworkMode:host PortBindings:map[] RestartPolicy:{Name: MaximumRetryCount:0} AutoRemove:false VolumeDriver: VolumesFrom:[] ConsoleSize:[0 0] CapAdd:[] CapDrop:[] CgroupnsMode: DNS:[] DNSOptions:[] DNSSearch:[] ExtraHosts:[] GroupAdd:[] IpcMode: Cgroup: Links:[] OomScoreAdj:0 PidMode: Privileged:false PublishAllPorts:false ReadonlyRootfs:false SecurityOpt:[] StorageOpt:map[] Tmpfs:map[] UTSMode: UsernsMode: ShmSize:0 Sysctls:map[] Runtime: Isolation: Resources:{CPUShares:0 Memory:0 NanoCPUs:0 CgroupParent: BlkioWeight:0 BlkioWeightDevice:[] BlkioDeviceReadBps:[] BlkioDeviceWriteBps:[] BlkioDeviceReadIOps:[] BlkioDeviceWriteIOps:[] CPUPeriod:0 CPUQuota:0 CPURealtimePeriod:0 CPURealtimeRuntime:0 CpusetCpus: CpusetMems: Devices:[] DeviceCgroupRules:[] DeviceRequests:[] KernelMemory:0 KernelMemoryTCP:0 MemoryReservation:0 MemorySwap:0 MemorySwappiness:<nil> OomKillDisable:<nil> PidsLimit:<nil> Ulimits:[] CPUCount:0 CPUPercent:0 IOMaximumIOps:0 IOMaximumBandwidth:0} Mounts:[{Type:volume Source:act-Python-package-build-8f9a08f8f46a1e7a9dbd8c238cbc4611e2d70f9b17622a900f16e35d2442f78f-env Target:/var/run/act ReadOnly:false Consistency: BindOptions:<nil> VolumeOptions:<nil> TmpfsOptions:<nil> ClusterOptions:<nil>} {Type:volume Source:act-Python-package-build-8f9a08f8f46a1e7a9dbd8c238cbc4611e2d70f9b17622a900f16e35d2442f78f Target:/home/sj/devel/github-actions-demo ReadOnly:false Consistency: BindOptions:<nil> VolumeOptions:<nil> TmpfsOptions:<nil> ClusterOptions:<nil>} {Type:volume Source:act-toolcache Target:/toolcache ReadOnly:false Consistency: BindOptions:<nil> VolumeOptions:<nil> TmpfsOptions:<nil> ClusterOptions:<nil>}] MaskedPaths:[] ReadonlyPaths:[] Init:<nil>}
Error: failed to create container: 'Error response from daemon: cannot share the host's network namespace when user namespaces are enabled'
```
