### ISSUE TITLE
The lack of a known_hosts  leads to hanging when checking authenticity of git host

### ISSUE THREAD

**Issue by seve** [nektos/act#191]
When running the following lines on a job I have:
```
steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
```

I receive the following output:
```
The authenticity of host 'github.com (140.82.113.3)' can't be established.
| RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
```

and then the process hangs, I believe because I can't answer the prompt that follows asking if I should trust the remote.
