### ISSUE TITLE
Interpolation not working for the Docker image name

### ISSUE THREAD

**Issue by 321zeno** [nektos/act#192]
Possibly related to https://github.com/nektos/act/issues/108:

Here's a sample of my workflow:
```yaml
jobs:
  build:
    strategy:
      matrix:
        container: [foo, bar]
    runs-on: ubuntu-latest
    name: ${{ matrix.container }}
    container: ${{ matrix.container }}
```
Using 0.2.7 outputs:
```
[testing/foo-2] 🧪  Matrix: map[variant:foo]
[testing/bar-1] 🧪  Matrix: map[variant:bar]
[testing/bar-1] 🚀  Start image=${{ matrix.variant }}
[testing/foo-2] 🚀  Start image=${{ matrix.variant }}
Error: invalid reference format
```
Using `-v`:
```
 🐳  docker pull ${{ matrix.container }}
pulling image 'docker.io/library/${{ matrix.container }}'
invalid reference format
```
It looks like the interpolation works for the `name` parameter but not for `container`
