### ISSUE TITLE
Change of behavior to pass inputs to manually triggered workflows

### ISSUE THREAD

**Issue by christinawongseequent** [nektos/act#1926]
### Act version

0.2.48

### Feature description

Since GitHub Action has an update of inputs context for both workflow_dispatch and workflow_call. Would you consider adopting the up-to-date GitHub Actions Context in ACT too? 

GitHub ref: https://github.blog/changelog/2022-06-10-github-actions-inputs-unified-across-manual-and-reusable-workflows/

Currently, we have to use a workaround ${{ github.event.inputs.act && github.event.inputs.inputA || inputs.inputA}} if we run locally in ACT, which is not ideal. 

ACT ref: https://github.com/nektos/act#pass-inputs-to-manually-triggered-workflows

**Comment by GuessWhoSamFoo** [comment]
@christinawongseequent Looking into the testcase https://github.com/nektos/act/blob/master/pkg/runner/testdata/workflow_dispatch/workflow_dispatch.yml, this is already supported unless I misunderstood the issue.

e.g. using a modified example from the readme
```
on:
  workflow_dispatch:
    inputs:
      NAME:
        description: "A random input name for the workflow"
        type: string
      SOME_VALUE:
        description: "Some other input to pass"
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Test with inputs
        run: |
          echo "Hello ${{ inputs.NAME }} and ${{ inputs.SOME_VALUE }}!"
```

gets as expected without the event payload:
```
$ act workflow_dispatch --input NAME=foo --input SOME_VALUE=bar
{"inputs":{"NAME":"foo","SOME_VALUE":"bar"}} test
[example.yml/Test] 🚀  Start image=ghcr.io/catthehacker/ubuntu:full-latest
[example.yml/Test]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:full-latest platform= username= forcePull=true
[example.yml/Test]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[example.yml/Test]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[example.yml/Test] ⭐ Run Main Test with inputs
[example.yml/Test]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/0] user= workdir=
| Hello foo and bar!
[example.yml/Test]   ✅  Success - Main Test with inputs
[example.yml/Test] 🏁  Job succeeded
sfoo@potato ~/act_examples (main)> act workflow_dispatch --input NAME=foo --input SOME_VALUE=bar    (base) 
[example.yml/Test] 🚀  Start image=ghcr.io/catthehacker/ubuntu:full-latest
[example.yml/Test]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:full-latest platform= username= forcePull=true
[example.yml/Test]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[example.yml/Test]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[example.yml/Test] ⭐ Run Main Test with inputs
[example.yml/Test]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/0] user= workdir=
| Hello foo and bar!
[example.yml/Test]   ✅  Success - Main Test with inputs
[example.yml/Test] 🏁  Job succeeded
```
