### ISSUE TITLE
skipping post step for 'Checkout Repo': no action model available

### ISSUE THREAD

**Issue by Drjacky** [nektos/act#1951]
### Bug report info

```plain text
act version:            0.2.49
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 12
Docker host:            unix:///Users/drjacky/.colima/default/docker.sock
Sockets found:
        /var/run/docker.sock
        $HOME/.colima/docker.sock
        $HOME/.docker/run/docker.sock
Config files:           
        /Users/drjacky/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.20.6
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.49
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        20.10.20
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Alpine Linux v3.16
        OS type:               linux
        OS version:            3.16.3
        OS arch:               aarch64
        OS kernel:             5.15.82-0-virt
        OS CPU:                2
        OS memory:             1976 MB
        Security options:
                name=seccomp,profile=default
```

### Command used with act

```sh
act --verbose
```

### Describe issue

cannot have a successful job run

### Link to GitHub repository

https://github.com/Drjacky/MVVMTemplate

### Workflow content

```yml
name: Pre Merge Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Cache Gradle Caches
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle-cache
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle-wrapper
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper
      - name: Run Gradle tasks
        run: ./gradlew build --continue
      - name: Stop Gradle
        run: ./gradlew --stop
```

### Relevant log output

```sh
> ...
[Pre Merge Checks/gradle-1         ] [DEBUG] executing remote job container: [node /var/run/act/actions/actions-setup-java@v3/dist/cleanup/index.js]
[Pre Merge Checks/gradle-1         ]   🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-java@v3/dist/cleanup/index.js] user= workdir=
[Pre Merge Checks/gradle-1         ] [DEBUG] Exec command '[node /var/run/act/actions/actions-setup-java@v3/dist/cleanup/index.js]'
[Pre Merge Checks/gradle-1         ] [DEBUG] Working directory '/Users/drjacky/Projectz/MVVMTemplate'
[Pre Merge Checks/gradle-1         ]   ✅  Success - Post set up JDK 17
[Pre Merge Checks/gradle-1         ] [DEBUG] skipping post step for 'Checkout Repo': no action model available
[Pre Merge Checks/gradle-1         ] 🏁  Job failed
[Pre Merge Checks/gradle-1         ] [DEBUG] Loading revision from git directory
[Pre Merge Checks/gradle-1         ] [DEBUG] Found revision: 6909b4982af3bf31ac1f210c5ae9c03ae5e1d005
...
```
