### ISSUE TITLE
dotnet cannot be installed

### ISSUE THREAD

**Issue by XmasApple** [nektos/act#1956]
### Bug report info

```plain text
act version:            0.2.49
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/user/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:full-latest
		-P ubuntu-latest=catthehacker/ubuntu:full-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:full-18.04
Build info:
	Go version:            go1.20.6
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -s -w -X main.version=0.2.49 -X main.commit=d5d854854651c151ecd914bb6e2e370e0057929a -X main.date=2023-08-01T02:21:56Z -X main.builtBy=goreleaser
		CGO_ENABLED:          0
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         d5d854854651c151ecd914bb6e2e370e0057929a
		vcs.time:             2023-08-01T02:21:38Z
		vcs.modified:         false
Docker Engine:
	Engine version:        24.0.5
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 22.04.3 LTS
	OS type:               linux
	OS version:            22.04
	OS arch:               x86_64
	OS kernel:             5.19.0-50-generic
	OS CPU:                12
	OS memory:             31694 MB
	Security options:
		name=apparmor
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
act pull_request
```

### Describe issue

```
[tests/unit-tests-1] 🚀  Start image=node:16-bullseye-slim
[tests/unit-tests-1]   🐳  docker pull image=node:16-bullseye-slim platform= username= forcePull=true
[tests/unit-tests-1]   🐳  docker create image=node:16-bullseye-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[tests/unit-tests-1]   🐳  docker run image=node:16-bullseye-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[tests/unit-tests-1]   ☁  git clone 'https://github.com/actions/setup-dotnet' # ref=v3
[tests/unit-tests-1] 🧪  Matrix: map[os:ubuntu-22.04]
[tests/unit-tests-1] ⭐ Run Main Checkout
[tests/unit-tests-1]   🐳  docker cp src=/home/user/src/project/. dst=/home/user/src/project
[tests/unit-tests-1]   ✅  Success - Main Checkout
[tests/unit-tests-1] ⭐ Run Main Setup dotnet
[tests/unit-tests-1]   🐳  docker cp src=/home/user/.cache/act/actions-setup-dotnet@v3/ dst=/var/run/act/actions/actions-setup-dotnet@v3/
[tests/unit-tests-1]   🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-dotnet@v3/dist/setup/index.js] user= workdir=
| [command]/run/act/actions/actions-setup-dotnet@v3/externals/install-dotnet.sh --channel 3.1
| dotnet_install: Error: curl (recommended) or wget are required to download dotnet. Install missing prerequisite to proceed.
[tests/unit-tests-1]   ❗  ::error::Failed to install dotnet, exit code: 1. dotnet_install: Error: curl (recommended) or wget are required to download dotnet. Install missing prerequisite to proceed.%0A
[tests/unit-tests-1]   ❌  Failure - Main Setup dotnet
[tests/unit-tests-1] exitcode '1': failure
[tests/unit-tests-1] 🏁  Job failed
```

### Workflow content

```yml
name: tests
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  unit-tests:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
      - name: Test
        run: | 
          cd src
          dotnet test
```

### Relevant log output

```sh
[tests/unit-tests-1] whale docker exec cmd=[node /var/run/act/actions/actions-setup-dotnet@v3/dist/setup/index.js] user= workdir=
| [command]/run/act/actions/actions-setup-dotnet@v3/externals/install-dotnet.sh --channel 3.1
| dotnet_install: Error: curl (recommended) or wget are required to download dotnet. Install missing prerequisite to proceed.
[tests/unit-tests-1] exclamation ::error::Failed to install dotnet, exit code: 1. dotnet_install: Error: curl (recommended) or wget are required to download dotnet. Install missing prerequisite to proceed.%0A
```
