### ISSUE TITLE
rustup not installed in ubuntu full-latest

### ISSUE THREAD

**Issue by budde25** [nektos/act#1960]
### Bug report info

```plain text
act version:            0.2.49
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 16
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:
	/Users/budd/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:full-latest
		-P ubuntu-20.04=catthehacker/ubuntu:full-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:full-18.04
Build info:
	Go version:            go1.20.6
	Module path:           command-line-arguments
	Main version:
	Main path:
	Main checksum:
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.49
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
Docker Engine:
	Engine version:        23.0.6
	Engine runtime:        runc
	Cgroup version:        1
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Alpine Linux v3.18
	OS type:               linux
	OS version:            3.18.0
	OS arch:               x86_64
	OS kernel:             6.1.32-0-virt
	OS CPU:                2
	OS memory:             5937 MB
	Security options:
		name=seccomp,profile=builtin
```

### Command used with act

```sh
act
```

### Describe issue

rustup should be installed on the full image 

### Workflow content

```yml
on:
  push:
    tags:
      - '*-?v[0-9]+*'

jobs:
  # Create the Github Release™ so the packages have something to be uploaded to
  create-release:
    runs-on: ubuntu-latest
    outputs:
      has-releases: ${{ steps.create-release.outputs.has-releases }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable --no-self-update && rustup default stable
```

### Relevant log output

```sh
[Release/create-release] 🚀  Start image=catthehacker/ubuntu:full-latest
[Release/create-release]   🐳  docker pull image=catthehacker/ubuntu:full-latest platform= username= forcePull=true
[Release/create-release]   🐳  docker create image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Release/create-release]   🐳  docker run image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Release/create-release] ⭐ Run Main actions/checkout@v3
[Release/create-release]   🐳  docker cp src=/Users/budd/Code/rust-stuff/. dst=/Users/budd/Code/rust-stuff
[Release/create-release]   ✅  Success - Main actions/checkout@v3
[Release/create-release] ⭐ Run Main Install Rust
[Release/create-release]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
| /var/run/act/workflow/1: line 2: rustup: command not found
[Release/create-release]   ❌  Failure - Main Install Rust
[Release/create-release] exitcode '127': command not found, please refer to https://github.com/nektos/act/issues/107 for more information
[Release/create-release] 🏁  Job failed
Error: Job 'create-release' failed
```
