### ISSUE TITLE
Error con rutas que contienen espacios en act

### ISSUE THREAD

**Issue by danielandeta** [nektos/act#1963]
### Bug report info

```plain text
? Please choose the default image you want to use with act:

  - Large size image: +20GB Docker image, includes almost all tools used on GitHub Actions (IMPORTANT: currently only ubuntu-18.04 platform is available)
  - Medium size image: ~500MB, includes only necessary tools to bootstrap actions and aims to be compatible with all actions
  - Micro size image: <200MB, contains only NodeJS required to bootstrap actions, doesn't work with all actions

Default image and other options can be changed manually in ~/.actrc (please refer to https://github.com/nektos/act#configuration for additional information about file structure) Large
[Devtools/Build and Test] 🚀  Start image=node:12-buster-slim
[Devtools/Build and Test]   🐳  docker run image=node:12-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Devtools/Build and Test]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[Devtools/Build and Test]   🐳  docker cp src=/media/daniela/TOSHIBA EXT/espol/is2/horta593/horta593-backend/. dst=/media/daniela/TOSHIBA EXT/espol/is2/horta593/horta593-backend
[Devtools/Build and Test]   🐳  docker exec cmd=[mkdir -p /media/daniela/TOSHIBA EXT/espol/is2/horta593/horta593-backend] user=

postgresql
[Devtools/Build and Test] ⭐  Run Checkout repository
[Devtools/Build and Test]   ✅  Success - Checkout repository
[Devtools/Build and Test] ⭐  Run ./.github/actions/docker-compose
[Devtools/Build and Test]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /media/daniela/TOSHIBA EXT/espol/is2/horta593/horta593-backend/workflow/composite-0.sh] user=
| bash: /media/daniela/TOSHIBA: No such file or directory
[Devtools/Build and Test]   ❌  Failure - ./.github/actions/docker-compose
Error: exit with `FAILURE`: 1
```

### Command used with act

```sh
act -W .github/workflows/main.yml
```

### Describe issue

Al utilizar `act` con un proyecto cuyo directorio contiene espacios en la ruta, se produce un error que dice "No such file or directory". Esto parece indicar que `act` no está manejando correctamente las rutas con espacios.

**Cómo reproducir el error**:
1. Crear o mover un proyecto a una ruta que contenga espacios.
2. Ejecutar `act` en ese directorio.

**Resultado esperado**:
`act` debería manejar las rutas con espacios y ejecutarse sin errores.

**Resultado actual**:
Se produce un error que indica que no se puede encontrar el archivo o directorio.

**Información adicional**:
(Aquí puedes incluir detalles adicionales como la versión de `act`, el sistema operativo, etc.)

¿Hay alguna solución temporal o alguna forma de abordar este problema?

### Workflow content

```yml
name: Devtools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    if: github.actor!= 'dependabot[bot]'
    name: Build and Test
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          JWT_SECRET: $${{ secrets.JWT_SECRET }}
          COOKIE_SECRET: $${{ secrets.COOKIE_SECRET }} 
          JWT_ACCESS_SECRET: $${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: $${{ secrets.JWT_REFRESH_SECRET }} 
          ACCESS_EXPIRATION: ${{ secrets.ACCESS_EXPIRATION }}
          REFRESH_EXPIRATION: ${{ secrets.REFRESH_EXPIRATION }}
        ports:
          - 5435:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/docker-compose
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18 
      - name: Install PNPM
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Export DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
      - name: Run Prisma Migrations
        run: pnpm prisma:migrate 
      - name: Deploy Prisma Migrations
        run: pnpm prisma:dev:deploy
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Setup Environment (PR)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >>\${GITHUB_ENV}
      - name: Setup Environment (Push)
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: echo "COMMIT_SHA=\${GITHUB_SHA}" >> \${GITHUB_ENV}
      - name: Check PostgreSQL Connection
        run: |
          export PGPASSWORD=${{ secrets.DB_PASSWORD }}
          psql -h localhost -p 5435 -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -c 'SELECT NOW();'
      - name: Check if Product ID exists
        run: |
          export PGPASSWORD=${{ secrets.DB_PASSWORD }}
          psql -h localhost -p 5435 -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -c "SELECT * FROM products;"
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
```

### Relevant log output

```sh
? Please choose the default image you want to use with act:

  - Large size image: +20GB Docker image, includes almost all tools used on GitHub Actions (IMPORTANT: currently only ubuntu-18.04 platform is available)
  - Medium size image: ~500MB, includes only necessary tools to bootstrap actions and aims to be compatible with all actions
  - Micro size image: <200MB, contains only NodeJS required to bootstrap actions, doesn't work with all actions

Default image and other options can be changed manually in ~/.actrc (please refer to https://github.com/nektos/act#configuration for additional information about file structure) Large
[Devtools/Build and Test] 🚀  Start image=node:12-buster-slim
[Devtools/Build and Test]   🐳  docker run image=node:12-buster-slim platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Devtools/Build and Test]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[Devtools/Build and Test]   🐳  docker cp src=/media/daniela/TOSHIBA EXT/espol/is2/horta593/horta593-backend/. dst=/media/daniela/TOSHIBA EXT/espol/is2/horta593/horta593-backend
[Devtools/Build and Test]   🐳  docker exec cmd=[mkdir -p /media/daniela/TOSHIBA EXT/espol/is2/horta593/horta593-backend] user=

postgresql
[Devtools/Build and Test] ⭐  Run Checkout repository
[Devtools/Build and Test]   ✅  Success - Checkout repository
[Devtools/Build and Test] ⭐  Run ./.github/actions/docker-compose
[Devtools/Build and Test]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /media/daniela/TOSHIBA EXT/espol/is2/horta593/horta593-backend/workflow/composite-0.sh] user=
| bash: /media/daniela/TOSHIBA: No such file or directory
[Devtools/Build and Test]   ❌  Failure - ./.github/actions/docker-compose
Error: exit with `FAILURE`: 1
```
