### ISSUE TITLE
Multiple line variable in .env file

### ISSUE THREAD

**Issue by chrowe** [nektos/act#1972]
### Bug report info

```plain text
act version:            0.2.49
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
        $HOME/.docker/run/docker.sock
Config files:           
        /Users/[username]/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.20.6
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.49
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        24.0.2
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.15.49-linuxkit-pr
        OS CPU:                6
        OS memory:             11963 MB
        Security options:
                name=seccomp,profile=builtin
                name=cgroupns
```

### Command used with act

```sh
act --container-architecture linux/amd64 --secret-file ../act.secrets workflow_dispatch
```

### Describe issue

The readme says that the `--secret-file` "file format is the same as .env format"
Looking at https://hexdocs.pm/dotenvy/dotenv-file-format.html the way to handle multi line values is
```
MULTILINE = """
long text here,
e.g. a private SSH key
"""
```
But when I try that throws an error

### Workflow content

```yml
name: Deploy to AWS
on:
  on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ssh-deploy:
    name: ssh-deploy
    runs-on: ubuntu-20.04
    steps:
    - name: cd in repo dir
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: whoami
```

### Relevant log output

```sh
DEBU[0000] Loading environment from /Users/[username]/Github/act.secrets
FATA[0000] Error loading from /Users/Chris.Rowe/Github/act.secrets: unexpected character "\"" in variable name near "\"\n[VALUE_FROM_FILE]\n\"\"\""
```

### Additional information

Looks like someone else was having a similar issue in https://github.com/nektos/act/issues/123#issuecomment-670055823
