### ISSUE TITLE
Fails silently when docker is not running

### ISSUE THREAD

**Issue by sobraljuanpa** [nektos/act#1980]
### Bug report info

```plain text
ct version:            0.2.49
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
        $HOME/.docker/run/docker.sock
Config files:           
        /Users/juan/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.20.6
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.49
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        23.0.5
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.15.49-linuxkit
        OS CPU:                4
        OS memory:             7851 MB
        Security options:
                name=seccomp,profile=builtin
                name=cgroupns
```

### Command used with act

```sh
act -j auctions-management --container-architecture linux/amd64
```

### Describe issue

When running act commands with the docker daemon not running, no warning or notification is provided to the user.

This might be an improvement rather than a bug.

### Workflow content

```yml
name: Lint build and unit test users management service

on:
    push:
      branches: ["main", "dev"]
    pull_request:
        branches: ["main", "dev"]

jobs:
    lint-build-unit:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./users-management-service/
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            cache: 'npm'
            cache-dependency-path: './users-management-service/package-lock.json'
        - run: npm ci
        - run: npm run lint
        - run: npm run build
        - run: npm run test:cov
```

### Relevant log output

```sh
No output is the issue
```
