### ISSUE TITLE
Different checkout behaviour in comparison to self hosted runner

### ISSUE THREAD

**Issue by suiluj** [nektos/act#2001]
### Bug report info

```plain text
checkout state is not kept for following jobs (no files exists in the following jobs after checkout)
```

### Command used with act

```sh
gh act -W '.github/workflows/manual-tests.yml'
```

### Describe issue

ls shows files and folder of repo in the checkout job

but ls does not show any files in the "next-job"

The self hosted runner allows working with the repo after a previous job the checkout before so I expected that act would do the same thing.

### Workflow content

```yml
name: manual tests

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: [ self-hosted ]
    
    steps:
    - uses: actions/checkout@v3
    - run: ls
  
  next-job:
    runs-on: [ self-hosted ]
    needs: checkout
    steps:
    - run: ls
```

### Relevant log output

```sh
ls shows files and folder of repo in the checkout job

but ls does not show any files in the "next-job"
```
