### ISSUE TITLE
Error setting up 3rd party Module/Action

### ISSUE THREAD

**Issue by yehoshuadimarsky** [nektos/act#202]
Act version: 0.2.7
Platform: Windows 10 Pro
The complete main.workflow file used:
```yaml
name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CONDA_ENV_NAME: test-env
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
       auto-update-conda: true
       activate-environment: ${{ env.CONDA_ENV_NAME }}
       environment-file: env.yml
       python-version: ${{ matrix.python-version }}
       auto-activate-base: false
```
Issue:
Looks like it couldn't properly set up the `setup-miniconda` module/action correctly - here is a screenshot of the error.
![image](https://user-images.githubusercontent.com/24758845/79680392-16e3ba00-81dd-11ea-8c29-9699358d92b0.png)
