### ISSUE TITLE
socket hang up during artifact container creation

### ISSUE THREAD

**Issue by dancaugherty** [nektos/act#2030]
### Bug report info

```plain text
act version:            0.2.51
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 20
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
	$HOME/.docker/run/docker.sock
Config files:
	/Users/caughert/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:full-latest
		-P ubuntu-latest=catthehacker/ubuntu:full-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:full-18.04
Build info:
	Go version:            go1.21.1
	Module path:           command-line-arguments
	Main version:
	Main path:
	Main checksum:
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.51
		DefaultGODEBUG:       panicnil=1
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               arm64
		GOOS:                 darwin
Docker Engine:
	Engine version:        20.10.23
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:
	OS arch:               aarch64
	OS kernel:             5.15.49-linuxkit
	OS CPU:                8
	OS memory:             19986 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
act  workflow_dispatch --input docker_tag=dan-pollutes-the-repo --container-architecture linux/amd64 -s GITHUB_TOKEN=`cat ~/.github_token` -P self-hosted=nektos/act-environments-ubuntu:18.04  --github-instance github.mycompany.com -j Build-NPM-Base --artifact-server-path /tmp/artifacts --env ACTIONS_RUNTIME_TOKEN=foo
```

### Describe issue

Using actions/upload-artifact@v2 dies horribly. Corporate output redacted as needed:
```

[Build the Gadget/Build-NPM-Base]   💬  ::debug::Root artifact directory is /Users/caughert/Documents/dev/gadget-repo/artifact-dir
| Starting artifact upload
| For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
| Artifact name is valid!
[Build the Gadget/Build-NPM-Base]   💬  ::debug::Artifact Url: http://X.X.X.X:34567/_apis/pipelines/workflows/1/artifacts?api-version=6.0-preview
| Create Artifact Container - Attempt 1 of 5 failed with error: socket hang up
| Create Artifact Container - Attempt 2 of 5 failed with error: socket hang up
| Create Artifact Container - Attempt 3 of 5 failed with error: socket hang up
| Create Artifact Container - Attempt 4 of 5 failed with error: socket hang up
| Create Artifact Container - Attempt 5 of 5 failed with error: socket hang up
[Build the Gadget/Build-NPM-Base]   ❗  ::error::Create Artifact Container failed: socket hang up
[Build the Gadget/Build-NPM-Base]   ❌  Failure - Main upload-prod-config
[Build the Gadget/Build-NPM-Base] exitcode '1': failure
[Build the Gadget/Build-NPM-Base] 🏁  Job failed
Error: Job 'Build-NPM-Base' failed

```

I expected the container to spin up, upload the artifacts, and go away. 

### Workflow content

```yml
# These are the only relevant portions, redacted as necessary.
# Yes, I do try download-artifact later, but I can't even get that far.

name: Build the Gadget

on:
  push:
    branches:
      # M999
      - 'M[0-9]+'
      # and the usual suspects
      - 'dev'
      - 'master'
  workflow_dispatch:
    inputs:
      docker_tag:
        required: true
        type: string
jobs:
  Build-NPM-Base:
    runs-on: self-hosted
    env:
        http_proxy: http://proxy.mycompany.net:8080
        https_proxy: http://proxy.mycompany.net:8080   
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
      - name: npm-install
        run: |
          npm config set proxy $http_proxy
          npm config set https-proxy $http_proxy
          npm install --loglevel verbose --fetch-timeout 6000000
          npm run timestamp
      - name: build-prod-config
        run: |
          npx ng build --configuration production
      - name: upload-prod-config
        uses: actions/upload-artifact@v2
        with:
          name: static-pro
          path: dist/stuff/**
      - name: build-dev-config
        run: |
          npx ng build --configuration development
      - name: upload-dev-config
        uses: actions/upload-artifact@v2
        with:
          name: static
          path: dist/stuff/**
```

### Relevant log output

```sh
See output snippet above
```

### Additional information

I understand that uploading artifacts isn't supported that well within act yet, but how can I diagnose this problem?
