### ISSUE TITLE
Can't pass reusable workflow input variable

### ISSUE THREAD

**Issue by haritowa** [nektos/act#2046]
### Bug report info

```plain text
act version:            0.2.52
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
        $HOME/.docker/run/docker.sock
Config files:           
        /Users/haritowa/.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:full-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:full-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:full-18.04
Build info:
        Go version:            go1.21.1
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.52
                DefaultGODEBUG:       panicnil=1
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               arm64
                GOOS:                 darwin
Docker Engine:
        Engine version:        23.0.5
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:            
        OS arch:               aarch64
        OS kernel:             5.15.49-linuxkit
        OS CPU:                4
        OS memory:             9951 MB
        Security options:
                name=seccomp,profile=builtin
                name=cgroupns
```

### Command used with act

```sh
act -W .github/workflows/base.yml --container-architecture linux/amd64 --secret-file my.secrets  --var-file my.variables --input-file my.input
```

### Describe issue

Workflow input is not propagated to called workflow

### Workflow content

```yml
## BASE

name: 'Core Workflow'

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      project:
        type: string
        required: true
      owner:
        type: string
        required: true
      options:
        type: string
        required: true

jobs:
  check-availability:
    uses: ./.github/workflows/base/check-availability.yml
    with:
      kek: "1"

## CALLED
name: 'Check mapping availability'

on:
  workflow_call:
    inputs:
      kek:
        type: string
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print workflow inputs
        run: |
          echo "${{ toJSON(inputs) }}"
```

### Relevant log output

```sh
[check-availability/Check mapping availability/run]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
| {
|   kek: 
| }
```
