### ISSUE TITLE
Unable to use expressions for default values in workflow_call inputs

### ISSUE THREAD

**Issue by mconigliaro** [nektos/act#2047]
### Bug report info

```plain text
act version:            0.2.52
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	$HOME/.docker/run/docker.sock
Config files:
	/Users/mike-conigliaro/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
		-P ubuntu-16.04=catthehacker/ubuntu:act-16.04
		-P self-hosted=catthehacker/ubuntu:act-latest
		-P cypress=cypress/included:cypress-12.6.0-node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1

		--env-file /Users/mike-conigliaro/.actenv
		--secret-file /Users/mike-conigliaro/.actsecret
		--input-file /Users/mike-conigliaro/.actinput
Build info:
	Go version:            go1.21.1
	Module path:           command-line-arguments
	Main version:
	Main path:
	Main checksum:
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.52
		DefaultGODEBUG:       panicnil=1
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1

Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Command used with act

```sh
act -W .github/workflows/test.yml
```

### Describe issue

Expressions are not evaluated in `on.workflow_call.inputs.*.default`.

### Workflow content

```yml
name: test

on:
  workflow_call:
    inputs:
      repository:
        type: string
        default: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ inputs.repository }}
```

### Relevant log output

```sh
[test/test] 🚀  Start image=catthehacker/ubuntu:act-latest
[test/test]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[test/test]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[test/test]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[test/test] ⭐ Run Main echo ${{ github.repository }}
[test/test]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/0] user= workdir=
| /var/run/act/workflow/0: line 2: ${{ github.repository }}: bad substitution
[test/test]   ❌  Failure - Main echo ${{ github.repository }}
[test/test] exitcode '1': failure
[test/test] 🏁  Job failed
Error: Job 'test' failed
```

**Comment by TWiStErRob** [comment]
Note: as far as I understood, this only affects direct `workflow_call`s from `act`. If the `uses: ./.github/workflows/test.yml` is in another workflow file, and `act` runs that one, it might "just work".

**Comment by TWiStErRob** [comment]
It's never stale, it's a bug that needs to be fixed.

**Comment by TWiStErRob** [comment]
@ChristopherHX isn't this a standard feature of GHA, or am I missing something? Would you mind elaborating why it's in the not-planned bucket?

**Comment by mcascone** [comment]
so... `workflow_call` just doesn't work, and there are no plans to fix it?

**Comment by TWiStErRob** [comment]
> IMHO this is not a big deal to do.

Yes and no, for example, we have many `workflow_call`s with 10+ inputs and use `act` to integration test them. So to parameterize those from tests one either has to create many many of these bootstraps (each test) or duplicate all the inputs in the test fixture yml. That said, having an explicit and correct trigger / event context (`push` in the above example) is a good thing!

**Comment by mcascone** [comment]
> [@mcascone](https://github.com/mcascone) No, you are supposed to use such a yaml to bootstrap your reusable workflow
> 
> on: push
> jobs:
>   _:
>     uses: ./.github/workflows/<reusable>.yml
> Now `act push`.
> 
> This should work correctly
> 
> IMHO this is not a big deal to do.

ok, so if we use a `push` trigger it will pass `with:` inputs from the caller to the called workflow? Because right now, with `workflow_call`, I'm seeing it not do that at all. Which really hampers its usability. 

Is the `_:` job name specifically required? What does it do? 

Is this documented anywhere?

@TWiStErRob how are you using `act` to integration test your reusable workflows with this functionality gap in play?

**Comment by TWiStErRob** [comment]
> it will pass with: inputs from the caller to the called workflow

https://github.com/nektos/act/issues/2047#issuecomment-1827671287
So I think that's the case, but not 100% sure.

> Is the _: job name specifically required? What does it do?

A job name is required there, I like the idea that _ is used, as the name doesn't matter, I usually used `job:` in these cases.

> how are you using act to integration test your reusable workflows with this functionality gap in play?

Don't test defaults: 1. Try to avoid expressions, 2. pass it in explicitly from test, or 3. manually handle expressions:
```js
// Instead of `default: ${{ github.workspace }}` have `default: ''` + below logic in a github-script step:
// Workaround for https://github.com/nektos/act/issues/2047.
    core.setOutput(
      "working-directory",
      process.env.INPUT_WORKING_DIRECTORY === ''
        ? process.env.GITHUB_WORKSPACE
        : process.env.INPUT_WORKING_DIRECTORY
    );
```

**Comment by mcascone** [comment]
I'm not sure I completely understand your mechanism, but that's ok. I'm focusing on getting reusable workflows to work with `act`/`act-js`.

Perhaps the issue is that I'm starting off the run with a workflow that is itself a reusable workflow? Meaning, an application's repo contains a workflow triggered by `push`, `pull_request`, etc. That workflow calls the "master" pipeline, which is what I'm trying to unit/integration test with `act-js`.

Is it possible that if I kick off the unit-test run with a workflow that uses `push`, the reusable workflows called by it will get their inputs properly passed on?

**Comment by mcascone** [comment]
OK, I created a test-kicker-offer that mimics our calling workflows:

```yaml
name: test-kickoff.yml

on:
  push:
    branches:
      - '*'
  
  workflow_dispatch:
    inputs:
      run-type:
        description: "Only Build-And-Deploy is supported"
        type: choice
        default: build-and-deploy
        options:
          - build-and-deploy

permissions:
  contents: read

jobs:
  java-pipeline:
    uses: ./.github/workflows/my-pipeline.yml
    secrets: inherit
    with:
      appId: 13234
      jiraKey: EMTN
      appName: e-exp-api
      liveTests: false
      performanceTests: false
      prod: true
```

This calls `my-pipeline` successfully, with the inputs passed properly through! Win!

I also checked that the downstream `workflow_call` 'flows are called properly, and all of the `fromJSON(<a passed-in JSON string>).<object-key` expressions work - even `workflow_call` inputs that are defined in the downstream workflows! Big Win!

Thanks all!
