### ISSUE TITLE
npm package "http-client" does not exist under owner "actions"

### ISSUE THREAD

**Issue by ospfranco** [nektos/act#2057]
### Bug report info

```plain text
I'm building an Android with React Native app. My action calls another script (Fastlane) internally. Part of building the app is installing JavaScript dependencies. This is done via `npm i`. However, the installation process errors out after a while with this error:


| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/simply-deferred.git
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/react-native-picker-select.git
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/react-native-image-size.git
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/expensify-common.git
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/react-native-image-manipulator.git
| npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
| npm WARN deprecated dommatrix@1.0.3: dommatrix is no longer maintained. Please use @thednp/dommatrix.
| npm WARN deprecated @types/pusher-js@5.1.0: This is a stub types definition. pusher-js provides its own type definitions, so you do not need this installed.
| npm WARN deprecated @types/concurrently@7.0.0: This is a stub types definition. concurrently provides its own type definitions, so you do not need this installed.
| npm ERR! code E404
| npm ERR! 404 Not Found - GET https://npm.pkg.github.com/@actions%2fhttp-client - npm package "http-client" does not exist under owner "actions"
| npm ERR! 404
| npm ERR! 404  '@actions/http-client@2.0.1' is not in this registry.
| npm ERR! 404
| npm ERR! 404 Note that you can also install from a
| npm ERR! 404 tarball, folder, http url, or git url.
|
| npm ERR! A complete log of this run can be found in:
| npm ERR!     /root/.npm/_logs/2023-10-20T06_27_57_927Z-debug-0.log
```

Am I doing something wrong, or is some sort of proxy when running on the cloud that gets setup and allows to fetch this package?
```


### Command used with act

```sh
act -W .github/workflows/e2ePerformanceTests.yml -j buildBaseline --container-architecture linux/amd64 -P ubuntu-latest-xl=nektos/act-environments-ubuntu:18.04
```

### Describe issue

Npm install should succeed without an error.

### Workflow content

```yml
name: E2E Performance Tests

on:
  workflow_call:
    inputs:
      PR_NUMBER:
        description: A PR number to run performance tests against. If the PR is already merged, the merge commit will be used. If not, the PR will be merged locally before running the performance tests.
        type: string
        required: true

  workflow_dispatch:
    inputs:
      PR_NUMBER:
        description: A PR number to run performance tests against. If the PR is already merged, the merge commit will be used. If not, the PR will be merged locally before running the performance tests.
        type: string
        required: true

jobs:
  buildBaseline:
    runs-on: ubuntu-latest-xl
    name: Build apk from latest release as a baseline
    outputs:
      VERSION: ${{ steps.getMostRecentRelease.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure MapBox SDK
        run: ./scripts/setup-mapbox-sdk.sh ${{ secrets.MAPBOX_SDK_DOWNLOAD_TOKEN }}

      - name: Build APK
        uses: Expensify/App/.github/actions/composite/buildAndroidAPK@main
        with:
          ARTIFACT_NAME: baseline-apk-${{ steps.getMostRecentRelease.outputs.VERSION }}
```

### Relevant log output

```sh
[E2E Performance Tests/Build apk from latest release as a baseline]   💬  ::debug::Running command npm ci on linux using shell bash
| npm WARN ERESOLVE overriding peer dependency
| npm WARN While resolving: react-element-to-jsx-string@14.3.4
| npm WARN Found: react@18.2.0
| npm WARN node_modules/react
| npm WARN   react@"18.2.0" from the root project
| npm WARN   161 more (@callstack/reassure-measure, ...)
| npm WARN
| npm WARN Could not resolve dependency:
| npm WARN peer react@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1" from react-element-to-jsx-string@14.3.4
| npm WARN node_modules/@storybook/react/node_modules/react-element-to-jsx-string
| npm WARN   react-element-to-jsx-string@"^14.3.4" from @storybook/react@6.5.10
| npm WARN   node_modules/@storybook/react
| npm WARN
| npm WARN Conflicting peer dependency: react@17.0.2
| npm WARN node_modules/react
| npm WARN   peer react@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1" from react-element-to-jsx-string@14.3.4
| npm WARN   node_modules/@storybook/react/node_modules/react-element-to-jsx-string
| npm WARN     react-element-to-jsx-string@"^14.3.4" from @storybook/react@6.5.10
| npm WARN     node_modules/@storybook/react
| npm WARN ERESOLVE overriding peer dependency
| npm WARN While resolving: react-element-to-jsx-string@14.3.4
| npm WARN Found: react-dom@18.1.0
| npm WARN node_modules/react-dom
| npm WARN   react-dom@"18.1.0" from the root project
| npm WARN   76 more (@expensify/react-native-web, @floating-ui/react-dom, ...)
| npm WARN
| npm WARN Could not resolve dependency:
| npm WARN peer react-dom@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1" from react-element-to-jsx-string@14.3.4
| npm WARN node_modules/@storybook/react/node_modules/react-element-to-jsx-string
| npm WARN   react-element-to-jsx-string@"^14.3.4" from @storybook/react@6.5.10
| npm WARN   node_modules/@storybook/react
| npm WARN
| npm WARN Conflicting peer dependency: react-dom@17.0.2
| npm WARN node_modules/react-dom
| npm WARN   peer react-dom@"^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1" from react-element-to-jsx-string@14.3.4
| npm WARN   node_modules/@storybook/react/node_modules/react-element-to-jsx-string
| npm WARN     react-element-to-jsx-string@"^14.3.4" from @storybook/react@6.5.10
| npm WARN     node_modules/@storybook/react
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/simply-deferred.git
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/react-native-picker-select.git
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/react-native-image-size.git
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/expensify-common.git
| npm WARN skipping integrity check for git dependency ssh://git@github.com/Expensify/react-native-image-manipulator.git
| npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
| npm WARN deprecated dommatrix@1.0.3: dommatrix is no longer maintained. Please use @thednp/dommatrix.
| npm WARN deprecated @types/pusher-js@5.1.0: This is a stub types definition. pusher-js provides its own type definitions, so you do not need this installed.
| npm WARN deprecated @types/concurrently@7.0.0: This is a stub types definition. concurrently provides its own type definitions, so you do not need this installed.
| npm ERR! code E404
| npm ERR! 404 Not Found - GET https://npm.pkg.github.com/@actions%2fhttp-client - npm package "http-client" does not exist under owner "actions"
| npm ERR! 404
| npm ERR! 404  '@actions/http-client@2.0.1' is not in this registry.
| npm ERR! 404
| npm ERR! 404 Note that you can also install from a
| npm ERR! 404 tarball, folder, http url, or git url.
|
| npm ERR! A complete log of this run can be found in:
| npm ERR!     /root/.npm/_logs/2023-10-20T06_27_57_927Z-debug-0.log
```
