### ISSUE TITLE
act fails where GitHub CI succeeds

### ISSUE THREAD

**Issue by dabrahams** [nektos/act#2095]
### Bug report info

```plain text
% act --bug-report
act version:            0.2.54
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 10
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	$HOME/.docker/run/docker.sock
Config files:
	/Users/dave/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.21.4
	Module path:           command-line-arguments
	Main version:
	Main path:
	Main checksum:
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.54
		DefaultGODEBUG:       panicnil=1
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               arm64
		GOOS:                 darwin

Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Command used with act

```sh
act --container-architecture linux/amd64 -v
```

### Describe issue

Note that **Docker IS in fact running**

act fails on my local machine but the workflow succeeds in Github Linux CI

See attached [act.log](https://github.com/nektos/act/files/13389841/act.log)

### Link to GitHub repository

https://github.com/dabrahams/SPMBuildToolSupport/actions/runs/6901849884

### Workflow content

```yml
---
name: Build and test

"on":
  push:
    branches: [main, rewrite]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:

  devcontainer:
    name: "Devcontainer: ${{ matrix.os }}/${{ matrix.configuration }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        configuration: [debug]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Build and Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: swift test -c ${{ matrix.configuration }}

  native:
    name: "Native: ${{ matrix.os }}/${{ matrix.configuration }}"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

        configuration: [debug]

        include:
          # Default values to add
          - shell: 'bash -eo pipefail {0}'

          # Overrides for the defaults
          - shell: pwsh
            os: windows-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Swift (Unices)
        if: ${{ matrix.os != 'windows-latest' }}
        uses: 'swift-actions/setup-swift@v1'
        with:
          version: 5.8

      - name: Setup Swift (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: 'compnerd/gha-setup-swift@main'
        with:
          github-repo: thebrowsercompany/swift-build
          release-asset-name: installer-amd64.exe
          release-tag-name: 20231010.3
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Test (${{ matrix.configuration }})
        run: swift test -c ${{ matrix.configuration }}
```

### Relevant log output

```sh
(too long; please see attached file)
```
