### ISSUE TITLE
Does not honor working-directory

### ISSUE THREAD

**Issue by fejx** [nektos/act#211]
Thanks for the awesome tool! It saved me a lot of time :heart:
However, while using it, I stumbled upon an issue.
Act does not honor the `working-directory` key you can set for `run` steps. It should `cd` into the specified path.

### Workflow
```yml
on: push

jobs:
  build:
    name: Test working directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: pwd
        working-directory: client
      - run: pwd
```
### GitHub output
```
Run pwd
/home/runner/work/test-project/test-project/client


Run pwd
/home/runner/work/test-project/test-project
```

### Local output from Act

```
[working-dir-test.yml/Test working directory] ⭐  Run pwd
| /github/workspace
[working-dir-test.yml/Test working directory]   ✅  Success - pwd
[working-dir-test.yml/Test working directory] ⭐  Run pwd
| /github/workspace
[working-dir-test.yml/Test working directory]   ✅  Success - pwd
```

**Comment by audioboxer217** [comment]
Mostly leaving a comment to keep this from going stale.  It's not stale, I am still seeing this issue and currently not utilizing act because of it.  Which is disappointing because, as @fejx said, this really is an awesome tool!

**Comment by plauche** [comment]
I'm also running into this issue! We set the working directory as a top level default:
```
jobs:
  lint:
    runs-on: ubuntu-latest
    name: A job to run the tests and linter
    defaults:
      run:
        working-directory: backend/
```
But it does not appear to be honored.

**Comment by iongion** [comment]
The same for defaults

```
name: Pipeline

on: [push]

defaults:
  run:
    working-directory: thumbnailer

jobs:
  build:

    runs-on: ubuntu-latest
...
```
