### ISSUE TITLE
OCI runtime create failed message with `docker:` uses

### ISSUE THREAD

**Issue by dlgreenwald-els** [nektos/act#212]
I'm trying to setup a simple Markdown Linter in a project with the following Workflow:
```
name: ADR Markdown Linter

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lintADRS:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1.1.0
      with:
        rules: '/lint/rules/changelog.js'
        config: '/lint/config/changelog.yml'
        args: 'README.md'
```

When I try to run with `act pull_request` I get the following error.

```
❯ act  pull_request
[ADR Markdown Linter/Lint changelog file] 🚀  Start image=node:12.6-buster-slim
[ADR Markdown Linter/Lint changelog file]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[ADR Markdown Linter/Lint changelog file]   🐳  docker cp src=/Users/greenwda/ADRS/rtarchitecture-adrs/. dst=/github/workspace
[ADR Markdown Linter/Lint changelog file] ⭐  Run Check out code
[ADR Markdown Linter/Lint changelog file]   ✅  Success - Check out code
[ADR Markdown Linter/Lint changelog file] ⭐  Run Lint changelog file
[ADR Markdown Linter/Lint changelog file]   🐳  docker run image=avtodev/markdown-lint:v1.1.0 entrypoint=[] cmd=["README.md"]
[ADR Markdown Linter/Lint changelog file]   ❌  Failure - Lint changelog file
Error: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"README.md\": executable file not found in $PATH": unknown
```

When I run the markdown-lint image directly it works fine, but would very much like to utilize the workflow locally for testing purposes rather than constant submission of pull requests.

I posted for advice on the gitter.im channel and was asked to create an issue.
https://gitter.im/nektos/act?at=5ea848ccb6dd2306979157d3

**Comment by publicarray** [comment]
Hm maybe try setting the entrypoint as a workaround?

```yml
- name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1.1.0
      with:
        rules: '/lint/rules/changelog.js'
        config: '/lint/config/changelog.yml'
        entrypoint: markdownlint # or wherever the binary is located
        args: 'README.md'
```
