### ISSUE TITLE
git command stuck waiting for pager input

### ISSUE THREAD

**Issue by enribus** [nektos/act#2125]
### Bug report info

```plain text
$ act --bug-report
act version:            0.2.55
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 8
Docker host:            tcp://10.10.10.220:2375
Sockets found:
Config files:
	/Users/user/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.21.4
	Module path:           command-line-arguments
	Main version:
	Main path:
	Main checksum:
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.55
		DefaultGODEBUG:       panicnil=1
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
Docker Engine:
	Engine version:        24.0.7
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 22.04.3 LTS
	OS type:               linux
	OS version:            22.04
	OS arch:               x86_64
	OS kernel:             5.15.0-89-generic
	OS CPU:                4
	OS memory:             3895 MB
	Security options:
		name=apparmor
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
cat events.json
{
    "act": true
}
act -v -W .github/workflows/build.yml --artifact-server-path /tmp/artifacts -e ~/events.json
```

### Describe issue

Hello,
thanks for the work so far with `act`, it's amazing ;)

I have an issue with this scenario:
- `act` v0.2.55, installed w/ brew on MacOS 13.6.3 Intel
- remote docker 24.0.7 engine on Ubuntu22.04

Job execution is stuck on a particular step where `git tag` is executed.
Looking at running processes inside the container, I see there is a `pager` process running, so I suspected a pagin issue for the maybe standard shell in the built container.
In fact, un-setting the pager w/ a global env var,
fixed the issue and the job executes correctly.
```
env:
  GIT_PAGER:
```

If you need more info I can collect them.
Thanks

### Workflow content

```yml
name: Build
on:
  push:
    branches: [  ]
jobs:
  my_job:
    name: My Job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          filter: "blob:none"
          fetch-tags: 'true'
          fetch-depth: '1000'
          submodules: 'true'
      - name: My Step
        id: MyStepID
        run: |
          git tag
```

### Relevant log output

```sh
Container processes:

ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 16:01 pts/0    00:00:00 tail -f /dev/null
root          19       0  0 16:01 pts/1    00:00:00 bash --noprofile --norc -e -o pipefail /var/run/act/workflow/MyStepID
root          29      19  0 16:01 pts/1    00:00:00 git tag
root          30      29  0 16:01 pts/1    00:00:00 /usr/bin/pager
root          31       0  0 16:01 ?        00:00:00 /bin/bash
root          44      31  0 16:03 ?        00:00:00 ps -ef
```
```


### Additional information

_No response_

**Comment by enribus** [comment]
Forgot to mention:
- the offending `git tag` command is returning more than 18 lines
- hitting `CTLR-C` stops `act` and containers as expected by #1072
- already tried, without success, a similar workaround suggested in #977 
  by unsetting `GIT_PAGER`:
    ```
    unset GIT_PAGER
    act ....
    ```

This isse seems similar to #995 and #1078
which I understand were closed as not resolved, am I right?

Thanks.

**Comment by enribus** [comment]
Current workaround:
unset GIT_PAGER in workflow, using an 'empty' global ENV var:
```yaml
name: my workflow
env:
  GIT_PAGER:
```
