### ISSUE TITLE
Shell settings not used?

### ISSUE THREAD

**Issue by kai-tub** [nektos/act#214]
Hi,
first of all thanks for providing such an awesome library! 

I am using a container to run all steps of a job, which doesn't offer a bash environment:
My workflow file looks something like this:
```
on:
  push:
    branches: [ master ]

jobs:
  test:
      name: Test and build latex documents
      runs-on: ubuntu-latest
      # runs all of the steps inside the specified container rather than on the VM host.
      # Bonus: The latest alpine image, which texlive is based on also integrates python3
      container:
        image: xucheng/texlive-small:latest
     # Reconfigure all following shells to use sh and not bash
      defaults:
        run:
          shell: sh
      steps:
          - name: Set up Git
            uses: actions/checkout@v2
          - name: Echo
            run: echo Hello
```
Which will fail with the following error message: 
`starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

It works on GitHub. The problem seems to be caused by act not saving using the default values. If I set the shell on a per run basis like:
```
- name: Echo
  run: echo Hello
  shell: sh
```
Everything works as expected.

Thanks!
