### ISSUE TITLE
Windows path issues

### ISSUE THREAD

**Issue by kai-tub** [nektos/act#215]
Hi,
I think I've stumbled over a Windows bug.
I've created a sample git repository for fast reproduction.
https://github.com/kai-tub/github_action_tester

The project has two files (excluding the workflow file)
```
tests/echo.py
minimal.tex
```
After checking out the repository I can access and work with `minimal.tex` without any issues. 
But if I try to access the `tests/` folder or the file inside the `tests` folder, I get an error.
If I move `echo.py` back to the root directory everything works as expected.
The error messages are usually similar to: `No such file or directory`

This issue does not occur on my Linux machine. 

Am I missing something basic?

The workflow file looks like this:
```
on:
  push:
    branches: [ master ]

jobs:
  test_and_build_latex:
      name: Test
      runs-on: ubuntu-latest
      # runs all of the steps inside the specified container rather than on the VM host.
      # Bonus: The latest alpine image, which texlive is based on also integrates python3
      container:
        image: xucheng/texlive-small:latest
      # This setting is enough for github action but the local act version doesn't support
      # it yet. To still be able to run the tests locally, I will configure the shell
      # on a per run basis
      defaults:
        run:
          shell: sh
      steps:
          - name: Set up Git
            uses: actions/checkout@v2
          - name: Ls
            run: ls
            shell: sh
          - name: Echo
            run: "python3 tests/echo.py"
            shell: sh
```

Thanks!
