### ISSUE TITLE
Missing AGENT_TOOLSDIRECTORY env variable for setup-python@v2

### ISSUE THREAD

**Issue by mjpieters** [nektos/act#217]
The [setup-python@v2 action](https://github.com/actions/setup-python/) makes the following assumptions:

- On linux, the `/etc/lsb-release` file is read and the `DISTRIB_RELEASE=...` value must match the [`platform_version` keys in the Python versions manifest](https://github.com/actions/python-versions/blob/master/versions-manifest.json). In practice this means the container must be based on Ubuntu.
- Once downloaded, each Python version has a `setup.sh` file, generated [from a template](https://github.com/actions/python-versions/blob/master/installers/nix-setup-template.sh) that assumes the `AGENT_TOOLSDIRECTORY` env variable exists; this is just an alias for `RUNNER_TOOL_CACHE`.
- The `python -m pip install --ignore-installed pip` upgrade step requires SSL libraries to be installed (openssl)

So I can make the action work by:

- Using my own Ubuntu-based docker image (`mjpieters/act-container:18.04`, which is just `node:buster-slim` but using `ubuntu:18.04` rather than Debian Buster, with openssl added; 180MB small, see https://hub.docker.com/repository/docker/mjpieters/act-container)
- adding the following build step:

    ```yaml
    env:
        AGENT_TOOLSDIRECTORY: ${{ runner.tool_cache }}
    ```

While I understand that the `node:*-slim` containers are only meant to be starter images, could act be updated to provide the `AGENT_TOOLSDIRECTORY` variable?

Test workflow:

```yaml
name: Run testsuite

on:
  push

jobs:
  test:
    name: Run Python
    runs-on: ubuntu-latest
    env:
        AGENT_TOOLSDIRECTORY: ${{ runner.tool_cache }}
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Test Python
      run: |
        python -V
```
