### ISSUE TITLE
Slow running with timeouts

### ISSUE THREAD

**Issue by fabiobsantosprogrow** [nektos/act#2194]
### Bug report info

```plain text
act version:            0.2.57
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
Config files:           
        /home/progrow/.actrc:
                #-P ubuntu-latest=nektos/act-environments-ubuntu:22.04
                -P ubuntu-latest=catthehacker/ubuntu:full-latest
                -P ubuntu-22.04=catthehacker/ubuntu:full-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:full-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:full-18.04
                --artifact-server-path /home/progrow/act
                --pull=false
Build info:
        Go version:            go1.21.5
        Module path:           command-line-arguments
        Main version:          
        Main path:             
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -X main.version=0.2.57
                DefaultGODEBUG:       panicnil=1
                CGO_ENABLED:          1
                CGO_CFLAGS:           
                CGO_CPPFLAGS:         
                CGO_CXXFLAGS:         
                CGO_LDFLAGS:          
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
Docker Engine:
        Engine version:        20.10.23
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Ubuntu 20.04.3 LTS
        OS type:               linux
        OS version:            20.04
        OS arch:               x86_64
        OS kernel:             5.15.0-92-generic
        OS CPU:                12
        OS memory:             15854 MB
        Security options:
                name=apparmor
                name=seccomp,profile=default
```

### Command used with act

```sh
act -j integration_test_stage -W .github/workflows/ci-pipeline.yml
```

### Describe issue

Slow running pipeline...
Sometimes getting timeout erros like this: Error: Get "https://github.com/actions/setup-node/info/refs?service=git-upload-pack": dial tcp 140.82.121.3:443: i/o timeout

Kind regards

### Workflow content

```yml
name: ci-pipeline
permissions: write-all

#new comment
on:
  push:
    branches: [develop]
    #branches: [develop, 'release/**']
  release:
    types: [created]

env:
  DB_CONNECTIONSTRING: postgresql://postgres:%23progrow%3D2015!@localhost:5432/
  DB_SCHEMA: test_db
  LOG_LEVEL: error
  DISABLE_JOB_SALVAGING: true
  NUMBER_OF_PROCESSING_THREADS: 16
  NUMBER_RETRIES_PER_JOB: 5
  DB_ENABLE_PATCHER: false
  REDIS_PORT: 6380
  VIEWS_TTL_START: 15
  EXPRESS_PORT: 3001
  PATCHER_APP_ENABLE: false
  REDIS_URI_INTEGRATION: redis://localhost:6380/0
  REDIS_URI_PRODUCT: redis://localhost:6380/1
  DISABLE_AUTH: true

jobs:
  commit_stage:
    name: Commit Stage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: npm install && npx lerna run build

      - name: Unit test
        run: npx lerna run test -- unit

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: development-pipeline-etl-core
          path: |
            packages/**/dist
            !packages/**/dist/*.md
          retention-days: 7

  integration_test_stage:
    name: Integration test stage
    needs: commit_stage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: development-pipeline-etl-core
          path: ./packages

      - name: Install necessary dependencies
        run: npm install

      - name: Sets up environment
        run: |
          sudo docker-compose up -d
          cd packages/management && npm run start &

      - name: Integration test stage
        run: cd packages/core && npm run test -- integration
```

### Relevant log output

```sh
Info on start:
INFO[0000] Start server on http://192.168.1.184:34567   
[ci-pipeline/Commit Stage] 🚀  Start image=catthehacker/ubuntu:full-latest
INFO[0000] Parallel tasks (0) below minimum, setting to 1 
[ci-pipeline/Commit Stage]   🐳  docker pull image=catthehacker/ubuntu:full-latest platform= username= forcePull=false
INFO[0000] Parallel tasks (0) below minimum, setting to 1 
Sometimes get timeout communication:
[ci-pipeline/Integration test stage] 🚀  Start image=catthehacker/ubuntu:full-latest
INFO[0054] Parallel tasks (0) below minimum, setting to 1 
[ci-pipeline/Integration test stage]   🐳  docker pull image=catthehacker/ubuntu:full-latest platform= username= forcePull=false
INFO[0054] Parallel tasks (0) below minimum, setting to 1 
[ci-pipeline/Integration test stage]   🐳  docker create image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[ci-pipeline/Integration test stage]   🐳  docker run image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[ci-pipeline/Integration test stage]   🐳  docker exec cmd=[chown -R 1001:127 /home/progrow/GitRepositories/DevOps/ETLCItest] user=0 workdir=
[ci-pipeline/Integration test stage]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v3
[ci-pipeline/Integration test stage] Cleaning up container for job Integration test stage
[ci-pipeline/Integration test stage] 🏁  Job succeeded
Error: Get "https://github.com/actions/setup-node/info/refs?service=git-upload-pack": dial tcp 140.82.121.3:443: i/o timeout
```
