### ISSUE TITLE
Support targeting specific workflows

### ISSUE THREAD

**Issue by rbellamy** [nektos/act#227]
With multiple workflows it is possible to have workflows and jobs with non-unique IDs.

*one.yml*
```yaml
name: basic
on: push

env:
  TEST: monkeys

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.TEST }} | grep value
```

*two.yml*
```yaml
name: basic
on: pull_request

env:
  TEST: shine

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.TEST }} | grep value
```

Right now the ability to target a job when working with multiple workflows requires that the job have a unique ID.

I think the best option would be to allow the `-W` flag to accept an array of workflow files (new feature) or a directory (current functionality).

I'm a novice at Go or I would create a PR. If it's relatively simple, and someone could give me some pointers, I'd be glad to give it a shot. I've looked at the code, and am unsure where to start.
