### ISSUE TITLE
Secrets are case sensitive

### ISSUE THREAD

**Issue by mheap** [nektos/act#230]
When running a workflow with `act`, the casing I specify with `-s CASED_SECRET=abc123` is the only one available in my workflows.

For example:

```yaml
steps:
  - uses: my/action@master
    with:
      not_working: ${{ secrets.cased_secret }}
      working: ${{ secrets.CASED_SECRET }}
```

In this workflow, `not_working` is an empty string whilst `working` returns `abc123` as expected.

When running this on Actions, both `not_working` and `working` have the value `abc123`

---

## Details

* act version 0.2.8
* MacOS 10.15.4
* go version go1.14.2 darwin/amd64

Full command:

```
act -j output-debug -W ~/development/oss/action-test/.github/workflows pull_request -e ~/development/oss/action-test/event.json
```
