### ISSUE TITLE
Boolean inputs in reusable workflows are not proper booleans

### ISSUE THREAD

**Issue by pgibson1-godaddy** [nektos/act#2344]
### Bug report info

```plain text
act version:            0.2.61
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 16
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
Config files:
Build info:
        Go version:            go1.20.14
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -trimpath:            true
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         e8856f0fb00fcdd16eef2325b845f55f5d346f51
                vcs.time:             2023-08-21T16:17:06Z
                vcs.modified:         true
Docker Engine:
        Engine version:        25.0.3
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.15.146.1-microsoft-standard-WSL2
        OS CPU:                16
        OS memory:             32100 MB
        Security options:
                name=seccomp,profile=unconfined
```

### Command used with act

```sh
act -W .github/workflows/act-test-caller.yml
```

### Describe issue

In GitHub Actions, `boolean` type inputs inside a `workflow_call` are real booleans, and you can use them as such. When a workflow is called with those in Act, they are converted to strings when they shouldn't be.

The output from my example below will be `This should not run` because `false` gets cast to `'false'` which actually ends up being truthy.

### Workflow content

```yml
# Calling workflow:
---
on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/act-test-called.yml

# Reusable workflow:
---
on:
  workflow_call:
    inputs:
      test:
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ !inputs.test }}
        run: |
          echo "This should run"
      
      - if: ${{ inputs.test }}
        run: |
          echo "This should not run"
```

### Relevant log output

```sh
[test/act-test-called.yml/test] ⭐ Run Main echo "This should not run"
[test/act-test-called.yml/test]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
| This should not run
[test/act-test-called.yml/test]   ✅  Success - Main echo "This should not run"

# Relevant line from debug output
[test/act-test-called.yml/test] [DEBUG] evaluating expression '${{ !inputs.test }}'
[test/act-test-called.yml/test] [DEBUG] expression '${{ !inputs.test }}' evaluated to 'false'
[test/act-test-called.yml/test] [DEBUG] Skipping step 'echo "This should run"
' due to '${{ !inputs.test }}'
...
[test/act-test-called.yml/test] [DEBUG] evaluating expression '${{ inputs.test }}'
[test/act-test-called.yml/test] [DEBUG] expression '${{ inputs.test }}' evaluated to '%!t(string=false)'
[test/act-test-called.yml/test] ⭐ Run Main echo "This should not run"
```
