### ISSUE TITLE
Turning on debug logging via `ACTIONS_RUNNER_DEBUG` is not reflected in `runner.debug` context

### ISSUE THREAD

**Issue by a-b** [nektos/act#2353]
### Bug report info

```plain text
act version:            0.2.62
GOOS:                   darwin
GOARCH:                 amd64
NumCPU:                 16
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
	$HOME/.docker/run/docker.sock
Config files:           
	/Users/user/.actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.22.2
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.62
		DefaultGODEBUG:       httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               amd64
		GOOS:                 darwin
		GOAMD64:              v1
Docker Engine:
	Engine version:        26.1.1
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        stargz
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             6.6.26-linuxkit
	OS CPU:                16
	OS memory:             15990 MB
	Security options:
		name=seccomp,profile=unconfined
		name=cgroupns
```

### Command used with act

```sh
act --env ACTIONS_RUNNER_DEBUG=true --workflows .github/workflows/test.yml
```

### Describe issue

Per [GHA enabling-debug-logging doc](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) and [runner-context](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context) runner's debug log status should be reflected via `runner.debug` expression. This behavior is not implemented in the current state of `act`.

### Workflow content

```yml
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-debug:
    name: Test Debug Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print expression details
        run: |
          echo "State of the runner.debug '${{ runner.debug }}'"
          env | grep ACTIONS_RUNNER_DEBUG
```

### Relevant log output

```sh
| State of the runner.debug ''
| ACTIONS_RUNNER_DEBUG=true
```
