### ISSUE TITLE
GitHub Event Context missing: github.event.repository.name

### ISSUE THREAD

**Issue by katherine-circularise** [nektos/act#2370]
### Bug report info

```plain text
not applicable
```

### Command used with act

```sh
act <any workflow>
```

### Describe issue

GitHub repository name is available via GITHUB_REPOSITORY env var, however I was using the event context (github.event.repository.name) as that already handles split by / for you. I've noticed that this is missing, which was leading to an empty string evaluation in my workflow.

If I have time, and manage to walk my way around the codebase, I'll send a PR adding this to the runner context. Creating the issue to keep track of htis.

### Workflow content

```yml
name: myWorkflow
on:
  push:
jobs:
  myJob:
    steps:
      - env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: echo "Name: m${REPO_NAME}m"
```

### Relevant log output

```sh
...
Name: mm
...
```
