### ISSUE TITLE
Permission denied error when downloading Java

### ISSUE THREAD

**Issue by just-dev-creator** [nektos/act#2374]
### Bug report info

```plain text
act version:            0.2.63
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/justus/.config/act/actrc:
		-P ubuntu-latest=catthehacker/ubuntu:full-latest
		-P ubuntu-22.04=catthehacker/ubuntu:full-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:full-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:full-18.04
Build info:
	Go version:            go1.22.3
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:         
	Build settings:
		-buildmode:           pie
		-compiler:            gc
		-trimpath:            true
		DefaultGODEBUG:       httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
		CGO_ENABLED:          1
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
Docker Engine:
	Engine version:        26.1.4
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Artix Linux
	OS type:               linux
	OS version:            
	OS arch:               x86_64
	OS kernel:             6.9.4-artix1-1
	OS CPU:                12
	OS memory:             15897 MB
	Security options:
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
act
```

### Describe issue

When downloading java via the `setup-java@v4` action, the step fails with a permission denied error. This is no problem when running the action on GH directly. 

### Link to GitHub repository

https://github.com/just-dev-creator/etb-plugin/

### Workflow content

```yml
name: Build spigot plugin
on: [push]
jobs:
  build:
    name: Build using maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21"
      - name: Build using maven
        run: mvn clean package
      - uses: actions/upload-artifact@v4
        with:
          path: target/*.jar
```

### Relevant log output

```sh
[Build spigot plugin/Build using maven]   💬  ::debug::Checking tar --version
[Build spigot plugin/Build using maven]   💬  ::debug::tar (GNU tar) 1.34%0ACopyright (C) 2021 Free Software Foundation, Inc.%0ALicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.%0AThis is free software: you are free to change and redistribute it.%0AThere is NO WARRANTY, to the extent permitted by law.%0A%0AWritten by John Gilmore and Jay Fenlason.
| [command]/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /tmp/20e695cc-5b57-4a4e-9dfa-64ea098fec3c -f /tmp/3ebeda1e-fae6-486a-a879-df45305329f3
[Build spigot plugin/Build using maven]   💬  ::debug::Caching tool Java_Adopt_jdk 21.0.3-9.0.LTS x64
[Build spigot plugin/Build using maven]   💬  ::debug::source dir: /tmp/20e695cc-5b57-4a4e-9dfa-64ea098fec3c/jdk-21.0.3+9
[Build spigot plugin/Build using maven]   💬  ::debug::destination /opt/hostedtoolcache/Java_Adopt_jdk/21.0.3-9.0.LTS/x64
[Build spigot plugin/Build using maven]   ❗  ::error::EACCES: permission denied, mkdir '/opt/hostedtoolcache/Java_Adopt_jdk/21.0.3-9.0.LTS'
[Build spigot plugin/Build using maven]   ❌  Failure - Main actions/setup-java@v4
[Build spigot plugin/Build using maven] exitcode '1': failure
[Build spigot plugin/Build using maven] ⭐ Run Post actions/setup-java@v4
[Build spigot plugin/Build using maven]   🐳  docker exec cmd=[node /var/run/act/actions/actions-setup-java@v4/dist/cleanup/index.js] user= workdir=
[Build spigot plugin/Build using maven]   ✅  Success - Post actions/setup-java@v4
[Build spigot plugin/Build using maven] 🏁  Job failed
```
