### ISSUE TITLE
docker compose setups are potentially loaded with environment from repository root instead of those from their own directory

### ISSUE THREAD

**Issue by simon-20** [nektos/act#2396]
### Bug report info

```plain text
act version:            0.2.64
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 20
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
Config files:           
	/home/simon/.config/act/actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.22.4
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.64
		DefaultGODEBUG:       httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
Docker Engine:
	Engine version:        27.0.3
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Ubuntu 22.04.4 LTS
	OS type:               linux
	OS version:            22.04
	OS arch:               x86_64
	OS kernel:             6.5.0-41-generic
	OS CPU:                20
	OS memory:             31757 MB
	Security options:
		name=apparmor
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
act push
```

### Describe issue

When running a docker compose setup within a Github Actions workflow, `act` does not load the docker compose with its correct environment file, but loads it with the environment variables loaded from the repository's root directory.

For example, given the following repository structure:

```
.
├── .github
│   └── workflows
│       └── test.yml
├── .env
└── automated-test-environment
    ├── .env
    └── docker-compose.yml
```

Where `test.yml` is:

```yaml
name: Run Automated Tests
on:
  workflow_dispatch:
  push:
    branches:
      develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run docker-compose
      run: cd ./automated-test-environment; docker compose up -d
```

The `docker compose` setup is loaded with values from `./.env` and not `./automated-test-environment/.env`.

This is different to what Github Actions does--Github Actions correctly loads the environment from `automated-test-environment/.env`.

The contents of `./.env`:

```env
DB_NAME=test_db
DB_USER=test_user
DB_PASS=pass
DB_PORT=5276

```

The contents of `./automated-test-environment/.env`:

```env
DB_NAME=test_db
DB_USER=test_user
DB_PASS=pass
DB_PORT=5277

```

Then, while the docker compose setup is running:

```bash
❯ psql -h localhost -U test_user -d test_db -p 5277
psql: error: connection to server at "localhost" (127.0.0.1), port 5277 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

❯ psql -h localhost -U test_user -d test_db -p 5276
Password for user test_user: 
```

### Workflow content

```yml
name: Run Automated Tests
on:
  workflow_dispatch:
  push:
    branches:
      develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run docker-compose
      run: cd ./automated-test-environment; docker compose up -d
```

### Relevant log output

```sh
❯ psql -h localhost -U test_user -d test_db -p 5277
psql: error: connection to server at "localhost" (127.0.0.1), port 5277 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

❯ psql -h localhost -U test_user -d test_db -p 5276
Password for user test_user:
```

### Additional information

May be related to: https://github.com/nektos/act/issues/2151
