### ISSUE TITLE
::error::error while setting context status: Not Found

### ISSUE THREAD

**Issue by brianjmurrell** [nektos/act#2399]
### Bug report info

```plain text
act version:            0.2.64
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            unix:///run/user/1001/podman/podman.sock
Sockets found:
        /var/run/docker.sock
        $XDG_RUNTIME_DIR/podman/podman.sock
Config files:           
        /home/brian/.config/act/actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
        /home/brian/.actrc:
                -s GITHUB_TOKEN=ghp_[redacted]
                --container-daemon-socket=unix:///run/user/1001/podman/podman.sock
Build info:
        Go version:            go1.22.4
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:         
        Build settings:
                -buildmode:           pie
                -compiler:            gc
                -trimpath:            true
                DefaultGODEBUG:       httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
                CGO_ENABLED:          1
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
Docker Engine:
        Engine version:        5.1.1
        Engine runtime:        crun
        Cgroup version:        2
        Cgroup driver:         systemd
        Storage driver:        overlay
        Registry URI:          
        OS:                    fedora
        OS type:               linux
        OS version:            40
        OS arch:               amd64
        OS kernel:             6.9.6-200.fc40.x86_64
        OS CPU:                12
        OS memory:             63943 MB
        Security options:
                name=seccomp,profile=default
                name=rootless
                name=selinux
```

### Command used with act

```sh
act --artifact-server-path=/var/tmp/artifacts --use-new-action-cache=false --pull=false -P self-hosted=-self-hosted -P light=-self-hosted -j …
```

### Describe issue

My workflow has the following step:

```yaml
      - name: Update commit status
        uses: ouzi-dev/commit-status-updater@v2
        with:
          # yamllint disable-line rule:line-length
          name: 'build/Build on ${{ env.DISTRO_NAME }} ${{ env.COMMIT_STATUS_DISTRO_VERSION && env.COMMIT_STATUS_DISTRO_VERSION || env.DISTRO_VERSION }}'
          status: "${{ job.status }}"
```

which causes the following error:

```
 ⭐ Run Main Update commit status
   ❗  ::error::error while setting context status: Not Found
   ❌  Failure - Main Update commit status
 exit status 1
```

While it does not seem at all unreasonable that such a step should not actually update any commit status, can this kind of failure be handled more gracefully than bombing the workflow run?

### Workflow content

```yml
- name: Update commit status
        uses: ouzi-dev/commit-status-updater@v2
        with:
          # yamllint disable-line rule:line-length
          name: 'build/Build on ${{ env.DISTRO_NAME }} ${{ env.COMMIT_STATUS_DISTRO_VERSION && env.COMMIT_STATUS_DISTRO_VERSION || env.DISTRO_VERSION }}'
          status: "${{ job.status }}"
```

### Relevant log output

```sh
⭐ Run Main Update commit status
   ❗  ::error::error while setting context status: Not Found
   ❌  Failure - Main Update commit status
 exit status 1
```
