### ISSUE TITLE
`actions/download-artifact@v4` downloads wrong file

### ISSUE THREAD

**Issue by malciin** [nektos/act#2433]
### Bug report info

```plain text
act version:            0.2.65
GOOS:                   windows
GOARCH:                 amd64
NumCPU:                 24
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
Config files:
        C:\Users\Marcin\AppData\Local\act\actrc:
                -P ubuntu-latest=node:16-buster-slim
                -P ubuntu-22.04=node:16-bullseye-slim
                -P ubuntu-20.04=node:16-buster-slim
                -P ubuntu-18.04=node:16-buster-slim
Build info:
        Go version:            go1.21.12
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.65 -X main.commit=bda491e406db6c85865498ced18764bc00491a5e -X main.date=2024-08-01T02:22:32Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 windows
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         bda491e406db6c85865498ced18764bc00491a5e
                vcs.time:             2024-08-01T02:22:10Z
                vcs.modified:         false
```

### Command used with act

```sh
act -P windows=-self-hosted -j test --artifact-server-path ./artifacts
```

### Describe issue

I've found that `actions/download-artifact@v4` can download invalid file (even tho name input parameter is specified) when running with `-self-hosted` flag.

If I use workflow like:

```yaml
      - run: echo "b content" > b/file.txt
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: a
      #     path: ./a
      #     if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: b
          path: ./b
          if-no-files-found: error
      - uses: actions/download-artifact@v4
        with:
          name: b
          path: ./downloaded
      - run: cat downloaded/file.txt
```

it will correctly print `b content`, however if we uncomment these lines we'll get a warning:

`  ::warning::Multiple artifacts found, defaulting to first.` because of following following response:

```json
{
    "artifacts": [
        {
            "workflowRunBackendId": "1",
            "workflowJobRunBackendId": "1",
            "databaseId": "1",
            "name": "a",
            "createdAt": "2024-08-22T17:37:41.104232900Z"
        },
        {
            "workflowRunBackendId": "1",
            "workflowJobRunBackendId": "1",
            "databaseId": "1",
            "name": "b",
            "createdAt": "2024-08-22T17:37:31.607801900Z"
        }
    ]
}
```

And `cat downloaded/file.txt` will print `a content` because it downloaded `a` artifact not the `b` artifact.

### Workflow content

```yml
name: Bugged

jobs:
  test:
    runs-on: windows
    steps:
      - run: |
          mkdir -p a
          mkdir -p b
      - run: echo "a content" > a/file.txt
      - run: echo "b content" > b/file.txt
      - uses: actions/upload-artifact@v4
        with:
          name: a
          path: ./a
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: b
          path: ./b
          if-no-files-found: error
      - uses: actions/download-artifact@v4
        with:
          name: b
          path: ./downloaded
      - run: cat downloaded/file.txt
```

### Relevant log output

```sh
[Bugged/test]   💬  ::debug::Body: {%0A  "artifacts": [%0A    {%0A      "workflowRunBackendId": "1",%0A      "workflowJobRunBackendId": "1",%0A      "databaseId": "1",%0A      "name": "a",%0A      "createdAt": "2024-08-22T17:37:41.104232900Z"%0A    },%0A    {%0A      "workflowRunBackendId": "1",%0A      "workflowJobRunBackendId": "1",%0A      "databaseId": "1",%0A      "name": "b",%0A      "createdAt": "2024-08-22T17:37:31.607801900Z"%0A    }%0A  ]%0A}
[Bugged/test]   🚧  ::warning::Multiple artifacts found, defaulting to first.
[Bugged/test]   💬  ::debug::[Request] GetSignedArtifactURL http://192.168.31.59:34567/twirp/github.actions.results.api.v1.ArtifactService/GetSignedArtifactURL
[Bugged/test]   💬  ::debug::[Response] - 200
[Bugged/test]   💬  ::debug::Headers: {%0A  "content-type": "application/json;charset=utf-8",%0A  "date": "Thu, 22 Aug 2024 17:40:41 GMT",%0A  "content-length": "237"%0A}
[Bugged/test]   💬  ::debug::Body: {%0A  "signedUrl": "http://192.168.31.59:34567/twirp/github.actions.results.api.v1.ArtifactService/DownloadArtifact?sig=o_ckWtmUh0AtNWvkayk1-5nBauAc3xsTsRGgS21syzk=&expires=2024-08-22+20%253A40%253A41.2640052+%252B0200+CEST&artifactName=a&taskID=1"%0A}
| Redirecting to blob download url: http://192.168.31.59:34567/twirp/github.actions.results.api.v1.ArtifactService/DownloadArtifact
| Starting download of artifact to: C:\Users\Marcin\.cache\act\12edfb9afc9aa2b3\hostexecutor\downloaded
| (node:18208) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
| (Use `node --trace-deprecation ...` to show where the warning was created)
| Artifact download completed successfully.
| Total of 1 artifact(s) downloaded
| Download artifact has finished successfully
[Bugged/test]   ✅  Success - Main actions/download-artifact@v4
[Bugged/test]   ⚙  ::set-output:: download-path=C:\Users\Marcin\.cache\act\12edfb9afc9aa2b3\hostexecutor\downloaded
[Bugged/test] ⭐ Run Main cat downloaded/file.txt
| a content
[Bugged/test]   ✅  Success - Main cat downloaded/file.txt
[Bugged/test] Cleaning up container for job test
[Bugged/test] 🏁  Job succeeded
```
