### ISSUE TITLE
ERRO[0010] Error while evaluating matrix: Invalid JSON: invalid character '$' looking for beginning of value 

### ISSUE THREAD

**Issue by brianjmurrell** [nektos/act#2447]
### Bug report info

```plain text
act version:            0.2.66
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            unix:///run/user/1001/podman/podman.sock
Sockets found:
        /var/run/docker.sock(broken)
        $XDG_RUNTIME_DIR/podman/podman.sock
Config files:           
        /home/brian/.config/act/actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
        /home/brian/.actrc:
                -s GITHUB_TOKEN=[redacted]
                --container-daemon-socket=unix:///run/user/1001/podman/podman.sock
Build info:
        Go version:            go1.22.6
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:         
        Build settings:
                -buildmode:           pie
                -compiler:            gc
                -trimpath:            true
                DefaultGODEBUG:       httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
                CGO_ENABLED:          1
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
Docker Engine:
        Engine version:        5.2.2
        Engine runtime:        crun
        Cgroup version:        2
        Cgroup driver:         systemd
        Storage driver:        overlay
        Registry URI:          
        OS:                    fedora
        OS type:               linux
        OS version:            40
        OS arch:               amd64
        OS kernel:             6.10.6-200.fc40.x86_64
        OS CPU:                12
        OS memory:             63943 MB
        Security options:
                name=seccomp,profile=default
                name=rootless
                name=selinux
```

### Command used with act

```sh
act --artifact-server-path=/var/tmp/artifacts --use-new-action-cache=false --pull=false -P self-hosted=-self-hosted -P light=-self-hosted -j Call-RPM-Build
```

### Describe issue

When a job is skipped due to a `needs` being skipped, it doesn't actually skip but instead emits an error from the job:

time="2024-09-10T15:09:27-04:00" level=error msg="Error while evaluating matrix: Invalid JSON: invalid character '$' looking for beginning of value"
time="2024-09-10T15:09:27-04:00" level=fatal msg="Failed to decode node {4 0 !!map   <nil> [0xc0000212c0 0xc000021360]    289 9} into *map[string][]interface {}: yaml: unmarshal errors:\n  line 289: cannot unmarshal !!str `${{ fro...` into []interface {}"

### Workflow content

```yml
…
  Build-RPM:
    name: Build RPM
    permissions:
      statuses: write
    runs-on: [self-hosted, docker]
    needs: [Calc-rpm-build-matrix,
            Import-commit-message]
    if: 
        (inputs.BRANCH != '' ||
         needs.Import-commit-pragmas.outputs.run-gha == 'true' ||
         github.event_name == 'workflow_dispatch') &&
        needs.Import-commit-pragmas.outputs.rpm-test-version == '' &&
        needs.Create-symlinks.result == 'success' &&
        ((!cancelled()) || success() || failure())
    strategy:
      matrix:
        distro: ${{ fromJSON(needs.Calc-rpm-build-matrix.outputs.matrix) }}
      fail-fast: false
    env:
…
```

### Relevant log output

```sh
Too much output to parse through line by line ensuring that no private/sensitive data is being sent, such as I found being sent from my actrc file.
```

### Additional information

In this run that emits the error, `Calc-rpm-build-matrix` is skipped, so `Build-RPM` should be also but clearly it's not since the line 298 being complained about is the line:

```
distro: ${{ fromJSON(needs.Calc-rpm-build-matrix.outputs.matrix) }}
```

from the `strategy` -> `matrix` in the workflow snippet above.

If the error and cause from what I have provided is not obvious enough, I will see if I can distill down my complicated workflows into a simple reproducer.

**Comment by brianjmurrell** [comment]
> Yes this is a known issue at least for me and has been raised a few times, order of if and matrix is incorrect.

~~Am I understanding correctly that you are suggesting that I need to move `strategy` before `if:`?~~  A little experiment here seems to confirm that is the case.

I was not aware that there was ordering specifics in GitHub's workflow files.  TIL.  Is there any documentation on the ordering specifics so that I don't fall into this trap again because it seems I have a different job that is being executed in _act_ that does not get executed on GitHub:

```yaml
  Calc-rpm-build-matrix:
    name: Calculate RPM Build Matrix
    runs-on: [self-hosted, wolf]
    needs: [Import-commit-pragmas, Create-symlinks, Import-commit-message]
    if: needs.Import-commit-pragmas.outputs.skip-build != 'true'
    outputs:
      distros: ${{ steps.distros.outputs.text }}
      matrix: ${{ steps.matrix.outputs.text }}
    steps:
```

when `Create-symlinks` is skipped.

> Keep in mind I can't handle this issue tracker alone and long standing issues like this get down priotised by me as my usecase doesn't depend on this part of act

Understood.  I did check the issue log before opening this issue but I didn't see anything matching.  Maybe my search was just not good enough.
