### ISSUE TITLE
How do I override and set a private github server?

### ISSUE THREAD

**Issue by kingrichard2005** [nektos/act#2465]
### Bug report info

```plain text
act version:            0.2.67
GOOS:                   windows
GOARCH:                 amd64
NumCPU:                 4
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        \\.\pipe\docker_engine(broken)
Config files:
        C:\Users\myfolder\.actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.21.13
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.67 -X main.commit=f75a2d8b38cc3b929ab652c0994d6d33f6584ed9 -X main.date=2024-09-10T18:17:24Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 windows
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         f75a2d8b38cc3b929ab652c0994d6d33f6584ed9
                vcs.time:             2024-09-10T18:17:07Z
                vcs.modified:         false
Docker Engine:
        Engine version:        20.10.21
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Rancher Desktop WSL Distribution
        OS type:               linux
        OS version:            0.34
        OS arch:               x86_64
        OS kernel:             5.15.153.1-microsoft-standard-WSL2
        OS CPU:                4
        OS memory:             5930 MB
        Security options:
                name=seccomp,profile=default
```

### Command used with act

```sh
act -s GITHUB_TOKEN="$(gh auth token)" --secret-file ./github_action_test.secrets -j lint -P self-hosted=catthehacker/ubuntu:act-20.04
```

### Describe issue

I'm using act version 0.2.67, I have a workflow that uses a private Github Enterprise server to host my custom GHA actions, e.g. https://git.my-org.com/myteam/gha-setup-node.  The problem is when I run the command it looks at the public https://github.com instead of my private Github enterprise server https://git.my-org.com.  Why does that happen?  And how can we fix it?   I'm also not sure why it says the "Job succeeded" then subsequently reports the error due to the repo not being found.  Help is appreciated

[my-api-ci/install-packages] Unable to clone https://github.com/myteam/gha-setup-node refs/heads/v1: repository not found
[myapi-ci/install-packages] Cleaning up container for job install-packages
[my-api-ci/install-packages] �  Job succeeded
Error: repository not found

### Workflow content

```yml
name: my-api-ci
on:
  workflow_dispatch:
    inputs:
      deployDockerImageJob:
        description: "Deploy Docker Image"
        required: false
        type: boolean
      deployHelmChartJob:
        description: "Deploy Helm Chart"
        required: false
        type: boolean
      runIntTests:
        description: "Run Integration Tests"
        required: false
        type: boolean
  push:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
concurrency:
  group: my-api-ci-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  install-packages:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node env
        uses: myteam/gha-setup-node@v1
        with:
          node-version: 18.20.4
          cache-dependency-path: |
            ./yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
```

### Relevant log output

```sh
[my-api-ci/install-packages] Unable to clone https://github.com/myteamrepo/gha-setup-node refs/heads/v1: repository not found
[my-api-ci/install-packages] Cleaning up container for job install-packages
[my-api-ci/install-packages] �  Job succeeded
Error: repository not found
```
