### ISSUE TITLE
Request to Disable IPv6 in Ubuntu Images to Enable JDK Installations

### ISSUE THREAD

**Issue by xingzhang-pku** [nektos/act#2482]
### Act version

act version 0.0.0-SNAPSHOT-a30d171

### Issue Description
We are encountering an issue where our continuous integration (CI) process fails during JDK installation via IPv6 connections. Specifically, attempts to access the JDK bundles from Azul's API through IPv6 consistently fail, while IPv4 connections are successful.

### Affected Images
The issue affects the following Docker images used in our GitHub Actions workflows:
- `catthehacker/ubuntu:act-latest-20240822`
- `catthehacker/ubuntu:act-22.04-20240822`
- `catthehacker/ubuntu:act-20.04-20240822`

### Expected Behavior
We propose to disable IPv6 in the aforementioned Docker images to ensure reliable access to necessary external resources like JDK downloads during CI processes. This change would help not only our workflows but also other users who might face similar networking issues.

### Steps to Reproduce
1. Run a CI job using any of the above images.
2. Attempt to install JDK from the following URL via IPv6: `https://api.azul.com/zulu/download/community/v1.0/bundles/?os=linux&ext=tar.gz&bundle_type=jdk&javafx=false&arch=x86&hw_bitness=64`

### Additional Information
Disabling IPv6 would be a temporary solution until a more robust handling of IPv4 and IPv6 compatibility issues can be implemented. This adjustment would facilitate a smoother development and testing process for teams relying on these Docker images.

Thank you for considering this enhancement to support better CI configuration and stability.

**Comment by xingzhang-pku** [comment]
@ChristopherHX Could you please please review the above issue? Your assistance would be greatly appreciated. Thank you!

**Comment by sebastien-perpignane** [comment]
Hi,

How do you know it is related to IP v6 ? What kind of error do you get ?

**Comment by xingzhang-pku** [comment]
Thanks for your reply. I give the more detailed information below.
## act command
`act -j 'build_and_test' --rm -s GITHUB_TOKEN --use-new-action-cache --tool-cache-volume act-cache-adaa-polsl_RuleKit-bdcddd -P ubuntu-20.04=catthehacker/ubuntu:act-20.04-20240822 -P ubuntu-22.04=catthehacker/ubuntu:act-22.04-20240822 -P ubuntu-latest=catthehacker/ubuntu:act-latest-20240822`

## workflow
```
name: GitHub Actions CI

on:
 push:
    branches:
      - master
    paths-ignore:
      - '**.md'    
 pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - '**.md'    
 workflow_dispatch:

jobs:
  python_script:
    name: Checking Java project version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checking Java project version
      continue-on-error: true
      run: |
        python ./.github/workflows/scripts/check_java_version.py
        
  build_and_test:
    name: Checking gradle build and running tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and test with Gradle
        run: ./adaa.analytics.rules/gradlew build
```


## CI log
```==== STDOUT ====
[GitHub Actions CI/Checking gradle build and running tests] 🚀  Start image=catthehacker/ubuntu:act-latest-20240822
[GitHub Actions CI/Checking gradle build and running tests]   🐳  docker pull image=catthehacker/ubuntu:act-latest-20240822 platform= username= forcePull=true
[GitHub Actions CI/Checking gradle build and running tests]   🐳  docker create image=catthehacker/ubuntu:act-latest-20240822 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[GitHub Actions CI/Checking gradle build and running tests]   🐳  docker run image=catthehacker/ubuntu:act-latest-20240822 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[GitHub Actions CI/Checking gradle build and running tests]   🐳  docker exec cmd=[node --no-warnings -e console.log(process.execPath)] user= workdir=
[GitHub Actions CI/Checking gradle build and running tests] ⭐ Run Main actions/checkout@v2
[GitHub Actions CI/Checking gradle build and running tests]   🐳  docker cp src=/Data2/v-zhangxing/cache/adaa-polsl_RuleKit/. dst=/Data2/v-zhangxing/cache/adaa-polsl_RuleKit
[GitHub Actions CI/Checking gradle build and running tests]   ✅  Success - Main actions/checkout@v2
[GitHub Actions CI/Checking gradle build and running tests] ⭐ Run Main Set up JDK 1.8
[GitHub Actions CI/Checking gradle build and running tests]   🐳  docker exec cmd=[/opt/acttoolcache/node/18.20.4/x64/bin/node /var/run/act/actions/actions-setup-java@v1/dist/setup/index.js] user= workdir=
[GitHub Actions CI/Checking gradle build and running tests]   💬  ::debug::isExplicit: 
[GitHub Actions CI/Checking gradle build and running tests]   💬  ::debug::explicit? false
[GitHub Actions CI/Checking gradle build and running tests]   💬  ::debug::evaluating 0 versions
[GitHub Actions CI/Checking gradle build and running tests]   💬  ::debug::match not found
[GitHub Actions CI/Checking gradle build and running tests]   💬  ::debug::Downloading JDK from Azul
[GitHub Actions CI/Checking gradle build and running tests]   ❓  ::error::connect ENETUNREACH 2606:4700:4400::6812:23d4:443
[GitHub Actions CI/Checking gradle build and running tests]   ❌  Failure - Main Set up JDK 1.8
[GitHub Actions CI/Checking gradle build and running tests] exitcode '1': failure
[GitHub Actions CI/Checking gradle build and running tests] ⭐ Run Post Set up JDK 1.8
[GitHub Actions CI/Checking gradle build and running tests]   🐳  docker exec cmd=[/opt/acttoolcache/node/18.20.4/x64/bin/node /var/run/act/actions/actions-setup-java@v1/dist/cleanup/index.js] user= workdir=
[GitHub Actions CI/Checking gradle build and running tests]   ✅  Success - Post Set up JDK 1.8
[GitHub Actions CI/Checking gradle build and running tests] Cleaning up container for job Checking gradle build and running tests
[GitHub Actions CI/Checking gradle build and running tests] 🏁  Job failed

==== STDERR ====
time="2024-10-11T15:46:54Z" level=info msg="Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock'"
Error: Job 'Checking gradle build and running tests' failed
```
