### ISSUE TITLE
Job waits for all initial parallel jobs to finish rather than just dependent job

### ISSUE THREAD

**Issue by MarkForesta** [nektos/act#2492]
### Bug report info

```plain text
act version:            0.2.68
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
	$HOME/.docker/run/docker.sock
Config files:           
	/Users/markforesta/Library/Application Support/act/actrc:
		-P ubuntu-latest=node:16-buster-slim
		-P ubuntu-22.04=node:16-bullseye-slim
		-P ubuntu-20.04=node:16-buster-slim
		-P ubuntu-18.04=node:16-buster-slim
Build info:
	Go version:            go1.23.1
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.68
		DefaultGODEBUG:       asynctimerchan=1,gotypesalias=0,httplaxcontentlength=1,httpmuxgo121=1,httpservecontentkeepheaders=1,tls10server=1,tls3des=1,tlskyber=0,tlsrsakex=1,tlsunsafeekm=1,winreadlinkvolume=0,winsymlink=0,x509keypairleaf=0,x509negativeserial=1
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               arm64
		GOOS:                 darwin
		GOARM64:              v8.0
Docker Engine:
	Engine version:        20.10.14
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               aarch64
	OS kernel:             5.10.104-linuxkit
	OS CPU:                4
	OS memory:             3933 MB
	Security options:
		name=seccomp,profile=default
		name=cgroupns
```

### Command used with act

```sh
act
```

### Describe issue

I made a very minimal workflow that has 2 jobs that start in parallel and one job that is dependent on the faster job. I expect

```
hello_world_job and another_job to start
another_job to complete
depends_on_another_job to start
depends_on_another_job to complete
hello_world_job to complete
```

What actually happens is 
```
hello_world_job and another_job starts
another_job completes
hello_world_job completes
depends_on_another_job starts
depends_on_another_job completes
```

I pushed it up to a private Github Repository and the actions tab works as expected.

### Workflow content

```yml
name: Hello World Workflow

on: [push]

jobs:
    hello_world_job:
        runs-on: ubuntu-latest

        steps:
            - name: Sleep 10 && Print Message
              run: sleep 10 && echo "This message takes a while"

    another_job:
        runs-on: ubuntu-latest

        steps:
            - name: Print Another Message
              run: echo "This is another job running in parallel!"
    
    depends_on_another_job:
        needs: [another_job]
        runs-on: ubuntu-latest

        steps:
            - name: Print Message
              run: echo "This job depends on another_job"
```

### Relevant log output

```sh
| This is another job running in parallel!
[Hello World Workflow/another_job    ]   ✅  Success - Main Print Another Message
...
| This message takes a while
[Hello World Workflow/hello_world_job]   ✅  Success - Main Sleep 10 && Print Message
...
| This job depends on another_job
[Hello World Workflow/depends_on_another_job]   ✅  Success - Main Print Message
```

### Additional information

I understand if I was doing something real maybe the actual work is happening in parallel in the correct order and maybe we are just having a difficult time displaying it. 

Forgive me I am very new to using act if this is a limitation of the framework that we already knew about. I didn't find any other issues regarding this.
