### ISSUE TITLE
PowerShell steps load profile during execution

### ISSUE THREAD

**Issue by HeyItsGilbert** [nektos/act#2545]
## Expected Behavior
Running a PowerShell script or command should run in it's own process without a profile being loaded.

## Current Behavior
Currently the invocation runs `powershell.exe -command . {0}` where the commands are replaced in.

## Possible Solution
Append `-NoProfile` to the powershell/pwsh calls.`

## Steps to Reproduce
1. On the instance running the command create a profile.
   - See https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4#how-to-create-a-profile
   - Add something like `throw 'An error in your profile'`
2. Create a github workflow that runs powershell.

```yaml filename="helloworld.yaml"
on:
  push:
jobs:
  test:
    runs-on: windows-latest
  steps:
    - run: |
      Write-Host "Hello world"
 ```
 
3. Run act on the workflow while using `-self-hosted`
   - `act --platform windows-latest=-self-hosted --workflows "./.github/workflows/helloworld.yaml"`
5. See error

## Context
We are currently attach with `-P windows=self-host` on a windows machine.
