### ISSUE TITLE
Composite Actions leak unnamed step outputs

### ISSUE THREAD

**Issue by ChristopherHX** [nektos/act#2553]
### Bug report info

```plain text
N/A
```

### Command used with act

```sh
N/A
```

### Describe issue

You don't need to map composite actions outputs for having the composite step outputs set, this make false claims about Actions

### Workflow content

```yml
N/A
```

### Relevant log output

```sh
N/A
```

**Comment by McNultyyy** [comment]
Here is a self-contained reproduction for this, since the report has no repro attached.

**`./leaky/action.yml`** — declares one output, its inner step writes two:

```yaml
name: 'leaky'
outputs:
  declared:
    description: 'declared'
    value: ${{ steps.inner.outputs.declared }}
runs:
  using: composite
  steps:
    - id: inner
      shell: bash
      run: |
        echo "declared=i-am-declared" >> "$GITHUB_OUTPUT"
        echo "undeclared=i-should-not-escape" >> "$GITHUB_OUTPUT"
```

**`.github/workflows/repro.yml`**:

```yaml
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: composite
        uses: ./leaky
      - run: |
          echo "declared   = '${{ steps.composite.outputs.declared }}'"
          echo "undeclared = '${{ steps.composite.outputs.undeclared }}'"
```

On current master:

```
| declared   = 'i-am-declared'
| undeclared = 'i-should-not-escape'
```

`undeclared` is not in the action's `outputs:`, so on GitHub it stays scoped to the inner step and the outer step sees an empty string.

**Root cause:** every step writes its file commands to the same paths in the job container — `workflow/outputcmd.txt`, `statecmd.txt`, `envs.txt`, `pathcmd.txt`, `SUMMARY.md` — and reads them back when it finishes. The composite's inner step writes to `$GITHUB_OUTPUT`, and those lines are still sitting in the shared file when the enclosing job step processes it, so they are attributed to the outer step. The same mechanism means any step can pick up the previous step's leftovers, not just composites.

#6154 gives each step execution its own directory and records the results against the id of the step they belong to. With it:

```
| declared   = 'i-am-declared'
| undeclared = ''
```

It carries a `composite-undeclared-outputs` fixture covering plain and nested composites over both `$GITHUB_OUTPUT` and `::set-output`, which fails on master and passes with the change. Same underlying cause as #2184 and #2697.
