### ISSUE TITLE
act doesn't honor options for actions/checkout

### ISSUE THREAD

**Issue by mgerring** [nektos/act#258]
I need to be able to set the `depth` input to at least 2 for `actions/checkout` in my workflow -- it's needed by another action further down in the workflow. But `act` doesn't seem to pick up the setting or act on it.

No matter what I set `fetch-depth` to I get this error:

```::error::This appears to be a shallow clone of your project. To determine whether the project version has changed and a new tag needs to be created, you should set a `fetch-depth` of 2 or higher on `@actions/checkout`.```

**Comment by cplee** [comment]
@mgerring - can you share the snippet of your workflow yaml with the checkout step?

**Comment by mgerring** [comment]
```
steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
```
