### ISSUE TITLE
GitHub.com/u-root/gobusy test fails

### ISSUE THREAD

**Issue by rminnich** [nektos/act#2598]
### Bug report info

```plain text
act version:            0.2.70
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
	$XDG_RUNTIME_DIR/podman/podman.sock
Config files:
	/home/rminnich/.config/act/actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.23.2
	Module path:           github.com/nektos/act
	Main version:          (devel)
	Main path:             github.com/nektos/act
	Main checksum:
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		CGO_ENABLED:          1
		CGO_CFLAGS:
		CGO_CPPFLAGS:
		CGO_CXXFLAGS:
		CGO_LDFLAGS:
		GOARCH:               amd64
		GOOS:                 linux
		GOAMD64:              v1
		vcs:                  git
		vcs.revision:         0ca1e1833458f9491b882b72c883b25d6cb8b806
		vcs.time:             2024-12-31T03:12:35Z
		vcs.modified:         false
Docker Engine:
	Engine version:        24.0.7
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         systemd
	Storage driver:        overlay2
	Registry URI:          https://index.docker.io/v1/
	OS:                    Pop!_OS 22.04 LTS
	OS type:               linux
	OS version:            22.04
	OS arch:               x86_64
	OS kernel:             6.9.3-76060903-generic
	OS CPU:                12
	OS memory:             39956 MB
	Security options:
		name=apparmor
		name=seccomp,profile=builtin
		name=cgroupns
```

### Command used with act

```sh
Note that the suggested command in here is wrong:
act -P ubuntu:latest -v -d
Error: unknown shorthand flag: 'd' in -d
but I ran
act -P ubuntu:latest -v
```

### Describe issue

checkout GitHub.com/u-root/gobusybox
run act
act -P ubuntu:latest -v
there are multiple failures that do not occur at GitHub.com

### Link to GitHub repository

https://github.com/u-root/gobusybox

### Workflow content

```yml
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Every day at 8am.
    - cron: "0 8 * * *"

# Cancel running workflows on new push to a PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tidy:
    name: Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: gofmt
        run: cd src && test -z "$(gofmt -s -l $(find -name '*.go'))"

      - name: go mod tidy
        run: |
          cd src
          go mod tidy
          git status
          if [[ -n "$(git status --porcelain .)" ]]; then
            echo 'go.mod/go.sum is out-of-date: run `go mod tidy` and then check in the changes'
            echo 'If `go mod tidy` results in no changes, make sure you are using the latest relase of Go'
            git status --porcelain .
            exit 1
          fi

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ['1.20', '1.21.x', '1.22.x']
    steps:
      - uses: actions/checkout@v4
        with:
          path: go/src/github.com/u-root/gobusybox

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}

      - name: Test
        run: |
          cd go/src/github.com/u-root/gobusybox/src

          # Make sure GO111MODULE=off cases work.
          go mod vendor

          # Unit tests cover both GO111MODULE=on and off cases.
          GOPATH=$GITHUB_WORKSPACE/go go test -covermode=atomic -coverprofile cover.out ./...

      - uses: codecov/codecov-action@036b81c4b4e8314b391265bc226440f9e2117e2a
        env:
          CODECOV_TOKEN: 'bf25d8b2-b4f9-43f4-b578-64eefbe31e61'
        with:
          working-directory: go/src/github.com/u-root/gobusybox
          flags: ${{ matrix.goversion }}
          fail_ci_if_error: true
          verbose: true

  test-gopath:
    name: gobuilds-gopath
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ['1.20', '1.21.x', '1.22.x']
    steps:
      - uses: actions/checkout@v4
        with:
          path: go/src/github.com/u-root/gobusybox

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}

      - name: Test
        run: |
          cd go/src/github.com/u-root/gobusybox
          mkdir cover
          GOPATH=$GITHUB_WORKSPACE/go GOCOVERDIR=$(pwd)/cover ./gobuilds-gopath.sh
          go tool covdata textfmt -i=cover -o cover.out

      - uses: codecov/codecov-action@036b81c4b4e8314b391265bc226440f9e2117e2a
        env:
          CODECOV_TOKEN: 'bf25d8b2-b4f9-43f4-b578-64eefbe31e61'
        with:
          working-directory: go/src/github.com/u-root/gobusybox
          flags: ${{ matrix.goversion }}
          fail_ci_if_error: true
          verbose: true

  test-gomodule:
    name: gobuilds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ['1.20', '1.21.x', '1.22.x']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}

      - name: Test
        run: |
          mkdir cover
          GOCOVERDIR=$(pwd)/cover ./gobuilds.sh
          go tool covdata textfmt -i=cover -o cover.out

      - uses: codecov/codecov-action@036b81c4b4e8314b391265bc226440f9e2117e2a
        env:
          CODECOV_TOKEN: 'bf25d8b2-b4f9-43f4-b578-64eefbe31e61'
        with:
          flags: ${{ matrix.goversion }}
          fail_ci_if_error: true
          verbose: true

  test-external-workspaces:
    name: test-external-workspaces
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ['1.20', '1.21.x', '1.22.x']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}

      - name: Test
        run: |
          mkdir cover
          GOCOVERDIR=$(pwd)/cover ./test-external-workspaces.sh
          go tool covdata textfmt -i=cover -o cover.out

      - uses: codecov/codecov-action@036b81c4b4e8314b391265bc226440f9e2117e2a
        env:
          CODECOV_TOKEN: 'bf25d8b2-b4f9-43f4-b578-64eefbe31e61'
        with:
          flags: ${{ matrix.goversion }}
          fail_ci_if_error: true
          verbose: true

  test-external-gopath:
    name: test-external-gopath
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: ['1.20', '1.21.x', '1.22.x']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goversion }}

      - name: Test
        run: |
          mkdir cover
          GOCOVERDIR=$(pwd)/cover ./test-external-gopath.sh
          go tool covdata textfmt -i=cover -o cover.out

      - uses: codecov/codecov-action@036b81c4b4e8314b391265bc226440f9e2117e2a
        env:
          CODECOV_TOKEN: 'bf25d8b2-b4f9-43f4-b578-64eefbe31e61'
        with:
          flags: ${{ matrix.goversion }}
          fail_ci_if_error: true
          verbose: true
```

### Relevant log output

```sh
Output is too long.
```
