### ISSUE TITLE
Freezes downloading setup stuff

### ISSUE THREAD

**Issue by gisborne** [nektos/act#2618]
### Bug report info

```plain text
% act --bug-report
act version:            0.2.71
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
	$HOME/.docker/run/docker.sock
Config files:           
	/Users/e86037/Library/Application Support/act/actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.23.4
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.71
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               arm64
		GOOS:                 darwin
		GOARM64:              v8.0
Docker Engine:
	Engine version:        27.4.0
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlayfs
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               aarch64
	OS kernel:             6.10.14-linuxkit
	OS CPU:                12
	OS memory:             7836 MB
	Security options:
		name=seccomp,profile=unconfined
		name=cgroupns
```

### Command used with act

```sh
act
```

### Describe issue

Gets to here then goes no further. Just stops. -v provides no more information. Have waited a whole day.

```
| The following NEW packages will be installed:
|   adwaita-icon-theme apparmor dbus-user-session firefox fuse3
|   gtk-update-icon-cache humanity-icon-theme libaec0 libatk1.0-0 libatk1.0-data
|   libavahi-client3 libavahi-common-data libavahi-common3 libcdt5 libcfitsio9
|   libcgif0 libcgraph6 libcups2 libfuse3-3 libgail-common libgail18 libgd3
|   libgeos++-dev libgeos-c1v5 libgeos-dev libgeos3.10.2 libgsf-1-114
|   libgsf-1-common libgsl27 libgslcblas0 libgtk2.0-0 libgtk2.0-bin
|   libgtk2.0-common libgts-0.7-5 libgts-bin libgvc6 libhdf5-103-1
|   libimagequant0 libmatio11 libnspr4 libnss3 libopenslide0 liborc-0.4-0
|   libpathplan4 libpoppler-glib8 libpoppler118 libsz2 libvips42 libxcomposite1
|   libxcursor1 libxdamage1 libxfixes3 libxi6 libxinerama1 libxpm4 libxrandr2
|   nip2 poppler-data snapd squashfs-tools systemd-hwe-hwdb ubuntu-mono udev
| 0 upgraded, 63 newly installed, 0 to remove and 27 not upgraded.
| Need to get 51.4 MB of archives.
| After this operation, 217 MB of additional disk space will be used.
```

### Workflow content

```yml
name: Formatting
on: [push]
jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      RAILS_ENV: development
    steps:
      - name: Install libvips package for ruby-vips gem
        run: sudo apt-get update && sudo apt-get install libvips42
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.16.1
          cache: yarn
      - name: Install YARN packages
        run: yarn install --frozen-lockfile
      - name: Run prettier
        run: ./node_modules/.bin/prettier --check '**/*'



name: Linting
on: [push]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      RAILS_ENV: development
    steps:
      - name: Install libvips package for ruby-vips gem
        run: sudo apt-get update && sudo apt-get install libvips42
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.16.1
          cache: yarn
      - name: Install YARN packages
        run: yarn install --frozen-lockfile
      - name: Run rubocop
        run: bundle exec rubocop --parallel


name: Test Dev Environment
on: [push]
jobs:
  test_dev_environment:
    name: Test Dev Environment
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:13-3.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
      redis:
        image: redis:7.0.11-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
      DISABLE_SPRING: 1
      DOMAIN_NAME: pinseeker-backend.test
      DOMAIN_NAME_SHORT_URL: pinseeker-backend.test
      APP_DOMAIN_NAME: app.pinseeker-backend.test
      JWT_HMAC_SECRET: 8664a392e6c947c123bcd6e92a8f38d9e7a3b285034136884ef94621bb365b9f8e8051e28db99c9a2ed87f2e7fd9c6b9ae1038e8de47297f72b79ce392ac7a2e
      JWT_ISS_SUFFIX: GitHub Actions
      NODE_ENV: development
      RAILS_ENV: development
      REDIS_URL: redis://localhost:6379/0
    steps:
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install libgeos++-dev libvips42
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.16.1
          cache: yarn
      - name: Install YARN packages
        run: yarn install --frozen-lockfile
      - name: Load environment variables from .env.template
        uses: falti/dotenv-action@v1.0.4
        with:
          path: .env.template
          keys-case: upper
          export-variables: true
      - name: Run rake db:schema:load db:seed
        run: bundle exec rake db:schema:load db:seed


name: Tests
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [15]
        ci_node_index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    services:
      postgres:
        image: postgis/postgis:13-3.4-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    env:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
      DISABLE_SPRING: 1
      DOMAIN_NAME: pinseeker-backend.test
      DOMAIN_NAME_SHORT_URL: pinseeker-backend.test
      APP_DOMAIN_NAME: app.pinseeker-backend.test
      JWT_HMAC_SECRET: 8664a392e6c947c123bcd6e92a8f38d9e7a3b285034136884ef94621bb365b9f8e8051e28db99c9a2ed87f2e7fd9c6b9ae1038e8de47297f72b79ce392ac7a2e
      JWT_ISS_SUFFIX: GitHub Actions
      NODE_ENV: test
      RAILS_ENV: test
    steps:
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install libgeos++-dev libvips42
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.16.1
          cache: yarn
      - name: Install YARN packages
        run: yarn install --frozen-lockfile
      - name: Set up test database
        run: bin/rake db:schema:load
      - name: Run tests
        run: bundle exec parallel_rspec -n $CI_NODE_TOTAL --only-group $CI_NODE_INDEX --group-by runtime --runtime-log spec/parallel_runtime_rspec.log -o '--format documentation'
        env:
          CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          PARALLEL_TEST_FIRST_IS_1: 1
          DONT_OUTPUT_PENDING_EXAMPLES: 1
```

### Relevant log output

```sh
act -v shows nothing more close to the point of stopping.
```

**Comment by MichaelSjogren** [comment]
i seem to have the same issue.

```
act version:            0.2.72
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 12
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
Config files:           
        /home/michael/.config/act/actrc:
                -P ubuntu-latest=catthehacker/ubuntu:act-latest
                -P ubuntu-22.04=catthehacker/ubuntu:act-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:act-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
        Go version:            go1.23.5
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:         
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.72 -X main.commit=be1b6ee581beb205736f837ae4fd3a43f62bc6e6 -X main.date=2025-02-01T02:27:06Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         be1b6ee581beb205736f837ae4fd3a43f62bc6e6
                vcs.time:             2025-02-01T02:26:50Z
                vcs.modified:         false
Docker Engine:
        Engine version:        27.5.1
        Engine runtime:        runc
        Cgroup version:        2
        Cgroup driver:         systemd
        Storage driver:        overlay2
        Registry URI:          https://index.docker.io/v1/
        OS:                    Debian GNU/Linux 12 (bookworm)
        OS type:               linux
        OS version:            12
        OS arch:               x86_64
        OS kernel:             6.1.0-30-amd64
        OS CPU:                12
        OS memory:             31731 MB
        Security options:
                name=apparmor
                name=seccomp,profile=builtin
                name=cgroupns

```

```
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock' 
[CI/build] 🚀  Start image=catthehacker/ubuntu:act-latest
[CI/build]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[CI/build]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[CI/build]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[CI/build]   🐳  docker exec cmd=[node --no-warnings -e console.log(process.execPath)] user= workdir=
[CI/build] ⭐ Run Main actions/checkout@v4
[CI/build]   🐳  docker cp src=/home/michael/worktree/Pi-900S/database-master/. dst=/home/michael/worktree/Pi-900S/database-master
[CI/build]   ✅  Success - Main actions/checkout@v4
[CI/build] ⭐ Run Main Update & install dependencies
[CI/build]   🐳  docker exec cmd=[bash -e /var/run/act/workflow/1] user= workdir=
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                
Get:3 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [3632 B]
Get:4 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main all Packages [1243 B]
Get:5 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [181 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1229 kB]
Get:7 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease [24.6 kB]
Get:8 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy/main amd64 Packages [2957 B]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [3606 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]       
Get:12 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2604 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]     
Get:14 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [45.2 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:11 https://packagecloud.io/github/git-lfs/ubuntu jammy InRelease [29.2 kB] 
Get:16 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:17 https://packagecloud.io/github/git-lfs/ubuntu jammy/main amd64 Packages [2213 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1521 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2904 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [3742 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [53.3 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [81.4 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.2 kB]
Fetched 36.4 MB in 4s (9168 kB/s)                             
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
| 41 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
| The following additional packages will be installed:
|   javascript-common libjs-jquery python-babel-localedata python3-attr
|   python3-babel python3-iniconfig python3-itsdangerous python3-jinja2
|   python3-markupsafe python3-openssl python3-pluggy python3-py
|   python3-pygments python3-pyinotify python3-simplejson python3-toml
|   python3-tz python3-werkzeug
| Suggested packages:
|   apache2 | lighttpd | httpd python-attr-doc python3-asgiref python3-dotenv
|   python-flask-doc python-jinja2-doc python-openssl-doc python3-openssl-dbg
|   python-pygments-doc ttf-bitstream-vera python-pyinotify-doc ipython3
|   python-werkzeug-doc python3-lxml python3-watchdog sqlite3-doc
| The following NEW packages will be installed:
|   javascript-common libjs-jquery python-babel-localedata python3-attr
|   python3-babel python3-flask python3-iniconfig python3-itsdangerous
|   python3-jinja2 python3-markupsafe python3-openssl python3-pluggy python3-py
|   python3-pygments python3-pyinotify python3-pytest python3-simplejson
|   python3-toml python3-tz python3-werkzeug shellcheck sqlite3
| 0 upgraded, 22 newly installed, 0 to remove and 41 not upgraded.
| Need to get 10.2 MB of archives.
| After this operation, 55.0 MB of additional disk space will be used.
^C[CI/build]   ❌  Failure - Main Update & install dependencies
[CI/build] Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.47/containers/5be85a5b7b8b5fb61d45a3eb1721648647b5ec646bec555ef409ca701d6f5a1c/archive?path=%2Fvar%2Frun%2Fact%2Fworkflow%2Fpathcmd.txt": context canceled
[CI/build] Cleaning up container for job build
[CI/build] 🏁  Job succeeded
Error: context canceled
```

**Comment by MichaelSjogren** [comment]
i seem to have fixed my issue. make sure you include the -y yes flag in your upgrade and upgrade commands.

this is my workflow file that fetches sqlite3 and then checks sql syntax.

```yaml
name: Check SQL Syntax

on: [push, pull_request]

jobs:
  check-sql-syntax:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install depends
      run: |
        sudo apt update && sudo apt upgrade -y; sudo apt install sqlite3 -y
    - name: Find and check SQL syntax
      run: |
        for file in $(find ./database/sql -name "*.sql"); do
          sqlite3 :memory: < "$file" || exit 1
        done
```
