### ISSUE TITLE
$PATH gets reset when invoking `uses: paambaati/codeclimate-action@v2.3.0`

### ISSUE THREAD

**Issue by jbooth-mastery** [nektos/act#262]
Hi folks! It looks like the $PATH variable is getting reset when using the codeclimate action. This doesn't happen on github itself, so I'm guessing it is an act bug?

```yaml
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: printenv                                                                
      run: printenv                                                                 
    - name: Act workaround for issue                                                
      id: yarn                                                                      
      run: echo "::set-output name=path::$PATH"                                     
    - name: printenv                                                                
      run: printenv                                                                 
    - name: Test & publish code coverage                                            
      uses: paambaati/codeclimate-action@v2.3.0                                     
      env:                                                                          
        CC_TEST_REPORTER_ID: fake                                                   
        SAVED_PATH: ${{ steps.yarn.outputs.path }}                                  
      with:                                                                         
        coverageCommand: printenv
```

When run, you'll see in the first printenv (before code climate):

```
[CI/build] ⭐  Run printenv
PATH=/opt/hostedtoolcache/node/14.3.0/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

But then on the printenv inside codeclimate-action:

```
[CI/build]   💬  ::debug::✅ CC Reporter before-build checkin completed...
| [command]printenv
| PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
| SAVED_PATH=/opt/hostedtoolcache/node/14.3.0/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

The same behavior also happens with a setup-python against version 3.x -- the path gets mutated and your setup is lost.
