### ISSUE TITLE
Inputs in env not parsed

### ISSUE THREAD

**Issue by kenorb** [nektos/act#263]
Steps to reproduce:
1. On the empty folder, create new repo: `git init`.
2. Create the following files:

### `action.yml`

```
name: 'Test'
inputs:
  MyInput:
    description: 'My input'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MYINPUT: ${{ inputs.MyInput }}
```

### `Dockerfile`

```
FROM ubuntu
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

### `entrypoint.sh`

```
#!/usr/bin/env bash

echo Input: $MYINPUT
```

### `.github/workflows/action.yml`

```
name: Action
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
```

## Problem

The script doesn't print my input.

```
% act -j Test
[Action/Test]   🐳  docker run image=act-test:latest entrypoint=[] cmd=[]
| Input: ${{ inputs.MyInput }}
```

It prints `${{ inputs.MyInput }}`, instead of the value of the variable.
