### ISSUE TITLE
Allow more control over how reusable Github actions are cloned

### ISSUE THREAD

**Issue by mtrmarko** [nektos/act#2672]
### Act version

0.2.74

### Feature description

Running into an issue where I am trying to use `docker/scout-action@v1` Github reusable action. On first workflow execution, act tries to clone this action's repository. Well, the repository is over 6GB in size and cloning kept going very slowly even though I am on a 1Gbps fiber connection. Then after about an hour `watch du -s` stopped incrementing on the repo directory `.cache/act/docker-scout-action@v1` while act kept sitting on `☁  git clone 'https://github.com/docker/scout-action' # ref=v1` step. Trying to do CTRL+C did not immediately stop the run. Took several tries. This repo appears to be large because Docker folks are committing a dist folder with all the pre-compiled binaries of Docker Scout CLI. This adds up. It would be nice to have something like a `--action-fetch-depth` parameter, or similar that would essentially allow act to run something like `git clone --depth 1 --branch v1 https://github.com/docker/scout-action.git docker-scout-action@v1`. Not sure if this fits act design goals or if the request even makes sense. For now, I am going to resort to installing Docker Scout CLI manually and running it as a bash step instead. This is what part of my workflow looked like when using the reusable action:

```yaml
      - name: Run Scout Scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.DOCKER_ORG }}/${{ env.DOCKER_IMAGE }}:latest
          only-fixed: true
          exit-code: true
          sbom: true
          attestation-add: true
```
