### ISSUE TITLE
"sudo: command not found" should never be possible

### ISSUE THREAD

**Issue by Pomax** [nektos/act#269]
Why is the `ubuntu-latest` container claiming that `sudo` doesn't exist? It kind of _has to_ in order to run installers.

```
slname: CI-CD

on:
  push:
    branches:
      - master

jobs:
  tex:
    name: Installing TeX Live and ((Xe)La)TeX related packages
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - name: Installing TeX Live
        run: |
          sudo apt-get update
```

This crashes, even though it _never_ should:

```
[ci.yml/Installing TeX Live and ((Xe)La)TeX related packages] �🚀  Start image=node:12.6-buster-slim
[ci.yml/Installing TeX Live and ((Xe)La)TeX related packages]   �🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[ci.yml/Installing TeX Live and ((Xe)La)TeX related packages] ⭐  Run Installing TeX Live
| /github/workflow/0: line 2: sudo: command not found
[ci.yml/Installing TeX Live and ((Xe)La)TeX related packages]   ❌  Failure - Installing TeX Live
Error: exit with `FAILURE`: 127
```

**Comment by Senui** [comment]
+1; installing the `sudo` package is also not required on the actual Github Actions. I currently work around this by doing `apt update && apt install sudo` prior to my regular workflow, just for act to run without this initial failure.

**Comment by Pomax** [comment]
it's not required _but it exists_ so that 3rd party source compiles don't break when they _rely_ on `sudo` existing =)

**Comment by przemub** [comment]
The issue is still prevalent and prohibits running many actions.

**Comment by andrewnitu** [comment]
@Senui where do you insert this line?

**Comment by Senui** [comment]
> @Senui where do you insert this line?

I just add it as the first step:

```
jobs:
  tex:
    name: Installing TeX Live and ((Xe)La)TeX related packages
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - name: Install sudo package
        run: apt update && apt install sudo
      - name: Installing TeX Live
        run: |
          sudo apt-get update
```

**Comment by andrewnitu** [comment]
> > @Senui where do you insert this line?
> 
> I just add it as the first step:

Ah gotcha, i guess installing it again (from the perspective of the actual GitHub actions running on the web) won't cause any harm. Thanks! :)

**Comment by cameron-martin** [comment]
I'm having this problem too. Can it be reopened?

**Comment by fabrice102** [comment]
One workaround if you do not want to run `apt-get update` and `apt-get install sudo` on Github actions is to add the following conditional step:

```yaml
      - name: Fix Act environment # see https://github.com/nektos/act/issues/269
        if: ${{ !env.ACT }}
        run: |
          apt-get update
          apt-get install sudo
```
