### ISSUE TITLE
Incorrect encoding in step output

### ISSUE THREAD

**Issue by mrjackdavis** [nektos/act#273]
It appears `steps.x.output` is not encoded correctly. 

The example below works perfectly fine in Github actions. But in `act`, `jq` throws the error:

```
parse error: Invalid numeric literal at line 1, column 5
```

Further inspection with `jq -R` suggest there is an encoding issue. Such a command outputs a string littered with `%!A(MISSING)`. See below:

```
{%!A(MISSING)  \"ref\": \"refs/heads/master\",%!A(MISSING)  \"node_id\": \"REDACTED\",%!A(MISSING)  \"url\": \"https://api.github.com/repos/REDACTED/git/refs/heads/master\",%!A(MISSING)  \"object\": {%!A(MISSING)    \"sha\": \"REDACTED\",%!A(MISSING)    \"type\": \"commit\",%!A(MISSING)    \"url\": \"https://api.github.com/repos/REDACTED/git/commits/REDACTED\"%!A(MISSING)  }%!A(MISSING)}
```

I expect there is an issue with multiline output. I think `%0A` exists in the output and is being inadvertantly operated upon

# Example workflow

```
name: Tag master

on:
  - push

jobs:
  tag-master:
    runs-on: ubuntu-latest
    name: "tag-master"
    steps:
      - uses: octokit/request-action@v2.0.6
        id: get_master_ref
        with:
          route: GET /repos/:repository/git/ref/heads/master
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo '${{ steps.get_master_ref.outputs.data }}' | jq"
```
