### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by mperham** [nektos/act#2758]
### Bug report info

```plain text
% act --bug-report
act version:            0.2.77
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 8
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock(broken)
Config files:           
	/Users/mperham/Library/Application Support/act/actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
Build info:
	Go version:            go1.24.2
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.77
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               arm64
		GOOS:                 darwin
		GOARM64:              v8.0

Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Command used with act

```sh
act
```

### Describe issue

I'm using OrbStack 1.10.3 on macOS 15.4. As you can see below, `act` is unable to download its image but I can pull it manually just fine. Does `act` work with OrbStack?

### Workflow content

```yml
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5

    - name: Install Redis
      run: sudo apt-get install redis-server

    - name: Test
      run: make prepare test
```

### Relevant log output

```sh
% act -v
[...snip...]
[Go/build] [DEBUG] evaluating expression 'success()'
[Go/build] [DEBUG] expression 'success()' evaluated to 'true'
[Go/build] ⭐ Run Set up job
[Go/build] 🚀  Start image=catthehacker/ubuntu:act-latest
DEBU[0000] Parallel tasks (0) below minimum, setting to 1 
[Go/build]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[Go/build] [DEBUG]   🐳  docker pull catthehacker/ubuntu:act-latest
[Go/build] [DEBUG] pulling image 'docker.io/catthehacker/ubuntu:act-latest' ()
[Go/build] using DockerAuthConfig authentication for docker pull
[Go/build] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[Go/build]   ❌  Failure - Set up job
[Go/build] 🏁  Job failed
Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

% docker pull catthehacker/ubuntu:act-latest
act-latest: Pulling from catthehacker/ubuntu
Digest: sha256:932a29dd9f17cceda5a85597b9c6d4705fd8da13e488e800be81feb98e505594
Status: Image is up to date for catthehacker/ubuntu:act-latest
docker.io/catthehacker/ubuntu:act-latest

% ls -l /var/run/docker.sock
lrwxr-xr-x  1 root  daemon  38 Apr 24 08:14 /var/run/docker.sock -> /Users/mperham/.docker/run/docker.sock
```
