### ISSUE TITLE
Ruby version not found

### ISSUE THREAD

**Issue by huseyin** [nektos/act#276]
I'm getting the following error when trying to run my workflow.

```
[test/Run linters] 🚀  Start image=node:12.6-buster-slim
[test/Run linters]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[test/Run linters]   🐳  docker cp src=/home/huseyin/Work/github.com/omu/ik/. dst=/github/workspace
[test/Run linters] ⭐  Run Checkout code
[test/Run linters]   ✅  Success - Checkout code
[test/Run linters] ⭐  Run Setup Ruby
[test/Run linters]   ☁  git clone 'https://github.com/actions/setup-ruby' # ref=v1
[test/Run linters]   🐳  docker cp src=/home/huseyin/.cache/act/actions-setup-ruby@v1 dst=/actions/
[test/Run linters]   💬  ##[debug]isExplicit: 2.7.1
[test/Run linters]   💬  ##[debug]explicit? true
[test/Run linters]   💬  ##[debug]checking cache: /opt/hostedtoolcache/Ruby/2.7.1/x64
[test/Run linters]   💬  ##[debug]not found
[test/Run linters]   ❗  ##[error]Version 2.7.1 not found
[test/Run linters]   ❌  Failure - Setup Ruby
Error: exit with `FAILURE`: 1
```

Here is the related configuration in my workflow:

```
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1
```

I use the standard actions provided by GitHub instead of containers. The error is also reproduced with different Ruby versions such as `2.6.1` and `2.6.5`
