### ISSUE TITLE
permissions models: read

### ISSUE THREAD

**Issue by pelikhan** [nektos/act#2766]
### Bug report info

```plain text
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock' 
Error: workflow is not valid. 'actions-summary.yml': Line: 12 Column 5: Failed to match job-factory: Line: 14 Column 7: Failed to match permissions-mapping: Line: 15 Column 7: Unknown Property models
Line: 14 Column 7: Failed to match permission-level-shorthand-read-all: Line: 14 Column 7: Expected a scalar got mapping
Line: 14 Column 7: Failed to match permission-level-shorthand-write-all: Line: 14 Column 7: Expected a scalar got mapping
Line: 12 Column 5: Failed to match workflow-job: Line: 12 Column 5: Unknown Property runs-on
Line: 14 Column 7: Failed to match permissions-mapping: Line: 15 Column 7: Unknown Property models
Line: 14 Column 7: Failed to match permission-level-shorthand-read-all: Line: 14 Column 7: Expected a scalar got mapping
Line: 14 Column 7: Failed to match permission-level-shorthand-write-all: Line: 14 Column 7: Expected a scalar got mapping
Line: 18 Column 5: Unknown Property steps
Actions YAML Schema Validation Error detected:
For more information, see: https://nektosact.com/usage/schema.html
```

### Command used with act

```sh
gh act --workflows ".github/workflows/curl-sample.yml" --job "call-model" --secret-file "" --var-file "" --input-file "" --eventpath ""
```

### Describe issue

new permission "models: read" to access GitHub Models (https://docs.github.com/en/github-models/use-github-models/prototyping-with-ai-models) in actions.

### Link to GitHub repository

https://github.com/microsoft/genaiscript

### Workflow content

```yml
# https://docs.github.com/en/github-models/integrating-ai-models-into-your-development-workflow#writing-your-workflow-file
name: curl-sample

on:
  workflow_dispatch:
  pull_request:
      types: [ready_for_review, review_requested]

permissions:
  models: read

jobs:
  call-model:
    runs-on: ubuntu-latest
    steps:
      - name: openai/gpt-4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --fail --show-error "https://models.github.ai/inference/chat/completions" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -d '{
              "messages": [{"role": "user","content": "Explain the concept of recursion."}],
               "model": "openai/gpt-4.1"
            }'
```

### Relevant log output

```sh
*  Executing task: GitHub Local Actions: curl-sample/call-model #1 

gh act --workflows ".github/workflows/curl-sample.yml" --job "call-model" --secret-file "" --var-file "" --input-file "" --eventpath ""

Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock'
Error: workflow is not valid. 'curl-sample.yml': Line: 10 Column 3: Failed to match permissions-mapping: Line: 10 Column 3: Unknown Property models
Line: 10 Column 3: Failed to match permission-level-shorthand-read-all: Line: 10 Column 3: Expected a scalar got mapping
Line: 10 Column 3: Failed to match permission-level-shorthand-write-all: Line: 10 Column 3: Expected a scalar got mapping
Actions YAML Schema Validation Error detected:
For more information, see: https://nektosact.com/usage/schema.html

curl-sample/call-model #1 exited with exit code 1.

 *  The terminal process terminated with exit code: 1.
```
