### ISSUE TITLE
OSX: hostedtoolcache missing

### ISSUE THREAD

**Issue by boesing** [nektos/act#289]
Hey there, I am getting the following error on my OSX machine.

```
[CI/Tests] ⭐  Run shivammathur/setup-php@v2
[CI/Tests]   ☁  git clone 'https://github.com/shivammathur/setup-php' # ref=v2
[CI/Tests]   🐳  docker cp src=/Users/act/.cache/act/shivammathur-setup-php@v2 dst=/actions/
[CI/Tests]   ❗  ::error::ENOENT: no such file or directory, open '/opt/hostedtoolcache/linux.sh'
[CI/Tests]   ❌  Failure - shivammathur/setup-php@v2
```

My workflow contains this step (which seems to cause the error):

```
steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
```

Is there some kind of initialization process which has to be done to receive that `linux.sh` file?

# Setup
Version of act: 0.2.9
Platform (Linux, macOS, Windows): macOS
The complete main.workflow file used:
```
name: CI
on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2

      # Initialize composer cache
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Downloads
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v1
```
The complete command that was executed
```
$ act
```
Any output from the command
```
[CI/Tests] 🚀  Start image=node:12.6-buster-slim
[CI/Tests]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/Tests]   🐳  docker cp src=/Users/max/git/github/kvb-api/. dst=/github/workspace
[CI/Tests] ⭐  Run shivammathur/setup-php@v2
[CI/Tests]   ☁  git clone 'https://github.com/shivammathur/setup-php' # ref=v2
[CI/Tests]   🐳  docker cp src=/Users/max/.cache/act/shivammathur-setup-php@v2 dst=/actions/
[CI/Tests]   ❗  ::error::ENOENT: no such file or directory, open '/opt/hostedtoolcache/linux.sh'
[CI/Tests]   ❌  Failure - shivammathur/setup-php@v2
Error: exit with `FAILURE`: 1
```
