### ISSUE TITLE
[Bug] Doesn't resolve a relative path to a docker file in the Action

### ISSUE THREAD

**Issue by JustinGrote** [nektos/act#291]
#Issue Summary
If I have an action specified like this:
```yaml
name: 'Super Duper Linter'
description: 'Lints and validates code files in your repository, very helpful for Pull Requests!'
runs:
  using: 'docker'
  image: '../../Dockerfile'
```

And a workflow specified like this:
```yaml
name: Sandbox
on:
  push:
    branches:
      - sandbox
jobs:
  localTest:
    runs-on: ubuntu-latest
    steps:
      - name: Super Duper Linter Test
        uses: ./Tests/act
        continue-on-error: true
```

When running `act -j localTest`, the docker build step doesn't resolve the relative path to the docker file in the `image:` section
![image](https://user-images.githubusercontent.com/15258962/85583394-14457c80-b5f3-11ea-8114-3794112d1d3b.png)

# Actual vs Expected
`docker build -t act-tests-act:latest C:\Users\jgrote\Projects\Super-Duper-Linter\Tests\act` 
should be 
`docker build -t act-tests-act:latest -f C:\Users\jgrote\Projects\Super-Duper-Linter\Dockerfile`

# Workaround
If you run `docker build -t act-tests-act:latest -f C:\Users\jgrote\Projects\Super-Duper-Linter\Dockerfile` manually right before the action, the `docker build -t act-tests-act:latest C:\Users\jgrote\Projects\Super-Duper-Linter\Tests\act` still silently fails but when the actual `docker run image=act-tests-act:latest entrypoint=[] cmd=[]` occurs then it is using the latest image.
