### ISSUE TITLE
Using custom Variable access

### ISSUE THREAD

**Issue by lautriva** [nektos/act#2928]
### Act version

act version 0.2.77

### Feature description

I'm using Gitea and their CI is based on act

I want to test my workflows locally before committing them on the repository

Unfortunately, the run fails with 
`Failed to match run-step: Line: 17 Column 14: Unknown Variable Access gitea`

Here is an example run command (other parts are irrelevant)
`echo ${{ gitea.workspace }}`

(same for `gitea.repository`, `gitea.ref`, etc...)

The `gitea.` group contain the same variables as `github.`

Is there a way to have act recognize it?

The idea would be to have a new act parameter that specifies a custom group that copies the `github.` variables into `gitea.` while still keeping `github.` to keep compatibility

for example, if this feature request were implemented, `act` could be called like that:

Fill `gitea.` variables like `${{ gitea.workspace }}`:
`act --variables-group gitea`

Fill `asdf.` variables like `${{ asdf.workspace }}`:
`act --variables-group asdf`

---

The workflow I use in case it might helps

`$ act -l -W ./.gitea/workflows/`

```yaml
name: Build and Test

on:
  push:
    branches:
      - main
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build
        run: |
            cmake -S ${{ gitea.workspace }} -B build
            cmake --build build --parallel

      - name: Run unit tests
        run: cmake --build build --target test

```
