### ISSUE TITLE
variables set using "::set-env" are not available to the steps commands

### ISSUE THREAD

**Issue by cuotos** [nektos/act#294]
I am using docker/build-push-action and wanted to set an env var in a Step and use it in the value of an input argument to another step.

```
      - name: extract branch name
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF##*/})"

      - uses: docker/build-push-action@v1
        with:
          ...
          build_args: version=${{ env.BRANCH_NAME }}
```

If BRANCH_NAME is set using "env: " in the actions file it is usable, but if i set it using actions "::set-env" syntax then the var is available IN THE CONTAINER, but not to the commands in the actions file. 

I spent a long time trying to work out how to do this in actions, pushed a test file and found that on github this works, but using act it doesn't.
