### ISSUE TITLE
trailing slash on URL from action output inconsistent between github.com and act

### ISSUE THREAD

**Issue by dskvr** [nektos/act#299]
_See `image` member_

Works on act, fails on github.com
```
   - name: Pull from ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.ID }}
        secret-access-key: ${{ secrets.SECRET }}
        region: us-east-1
        image: ${{ steps.login-ecr.outputs.registry }}somerepo:1.2.3
```

Github.com error
```
Error: Command failed: docker pull ***.dkr.ecr.us-east-2.amazonaws.com/***.dkr.ecr.us-east-2.amazonaws.comsomerepo:1.2.3
Error response from daemon: repository ***.dkr.ecr.us-east-2.amazonaws.com/***.dkr.ecr.us-east-2.amazonaws.comsomerepo not found: name unknown: The repository with name '***.dkr.ecr.us-east-2.amazonaws.comsomerepo' does not exist in the registry with id '***'
```

Works on github.com, fails on act
```
   - name: Pull from ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.ID }}
        secret-access-key: ${{ secrets.SECRET }}
        region: us-east-1
        image: ${{ steps.login-ecr.outputs.registry }}/somerepo:1.2.3
```

Act error:
```
$ docker pull some ***.dkr.ecr.us-east-2.amazonaws.com//somerepo:1.2.3
| invalid reference format
| child_process.js:669
```
