### ISSUE TITLE
entry point in action.yml should be relative to action.yml not cwd/project-root

### ISSUE THREAD

**Issue by jsg2021** [nektos/act#305]
First, I want to say this project is amazing. It has sped up my workflow testing/debugging so much! Thank you for this!

Anyways,
I was using this to test a private action that is hosted in a subdirectory of my project. When I came across this bug.
I didn't think anything of it and thought my entry point was just wrong and updated it to cwd/project-root relative and moved on... however when I pushed it to GitHub, it failed when looking for my entry point.

ex: 
 `<project>/actions/sync/action.yml` 
with:
```yml
runs:
  using: 'node12'
  main: 'src/index.js' # when running local this has to be 'actions/sync/src/index.js'
```

In my `<project>/.github/workflows/test-sync.yml` workflow:
```yml
  - name: Sync
    uses: ./actions/sync
```
