### ISSUE TITLE
yanr-cache is not supported 

### ISSUE THREAD

**Issue by rafilkmp3** [nektos/act#306]
Im using the following action to have cache to my yarn but dont work with act
```
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
```
I get this error

```
ERRO[0015] Unable to interpolate string '${{ steps.yarn-cache-dir-path.outputs.dir }}' - [ReferenceError: 'cache' is not defined]
[Lint on PRs/Lint on Prs] ⭐  Run actions/cache@v2
[Lint on PRs/Lint on Prs]   ☁  git clone 'https://github.com/actions/cache' # ref=v2
[Lint on PRs/Lint on Prs]   🐳  docker cp src=/Users/myuser/.cache/act/actions-cache@v2 dst=/actions/
[Lint on PRs/Lint on Prs]   ❓  ::save-state name=CACHE_KEY::Linux-yarn-23b4f114f83611ef940ffe19e3011bfe81ee2891759aaf728af6c8cd6522b667
[Lint on PRs/Lint on Prs]   ❗  ::error::Input required and not supplied: path
[Lint on PRs/Lint on Prs]   ❌  Failure - actions/cache@v2
Error: exit with `FAILURE`: 1
```
