### ISSUE TITLE
Unable to resolve v1: reference not found

### ISSUE THREAD

**Issue by MartinGonzalez** [nektos/act#311]
Hi!
It's the first time I'm working with github actions and I saw this to test them locally.

I have this workflow

```
name: Test-Build-Publish

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
    - name: Install dependencies
      run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
    - name: Run tests
      run: bundle exec rake
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results
  build:
    name: "Build Gem"
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - name: Build
      run: echo 'building'
  publish:
    name: Publish Gem
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: Publish
      run: echo 'publish'
```

But I'm having this error when running act

```
➜  fastlane-plugin-json git:(master) act
[Test-Build-Publish/test       ] 🚀  Start image=node:12.6-buster-slim
[Test-Build-Publish/test       ]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Test-Build-Publish/test       ]   🐳  docker cp src=/Users/martin.gonzalez/Desktop/fastlane-plugin-json/. dst=/github/workspace
[Test-Build-Publish/test       ] ⭐  Run actions/checkout@v2
[Test-Build-Publish/test       ]   ✅  Success - actions/checkout@v2
[Test-Build-Publish/test       ] ⭐  Run actions/cache@v1
[Test-Build-Publish/test       ]   ☁  git clone 'https://github.com/actions/cache' # ref=v1
[Test-Build-Publish/test       ]   🐳  docker cp src=/Users/martin.gonzalez/.cache/act/actions-cache@v1 dst=/actions/
[Test-Build-Publish/test       ]   💬  ::debug::Cache Path: /github/workspace/vendor/bundle
[Test-Build-Publish/test       ]   ❓  ::save-state name=CACHE_KEY,::Linux-gem-df84e4ade202d5cd4280a79acfea544a600ef73f1b39b2097a1f660ed64dd2a7
[Test-Build-Publish/test       ]   💬  ::debug::Resolved Keys:
[Test-Build-Publish/test       ]   💬  ::debug::["Linux-gem-df84e4ade202d5cd4280a79acfea544a600ef73f1b39b2097a1f660ed64dd2a7","Linux-gem-"]
[Test-Build-Publish/test       ]   💬  ::debug::getCacheEntry - Attempt 1 of 2 failed with error: Cache Service Url not found, unable to restore cache.
[Test-Build-Publish/test       ]   💬  ::debug::getCacheEntry - Attempt 2 of 2 failed with error: Cache Service Url not found, unable to restore cache.
| [warning]getCacheEntry failed: Cache Service Url not found, unable to restore cache.
[Test-Build-Publish/test       ]   ⚙  ::set-output:: cache-hit=false
[Test-Build-Publish/test       ]   ✅  Success - actions/cache@v1
[Test-Build-Publish/test       ] ⭐  Run Set up Ruby
[Test-Build-Publish/test       ]   ☁  git clone 'https://github.com/ruby/setup-ruby' # ref=v1
[Test-Build-Publish/test       ] Unable to resolve v1: reference not found
[Test-Build-Publish/test       ]   ❌  Failure - Set up Ruby
Error: reference not found
```

If I run `git clone 'https://github.com/ruby/setup-ruby' # ref=v1` it succeed. Should I configure something? A github token to an Env variable or something?
