### ISSUE TITLE
Where is the best position to set GOPROXY?

### ISSUE THREAD

**Issue by davidmlw** [nektos/act#312]
Some times, it needs to setup GOPROXY for go execution env:
`go env -w GOPROXY=URL`

When I `make test`, I set up the current go env proxy, while act will download a docker image and run go inside the container and fail due to no properate proxy. 

Where is the best position to set GOPROXY? If I have to do a little local hack, which file should I inspect?

**Comment by cupen** [comment]
Just use env in your workflows.
```yml
name: test

on:
  push:
    branches: [master]

env:
  GOPROXY: your url
  GOPATH: ${{ github.workspace }}
```

You can also  use `act --env-file  path/to/env` if you need it. 
See the help infomation. `act --help | grep env`
