### ISSUE TITLE
/github/workflow/1: line 2: git: command not found

### ISSUE THREAD

**Issue by ssbarnea** [nektos/act#316]
```
[gh/lint-1                           ] ⭐  Run Set up Python ${{ matrix.python-version }}
[gh/lint-1                           ]   ☁  git clone 'https://github.com/actions/setup-python' # ref=v1
| /github/workflow/1: line 2: git: command not found
| /github/workflow/1: line 2: git: command not found
| /github/workflow/1: line 2: git: command not found
```

I wasn't expected to see such an error with a very basic step:

```
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
```

**Comment by myselfhimself** [comment]
Reproduced today after bash sudo install on linux, git not found

**Comment by myselfhimself** [comment]
```
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        pythonversion: [3.7]

    steps:
    - uses: actions/checkout@v1

    # Prevent running this job on tag-based releases
    - name: Check if Git tag exists
      run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
```
