### ISSUE TITLE
docker cp fails with actions-rs-toolchain

### ISSUE THREAD

**Issue by tyler274** [nektos/act#328]
Running act locally on windows 10 fails with MODULE_NOT_FOUND here, setting the path key in the yml didn't seem to affect it. 
Running ACT within a WSL2 shell works though. 

```
PS C:\Users\tyler\Code\ggpo-rs> act -j check
[CI/Check ubuntu-latest (nightly)-2] 🧪  Matrix: map[os:ubuntu-latest toolchain:nightly]
[CI/Check ubuntu-latest (stable)-1 ] 🧪  Matrix: map[os:ubuntu-latest toolchain:stable]
[CI/Check ubuntu-latest (nightly)-2] 🚀  Start image=node:12.6-buster-slim
[CI/Check ubuntu-latest (stable)-1 ] 🚀  Start image=node:12.6-buster-slim
[CI/Check ubuntu-latest (stable)-1 ]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/Check ubuntu-latest (stable)-1 ]   🐳  docker cp src=C:\Users\tyler\Code\ggpo-rs/. dst=\github\workspace
[CI/Check ubuntu-latest (stable)-1 ] ⭐  Run actions/checkout@v2
[CI/Check ubuntu-latest (stable)-1 ]   ✅  Success - actions/checkout@v2
[CI/Check ubuntu-latest (stable)-1 ] ⭐  Run toolchain
[CI/Check ubuntu-latest (stable)-1 ]   ☁  git clone 'https://github.com/actions-rs/toolchain' # ref=v1
[CI/Check ubuntu-latest (stable)-1 ]   🐳  docker cp src=act/actions-rs-toolchain@v1 dst=/actions\
| internal/modules/cjs/loader.js:628
|     throw err;
|     ^
|
| Error: Cannot find module '/github/workspace/\actions\actions-rs-toolchain@v1\dist\index.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
|     at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
|     at internal/main/run_main_module.js:17:11 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
```

action.yml that triggers it. 
```
on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check ${{ matrix.os }} (${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - name: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          command: check
```
