### ISSUE TITLE
cannot unmarshal error

### ISSUE THREAD

**Issue by shinhyo** [nektos/act#330]
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson

``` yml
name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.project }}
```

```
Error: yaml: unmarshal errors:
  line 15: cannot unmarshal !!str `${{from...` into map[string][]interface {}
```

fromjson Not supported?

**Comment by ElderOrb** [comment]
I do see similar issue on

**Comment by niclascarlstedt** [comment]
👋 
Any possibility to re-open this issue?
I see the same problem and it seems that this possibly is patched in the runner.
[https://github.com/actions/runner/issues/751](https://github.com/actions/runner/issues/751)

**Comment by Nuru** [comment]
Looks to me like this is a duplicate of #284

**Comment by frezbo** [comment]
I can confirm the `fromJson` is not working in version `0.2.18`. My example is similar to https://github.com/nektos/act/issues/330#issue-672533677

**Comment by Nuru** [comment]
This was not fixed by #352. Is there something tricky about this?

**Comment by dprotaso** [comment]
I'd re-open this - I just encountered this with 

https://github.com/knative-sandbox/knobots/blob/dd204c1b08700da564ffab1808982a618b9b7e18/.github/workflows/auto-updates.yaml#L126-L127
```
  line 126: cannot unmarshal !!str `${{from...` into []interface {}
  line 127: cannot unmarshal !!str `${{from...` into []interface {}
```

**Comment by tigattack** [comment]
I'm also seeing this error on a brand new install on macOS.

**Comment by evilr00t** [comment]
I have similar issue using https://github.com/dflook/terraform-plan in my CI

```
[PR Plan/Create terraform plan] ⭐  Run Checkout
[PR Plan/Create terraform plan]   ✅  Success - Checkout
[PR Plan/Create terraform plan] ⭐  Run terraform plan
[PR Plan/Create terraform plan]   ☁  git clone 'https://github.com/dflook/terraform-plan' # ref=v1
[PR Plan/Create terraform plan]   ❌  Failure - terraform plan
Error: yaml: unmarshal errors:
  line 49: cannot unmarshal !!str `/entryp...` into []string
```

Looks like

```
runs:
  using: docker
  image: docker://danielflook/terraform-github-actions:v1.9.1
  entrypoint: /entrypoints/plan.sh
```

First slash in entrypoint is causing an issue.
