### ISSUE TITLE
How to trigger event: workflow_dispatch with inputs ?

### ISSUE THREAD

**Issue by cupen** [nektos/act#332]
Here is a example, how to trigger it?
```yml
name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
        default: "world"

jobs:
  show_inputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
```
