### ISSUE TITLE
Support for "defaults" job statement

### ISSUE THREAD

**Issue by Ckarles** [nektos/act#336]
It seems that `defaults` are not supported at the job level.
The folling is changing the working-directory for all subsequent tasks:
```yaml
    defaults:
      run:
        working-directory: app
```
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_iddefaults
