### ISSUE TITLE
act does not support matrix variables with "-" in their names, GitHub does

### ISSUE THREAD

**Issue by adamtheturtle** [nektos/act#337]
I had:

```yaml
      matrix:
        python-version: [3.7, 3.8]
```

and

```yaml
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
```

This works on GitHub but `act` shows:

```
ERRO[0004] Unable to interpolate string '${{ matrix.python-version }}' - [ReferenceError: 'version' is not defined] 
```
