### ISSUE TITLE
Error: unable to determine if image already exists for image "docker://dvcorg/cml-py3:latest": Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by ucalyptus** [nektos/act#338]
```
name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py
          
          cat metrics.txt >> report.md
          cml-publish confusion_matrix.png --md --title 'confusion-matrix' >> report.md
          cml-send-comment report.md 
```

# [Gist Colab to reproduce issue](https://colab.research.google.com/gist/ucalyptus/4d3e21374cd50a48f9aa898925fb03ff/trial-bedardi-raja.ipynb)
