### ISSUE TITLE
[Bugs] ReferenceError: 'fromJSON' is not defined

### ISSUE THREAD

**Issue by theowenyoung** [nektos/act#350]
```yaml
on:
  push:
env:
  TEST: '{"outputs":{"test":"value1"}}'
jobs:
  print_0:
    name: Print 0
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          text: ${{ fromJSON(env.TEST).outputs.test }}
        run: |
          echo text: $text
```

get error:

```bash
Unable to interpolate string '${{ fromJSON(env.TEST).outputs.test }}' - [ReferenceError: 'fromJSON' is not defined]
```

Github actions docs about fromJson: <https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson>

relative issue: #284
