### ISSUE TITLE
Run docker fails: docker: command not found

### ISSUE THREAD

**Issue by dfreilich** [nektos/act#355]
When I try to run `docker` commands locally, it seems to fail. 

```
name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Registry
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
```

Fails for 
```
test/Pack Local Build] ⭐  Run Run local registry
| /github/workflow/1: line 2: docker: command not found
[test/Pack Local Build]   ❌  Failure - Run local registry
```

The same file works on Github Actions.
