### ISSUE TITLE
Makefile support

### ISSUE THREAD

**Issue by ctopinka** [nektos/act#358]
[CI/test] ⭐  Run make test
| /github/workflow/5: line 2: make: command not found
[CI/test]   ❌  Failure - make test

**Comment by ctopinka** [comment]
I see this now.

```

. Use an alternative runner image
To use a different image for the runner, use the -P option:

act -P ubuntu-latest=nektos/act-environments-ubuntu:18.04. 

```

Just grab an image that includes make?

**Comment by ctopinka** [comment]
Action is:


```
name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14' # The Go version to download (if necessary) and use.
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk.
          architecture: x64 # (x64 or x86) - defaults to x64.
      - run: go version
      - run: java -version
      - run: make test

```
