### ISSUE TITLE
error Couldn't find the binary git

### ISSUE THREAD

**Issue by thegostep** [nektos/act#363]
one of my npm dependencies resolves with a git link - this does not seem to be supported in act yet works fine in github actions

```
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-contracts:
    name: Test Contracts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn build
      - run: yarn test
```
