### ISSUE TITLE
Support expressions in runs.env for docker actions

### ISSUE THREAD

**Issue by justincy** [nektos/act#364]
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsenv

act isn't parsing expressions in `runs.env`, it's treating them as strings. With this setup:

```
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PROCESS_NAME: ${{ inputs.process-name }}
```

`PROCESS_NAME` always has the value of the string `${{ inputs.process-name }}` instead of the actual input value.
