### ISSUE TITLE
Support for $GITHUB_ENV

### ISSUE THREAD

**Issue by haizaar** [nektos/act#384]
Good day,
First, thank you for writing this tool - AFAIK it's the only local simulator for any CI out there.

To the topic - GH seem to have moved to a new way to define env vars [1]:
```shell
echo "action_state=yellow" >> $GITHUB_ENV
```
However it doesn't seem to be supported by act. Specifying the following in the workflow file:
```yaml
- name: Set CI instance ID                                                                                               
  run: |                                                                                                                 
    echo GITHUB_ENV=$GITHUB_ENV                                                                                          
    echo 'CI_INSTANCE_ID="-ci${{ github.run_id }}"' >> $GITHUB_ENV  
```
fails with:
```
| GITHUB_ENV=
| /github/workflow/1: line 3: $GITHUB_ENV: ambiguous redirect
```

Can you please support it?

[1] https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
