### ISSUE TITLE
Align "if: ${{ always() }}" step behaviour to GH

### ISSUE THREAD

**Issue by haizaar** [nektos/act#387]
Good day,

I'm using act 0.2.15 here.

I have a job that creates per-job objects in the cloud so it needs to clean up them regardless whether it was successful or not.
I solved it by defining the last clean up step as:

```yaml
    - name: Cleanup
      if: ${{ always() }}
      run: make cleanup
```

Indeed this step is unconditionally executed when it runs in GitHub actions but not by act. I.e. if one of the previous step fails, act will not run my Cleanup step.

Can you please align this behaviour with the GH?
