### ISSUE TITLE
Can not start python environment in MacOS

### ISSUE THREAD

**Issue by magiskboy** [nektos/act#388]
I run `act push -j fastapi`, then I got a error

<img width="1420" alt="Screen Shot 2020-10-12 at 09 15 45" src="https://user-images.githubusercontent.com/13352088/95698311-b73a0900-0c6b-11eb-8396-c72f5eb67558.png">

This is the action file 

```yaml
name: Test

on: [push]

jobs:
  fastapi:
    runs-on: ubuntu-latest
    # if: "contains(github.event.head_commit.message, 'FASTAPI: ')"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install cookiecutter
      run: |
        pip install cookiecutter
    - name: Test generate
      run: |
        cookiecutter --no-input fastapi -o target
```
 Who can help me to resolve this problem?
