### ISSUE TITLE
dependent workflows with `workflow_run` not triggering

### ISSUE THREAD

**Issue by aldegoeij** [nektos/act#390]
Hi!

I have two workflow files:

`one.yml`:

```yml
name: One

on:
  push:

jobs:
  ...ABC
```

`two.yml`:

```yml
name: Two

on:
  workflow_run:
    workflows: ["One"]
    branches: [main]
    types:
      - completed

jobs:
  ...XYZ
```

And an event payload `event.json`:

```json
{
  "action": "completed"
}

```

However, when I try to run the command:

`act workflow_run --workflows ./.github/workflows/two.yml --eventpath ./event.json --verbose`

I get error:

```bash
DEBU[0000] Loading environment from /xxxx/.env 
DEBU[0000] Loading secrets from                         
DEBU[0000] Loading workflow '/xxxx/.github/workflows/two.yml' 
DEBU[0000] Reading workflow '/xxxx/.github/workflows/two.yml' 
DEBU[0000] Planning event: workflow_run                 
FATA[0000] Unable to build dependency graph!
```

Could anyone give me a hand with triggering 'secondary' workflow files?

For `workflow_run` see: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run
