### ISSUE TITLE
Dry run fails on fairly simple workflow

### ISSUE THREAD

**Issue by godrose** [nektos/act#392]
Arrange: 
- Win 10 env
- `act` installed via `choco`

Act:

- Nav to root folder
- Use workflow file
```
name: Build Angular project  

on: 
  push:
    branches:
      - Development

jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        node-version: [12.x]  
 
    steps:  
      - uses: actions/checkout@v1  
 
      - name: Cache node modules  
        uses: actions/cache@v1  
        with:  
          path: ~/.npm  
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}  
          restore-keys: |  
            ${{ runner.os }}-node-  
      - name: Node ${{ matrix.node-version }}  
        uses: actions/setup-node@v1  
        with:  
          node-version: ${{ matrix.node-version }}  
      - name: Build->Lint-Test
        run: |
          cd ${WEB_ROOT_DIR}
          #using npm ci vs. npm i because of this issue https://github.com/Gbuomprisco/ngx-chips/issues/974
          npm ci    
          npm run build --if-present                     
          npm run test:ci
```
- Run `act -n`

Assert:

- Expected: the workflow runs
- Actual: Exception is raised:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9a9d0f]

goroutine 8 [running]:
github.com/robertkrimen/otto.catchPanic.func1(0xc0001075d0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/error.go:248 +0x591
panic(0xbf8b80, 0x1334e60)
        /opt/hostedtoolcache/go/1.14.3/x64/src/runtime/panic.go:969 +0x174
gopkg.in/godo.v2/glob.isDir(0xc0004fe270, 0x29, 0x40)
        /home/runner/go/pkg/mod/gopkg.in/godo.v2@v2.0.9/glob/glob.go:221 +0x9f
gopkg.in/godo.v2/glob.PatternRoot(0xc0004fe270, 0x29, 0x0, 0x0)
        /home/runner/go/pkg/mod/gopkg.in/godo.v2@v2.0.9/glob/glob.go:227 +0x54
gopkg.in/godo.v2/glob.Glob(0xc000106618, 0x1, 0x1, 0xc0004fe270, 0x29, 0x2030001, 0xc0004acd78, 0x74732029676e6972, 0x29676e6972, 0xc000128c60, ...)
        /home/runner/go/pkg/mod/gopkg.in/godo.v2@v2.0.9/glob/glob.go:172 +0x90c
github.com/nektos/act/pkg/runner.(*RunContext).vmHashFiles.func1.1(0xc0004fe1bc, 0x14, 0x0, 0x0)
        /home/runner/work/act/act/pkg/runner/expression.go:198 +0xff
reflect.Value.call(0xbcbcc0, 0xc0004c0f30, 0x13, 0xcd5c74, 0x4, 0xc0004e54a0, 0x1, 0x1, 0xc000106910, 0x449f53, ...)
        /opt/hostedtoolcache/go/1.14.3/x64/src/reflect/value.go:460 +0x8b2
reflect.Value.Call(0xbcbcc0, 0xc0004c0f30, 0x13, 0xc0004e54a0, 0x1, 0x1, 0xbb4020, 0xc0004c12a0, 0x98)
        /opt/hostedtoolcache/go/1.14.3/x64/src/reflect/value.go:321 +0xbb
github.com/robertkrimen/otto.(*_runtime).toValue.func1(0xc000045b00, 0x0, 0x0, 0x5, 0xcbb420, 0xc00048c180, 0xc0004e5460, 0x1, 0x1, 0xc0004c0a30, ...)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:713 +0x602
github.com/robertkrimen/otto.(*_object).call(0xc0004ddc20, 0x5, 0xcbb420, 0xc00048c180, 0xc0004e5460, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/type_function.go:201 +0x718
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc000045b00, 0xc0004ec960, 0x0, 0x0, 0x0, 0xc000107268, 0x40ca20, 0x30001)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_expression.go:244 +0x477
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc000045b00, 0xe04840, 0xc0004ec960, 0x44a195, 0xc0004c1270, 0x10)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_expression.go:44 +0x501
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc000045b00, 0xe04900, 0xc0004c12b0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_statement.go:62 +0xe5c
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc000045b00, 0xc0004c1280, 0x1, 0x1, 0x6e6f736a2f6e6f69, 0xc0004ec8d0, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_statement.go:121 +0x95
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc000045b00, 0xc000508150, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate.go:17 +0xff
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:785 +0x4b
github.com/robertkrimen/otto.catchPanic(0xc000107638, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/error.go:251 +0x5e
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc000045b00, 0xbb4020, 0xc0004c1240, 0x0, 0x0, 0xc000107600, 0x40a3f2, 0x10, 0xbb3e60, 0x55be01, ...)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:784 +0x116
github.com/robertkrimen/otto.(*_runtime).cmpl_run(...)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:797
github.com/robertkrimen/otto.Otto.Run(0x0, 0xc000045b00, 0xbb4020, 0xc0004c1240, 0x5, 0x0, 0xe1a6a0, 0x40ca20, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/otto.go:295 +0x5a
github.com/nektos/act/pkg/runner.(*expressionEvaluator).Evaluate(0xc000006e00, 0xc000276b19, 0x23, 0x1, 0x10, 0xc0004acd80, 0x0)
        /home/runner/work/act/act/pkg/runner/expression.go:64 +0x73
github.com/nektos/act/pkg/runner.(*expressionEvaluator).Interpolate.func1(0xc000276b16, 0x28, 0x5, 0xc0004acd80)
        /home/runner/work/act/act/pkg/runner/expression.go:81 +0xd6
regexp.(*Regexp).ReplaceAllStringFunc.func1(0xc0004acd80, 0xb, 0x10, 0xc0004acd40, 0x2, 0x2, 0x5, 0x10, 0x10)
        /opt/hostedtoolcache/go/1.14.3/x64/src/regexp/regexp.go:578 +0x91
regexp.(*Regexp).replaceAll(0xc00033f400, 0x0, 0x0, 0x0, 0xc000276b00, 0x3e, 0x2, 0xc000107978, 0xc0004acd30, 0xc000107998, ...)
        /opt/hostedtoolcache/go/1.14.3/x64/src/regexp/regexp.go:616 +0x2f0
regexp.(*Regexp).ReplaceAllStringFunc(0xc00033f400, 0xc000276b00, 0x3e, 0xc000107a10, 0xc0004acd38, 0x6)
        /opt/hostedtoolcache/go/1.14.3/x64/src/regexp/regexp.go:577 +0xa4
github.com/nektos/act/pkg/runner.(*expressionEvaluator).Interpolate(0xc000006e00, 0xc000276b00, 0x3e, 0xa, 0xc0004f4bc8)
        /home/runner/work/act/act/pkg/runner/expression.go:79 +0xe2
github.com/nektos/act/pkg/runner.(*StepContext).setupEnv.func1(0xe189e0, 0xc0003f39e0, 0x1300a51, 0x1)
        /home/runner/work/act/act/pkg/runner/step_context.go:94 +0x1b8
github.com/nektos/act/pkg/runner.(*RunContext).newStepExecutor.func1(0xe189e0, 0xc0003f39e0, 0x0, 0x0)
        /home/runner/work/act/act/pkg/runner/run_context.go:197 +0x126
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe189e0, 0xc0003f39e0, 0xc0003bd9d0, 0x412e95)
        /home/runner/work/act/act/pkg/common/executor.go:146 +0x181
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe189e0, 0xc0003f39e0, 0xbf27e0, 0xc0003be1e0)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe189e0, 0xc0003f39e0, 0xbb4020, 0xe23a80)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe189e0, 0xc0003f39e0, 0x1, 0x13722c0)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.If.func1(0xe189e0, 0xc0003f39e0, 0xc0003b9100, 0x1b)
        /home/runner/work/act/act/pkg/common/executor.go:154 +0x71
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1(0xe189e0, 0xc0003be210, 0xc0004871e0, 0xc000057f70)
        /home/runner/work/act/act/pkg/runner/runner.go:76 +0x252
github.com/nektos/act/pkg/common.Executor.ChannelError.func1(0xe189e0, 0xc0003be210, 0xc0004871e0, 0x0)
        /home/runner/work/act/act/pkg/common/executor.go:125 +0x4c
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1(0xc0004871a0, 0xc000039a40, 0xe189e0, 0xc0003be210)
        /home/runner/work/act/act/pkg/common/executor.go:101 +0x5d
created by github.com/nektos/act/pkg/common.NewParallelExecutor.func1
        /home/runner/work/act/act/pkg/common/executor.go:100 +0xbe
```

**Comment by etiennestuder** [comment]
I'm observing the same (on MacOS 10.15.7)

**Comment by magneticflux-** [comment]
Same here:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x9be1cf]

goroutine 10 [running]:
github.com/robertkrimen/otto.catchPanic.func1(0xc00015d490)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/error.go:248 +0x591
panic(0xc0f4e0, 0x135aef0)
        /opt/hostedtoolcache/go/1.14.10/x64/src/runtime/panic.go:969 +0x174
gopkg.in/godo.v2/glob.isDir(0xc000030c30, 0x45, 0x85)
        /home/runner/go/pkg/mod/gopkg.in/godo.v2@v2.0.9/glob/glob.go:221 +0x9f
gopkg.in/godo.v2/glob.PatternRoot(0xc000030c30, 0x45, 0x0, 0x0)
        /home/runner/go/pkg/mod/gopkg.in/godo.v2@v2.0.9/glob/glob.go:227 +0x54
gopkg.in/godo.v2/glob.Glob(0xc00015c4d8, 0x1, 0x1, 0xc000030c30, 0x45, 0x2030001, 0xc00014e408, 0x74732029676e6972, 0x29676e6972, 0xc0004b4420, ...)
        /home/runner/go/pkg/mod/gopkg.in/godo.v2@v2.0.9/glob/glob.go:172 +0x90c
github.com/nektos/act/pkg/runner.(*RunContext).vmHashFiles.func1.1(0xc0004fc48b, 0x14, 0x0, 0x0)
        /home/runner/work/act/act/pkg/runner/expression.go:240 +0xff
reflect.Value.call(0xbe1f20, 0xc00044df10, 0x13, 0xcee219, 0x4, 0xc0007321e0, 0x1, 0x1, 0xc00015c7d0, 0x44a843, ...)
        /opt/hostedtoolcache/go/1.14.10/x64/src/reflect/value.go:460 +0x8b2
reflect.Value.Call(0xbe1f20, 0xc00044df10, 0x13, 0xc0007321e0, 0x1, 0x1, 0xbca040, 0xc0003d4e70, 0x98)
        /opt/hostedtoolcache/go/1.14.10/x64/src/reflect/value.go:321 +0xbb
github.com/robertkrimen/otto.(*_runtime).toValue.func1(0xc000071980, 0x0, 0x0, 0x5, 0xcd3980, 0xc000693680, 0xc0007321a0, 0x1, 0x1, 0xc00044d950, ...)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:713 +0x605
github.com/robertkrimen/otto.(*_object).call(0xc000013380, 0x5, 0xcd3980, 0xc000693680, 0xc0007321a0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/type_function.go:201 +0x718
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc000071980, 0xc000735170, 0x0, 0x0, 0x0, 0xc00015d128, 0x40ca30, 0x30001)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_expression.go:244 +0x477
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc000071980, 0xe1e640, 0xc000735170, 0x44aa85, 0xc0003d4e40, 0x10)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_expression.go:44 +0x501
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc000071980, 0xe1e700, 0xc0003d4e80, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_statement.go:62 +0xe5c
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc000071980, 0xc0003d4e50, 0x1, 0x1, 0x6e6f736a2f6e6f69, 0xc0007350e0, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_statement.go:121 +0x95
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc000071980, 0xc0000c4d20, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate.go:17 +0xff
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:785 +0x4b
github.com/robertkrimen/otto.catchPanic(0xc00015d4f8, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/error.go:251 +0x5e
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc000071980, 0xbca040, 0xc0003d4e10, 0x0, 0x0, 0xc00015d500, 0x40a402, 0x10, 0xbc9e80, 0xc0004fc401, ...)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:784 +0x116
github.com/robertkrimen/otto.(*_runtime).cmpl_run(...)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:797
github.com/robertkrimen/otto.Otto.Run(0x0, 0xc000071980, 0xbca040, 0xc0003d4e10, 0x21, 0x4, 0xc00015d5e8, 0xc0004fc3f0, 0x21)
        /home/runner/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/otto.go:295 +0x5a
github.com/nektos/act/pkg/runner.(*expressionEvaluator).Evaluate(0xc00030e078, 0xc0004fc420, 0x21, 0xcedb23, 0x2, 0xc0004fc420, 0x21)
        /home/runner/work/act/act/pkg/runner/expression.go:68 +0x185
github.com/nektos/act/pkg/runner.(*expressionEvaluator).Interpolate.func1(0xc00014d856, 0x28, 0x5, 0xc00014e410)
        /home/runner/work/act/act/pkg/runner/expression.go:87 +0x9b
regexp.(*Regexp).ReplaceAllStringFunc.func1(0xc00014e410, 0xb, 0x10, 0xc00014e3a0, 0x2, 0x2, 0x5, 0x10, 0x10)
        /opt/hostedtoolcache/go/1.14.10/x64/src/regexp/regexp.go:578 +0x91
regexp.(*Regexp).replaceAll(0xc00035fae0, 0x0, 0x0, 0x0, 0xc00014d840, 0x3e, 0x2, 0xc00015d868, 0xc00014e318, 0xc00015d888, ...)
        /opt/hostedtoolcache/go/1.14.10/x64/src/regexp/regexp.go:616 +0x2f0
regexp.(*Regexp).ReplaceAllStringFunc(0xc00035fae0, 0xc00014d840, 0x3e, 0xc00015d900, 0xc00014e390, 0x6)
        /opt/hostedtoolcache/go/1.14.10/x64/src/regexp/regexp.go:577 +0xa4
github.com/nektos/act/pkg/runner.(*expressionEvaluator).Interpolate(0xc00030e078, 0xc00014d840, 0x3e, 0xa, 0xc0001bebc8)
        /home/runner/work/act/act/pkg/runner/expression.go:83 +0xe2
github.com/nektos/act/pkg/runner.(*StepContext).setupEnv.func1(0xe32c40, 0xc000469890, 0x1326ad2, 0x1)
        /home/runner/work/act/act/pkg/runner/step_context.go:101 +0x1dc
github.com/nektos/act/pkg/runner.(*RunContext).newStepExecutor.func1(0xe32c40, 0xc000469890, 0x0, 0x0)
        /home/runner/work/act/act/pkg/runner/run_context.go:200 +0x126
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe32c40, 0xc000469890, 0xd, 0xc000147c00)
        /home/runner/work/act/act/pkg/common/executor.go:146 +0x181
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe32c40, 0xc000469890, 0xc000147c68, 0xc0000326f0)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe32c40, 0xc000469890, 0xc00017a3c0, 0x412ea5)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe32c40, 0xc000469890, 0xc09080, 0xc0002f7aa0)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe32c40, 0xc000469890, 0xbca040, 0xe3de20)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xe32c40, 0xc000469890, 0x1, 0x13983e0)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.If.func1(0xe32c40, 0xc000469890, 0xc00002f340, 0x12)
        /home/runner/work/act/act/pkg/common/executor.go:154 +0x71
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1(0xe32c40, 0xc0002f7ad0, 0xc0000abe20, 0xc000147f70)
        /home/runner/work/act/act/pkg/runner/runner.go:78 +0x252
github.com/nektos/act/pkg/common.Executor.ChannelError.func1(0xe32c40, 0xc0002f7ad0, 0xc0000abe20, 0x1)
        /home/runner/work/act/act/pkg/common/executor.go:125 +0x4c
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1(0xc0000abdc0, 0xc000035080, 0xe32c40, 0xc0002f7ad0)
        /home/runner/work/act/act/pkg/common/executor.go:101 +0x5d
created by github.com/nektos/act/pkg/common.NewParallelExecutor.func1
        /home/runner/work/act/act/pkg/common/executor.go:100 +0xbe
```

My workflow:
```yaml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run build
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
```
