### ISSUE TITLE
zip: not found

### ISSUE THREAD

**Issue by JBaczuk** [nektos/act#394]
I have an action that zips a file:
```
name: build and test

on: push
  deploy:
    defaults:
      run:
        working-directory: ./lambda/custom
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: zip -r -X "../deploy.zip" * 
        env:
          CI: true
      - name: Deploy app
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: es-east-1
          function_name: myFunction
          zip_file: ./deploy.zip
      - run: ls

```

and I get the following error:
```
> zip -r -X "../deploy.zip" *
sh: 1: zip: not found
```
