### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by MVEMCJSUNPE** [nektos/act#402]
Act gives index out of range error:
<img width="950" alt="act_error" src="https://user-images.githubusercontent.com/10354503/97396538-49215300-18b5-11eb-87b0-719e66177152.png">

As we can see from the screenshot, the error occurs on https://github.com/nektos/act/blob/1e69525fb4ed3ef539b108d1844b2782338046e7/pkg/runner/step_context.go#L381 . The code fails to check if NO substring matches were found. If that is the case, then matches is an empty slice, so 
```
ra.Org = matches[1]
```
causes the application to crash. 

How to reproduce:
```pwsh
git clone https://github.com/drashland/deno-drash.git
```
and change .github/workflows/master.yml like mentioned in this issue message [parameter 'commandLine' cannot be empty](https://github.com/denolib/setup-deno/issues/51#issuecomment-662442252) for BOTH linter and tests. Yes, it's not minimal, but the stack trace is pretty large and I'm kind of lazy. 

OS: Windows 10 Home 64-bit (Build 10.0, Build 19041)
*Note: act was compiled using MinGW 64, but using go downloaded for windows.

**Comment by tadman** [comment]
I've also seen this. A minimal example to reproduce it:

```yaml
name: Crash
on: push
jobs:
  crash:
    name: Crashing
    runs-on: ubuntu-latest
    steps:
      - name: Crashy!
        uses: crash
```
