### ISSUE TITLE
step set output string should be unescaped

### ISSUE THREAD

**Issue by theowenyoung** [nektos/act#403]
Hi, I found act does not unescape the step outputs string, for example: 

> This workflow will be printed Hello 2%25 in act
>  It will be printed Hello 2% in Github Actions

```yaml
on:
  workflow_dispatch:
  push:
jobs:
  script:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Format message
        id: format
        uses: actions/github-script@v2
        with:
          script: |
            return {"message":"Hello 2%"}
      - name: Format message
        uses: actions/github-script@v2
        env:
          TEXT: ${{ fromJSON(steps.format.outputs.result).message }}
        with:
          script: |
            console.log('text', process.env.TEXT)
            // will be printed Hello 2%25 in act
            // will be printed Hello 2% in Github Actions
```

Github demo action log: https://github.com/theowenyoung/test-actions/runs/1331351240?check_suite_focus=true
