### ISSUE TITLE
How to determine whether running workflows with act?

### ISSUE THREAD

**Issue by theowenyoung** [nektos/act#422]
Hi,

I can check if a workflow running in Github Actions by `${{ env.GITHUB_ACTIONS=='true'}}`, but act also define env `GITHUB_ACTIONS: true`, so how to determine whether running workflows with act?

There are some steps that I only want to run with Github, not locally.

Example:

```yaml
name: Build Site
on:
  workflow_dispatch:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: env.GITHUB_ACTION=='true'
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
```

How to define `if` condition?
