### ISSUE TITLE
act fails to interpolate matrix variable in step with: arguments

### ISSUE THREAD

**Issue by artis3n** [nektos/act#435]
I have a step in a workflow that looks like:

```yaml
      - name: "Conftest Verify"
        uses: docker://openpolicyagent/conftest:v0.21.0
        with:
          entrypoint: conftest
          # github mounts the project at /github/workspace for us
          args: verify -p /github/workspace/${{ matrix.policyDir }}/**/*/src.rego -d /github/workspace/lib/
```

Where the strategy matrix is:

```yaml
    strategy:
      fail-fast: false
      matrix:
        policyDir: ['nonblocking'] # ['nonblocking', 'blocking']
```

This works correctly on an actual github action workflow. However, `act` does not interpolate the matrix variable in the `with:` argument:

```bash
[Conftest CI/Validate Rego Syntax & Test Policies]   🐳  docker run image=openpolicyagent/conftest:v0.21.0 entrypoint=["conftest"] cmd=["verify" "-p" "/github/workspace/${{" "matrix.policyDir" "}}/**/*/src.rego" "-d" "/github/workspace/lib/"]
| Error: running verification: load failed: read rego files: search rego files: walk path: lstat /github/workspace/${{: no such file or directory
```

The path is passed into the docker container which then fails to traverse that directory tree because `${{` is still present in the path.
