### ISSUE TITLE
Add warning when Docker installation not found

### ISSUE THREAD

**Issue by nelsonni** [nektos/act#440]
**Version**: [v0.2.17](https://github.com/nektos/act/releases/tag/v0.2.17)
**Platform**: MacOS
**Command**: `act -n`
**`main.workflow` file**:
```yml
name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
```
**Output**:
```console
(blank)
```
**Expected Output**:
A warning indicating that Docker needs to be installed.

If Docker is installed, but the Docker Daemon isn't running, then there is the following warning:
```console
Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Can this type of check and warning be replicated when Docker is missing?
