### ISSUE TITLE
Unmarshal error

### ISSUE THREAD

**Issue by noah-friedman** [nektos/act#450]
When unmarshalling:
```yaml
strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
```
I get the error:
```shell
Error: yaml: unmarshal errors:
  line 118: cannot unmarshal !!str `${{ fro...` into map[string][]interface {}
```
