### ISSUE TITLE
Same. I get `| /github/workflow/1: line 2: cargo: command not found` with just the basic Rust workflow (without using the *actions-rs* action).

### ISSUE THREAD

**Issue by hendis85** [nektos/act#452]
Same. I get `| /github/workflow/1: line 2: cargo: command not found` with just the basic Rust workflow (without using the *actions-rs* action).

This is the file:
```yaml
name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
```

EDIT: I saw that [this](https://github.com/nektos/act/issues/107) is a "pinned issue". (Didn't know this existed) Which explains what I see.

_Originally posted by @siedentop in https://github.com/nektos/act/issues/297#issuecomment-662590584_
