### ISSUE TITLE
act not honoring on.push.paths

### ISSUE THREAD

**Issue by jmcarbo** [nektos/act#454]
* Version of act: act version 0.2.17
* Platform: Linux, macOS
* The complete main.workflow file used
```
name: bla

on:
  push:
    paths:
      - 'docs/*'

jobs:
  bla2:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
```
* The complete command that was executed
act -r

Any output from the command

[bla/bla2] 🚀  Start image=node:12.6-buster-slim
[bla/bla2]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[bla/bla2] ⭐  Run echo hello world
| hello world
[bla/bla2]   ✅  Success - echo hello world

Desired behaviour:

The second time the command is run it should no run because no changes were made to docs/* files.
