### ISSUE TITLE
cant find python version 3.8

### ISSUE THREAD

**Issue by KIC** [nektos/act#464]
I get the follwoing error for any python verion I try 3.7, 3.8, 3.8.1, ....

```bash
# act -b
[NOX-Tests/build] 🧪  Matrix: map[python-version:3.8]
[NOX-Tests/build] 🚀  Start image=node:12.6-buster-slim
[NOX-Tests/build]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[NOX-Tests/build] ⭐  Run actions/checkout@v2
[NOX-Tests/build]   ✅  Success - actions/checkout@v2
[NOX-Tests/build] ⭐  Run Set up Python ${{ matrix.python-version }}
[NOX-Tests/build]   ☁  git clone 'https://github.com/actions/setup-python' # ref=v2
[NOX-Tests/build]   🐳  docker cp src=/home/kic/.cache/act/actions-setup-python@v2 dst=/actions/
[NOX-Tests/build]   💬  ::debug::Semantic version spec of 3.8 is 3.8
[NOX-Tests/build]   💬  ::debug::isExplicit: 
[NOX-Tests/build]   💬  ::debug::explicit? false
[NOX-Tests/build]   💬  ::debug::evaluating 0 versions
[NOX-Tests/build]   💬  ::debug::match not found
| Version 3.8 was not found in the local cache
[NOX-Tests/build]   💬  ::debug::check 3.10.0-alpha.4 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.10.0-alpha.3 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.10.0-alpha.2 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.10.0-alpha.1 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.9.1 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.9.1-rc.1 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.9.0 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.9.0-rc.2 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.9.0-rc.1 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.9.0-beta.5 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.9.0-beta.4 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.8.7 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::x64===x64 && darwin===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::x86===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::check 3.8.6 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::x64===x64 && darwin===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::x86===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::check 3.8.5 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::x64===x64 && darwin===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::x86===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::check 3.8.4 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::x64===x64 && darwin===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::x86===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::check 3.8.3 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::x64===x64 && darwin===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::x86===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::check 3.8.2 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::x64===x64 && darwin===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::x86===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::check 3.8.1 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::x64===x64 && darwin===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::x86===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::check 3.8.0 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::x64===x64 && darwin===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && linux===linux
[NOX-Tests/build]   💬  ::debug::x64===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::x86===x64 && win32===linux
[NOX-Tests/build]   💬  ::debug::check 3.7.9 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.7.8 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.7.7 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.7.6 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.7.5 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.7.1 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.6.12 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.6.11 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.6.10 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.6.9 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.6.8 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.6.7 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.5.10 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.5.9 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.5.4 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.4.10 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.4.4 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.3.7 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.3.5 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.2.5 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.1.4 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 3.0.1 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 2.7.18 satisfies 3.8
[NOX-Tests/build]   💬  ::debug::check 2.7.17 satisfies 3.8
[NOX-Tests/build]   ❗  ::error::Version 3.8 with arch x64 not found%0AThe list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
[NOX-Tests/build]   ❌  Failure - Set up Python ${{ matrix.python-version }}
Error: exit with `FAILURE`: 1
```

workflow file:
```
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: NOX-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    env:
      LD_LIBRARY_PATH: '/tmp/lib:/usr/lib:/usr/local/lib/'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install C dependencies
      env:
        LD_LIBRARY_PATH: '/tmp/lib:/usr/lib:/usr/local/lib/'
        TA_LIBRARY_PATH: '/tmp/lib/'
        TA_INCLUDE_PATH: '/tmp/include/'
      run: |
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/tmp
        make
        make install
        pip install TA-Lib
    - name: Install nox
      run: pip install -U nox pytest
    - name: execute nox tests
      run: nox
```
