### ISSUE TITLE
Miss steps context outcome, conclusion

### ISSUE THREAD

**Issue by theowenyoung** [nektos/act#465]
Hi, Currently, the steps context does not match the Github action.

Docs: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#steps-context

For example:

```yaml
steps:
  - id: test
    run: echo test
  - run: echo $outcome
    env:
      outcome: steps.test.outcome
```

Currently the step context:

```json
{"success": true,"outputs": {}}
```

Expected:

```json
{
  "outcome": "success",
  "conclusion": "success",
  "outputs": {
  }
}
```

Code: https://github.com/nektos/act/blob/e47a2395a5260aca1cec1506f0243e919ed4e70c/pkg/runner/run_context.go#L40-L43
