### ISSUE TITLE
Doesn't correctly handle worker-level Powershell script runs

### ISSUE THREAD

**Issue by JustinGrote** [nektos/act#467]
### Issue
Powershell 7 scripts do not run in native workers via `run:` step, and report a false positive of succeeding

### Steps to Reproduce
With the following simple config:
```yaml
name: Test
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          "this should work!"
          "Evidence" > /github/workspace/worked
```
and swapping in the official powershell worker (and using -r so the container doesn't disappear):
`act -rvP ubuntu-latest=mcr.microsoft.com/powershell:lts-ubuntu-18.04`
The result says success:
![image](https://user-images.githubusercontent.com/15258962/104225876-d1ff5380-53fb-11eb-8412-4262edaa3b40.png)

However upon inspecting the image via attaching a shell to the docker container the "evidence" file was not created:
![image](https://user-images.githubusercontent.com/15258962/104225778-abd9b380-53fb-11eb-912f-db984aa471c9.png)

And running the command manually in the container from shell shows an exec problem
![image](https://user-images.githubusercontent.com/15258962/104226011-01ae5b80-53fc-11eb-8b36-132629b47f58.png)

Running the command using the `-f` format works fine however
![image](https://user-images.githubusercontent.com/15258962/104226117-24d90b00-53fc-11eb-9fe2-76bb7ba4aa21.png)
![image](https://user-images.githubusercontent.com/15258962/104226128-2a365580-53fc-11eb-92ef-2b2b0c714c22.png)
