### ISSUE TITLE
if: syntax without ${{ }} seems to always evaluate to false, even if invalid

### ISSUE THREAD

**Issue by edtan** [nektos/act#482]
This issue is similar to #366, but in this case, it appears that `if` statements without `${{ }}` are not evaluated, and always return `false`.  This sample workflow illustrates the issue:

```
name: "Test if statements"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: "bad expression, but act does not evaluate it and skips this step"
       if: foobar1
       run: echo "This does not run"

     - name: "bad expression, and act evaluates it and detects a bad expression "
       if: ${{ foobar2 }}
       run: echo "act will error before reaching this part"
```
For the second step, the logs show:
```
ERRO[0000] Unable to interpolate string '${{ foobar2 }}' - [ReferenceError: 'foobar2' is not defined]
```

This was tested on `v0.2.18`.
