### ISSUE TITLE
Can't access to input variables on 'workflow_dispatch' event

### ISSUE THREAD

**Issue by matiasalbarello** [nektos/act#490]
I have this action:
```yml
name: Simple Task

on:
  workflow_dispatch:
    inputs:
      delay_seconds:
        description: 'Time to delay'
        required: false
        default: 60

jobs:
  simple-task:
    runs-on: ubuntu-latest

    steps:
      - name: delay execution
        env:
          input_delay: ${{ github.event.inputs.delay_seconds }}
        run: sleep $input_delay

      - name: Run a one-line script
        run: echo 'done'
```

When executing `act workflow_dispatch -j simple-task` I get the following error:
`ERRO[0000] Unable to interpolate string '${{ github.event.inputs.delay_seconds }}' - [TypeError: Cannot access member 'delay_seconds' of undefined]`

The workflow works fine on github.
