### ISSUE TITLE
Github Enterprise

### ISSUE THREAD

**Issue by MichaelSp** [nektos/act#497]
Unfortunately GH Enterprise is not supported.

For actions to work on Enterprise you'll have to mirror the actions (ugly but 🤷). In our enterprise setup this means we'll have to define the official action `https://github.com/github/super-linter/`
as mirrored in `https://<gh-enterprise>/ghcom-actions/github-super-linter`
Now additionally we're required to authenticate even for `git clone`.

This is the current output with `-v`:

```
[...]
[CI/lint] ⭐  Run Lint Code Base
[CI/lint]   ☁  git clone 'https://github.com/ghcom-actions/github-super-linter' # ref=v3
[CI/lint]   cloning https://github.com/ghcom-actions/github-super-linter to /Users/<user>/.cache/act/ghcom-actions-github-super-linter@v3
[CI/lint] Unable to clone https://github.com/ghcom-actions/github-super-linter refs/heads/v3: authentication required
DEBU[0016] authentication required
```

for the following `ci.yml`

```yaml
jobs:
  lint:
    runs-on: self-hosted
    steps:
    - name: Lint Code Base
      uses: ghcom-actions/github-super-linter@v3
      env:
        VALIDATE_HTML: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

For that to work we need: 
 1. The correct enterprise URL instead of `github.com`
 2. possibility to do authentication. Ideally inherit authentication from `git-cli`.
