### ISSUE TITLE
jobs.*.strategy.matrix.include doesnt seem to be parsed correctly when used in a step's env.

### ISSUE THREAD

**Issue by bagel-dawg** [nektos/act#499]
Here's an example workflow file that works in GIthub, but not in act:

```
---
name: "Test Platform GH Actions"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    strategy:
      matrix:
        include:
          - example_var_1: "this_is_var_1"
            nested_var_1: "this_is_nested_var_1"
    runs-on: ubuntu-latest
    steps:

      - name: Show the environment
        run: |
          env
        env:
          ENV_VAR_1: "${{ matrix.example_var_1 }}"
          NESTED_ENV_VAR_1: "${{ matrix.nested_var_1 }}"
 ```
 
Expected output (truncated to the relevant parts):
```
[Test Platform GH Actions/build-2]   ✅  Success - Show the environment
| ENV_VAR_1=this_is_var_1
| NESTED_ENV_VAR_1=this_is_nested_var_1
```
 
 Actual output:
 
```
[Test Platform GH Actions/build-2]   ✅  Success - Show the environment
| ENV_VAR_1=
| NESTED_ENV_VAR_1=
```
