### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by cscetbon** [nektos/act#509]
Trying to run act (0.2.19) with [my workflow](https://github.com/cscetbon/cass-operator-casskop-compat/blob/master/.github/workflows/run-kuttl-tests.yml ) I get the following error:

```
[Compatibility casskop/cass-operator/scaleup-gke        ] 🚀  Start image=catthehacker/ubuntu:act-latest
[Compatibility casskop/cass-operator/scaleup-gke        ]   🐳  docker run image=catthehacker/ubuntu:act-latest entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Compatibility casskop/cass-operator/scaleup-gke        ] ⭐  Run Disallow Concurrent Runs
[Compatibility casskop/cass-operator/scaleup-gke        ]   ☁  git clone 'https://github.com/byu-oit/github-action-disallow-concurrent-runs' # ref=v1
[Compatibility casskop/cass-operator/scaleup-gke        ]   🐳  docker cp src=/Users/cscetbon/.cache/act/byu-oit-github-action-disallow-concurrent-runs@v1 dst=/actions/
[Compatibility casskop/cass-operator/scaleup-gke        ]   ❗  ::error::An error occurred: Cannot read property 'slice' of undefined
[Compatibility casskop/cass-operator/scaleup-gke        ]   ❌  Failure - Disallow Concurrent Runs
```

**Comment by catthehacker** [comment]
Use `if:` to run it only on GitHub Actions

```yaml
      - name: Disallow Concurrent Runs
        uses: byu-oit/github-action-disallow-concurrent-runs@v1
        if: env.GITHUB_ACTIONS == true
        with:
          token: ${{ github.token }}
```
