### ISSUE TITLE
Error when trying to use git.

### ISSUE THREAD

**Issue by Ayfri** [nektos/act#510]
Hi, I have this action:
```yml
name: Generate Documentation

on:
  workflow_dispatch:
  push:
    paths:
    - '**.ts'
    branches:
    - master

jobs:
  genDocs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm ci

      - name: Format & Lint
        run: |
          npm run prettier
          npm run lint

      - name: Generate Documentation
        run: npm run genDocs

      - name: Commit changes
      - run: git init
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "GitHub Action"
      - run: git add *
      - run: git pull
      - run: git commit --amend --no-edit
      - run: git push origin -f
```
And I'm getting this error:
```go
panic: runtime error: index out of range [1] with length 0

goroutine 8 [running]:
github.com/nektos/act/pkg/runner.newRemoteAction(0x0, 0x0, 0x0)
        /home/runner/work/act/act/pkg/runner/step_context.go:408 +0x189
github.com/nektos/act/pkg/runner.(*StepContext).Executor(0xc00047a940, 0xde001b)
        /home/runner/work/act/act/pkg/runner/step_context.go:59 +0x249
github.com/nektos/act/pkg/runner.(*RunContext).newStepExecutor.func1(0xf42540, 0xc000467890, 0x0, 0x0)
        /home/runner/work/act/act/pkg/runner/run_context.go:223 +0x37f
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0x0, 0x10)
        /home/runner/work/act/act/pkg/common/executor.go:146 +0x181
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0xc9a320, 0xd)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0x2, 0xc000115b68)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0xd, 0x0)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0xc000115b01, 0xc000115c88)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0xc000462be0, 0xda2c20)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0xc0002a4fd1, 0x1e)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0xc9a320, 0xc000462bd0)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.Then.func1(0xf42540, 0xc000467890, 0x1, 0x1554668)
        /home/runner/work/act/act/pkg/common/executor.go:133 +0x53
github.com/nektos/act/pkg/common.Executor.If.func1(0xf42540, 0xc000467890, 0xc0002a5920, 0x2d)
        /home/runner/work/act/act/pkg/common/executor.go:154 +0x71
github.com/nektos/act/pkg/runner.(*runnerImpl).NewPlanExecutor.func1(0xf42540, 0xc0004280f0, 0xc000500080, 0xc000069f70)
        /home/runner/work/act/act/pkg/runner/runner.go:79 +0x263
github.com/nektos/act/pkg/common.Executor.ChannelError.func1(0xf42540, 0xc0004280f0, 0xc000500080, 0x0)
        /home/runner/work/act/act/pkg/common/executor.go:125 +0x4c
github.com/nektos/act/pkg/common.NewParallelExecutor.func1.1(0xc000500040, 0xc00044c120, 0xf42540, 0xc0004280f0)
        /home/runner/work/act/act/pkg/common/executor.go:101 +0x5d
created by github.com/nektos/act/pkg/common.NewParallelExecutor.func1
        /home/runner/work/act/act/pkg/common/executor.go:100 +0xbe
```
At the `commit changes` step.
