### ISSUE TITLE
Error: Cannot find module dist/index.js

### ISSUE THREAD

**Issue by vitorcamachoo** [nektos/act#522]
Hi guys,

I'm having problems to use act along with local action.yaml (`uses: ./`)with the following configuration:
```yaml
name: Testing Affected

on:
  push:
    branches-ignore:
      - 'dependabot/**'
env:
    NX_WORKSPACE_ROOT_PATH: ./example

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: nx-affected
        uses: ./
        with:
          base: ${{ env.BRANCH_NAME }}
      - name: Print affected
        run: |
          echo affected: ${{ steps.nx-affected.outputs.affected}}
          echo affected-apps: ${{ steps.nx-affected.outputs.affected-apps }}
          echo affected-libs: ${{ steps.nx-affected.outputs.affected-libs }}
```

It gives me the following error:
```

➜  nx-affected-gh-action git:(master) ✗ act -b -P ubuntu-latest=nektos/act-environments-ubuntu:18.04
[Testing Affected/test] 🚀  Start image=nektos/act-environments-ubuntu:18.04
[Testing Affected/test]   🐳  docker run image=nektos/act-environments-ubuntu:18.04 entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Testing Affected/test] ⭐  Run ./
| internal/modules/cjs/loader.js:985
|   throw err;
|   ^
| 
| Error: Cannot find module '/github/workspace/nx-affected-gh-action/dist/index.js'
|     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
|     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
|     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
|     at internal/main/run_main_module.js:18:47 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
[Testing Affected/test]   ❌  Failure - ./
Error: exit with `FAILURE`: 1
```
but I have the dist/index.js on my directory.

Am I doing anything wrong?

Thanks.
