### ISSUE TITLE
Issue: act will parse/evaluate arithmetic context expressions that github wont

### ISSUE THREAD

**Issue by dannystaple** [nektos/act#526]
## Act version

```none
$ act --version
act version 0.2.20
```

## Expected behaviour

The code below, which looks viable, is actually invalid. Run within the genuine github workflow context, it will result in invalid reference and not run the whole workflow file. I would expect act to output the same error for the same line.

## Actual behaviour

Act will evaluate this expression to the value. This leads to workflows debugged/developed locally that will not run in github.

## Workflow and/or repository

The step definition (minimal reproducible):

```
name: unreal
jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - env:
          EXPIRY_TIME: ${{ 3 * 24 * 60 * 60 }}
        run: echo ${EXPIRY_TIME}
```

## Steps to reproduce

Run the above in act (eg `act push`), it will run, and echo that calculated time.
Commit to github (with the right on definition to function) and it will fail.
