### ISSUE TITLE
Issue: Expression evaluated to false, workflow not run

### ISSUE THREAD

**Issue by dave-irvine** [nektos/act#532]
## Act version

```none
act version 0.2.20
```

## Expected behaviour

I've defined an event that looks like this:

```json
{
  "pull_request": {
    "labels": [
      {
        "name": "needs-qa"
      }
    ]
  }
}
```

And my workflow has a check that looks for a label on a pull-request:

```yml
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # Check to see if the labels on the PR contain a label named 'needs-qa'
    if: ${{ contains(github.event.pull_request.labels.*.name, 'needs-qa') }}
```

Given the event passed in with `--eventpath`  I would expect my workflow to be run

## Actual behaviour

My workflow is not run, with the following message:

```
DEBU[0000] expression '${{ contains(github.event.pull_request.labels.*.name, 'needs-qa') }}' evaluated to 'false' 
```

I think it might be related to how the expression is being evaluated?

```
DEBU[0000] Evaluating 'contains(github['event']['pull_request']['labels']['']*['name'], 'needs-qa')' instead of 'contains(github.event.pull_request.labels.*.name, 'needs-qa')' 
```
