### ISSUE TITLE
Enhancement: Support matrix builds with dynamic input

### ISSUE THREAD

**Issue by jonico** [nektos/act#540]
## Describe feature

GitHub Actions has a neat feature to [create a matrix dynamically](https://github.blog/changelog/2020-04-15-github-actions-new-workflow-features/) based on the outputs of a previous job:

```yaml

name: Dynamic Matrix build

on:
  workflow_dispatch:
    inputs:
          x:
            description: 'Number of jobs on x-Axis'
            required: true
            default: '8'
          y:
            description: 'Number of jobs on y-Axis'
            required: true
            default: '4'

jobs:
  generate-matrix:
    name: "Generate matrix job specs"
    outputs:
      x: ${{ steps.generate-matrix.outputs.x }}
      y: ${{ steps.generate-matrix.outputs.y }}
    runs-on: ubuntu-latest
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: |
          echo "::set-output name=x::[`seq -s , ${{ github.event.inputs.x }}`]"
          echo "::set-output name=y::[`seq -s , ${{ github.event.inputs.y }}`]"

  matrix:
      name: "Matrix job"
      runs-on: ubuntu-latest
      needs: [generate-matrix]
  
      strategy:
        fail-fast: false
        matrix:
          x: ${{ fromJson(needs.generate-matrix.outputs.x) }}
          y: ${{ fromJson(needs.generate-matrix.outputs.y) }}
      steps:
            - name: Perform job
              run: echo "${{matrix.x}}, ${{matrix.y}}"
```

`nektos/act` currently does not understand the dynamic input for the matrix dimensions as already reported in #450 - and errors out even if there is just one workflow file in the repository that is using this feature:

```bash
$ act -l
Error: yaml: unmarshal errors:
  line 37: cannot unmarshal !!str `${{ fro...` into []interface {}
  line 38: cannot unmarshal !!str `${{ fro...` into []interface {}
```

It would be amazing if `nektos/act` would be able to support dynamic matrix builds as well - or at least does not error out if it finds a workflow file with that syntax.
