### ISSUE TITLE
Enhancement: Fail if env variable is used outside of job

### ISSUE THREAD

**Issue by pdecat** [nektos/act#573]
## Describe feature

The [following configuration](https://github.com/fbradyirl/openwrt-luci-rpc/pull/47/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R1-R27) works in act:

```
name: Python package

on: [push, pull_request]

env:
  target_python_version: 3.8

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7, "${{env.target_python_version}}"]

    steps:
    - uses: actions/checkout@v1
	@@ -19,13 +22,28 @@ jobs:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
```

but [fails in Github Actions](https://github.com/fbradyirl/openwrt-luci-rpc/actions/runs/648723692):

```
.github/workflows/main.yml#L14The workflow is not valid. .github/workflows/main.yml (Line: 14, Col: 31): Unrecognized named-value: 'env'. Located at position 1 within expression: env.target_python_version
```

Sadly, this is not supported:

* https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#env
* https://github.community/t/env-vars-are-not-expanded-causing-dry-violations/16550
* https://github.community/t/how-to-use-env-context/16975/2
