### ISSUE TITLE
Issue with mongodb github action

### ISSUE THREAD

**Issue by dhowe** [nektos/act#5804]
### Bug report info

```plain text
act version:            0.2.78
GOOS:                   darwin
GOARCH:                 arm64
NumCPU:                 14
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
	/var/run/docker.sock
	$HOME/.docker/run/docker.sock
Config files:           
	/Users/dhowe/Library/Application Support/act/actrc:
		-P ubuntu-latest=catthehacker/ubuntu:act-latest
		-P ubuntu-22.04=catthehacker/ubuntu:act-22.04
		-P ubuntu-20.04=catthehacker/ubuntu:act-20.04
		-P ubuntu-18.04=catthehacker/ubuntu:act-18.04
	/Users/dhowe/.actrc:
		--container-architecture linux/amd64
Build info:
	Go version:            go1.24.3
	Module path:           command-line-arguments
	Main version:          
	Main path:             
	Main checksum:         
	Build settings:
		-buildmode:           exe
		-compiler:            gc
		-ldflags:             -X main.version=0.2.78
		CGO_ENABLED:          1
		CGO_CFLAGS:           
		CGO_CPPFLAGS:         
		CGO_CXXFLAGS:         
		CGO_LDFLAGS:          
		GOARCH:               arm64
		GOOS:                 darwin
		GOARM64:              v8.0
Docker Engine:
	Engine version:        28.1.1
	Engine runtime:        runc
	Cgroup version:        2
	Cgroup driver:         cgroupfs
	Storage driver:        overlayfs
	Registry URI:          https://index.docker.io/v1/
	OS:                    Docker Desktop
	OS type:               linux
	OS version:            
	OS arch:               aarch64
	OS kernel:             6.10.14-linuxkit
	OS CPU:                14
	OS memory:             7836 MB
	Security options:
		name=seccomp,profile=unconfined
		name=cgroupns
```

### Command used with act

```sh
act push
```

### Describe issue

Tests pass in github action but fail with act:
```
[Playwright Tests/test]   ✅  Success - Main Install Playwright Browsers [1m23.414296292s]
[Playwright Tests/test] ⭐ Run Main Start MongoDB
[Playwright Tests/test]   🐳  docker build -t act-supercharge-mongodb-github-action-1-12-0-dockeraction:latest --platform linux/amd64 /Users/dhowe/.cache/act/supercharge-mongodb-github-action@1.12.0
[Playwright Tests/test]   ❌  Failure - Main Start MongoDB [4.758423958s]
[Playwright Tests/test] failed to export image: NotFound: content digest sha256:59a833fde12d7bcc06ff52f0b44a410d8000b7f132fd102db60c4454e3038bf5: not found
[Playwright Tests/test] ⭐ Run Main actions/upload-artifact@v4
[Playwright Tests/test]   🐳  docker cp src=/Users/dhowe/.cache/act/actions-upload-artifact@v4/ dst=/var/run/act/actions/actions-upload-artifact@v4/
[Playwright Tests/test]   🐳  docker exec cmd=[/opt/acttoolcache/node/18.20.8/x64/bin/node /var/run/act/actions/actions-upload-artifact@v4/dist/upload/index.js] user= workdir=
[Playwright Tests/test]   🚧  ::warning::No files were found with the provided path: playwright-report/. No artifacts will be uploaded.
[Playwright Tests/test]   ✅  Success - Main actions/upload-artifact@v4 [989.559666ms]
[Playwright Tests/test] ⭐ Run Complete job
[Playwright Tests/test]   ✅  Success - Comp
```

### Link to GitHub repository

private

### Workflow content

```yml
name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: 8.0.4
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
```

### Relevant log output

```sh
[Playwright Tests/test]   ✅  Success - Main Install Playwright Browsers [1m23.414296292s]
[Playwright Tests/test] ⭐ Run Main Start MongoDB
[Playwright Tests/test]   🐳  docker build -t act-supercharge-mongodb-github-action-1-12-0-dockeraction:latest --platform linux/amd64 /Users/dhowe/.cache/act/supercharge-mongodb-github-action@1.12.0
[Playwright Tests/test]   ❌  Failure - Main Start MongoDB [4.758423958s]
[Playwright Tests/test] failed to export image: NotFound: content digest sha256:59a833fde12d7bcc06ff52f0b44a410d8000b7f132fd102db60c4454e3038bf5: not found
[Playwright Tests/test] ⭐ Run Main actions/upload-artifact@v4
[Playwright Tests/test]   🐳  docker cp src=/Users/dhowe/.cache/act/actions-upload-artifact@v4/ dst=/var/run/act/actions/actions-upload-artifact@v4/
[Playwright Tests/test]   🐳  docker exec cmd=[/opt/acttoolcache/node/18.20.8/x64/bin/node /var/run/act/actions/actions-upload-artifact@v4/dist/upload/index.js] user= workdir=
[Playwright Tests/test]   🚧  ::warning::No files were found with the provided path: playwright-report/. No artifacts will be uploaded.
[Playwright Tests/test]   ✅  Success - Main actions/upload-artifact@v4 [989.559666ms]
[Playwright Tests/test] ⭐ Run Complete job
[Playwright Tests/test]   ✅  Success - Comp
```
