### ISSUE TITLE
setup-python@v2: Unable to resolve v2: reference not found error

### ISSUE THREAD

**Issue by obzenner** [nektos/act#622]
## Act version
```
$ act --version
act version 0.2.21

Runner: -P ubuntu-18.04=catthehacker/ubuntu:act-18.04

macOS Big Sur 11.2.3
Running in console
```

## Expected behaviour

Should install `setup-python@v2`

## Actual behaviour

![image](https://user-images.githubusercontent.com/3275754/115022842-3f6cc580-9ebe-11eb-952b-73242e75883d.png)

## Workflow and/or repository
```
name: Master Build & Publish to Dev

on:
  push:
    branches:
      - master

jobs:

  build-service-container:
    name: Master - Build MSP Service Container
    runs-on: ubuntu-latest

    env:
      DEFAULT_PYTHON: 3.8
    
    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v2

      # -- Set-up GitHub Pipeline Library --

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
```

on: [push]

Is the issue happening because we are running it on macOS? Any other feedback is appreciated!
