### ISSUE TITLE
Issue: a strategy clause without matrix 'disables' a job

### ISSUE THREAD

**Issue by Totktonada** [nektos/act#625]
## Act version

```none
$ ~/go/bin/act --version
Error: unknown flag: --version
$ strings ~/go/bin/act | grep '^mod.*v[0-9]\+\.[0-9]\+\.[0-9]\+'
mod	github.com/nektos/act	v0.2.21	h1:mx5wheBRwuwrCaZb+gL0QcxIQQCsUFKtafmamfqtfWU=
```

I'm on Gentoo Linux (if it matters).

## Expected behaviour

The job below is run when I type `~/go/bin/act` (it is run on GitHub Actions).

## Actual behaviour

The job below does not run when I type `~/go/bin/act`.

## Workflow

<details>
  <summary>workflow</summary>

```yaml
name: Hello, world!

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo Hello, world!
```
</details>

## Steps to reproduce

1. Create an empty git repository.
2. Place the workflow above into the `.github/workflows/hello_world.yml` file.
3. Run `~/go/bin/act`.

## `act` output

<details>
  <summary>Log</summary>

```none
$ ~/go/bin/act --verbose
DEBU[0000] Loading environment from /home/alex/p/p/test/.env 
DEBU[0000] Loading secrets from /home/alex/p/p/test/.secrets 
DEBU[0000] Loading workflows from '/home/alex/p/p/test/.github/workflows' 
DEBU[0000] Reading workflow '/home/alex/p/p/test/.github/workflows/hello_world.yml' 
DEBU[0000] Planning event: push 
```
</details>

## Looking a bit deeper

When I remove the `strategy` clause the job is run:

<details>
  <summary>workflow (without strategy clause)</summary>

```yaml
name: Hello, world!

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo Hello, world!
```
</details>

Or, when I add `matrix clause, the job is run too:

<details>
  <summary>workflow (with matrix clause)</summary>

```yaml
name: Hello, world!

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: echo Hello, world!
```
</details>
