### ISSUE TITLE
Issue: Does not run a github action library

### ISSUE THREAD

**Issue by fagianijunior** [nektos/act#647]
## Act version

```act version 0.2.21

```

## Expected behaviour

Download a github action (fagiani/buildpacks-action@v0.3.0) library and use it.

## Actual behaviour

Only do a download of a library and does nothing. None error message, only don't execute.

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```
on:
  push:
    branches:
      - staging
      
name: Deploy to AWS ECS
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: aws-config
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets['AWS_ACCESS_KEY_ID'] }}
        aws-secret-access-key: ${{ secrets['AWS_SECRET_ACCESS_KEY'] }}
        aws-region: ${{ secrets['AWS_REGION'] }}

    - name: Inject slug and short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Build and publish image
      id: build-image
      uses: fagiani/buildpacks-action@v0.3.0
      with:
        registry: ${{ steps['aws-config']['outputs']['aws-account-id'] }}.dkr.ecr.${{ secrets['AWS_REGION'] }}.amazonaws.com
        image: novonoticias-wordpress-${{ env['GITHUB_REF_SLUG'] }}
        tag: ${{ env['GITHUB_SHA_SHORT'] }}
        path: .
        builder: 'heroku/buildpacks:18'
        buildpacks: "heroku/nodejs-engine@0.7.3 buildpacks/nodejs-yarn-buildpack heroku/procfile@0.6.2"
        publish: true
```

</details>

## Steps to reproduce

1. Create a repository with .github/workflow/deploy.yml
2. Create a .secrets with this values:
AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AWS_REGION=us-east-1
AWS_SECRET_ACCESS_KEY=nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
WP_DB_URL_STAGINGhttp://staging.myawesomesite.com
2. Run act --bind -v
## `act` output

<details>
  <summary>Log</summary>

```
[Deploy to AWS ECS/Deploy] 🚀  Start image=nektos/act-environments-ubuntu:18.04
[Deploy to AWS ECS/Deploy]   🐳  docker run image=nektos/act-environments-ubuntu:18.04 platform=linux/amd64 entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Deploy to AWS ECS/Deploy] ⭐  Run Checkout
[Deploy to AWS ECS/Deploy]   ✅  Success - Checkout
[Deploy to AWS ECS/Deploy] ⭐  Run Configure AWS credentials
[Deploy to AWS ECS/Deploy]   ☁  git clone 'https://github.com/aws-actions/configure-aws-credentials' # ref=v1
[Deploy to AWS ECS/Deploy]   🐳  docker cp src=/home/terabytes/.cache/act/aws-actions-configure-aws-credentials@v1 dst=/actions/
[Deploy to AWS ECS/Deploy]   ⚙  ::add-mask::***
[Deploy to AWS ECS/Deploy]   ⚙  ::add-mask::***
[Deploy to AWS ECS/Deploy]   ⚙  ::add-mask::657572075293
[Deploy to AWS ECS/Deploy]   ⚙  ::set-output:: aws-account-id=657572075293
[Deploy to AWS ECS/Deploy]   ✅  Success - Configure AWS credentials
[Deploy to AWS ECS/Deploy] ⭐  Run Inject slug and short variables
[Deploy to AWS ECS/Deploy]   ☁  git clone 'https://github.com/rlespinasse/github-slug-action' # ref=v3.x
[Deploy to AWS ECS/Deploy]   🐳  docker cp src=/home/terabytes/.cache/act/rlespinasse-github-slug-action@v3.x dst=/actions/
[Deploy to AWS ECS/Deploy]   ✅  Success - Inject slug and short variables
[Deploy to AWS ECS/Deploy] ⭐  Run Build and publish image
[Deploy to AWS ECS/Deploy]   ☁  git clone 'https://github.com/fagiani/buildpacks-action' # ref=v0.3.0
[Deploy to AWS ECS/Deploy]   ✅  Success - Build and publish image

```

</details>

Now last part with act --bind -v

<details>
  <summary>Log with verbose</summary>

```
[Deploy to AWS ECS/Deploy] ⭐  Run Build and publish image
[Deploy to AWS ECS/Deploy]   ☁  git clone 'https://github.com/fagiani/buildpacks-action' # ref=v0.3.0
[Deploy to AWS ECS/Deploy]   cloning https://github.com/fagiani/buildpacks-action to /home/terabytes/.cache/act/fagiani-buildpacks-action@v0.3.0
[Deploy to AWS ECS/Deploy] Cloned https://github.com/fagiani/buildpacks-action to /home/terabytes/.cache/act/fagiani-buildpacks-action@v0.3.0
[Deploy to AWS ECS/Deploy] Checked out v0.3.0
DEBU[0003] Read action &{buildpacks-action mamezou-tech Execute buildpacks CLI in GitHub Actions map[builder:{Builder to use true } buildpacks:{Custom buildpacks to use false } env:{Build-time environment variables false } image:{Name of container image true } path:{Path to target application true } publish:{Set true to push image to registry false } registry:{Image repository for publishing false } tag:{Tag of container image false latest}] map[command:{build command executed} image-name:{image full name with registry and tag}] {docker map[]  Dockerfile [] []} {purple chevron-right}} from '/home/terabytes/.cache/act/fagiani-buildpacks-action@v0.3.0/action.yml' 
DEBU[0003] About to run action &{buildpacks-action mamezou-tech Execute buildpacks CLI in GitHub Actions map[builder:{Builder to use true } buildpacks:{Custom buildpacks to use false } env:{Build-time environment variables false } image:{Name of container image true } path:{Path to target application true } publish:{Set true to push image to registry false } registry:{Image repository for publishing false } tag:{Tag of container image false latest}] map[command:{build command executed} image-name:{image full name with registry and tag}] {docker map[]  Dockerfile [] []} {purple chevron-right}} 
DEBU[0003] type=3 actionDir=/home/terabytes/.cache/act/fagiani-buildpacks-action@v0.3.0 actionPath= Workdir=/home/terabytes/Workspace/NovoJornalismo/heroku-wp ActionCacheDir=/home/terabytes/.cache/act actionName=fagiani-buildpacks-action@v0.3.0 containerActionDir=/actions 
[Deploy to AWS ECS/Deploy]   ✅  Success - Build and publish image
[Deploy to AWS ECS/Deploy] Removed container: ed25671121f0c8bc73bb085a3675b11583e0e9a1bc2db0d77bde0423d5ecda5d
[Deploy to AWS ECS/Deploy]   🐳  docker volume rm act-Deploy-to-AWS-ECS-Deploy
```

</details>

Its end with success, but does noting
