### ISSUE TITLE
Issue: private action using local machine path and not docker container path

### ISSUE THREAD

**Issue by TonyRouse** [nektos/act#707]
## Act version

```none
❯ act --version
act version 0.2.22
```

## Expected behaviour

I checkout the actions repo of my organization and try to call an action in it. `path` is the same name as the repo because of the known issue with `MODULE_NOT_FOUND` in the README.

## Actual behaviour

The error is looking for the right file, that IS on the docker container, but the path is it calling `/Volumes/Code/..` is on my local machine, not the docker container.

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```none
name: example workflow

on: [push]

jobs:
  build:
    steps:
      - name: Checkout Action Repo
        uses: actions/checkout@v2
        with:
          repository: [organization]/actions
          ref: main
          token: ${{ secrets.GITHUB_PAT }}
          path: actions
      - uses: ./actions/gradle-build
```

</details>

## Steps to reproduce

- Have a private `actions` repo with `gradle-build/action.yaml` file
- From a different repo workflow, checkout actions repo and trigger workflow with PAT

## `act` output

<details>
  <summary>Log</summary>

```none
[test-workflow/build-it]   ❌  Failure - ./actions/gradle-build
Error: open /Volumes/Code/[organization]/[code]/actions/gradle-build/action.yaml: no such file or directory
```

</details>

**Comment by ekallevig** [comment]
I ran into the same issue. However, I tried to test the theory that it's looking for the files on the local machine (and not the docker container) by putting the same files on my local machine and it still gave the same "not found" error. Which then made me wonder if perhaps it's permissions issue?

**Comment by TonyRouse** [comment]
I assumed this because the `/Volumns/Code/.../..` file path is from my local system. I would wonder if the reason you test didn't work is because it is running it in the container that doesn't have access to your local files. The "path to code" is from the directory structure is from my local machine, the command is executed in the contain, which the file doesn't exist on.

**Comment by ChristopherHX** [comment]
My thoughts about this issue, after looking at the sources.

> I assumed this because the /Volumns/Code/.../.. file path is from my local system

[A recent change to act](https://github.com/nektos/act/pull/567), use the exact same path of your host workdir inside the container (except on windows).

I think the problem is, act uses docker cp for local actions, from the host to the container. This leads missing files, at the action destination, which isn't your working dir.

Possible workaround, until fixed:
Clone `[organization]/actions` manually into your working dir, before running act (a `.gitignore` file excluding the action may break the workaround)
Disable the remote checkout step, to avoid overriding files.
```yaml
name: example workflow

on: [push]

jobs:
  build:
    steps:
      - name: Checkout Action Repo
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          repository: [organization]/actions
          ref: main
          token: ${{ secrets.GITHUB_PAT }}
          path: actions
      - uses: ./actions/gradle-build
```

_I haven't tried it yet, but act has a lot of (reported and not reported) bug's in this area_
