### ISSUE TITLE
Issue: no expansion in env

### ISSUE THREAD

**Issue by chevdor** [nektos/act#713]
## Act version

`act version 0.2.22`

## Expected behaviour

With the following action definition:
```
...
- id: build
   name: Build ${{ inputs.package }} using ${{ inputs.image }}:${{ inputs.tag }}
   shell: bash
   env:  
      FOOBAR: foo/${{ inputs.bar }}
```

The expectation is to have the env FOOBAR set to "foo/bar" if `inputs.bar` was passed as "bar".
 
## Actual behaviour

FOOABAR expands (or should I say does not ~) to `foo/${{ inputs.bar }}`

## Workflow and/or repository

<!--
    - Provide workflow with which we can reproduce the issue
      OR
    - Provide link to your GitHub repository that contains the workflow

<details>
  <summary>workflow</summary>

```none
name: example workflow

on: [push]

jobs:
  [...]
```

</details>

## Steps to reproduce

Running `act` as `act -b --insecure-secrets --env-file .env -W tests/test.yml`
