### ISSUE TITLE
Issue: GitHub Actions says workflow is not valid because of `${{ !env.ACT }}`

### ISSUE THREAD

**Issue by merlinpatt** [nektos/act#720]
## Expected behaviour

GitHub Actions should not error regarding `${{ !env.ACT }}`

## Actual behaviour

GitHub Actions says workflow is not valid because of `${{ !env.ACT }}`

```
The workflow is not valid. .github/workflows/deploy.yml (Line: 11, Col: 13): Unrecognized named-value: 'env'. Located at position 2 within expression: !env.ACT
```

## Workflow and/or repository

[Erroring Workflow](https://github.com/merlinpatt/paypal-messaging-components/actions/runs/903119301)

<details>
  <summary>workflow</summary>

```none
name: Deploy
on:
    push:
        branches:
            - release
    # run for every pull request
    pull_request: {}
jobs:
    deploy:
        name: Deploy
        if: ${{ !env.ACT }} # skip during local actions testing
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Deploy
              run: npx semantic-release@15

```

</details>

**Comment by merlinpatt** [comment]
Keep

**Comment by catthehacker** [comment]
That's a problem with GitHub and not Act.

**Comment by merlinpatt** [comment]
@catthehacker how do you suggest I fix it? Who should I contact? The docs for act include this line, but if it doesn't work with GitHub, that's a bug that should be fixed.

**Comment by catthehacker** [comment]
act docs mention this but only for a step and it works on GitHub Actions, create issue on https://github.com/actions/runner to implement support for non-existing environment variables in job context of `if:`

**Comment by ChristopherHX** [comment]
If you ask me your statement in a job-if is a syntax violation and is correctly rejected by github, but act has no such validation. The env context is only evaluated in the runner not the server (I made my own server).
Please consider using the `github` context instead:

```yml
name: Deploy
on:
    push:
        branches:
            - release
    # run for every pull request
    pull_request: {}
jobs:
    deploy:
        name: Deploy
        if: ${{ !github.event.act }} # skip during local actions testing
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Deploy
              run: npx semantic-release@15
```
And use this `event.json` file with act or [Runner.Client](https://github.com/ChristopherHX/runner.server) otherwise the Job will run:
```json
{
    "act": true
}
```
Run act like
```
act -e event.json
```
_Hint: you can add / append `-e event.json` as a line into `./.actrc`_
