### ISSUE TITLE
Issue: Dockerfile context relative path

### ISSUE THREAD

**Issue by ryuheechul** [nektos/act#739]
I experience this with such action below

```
      - name: yq - my yq step
        uses: mikefarah/yq@v4.9.6
        with:
          cmd: yq --help
```

it appears to use https://github.com/mikefarah/yq/blob/master/Dockerfile even though it points to 
https://github.com/mikefarah/yq/blob/master/github-action/Dockerfile via https://github.com/mikefarah/yq/blob/master/action.yml#L15.

Probably somethings should be done in this line below  to fix this issue. https://github.com/nektos/act/blob/a9fe0383478554705100dc4416b235b2265f718c/pkg/runner/step_context.go#L472

## System information
    - Operating System: macOS
    - Architecture: arm64 (64-bit)
    - Apple M1: yes
    - Docker version: 20.10.7
    - Docker image used in `act`: catthehacker/ubuntu:act-latest
    - `act` version: act version 0.2.23

## Expected behaviour

use the right context path (`github.com/mikefarah/yq/github-action(/Dockerfile)`) to build the image
## Actual behaviour

use the wrong context path (`github.com/mikefarah/yq(/Dockerfile`) to build the image

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```yaml
name: example workflow
on: [push]
jobs:
  example-action:
    runs-on: ubuntu-latest
    steps:
      - name: yq - my yq step
        uses: mikefarah/yq@v4.9.6
        with:
          cmd: yq --help
```

</details>

## `act` output

<details>
  <summary>Log</summary>

```none
...
[Repository xxx/myEvent] Starting container: 9403a846d8fa99c60c066cc1b480e0b2039f6d47149122953583cc4abaaed313
| Error: unknown command "yq e --help" for "yq"
| Run 'yq --help' for usage.
```

</details>
