### ISSUE TITLE
Environment variables defined in the container are not evaluatable

### ISSUE THREAD

**Issue by mulle-nat** [nektos/act#757]
## System information

- Operating System: macOS
- Architecture: x86_64

- Docker version: Docker version 20.10.7, build f0df350
- Docker image used in `act`: catthehacker/ubuntu:act-20.04
- `act` version: 0.2.23

## Expected behaviour

I expected to be able to use container defined environment variables in if: statements.

```
name: CI

on: [push]

env:
# ENV2: # undefined here, but defined in local container 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest] # macos-latest,

    steps:
    - name: Dump Environment
      run:  env | sort

    - name: Test
      if: ${{ env.ENV2 }} 
      run:  echo Test
```

## Actual behaviour

`ENV2` value is ignored, unless defined in workflow file.

## Workflow and/or repository

See the complete workflow with step by step instructions on how to reproduce:

https://github.com/mulle-nat/act-and-github

</details>
