### ISSUE TITLE
Issue: container-tools/kind-action@v1.5.0 (registry:true) not working 

### ISSUE THREAD

**Issue by kanedafromparis** [nektos/act#782]
## System information

    - Operating System: macOS 
    - Architecture: x64 (64-bit) 
    - Apple M1: no
    - Docker version: 20.10.6
    - Docker image used in `act`: catthehacker/ubuntu:act-latest (digests sha256:26199cb25652c2f8a373cd5891fc9fee75f3f509d0667f35e7eabdc5e0be7713)
    - `act` version: act version 0.2.24

## Actual behaviour

this action : 

```yaml
        - name: Create Kubernetes KinD Cluster (ACT)
          uses: container-tools/kind-action@v1.5.0
          with:
            cluster_name: tomcat-local-apply
            registry: true
```
works in [github action](https://github.com/kanedafromparis/act-issue-with-kind-registry/actions/runs/1151462018) but not locally.

## Workflow and/or repository

I set a sample repository : https://github.com/kanedafromparis/act-issue-with-kind-registry/

## Steps to reproduce

just run `act`
## `act` output

<details>
  <summary>Log</summary>

```none
[Sample integration test/kind_integration_test]   🐳  docker exec cmd=[node /var/run/act/actions/container-tools-kind-action@v1.5.0/main.js] user=
| Creating registry "kind-registry" on port 5000 from image "registry:2"...
| 127.0.0.1 kind-registry
| jq: error: Could not open file /etc/docker/daemon.json: No such file or directory
| docker: unrecognized service
```

</details>

**Comment by johnpoth** [comment]
Ran into the same issue. That being said, it might be tricky to restart docker within docker ...

**Comment by catthehacker** [comment]
This should be possible with [`live-restore`](https://docs.docker.com/config/containers/live-restore/) option but it would require user to configure it first or run `act` as root (`sudo`/`doas`/`su`)

**Comment by johnpoth** [comment]
The script that's being run is [trying](https://github.com/container-tools/kind-action/blob/e7d0dcb30a69f6e36299e015e60d0fbf72d085d3/registry.sh#L136) to restart docker via `    sudo service docker restart
` inside `act`'s docker container `catthehacker/ubuntu:act-20.04`, which doesn't exist hence the error. 
It's trying to restart Docker because it added an insecure registry to /etc/docker/deamon.json (the file doesn't even exists in `act`'s docker container).
This is all because this action it thinks it's on the root machine and not in a docker container

**Comment by kanedafromparis** [comment]
Hi, thank for your feed back.

I did found a way around using [registry: false] (https://github.com/kanedafromparis/act-issue-with-kind-registry/blob/testing-hack/.github/workflows/kind-registry-example.yml#L19) and [kind load image-archive](https://github.com/kanedafromparis/act-issue-with-kind-registry/blob/testing-hack/.github/workflows/kind-registry-example.yml#L52)

WDYT ?

**Comment by johnpoth** [comment]
yeah me too then in a step just before the `kind-action` something like:
```
    - name: Configure docker registry
      if: ${{ env.ACT }}
      run: |
        sudo mkdir -p /etc/kind-registry
        cat <<EOF | sudo dd status=none of=/etc/kind-registry/config.yaml
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        containerdConfigPatches:
        - |-
          [plugins."io.containerd.grpc.v1.cri".registry.mirrors."${KIND_REGISTRY}"]
            endpoint = ["http://${KIND_REGISTRY}"]
        EOF
        sudo chmod a+r /etc/kind-registry/config.yaml
``` 
and after something like
```
    - name: Configure docker registry
      if: ${{ env.ACT }}
      run: |
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: local-registry-hosting
          namespace: kube-public
        data:
          localRegistryHosting.v1: |
            host: "${KIND_REGISTRY}"
            help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
        EOF
```
So that the `kind` cluster is setup to use your local registry.
