### ISSUE TITLE
Using "uses" inside composite action

### ISSUE THREAD

**Issue by nenadfilipovic** [nektos/act#783]
## System information

- Operating System: Linux
- Architecture: x64
- Apple M1: -
- Docker version: 20.10.8
- Docker image used in `act`: custom image
- `act` version: 0.2.24

## Expected behaviour

I would like to use other actions inside my own actions and it is now possible on GitHub actions: https://github.com/actions/runner/issues/646#issuecomment-901336347

Is this feature supported in act?

This is custom action:

```yml
name: 'Login to GitHub Container Registry'
description: 'Action that logs user in to GitHub Container Registry'

inputs:
  token:
    required: true
    description: 'User GitHub token'

runs:
  using: 'composite'
  steps:
    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

```

## Actual behaviour

`Error: (StepID: Login): Unexpected value 'uses'`

## Workflow and/or repository

```yml
job-2:
    name: End to end (E2E) tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Login to ghcr
        uses: ./.github/actions/docker-ghcr-login
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

## Steps to reproduce

`act pull_request -j job-2`

## `act` output

`Error: (StepID: Login): Unexpected value 'uses'`
