### ISSUE TITLE
Enhancement: support for container option: --hostname

### ISSUE THREAD

**Issue by MarcinFalkowski** [nektos/act#808]
Currently container option `--hostname` is not supported. 

Example:
```
name: container-hostname
on: push

jobs:
  with-hostname:
    runs-on: ubuntu-latest
    container:
      image: node:12-buster-slim
      options: "--hostname my.host.local"
    steps:
      - run: |
          [[ $(uname -n) == "my.host.local" ]]
```

above example will fail, because the container has default hostname, not requested hostname: `my.host.local`

# Expected behaviour:
above example run successfully
