### ISSUE TITLE
Question: Step container network mode

### ISSUE THREAD

**Issue by Jacob-Morgan** [nektos/act#835]
I have a GitHub workflow which launches a container to execute the build process this in turn launches a docker-compose stack for integration test which talks back to the build container for endpoint mocking.   While this works locally and in Github, when attempting to run the workflow locally using ACT it fails.  The failure is caused by a change made in #141 where-by it starts a step container in network isolation mode sharing the same network namespace as the ACT container used to launch the build container.  This in turn then prevents the build container from joining the network created by the launch of the docker-compose stack.

I've managed to verify that relaxing the network mode back to 'default' (https://github.com/pharos/act/commit/6f9a94dd078a802d93ae09645300ab4a3dd746e1) resolves the problem.  However I struggling to understand the original intent of #141 by forcing newly launched containers into such a restrictive network mode, as this is very different form GitHub.

The following workflow and action where used to verify the networking information for the build container is blank and the NetworkMode is 'container:<container-id>' when launched by Act, but is populated when run by Github.

<details>
<summary>Workflow</summary>

```
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker pull
        run: docker pull docker:latest

      - name: Docker Inspect
        uses: ./.github/actions/docker-inspect
```

```
name: Docker Inspect
runs:
  using: docker
  image: docker://docker:latest
  args:
    - "sh"
    - "-c"
    - >-
        cat /proc/self/cgroup  &&
        docker inspect $(cat /proc/self/cgroup | grep 'docker' | sed 's/^.*\///' | tail -n1)
```
* NOTE: For GitHub replace `docker` with `actions_job`.

</details>
