### ISSUE TITLE
Can't install npm dependencies

### ISSUE THREAD

**Issue by finleygn** [nektos/act#86]
I've been trying to get my github actions working locally with act (really cool tool btw) but I can't seem to get npm working.

Heres an example workflow to show the problem:

```
name: Test Somethin

on:
  pull_request:
    branches:
      - develop

jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

Running command `act -j do-stuff -s NPM_TOKEN=XXXX_XXXX_XXXX`
I get this output

```
[Test Somethin/do-stuff] ⭐  Run actions/checkout@v2
[Test Somethin/do-stuff]   ✅  Success - actions/checkout@v2
[Test Somethin/do-stuff] ⭐  Run actions/setup-node@v1
[Test Somethin/do-stuff]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v1
[Test Somethin/do-stuff]   🐳  docker pull node:12-alpine
[Test Somethin/do-stuff]   🐳  docker run image=node:12-alpine entrypoint=[] cmd=["node" "/github/home//setup-node985111831/dist/index.js"]
[Test Somethin/do-stuff]   💬  ::debug::isExplicit:
[Test Somethin/do-stuff]   💬  ::debug::explicit? false
[Test Somethin/do-stuff]   💬  ::debug::evaluating 0 versions
[Test Somethin/do-stuff]   💬  ::debug::match not found
[Test Somethin/do-stuff]   💬  ::debug::evaluating 378 versions
[Test Somethin/do-stuff]   💬  ::debug::matched: v12.16.1
[Test Somethin/do-stuff]   💬  ::debug::isExplicit: 12.16.1
[Test Somethin/do-stuff]   💬  ::debug::explicit? true
[Test Somethin/do-stuff]   💬  ::debug::checking cache: /home/actions/cache/node/12.16.1/x64
[Test Somethin/do-stuff]   💬  ::debug::not found
[Test Somethin/do-stuff]   💬  ::debug::Downloading https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz
[Test Somethin/do-stuff]   💬  ::debug::Downloading /home/actions/temp/1a31fd1a-a499-4e30-9d38-531f090e84b2
[Test Somethin/do-stuff]   💬  ::debug::download complete
[Test Somethin/do-stuff]   💬  ::debug::Caching tool node 12.16.1 x64
[Test Somethin/do-stuff]   💬  ::debug::source dir: /home/actions/temp/692cf33e-d4ab-4040-a505-f1e4bd026f89/node-v12.16.1-linux-x64
[Test Somethin/do-stuff]   💬  ::debug::destination /home/actions/cache/node/12.16.1/x64
[Test Somethin/do-stuff]   💬  ::debug::finished caching tool
[Test Somethin/do-stuff]   ⚙  ::add-path:: /home/actions/cache/node/12.16.1/x64/bin
[Test Somethin/do-stuff]   💬  ::debug::Setting auth in /github/workspace/.npmrc
[Test Somethin/do-stuff]   ⚙  ::set-env:: NPM_CONFIG_USERCONFIG=/github/workspace/.npmrc
[Test Somethin/do-stuff]   ⚙  ::set-env:: NODE_AUTH_TOKEN=XXXXX-XXXXX-XXXXX-XXXXX
[Test Somethin/do-stuff]   ✅  Success - actions/setup-node@v1
[Test Somethin/do-stuff] ⭐  Run Install Dependencies
[Test Somethin/do-stuff]   🐳  docker pull ubuntu:18.04
[Test Somethin/do-stuff]   🐳  docker run image=ubuntu:18.04 entrypoint=[] cmd=["bash" "--noprofile" "--norc" "-eo" "pipefail" "/github/home/.temp-script-262291398"]
[Test Somethin/do-stuff]   ❌  Failure - Install Dependencies
Error: exit with `FAILURE`: 127
```

In the verbose output the verbose output says `npm: command not found` which causes the exit.

---

I thought maybe it was the same issue as #85 but after following @davidalger's steps the output was the same. (I'm also on macOS)

**Comment by fwilhe** [comment]
Have you tried configuring another image? I had some (limited) success with `act -P ubuntu-latest=node:12`. Might also depend on if you rely on the default node version or use the setup node action.

I'm wondering about the default home dir `/github/workspace`. Is this a leftover from the "old" actions? My understanding is that the "new" ones use `/home/actions`.

**Comment by fwilhe** [comment]
Interesting thing: In this repo https://github.com/SAP/project-piper-action

this job works

```
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
```

but this does not

```
  dist-is-up-to-date:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run package
    - run: git diff --name-only --exit-code
```

It seems to fail in installing packages, I don't understand why.
