### ISSUE TITLE
Issue: Unable to parse file paths that include spaces

### ISSUE THREAD

**Issue by participator** [nektos/act#865]
## System information

- Operating System: macOS
- Architecture: x64 (64-bit)
- Apple M1: no
- Docker version: 20.10.8
- `act` version: 0.2.24

## Expected behaviour

When `uses/setup-node@v2` is used, the version of node should print

## Actual behaviour

I have spaces in my file path `/Users/[my_username]/Code Projects`.  When I run `npm -v` I receive the error `bash: /Users/[my_username]/Code: No such file or directory`. 

## Workflow and/or repository

<details>
  <summary>workflow</summary>

```yaml
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
         run: npm -v

```

</details>

## `act` output
if filepath = /Users/username/Code Projects/repo

`bash: /Users/username/Code : No such file or directory`

<details>
  <summary>Log</summary>

```none
PASTE YOUR LOG HERE
```

</details>
