### ISSUE TITLE
Issue: cannot unmarshal single string into slice

### ISSUE THREAD

**Issue by catthehacker** [nektos/act#875]
When using `entrypoint:` in `action.yml`, it fails to unmarshal it via `yaml.Decoder`

```
[PR Plan/Create terraform plan] ⭐  Run Checkout
[PR Plan/Create terraform plan]   ✅  Success - Checkout
[PR Plan/Create terraform plan] ⭐  Run terraform plan
[PR Plan/Create terraform plan]   ☁  git clone 'https://github.com/dflook/terraform-plan' # ref=v1
[PR Plan/Create terraform plan]   ❌  Failure - terraform plan
Error: yaml: unmarshal errors:
  line 49: cannot unmarshal !!str `/entryp...` into []string
```

```
runs:
  using: docker
  image: docker://danielflook/terraform-github-actions:v1.9.1
  entrypoint: /entrypoints/plan.sh
```

_Originally posted by @evilr00t in https://github.com/nektos/act/issues/330#issuecomment-830625229_
