### ISSUE TITLE
Issue: Steps with if-expression `failure()` are ignored after a fail

### ISSUE THREAD

**Issue by cmitz** [nektos/act#897]
## System information

- Operating System: macOS
- Architecture: x64
- Apple M1: no
- Docker version: 20.10.10
- Docker image used in `act`: normal
- `act` version: 0.2.24

## Expected behaviour

I expected the expressions `failure()` and `always()` within `if:` statements of steps to work even when the job has failed already

## Actual behaviour

The steps are ignored

## Workflow and/or repository

<details>
  <summary>Example workflow</summary>

```yaml
name: Test workflow

on:
  push:
    branches: 
      - main

jobs:
  deploy_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        run: |
          echo "::notice title=Proceeding::Job has not failed yet"

      - name: Fail the job
        run: |
          echo "::error title=Job failed::Job failed "
          exit 1

      - name: Print something else
        if: ${{ failure() }}
        run: |
          echo "::notice title=Failed::Job has failed but this is not executed"

```

</details>

## `act` output

Just `act`

<details>
  <summary>Log</summary>

```none
[Test workflow/deploy_notification] 🚀  Start image=catthehacker/ubuntu:act-latest
[Test workflow/deploy_notification]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Test workflow/deploy_notification]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[Test workflow/deploy_notification] ⭐  Run Print something
[Test workflow/deploy_notification]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/my.user/src/working-folder/workflow/0] user=
[Test workflow/deploy_notification]   ❓  ::notice title=Proceeding::Job has not failed yet
[Test workflow/deploy_notification]   ✅  Success - Print something
[Test workflow/deploy_notification] ⭐  Run Fail the job
[Test workflow/deploy_notification]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/my.user/src/working-folder/workflow/1] user=
[Test workflow/deploy_notification]   ❗  ::error title=Job failed::Job failed
[Test workflow/deploy_notification]   ❌  Failure - Fail the job
Error: exit with `FAILURE`: 1
```

</details>
