### ISSUE TITLE
Issue: <shortly describe issue>

### ISSUE THREAD

**Issue by tanul-bhasin** [nektos/act#899]
Team.
My workflow has this step
```
- name: Run build
   id: frontend-build
   uses: ./src/shared/github-actions/code/build-job
   with:
      src_path: ${{ env.project_path }}

```
At this path `./src/shared/github-actions/code/build-job, I have my action.yml` but always getting this error 

> DEBU[0001] file does not exist
> DEBU[0001] file does not exist
> DEBU[0001] file does not exist
> DEBU[0001] file does not exist
> Error: file does not exist

I have tried shifting the **action.yml** to the same folder as workflow with changing `uses:` value to `./` still getting the same error. Any suggestion please.

Thanks
