### ISSUE TITLE
Issue: <shortly describe issue>

### ISSUE THREAD

**Issue by azarudeena** [nektos/act#900]
## System information

- Operating System: macOS
- Architecture: x64
- Apple M1: No
- Docker version: 20.10.10
- Docker image used in `act`: 
- `act` version: 0.2.24

## Expected behaviour

On using `continue-on-error`, Act should run though

## Actual behaviour

I am using a snippet 

```
      - name: Terraform - Plan
        if: ${{ steps.filter.outputs.changed == 'true' && github.event_name == 'pull_request' }}
        id: plan
        continue-on-error: ${{ github.event_name == 'pull_request' }}
```
Getting the output as `line 68: cannot unmarshal !!str `${{ git...` into bool`

## Steps to reproduce

use: continue-on-error with github event validation.

**Comment by JossefMo1** [comment]
Retested the step-level expression from this report with the published act v0.2.89 Linux x86_64 binary. I could not reproduce the YAML unmarshalling error with this reduced workflow:

```yaml
name: continue-on-error expression regression
on: [pull_request, push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Deliberate failure
        id: plan
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        run: exit 7
      - name: Assert original outcome and continued conclusion
        run: |
          test '${{ steps.plan.outcome }}' = failure
          test '${{ steps.plan.conclusion }}' = success
          echo CONTINUED_AS_EXPECTED
```

Commands (save as workflow.yml):

```sh
act pull_request -W workflow.yml -P ubuntu-latest=-self-hosted --no-cache-server --action-offline-mode
act push -W workflow.yml -P ubuntu-latest=-self-hosted --no-cache-server --action-offline-mode
```

Results:

• pull_request: exit 0; the deliberately failing step retains outcome=failure, has conclusion=success, and the assertion step prints CONTINUED_AS_EXPECTED.
• push: exit 1; the failed step stops normal execution and the assertion step is skipped.
• Neither run produces cannot unmarshal !!str ... into bool.

Scope: Linux x86_64, host execution (no Docker), a shell failure replacing Terraform. This does not verify the original macOS/Docker/Terraform setup or job-level continue-on-error. It does exercise both branches of the exact step-level event expression.

The archive SHA-256 matched the release’s checksums file: 0191d6f1f3b716b5c55820032605d05fc3c1cdbf581ebeff655019e5dd1524c0.

This was an AI-assisted retest while investigating CI failure handling for WorldBisect. Providing the reduced case and results so the original reporter or maintainers can check whether this report still applies to a current release.
