### ISSUE TITLE
Issue: error adding seccomp filter rule for syscall clone3: permission denied": unknown

### ISSUE THREAD

**Issue by ghenry** [nektos/act#914]
Hi all,

This is known issue on Fedora 35 Docker and in other yml I do:

```
version: '3'

services:

  hydra:
    image: oryd/hydra:v1.10.7
...
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
```

Where would I add this last part ^^^ with GH actions and act?

Thanks.
