### ISSUE TITLE
Enhancement: support for container option: --privileged

### ISSUE THREAD

**Issue by hlovdal** [nektos/act#947]
## Describe feature

(Similar to #808)

Example:

```yaml
...
  mockTest:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
      options: --privileged
    steps:
      - uses: actions/checkout@v2
```

which generates a warning (and the build fails later).

```shell
...
[Build Check/makeTest]   ✅  Success - Test Makefile Targets
WARN[0106] Cannot parse container options: --privileged 
[Build Check/mockTest] 🚀  Start image=rockylinux:8
...
```

(This was found trying to run `act` on https://github.com/displaylink-rpm/displaylink-rpm).
