### ISSUE TITLE
ports not being parsed correctly

### ISSUE THREAD

**Issue by pjmartorell** [nektos/act#95]
Is not parsing ports correctly, as far as I know is a valid syntax:
```
> act -l
Error: yaml: unmarshal errors:
  line 13: cannot unmarshal !!str `5432:5432` into int
```
Failing yml:
```
name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

```
