### ISSUE TITLE
Unmarshall error when specifying a container in the workflow

### ISSUE THREAD

**Issue by schof** [nektos/act#99]
Act seems to be failing on any workflow that specifies a `container`. See error message below along with included workflow file. 

NOTE: This runs fine for me on simpler workflows when I do not specify a `container` attribute. It also fails if I put the text in quotes, etc.

p.s. Thanks for act. Great tool and I'd love to get it working with these other workflows.

***

Version: 0.2.1
Platform: OS X

Error:

```
Error: yaml: unmarshal errors:
  line 10: cannot unmarshal !!str `mobilep...` into model.ContainerSpec
child_process.js:656
    throw err;
    ^
Error: Command failed: act pull_request 
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at runAction (/Users/schof/repos/neptune/dist/util/action-local.js:29:5)
    at Object.<anonymous> (/Users/schof/repos/neptune/dist/util/action-local.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
error Command failed.
Exit code: 1
```

Workflow used:

```yml
name: Android
on:
  pull_request:
    paths:
      - 'client/**'
jobs:
  build:
    name: Lint Check
    runs-on: ubuntu-18.04
    container: mobileposse/dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Decrypt keystore files
        run: ./client/keystores/decrypt-keystores.sh
        env:
          GPG_DECRYPT_KEY: ${{ secrets.GPG_DECRYPT_KEY }}
      - name: Gradle Lint
        run: cd client && ./gradlew lintMobileposseSandboxDebug
      - name: Checkrun (Lint)
        uses: mobileposse/github-android-lint-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          filename: 'client/app/build/reports/lint-results-mobileposseSandboxDebug.xml'
          exclude: 'MissingTranslation'
          report_name: 'Gradle Lint Check'
      - name: Checkrun (Translations)
        uses: mobileposse/github-android-lint-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          filename: 'client/app/build/reports/lint-results-mobileposseSandboxDebug.xml'
          only: 'MissingTranslation'
          report_name: 'Translations'
```
