### ISSUE TITLE
Issue: Standalone strategy.matrix.include doesn't work

### ISSUE THREAD

**Issue by iluuu1994** [nektos/act#996]
## System information

Most likely irrelevant.

- Operating System: Linux (Pop!_OS 21.10)
- Architecture: x64 (64-bit)
- Dell XPS 9700
- Docker version: 20.10.12
- Docker image used in `act`: ghcr.io/catthehacker/ubuntu:act-20.04
- `act` version: 0.2.25

## Expected behaviour

```yml
name: Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        # This line is required for act to pick up the job
        # foo: []
        include:
          - foo: a
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Echo matrix
        run: echo "${{ matrix.foo }}"
```

I'd expect this to run one job for `{ foo: a }`.

## Actual behaviour

No job is run. The commented line needs to be added for this to work. The configuration runs on GitHub actions without issues.

## `act` output

<details>
  <summary>Log</summary>

```none
DEBU[0000] Loading environment from [hidden]/.env 
DEBU[0000] Loading secrets from [hidden]/.secrets 
DEBU[0000] Loading workflows from '[hidden]/.github/workflows' 
DEBU[0000] Loading workflows recursively                
DEBU[0000] Found workflow 'push.yml' in '[hidden]/.github/workflows/push.yml' 
DEBU[0000] Reading workflow '[hidden]/.github/workflows/push.yml' 
DEBU[0000] Correcting if statements '[hidden]/.github/workflows/push.yml' 
DEBU[0000] Planning event: push             
DEBU[0000]
```

</details>
